<?php

namespace App\Http\Resources\Api\Operationi18ndata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class OprGachaDisplayUnitI18nResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_oprGachaId = 'oprGachaId';
    protected const C_mstUnitId = 'mstUnitId';
    protected const C_language = 'language';
    protected const C_sortOrder = 'sortOrder';
    protected const C_description = 'description';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->oprGachaId = $data['oprGachaId'];
            $this->mstUnitId = $data['mstUnitId'];
            $this->language = $data['language'];
            $this->sortOrder = $data['sortOrder'];
            $this->description = $data['description'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'oprGachaId' => 'string',
        'mstUnitId' => 'string',
        'language' => 'string',
        'sortOrder' => 'int',
        'description' => 'string',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'oprGachaId' => 'opr_gacha_id',
        'mstUnitId' => 'mst_unit_id',
        'language' => 'language',
        'sortOrder' => 'sort_order',
        'description' => 'description',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $oprGachaId;

    /** @var string */
    protected $mstUnitId;

    /** @var string */
    protected $language;

    /** @var int */
    protected $sortOrder;

    /** @var string */
    protected $description;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'oprGachaId' => $this->oprGachaId,
            'mstUnitId' => $this->mstUnitId,
            'language' => $this->language,
            'sortOrder' => $this->sortOrder,
            'description' => $this->description,
        ];
    }
}
