<?php

namespace App\Http\Resources\Api\Operationi18ndata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class OprStepupGachaStepI18nResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_oprStepupGachaStepId = 'oprStepupGachaStepId';
    protected const C_language = 'language';
    protected const C_fixedPrizeDescription = 'fixedPrizeDescription';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->oprStepupGachaStepId = $data['oprStepupGachaStepId'];
            $this->language = $data['language'];
            $this->fixedPrizeDescription = $data['fixedPrizeDescription'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'oprStepupGachaStepId' => 'string',
        'language' => 'string',
        'fixedPrizeDescription' => 'string',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'oprStepupGachaStepId' => 'opr_stepup_gacha_step_id',
        'language' => 'language',
        'fixedPrizeDescription' => 'fixed_prize_description',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $oprStepupGachaStepId;

    /** @var string */
    protected $language;

    /** @var string */
    protected $fixedPrizeDescription;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'oprStepupGachaStepId' => $this->oprStepupGachaStepId,
            'language' => $this->language,
            'fixedPrizeDescription' => $this->fixedPrizeDescription,
        ];
    }
}
