<?php

namespace App\Constants;

enum MstDataMenuDisplayOrder: int
{
    case UNIT_DISPLAY_ORDER = 10;
    case ENEMY_DISPLAY_ORDER = 15;
    case ITEM_DISPLAY_ORDER = 20;
    case GATE_DISPLAY_ORDER = 30;
    case EMBLEM_DISPLAY_ORDER = 40;
    case QUEST_DISPLAY_ORDER = 50;
    case EVENT_DISPLAY_ORDER = 60;
    case SHOP_ITEM_DISPLAY_ORDER = 70;
    case SHOP_PASS_DISPLAY_ORDER = 80;
    case ADVENT_BATTLE_DISPLAY_ORDER = 90;
    case CAMPAIGN_DISPLAY_ORDER = 100;
    case MISSION_DISPLAY_ORDER = 110;
    case GACHA_DISPLAY_ORDER = 120;
    case PRODUCT_DISPLAY_ORDER = 130;
    case UNIT_ENCYCLOPEDIA_REWARD_DISPLAY_ORDER = 140;
    case IDLE_INCENTIVE_DISPLAY_ORDER = 150;
    case ARTWORK_DISPLAY_ORDER = 160;
    case LEADER_LEVEL_ORDER = 170;
    case PVP_DISPLAY_ORDER = 180;
    case COMEBACK_BONUS_ORDER = 190;
    case EXCHANGE_DISPLAY_ORDER = 200;
    case BOX_GACHA_DISPLAY_ORDER = 210;
}
