<?php

namespace App\Filament\Pages;

use App\Constants\ImagePath;
use App\Constants\UserSearchTabs;
use App\Filament\Authorizable;
use App\Filament\Pages\User\UserDataBasePage;
use App\Models\Mst\MstUnit;
use App\Models\Usr\UsrUnit;
use App\Services\AssetService;
use Illuminate\Support\Str;

class SendUserUnit extends UserDataBasePage
{
    use Authorizable;
    protected static ?string $navigationIcon = 'heroicon-o-document-text';

    protected static string $view = 'filament.pages.send-user-unit';

    public string $currentTab = UserSearchTabs::UNIT->value;

    public array $unit_ids = [];

    public function mount()
    {
        parent::mount(); // TODO: Change the autogenerated stub
        $this->breadcrumbList = array_merge($this->breadcrumbList, [
            UserUnit::getUrl(['userId' => $this->userId]) => $this->currentTab,
            self::getUrl(['userId' => $this->userId]) => '付与',
        ]);
    }

    public function getUnitList()
    {
        // 所持済みのキャラクターを取得
        $userUnits = UsrUnit::query()->where('usr_user_id', $this->userId)->get();

        $ownedUnitIds = $userUnits->pluck('mst_unit_id')->toArray();

        // 所持していないキャラクターマスターを取得
        $mstUnits = MstUnit::query()
            ->whereNotIn('id', $ownedUnitIds)
            ->get();

        $mstUnitData = [];
        foreach ($mstUnits as $mstUnit) {
            $mstUnitData[] = [
                'id' => $mstUnit?->id,
                'name' => $mstUnit?->mst_unit_i18n?->name,
                'assetPath' => $mstUnit->makeAssetPath(),
                'bgPath' => $mstUnit->makeBgPath(),
            ];
        }
        return $mstUnitData;
    }

    public function send()
    {
        $units = array_map(function ($unit_id) {
            return [
                'id' => Str::uuid(),
                'usr_user_id' => $this->userId,
                'mst_unit_id' => $unit_id,
                'rank' => 0,
                'grade_level' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }, $this->unit_ids);

        UsrUnit::insert($units);

        // チェックボックスが中途半端に残ってしまうので自ページリダイレクト
        $this->redirectRoute('filament.admin.pages.send-user-unit', ['userId' => $this->userId]);
    }
}
