<?php

namespace App\Filament\Pages;

use App\Constants\MissionStatus;
use App\Constants\UserSearchTabs;
use App\Filament\Pages\User\UserDataBasePage;
use App\Models\Mst\MstMissionEventDaily;
use App\Models\Usr\UsrMissionEvent;
use App\Tables\Columns\MstMissionInfoColumn;
use Filament\Forms\Components\TextInput;
use Filament\Tables\Actions\Action;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Concerns\InteractsWithTable;
use Filament\Tables\Contracts\HasTable;
use Filament\Tables\Enums\ActionsPosition;
use Filament\Tables\Enums\FiltersLayout;
use Filament\Tables\Filters\Filter;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use App\Constants\MissionType;
use App\Constants\MissionUnlockStatus;

class UserMissionEventDaily extends UserDataBasePage implements HasTable
{
    use InteractsWithTable;

    protected static string $view = 'filament.pages.user-mission-event-daily';

    public string $currentTab = UserSearchTabs::MISSION_EVENT_DAILY->value;

    public function mount()
    {
        parent::mount(); // TODO: Change the autogenerated stub
        $this->breadcrumbList = array_merge($this->breadcrumbList, [
            self::getUrl(['userId' => $this->userId]) => $this->currentTab,
        ]);
    }

    public function table(Table $table): Table
    {
        $query = MstMissionEventDaily::query()
            ->with([
                'mst_mission_i18n',
            ]);

        $usrMissionEventDailies = UsrMissionEvent::query()
            ->where('usr_user_id', $this->userId)
            ->get()
            ->keyBy(function (UsrMissionEvent $usrMissionEvent) {
                return $usrMissionEvent->mst_mission_id;
            });

        return $table
            ->query($query)
            ->searchable(false)
            ->hiddenFilterIndicators()
            ->columns([
                MstMissionInfoColumn::make('mst_mission_info')
                    ->label('ミッション情報')
                    ->searchable()
                    ->getStateUsing(
                        function (MstMissionEventDaily $mstMission) {
                            return $mstMission;
                        }
                    ),
                TextColumn::make('status_label')
                    ->label('ステータス')
                    ->searchable()
                    ->getStateUsing(
                        function (MstMissionEventDaily $mstMission) use ($usrMissionEventDailies) {
                            $usrMissionEventDaily = $usrMissionEventDailies->get($mstMission->id);
                            return $usrMissionEventDaily?->status_label ?? MissionStatus::LOCKED->label();
                        }
                    )
                    ->badge(true)
                    ->color(function (MstMissionEventDaily $mstMission) use ($usrMissionEventDailies) {
                        $usrMissionEventDaily = $usrMissionEventDailies->get($mstMission->id);
                        return $usrMissionEventDaily?->status_badge ?? MissionStatus::LOCKED->badge();
                    }),
                TextColumn::make('open_status')
                    ->label('開放ステータス')
                    ->searchable()
                    ->getStateUsing(
                        function (MstMissionEventDaily $mstMission) use ($usrMissionEventDailies) {
                            $usrMissionEventDaily = $usrMissionEventDailies->get($mstMission->id);
                            return $usrMissionEventDaily?->is_open ? MissionUnlockStatus::OPEN->label() : MissionUnlockStatus::LOCK->label();
                        }
                    )
                    ->badge(true)
                    ->color(function (MstMissionEventDaily $mstMission) use ($usrMissionEventDailies) {
                        $usrMissionEventDaily = $usrMissionEventDailies->get($mstMission->id);
                        return $usrMissionEventDaily?->is_open ? MissionUnlockStatus::OPEN->badge() : MissionUnlockStatus::LOCK->badge();
                    }),
                TextColumn::make('progress')
                    ->label('進捗値')
                    ->searchable()
                    ->getStateUsing(
                        function (MstMissionEventDaily $mstMission) use ($usrMissionEventDailies) {
                            $usrMissionEventDaily = $usrMissionEventDailies->get($mstMission->id);
                            return $usrMissionEventDaily?->progress ?? 0;
                        }
                    ),
                TextColumn::make('cleared_at')
                    ->label('達成日時')
                    ->searchable()
                    ->getStateUsing(
                        function (MstMissionEventDaily $mstMission) use ($usrMissionEventDailies) {
                            $usrMissionEventDaily = $usrMissionEventDailies->get($mstMission->id);
                            return $usrMissionEventDaily?->cleared_at ?? '';
                        }
                    ),
                TextColumn::make('received_reward_at')
                    ->label('報酬受取日時')
                    ->searchable()
                    ->getStateUsing(
                        function (MstMissionEventDaily $mstMission) use ($usrMissionEventDailies) {
                            $usrMissionEventDaily = $usrMissionEventDailies->get($mstMission->id);
                            return $usrMissionEventDaily?->received_reward_at ?? '';
                        }
                    ),
                ])
            ->filters([
                Filter::make('id')
                    ->form([
                        TextInput::make('id')
                            ->label('ミッションID')
                    ])
                    ->label('ミッションID')
                    ->query(function (Builder $query, array $data): Builder {
                        if (blank($data['id'])) {
                            return $query;
                        }
                        return $query->where('id', $data['id']);
                    }),
                Filter::make('description')
                    ->form([
                        TextInput::make('description')
                            ->label('ミッション説明')
                    ])
                    ->label('ミッション説明')
                    ->query(function (Builder $query, array $data): Builder {
                        if (blank($data['description'])) {
                            return $query;
                        }
                        return $query->whereHas('mst_mission_i18n', function ($query) use ($data) {
                            $query->where('description', 'like', "%{$data['description']}%");
                        });
                    }),
                SelectFilter::make('status')
                    ->options(MissionStatus::labels()->toArray())
                    ->query(function (Builder $query, $data): Builder {
                        if (blank($data['value'])) {
                            return $query;
                        }

                        if ($data['value'] == MissionStatus::LOCKED->value) {
                            $missionIds = UsrMissionEvent::query()
                                ->where('usr_user_id', $this->userId)
                                ->where('mission_type', MissionType::EVENT_DAILY->getIntValue())
                                ->pluck('mst_mission_id');
                            return $query->whereNotIn('id', $missionIds);
                        }

                        $missionIds = UsrMissionEvent::query()
                            ->where('usr_user_id', $this->userId)
                            ->where('status', $data)
                            ->where('mission_type', MissionType::EVENT_DAILY->getIntValue())
                            ->pluck('mst_mission_id');
                        return $query->whereIn('id', $missionIds);
                    })
                    ->label('ステータス'),
                ], FiltersLayout::AboveContent)
            ->deferFilters()
            ->filtersApplyAction(
                fn (Action $action) => $action
                    ->label('適用'),
            )
            ->actions([
                Action::make('edit')
                    ->label('編集')
                    ->button()
                    ->url(function (MstMissionEventDaily $mstMission) {
                        return EditUserMissionEvent::getUrl([
                            'userId' => $this->userId,
                            'mstMissionId' => $mstMission->id,
                            'missionType' => MissionType::EVENT_DAILY->getIntValue()
                        ]);
                    })
                    ->visible(fn () => EditUserMissionEvent::canAccess()),
            ], position: ActionsPosition::BeforeColumns);
    }

}
