<?php

namespace App\Filament\Pages;

use App\Constants\MissionStatus;
use App\Constants\MissionType;
use App\Constants\MissionUnlockStatus;
use App\Constants\UserSearchTabs;
use App\Filament\Pages\User\UserDataBasePage;
use App\Models\Mst\MstMissionDaily;
use App\Models\Usr\UsrMissionNormal;
use App\Tables\Columns\MstMissionInfoColumn;
use Filament\Forms\Components\TextInput;
use Filament\Tables\Actions\Action;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Concerns\InteractsWithTable;
use Filament\Tables\Contracts\HasTable;
use Filament\Tables\Enums\ActionsPosition;
use Filament\Tables\Enums\FiltersLayout;
use Filament\Tables\Filters\Filter;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;

class UserMissionDaily extends UserDataBasePage implements HasTable
{
    use InteractsWithTable;

    protected static string $view = 'filament.pages.user-mission-daily';

    public string $currentTab = UserSearchTabs::MISSION_DAILY->value;

    public function mount()
    {
        parent::mount(); // TODO: Change the autogenerated stub
        $this->breadcrumbList = array_merge($this->breadcrumbList, [
            self::getUrl(['userId' => $this->userId]) => $this->currentTab,
        ]);
    }

    public function table(Table $table): Table
    {
        $query = MstMissionDaily::query()
            ->with([
                'mst_mission_i18n'
            ]);

        $usrMissionDailys = UsrMissionNormal::query()
            ->where('usr_user_id', $this->userId)
            ->where('mission_type', MissionType::DAILY->getIntValue())
            ->get()
            ->keyBy('mst_mission_id');

        return $table
            ->query($query)
            ->searchable(false)
            ->hiddenFilterIndicators()
            ->columns([
                MstMissionInfoColumn::make('mst_mission_info')
                    ->label('ミッション情報')
                    ->searchable()
                    ->getStateUsing(
                        function (MstMissionDaily $mstMission) {
                            return $mstMission;
                        }
                    ),
                TextColumn::make('status_label')
                    ->label('ミッションステータス')
                    ->searchable()
                    ->getStateUsing(
                        function (MstMissionDaily $mstMission) use ($usrMissionDailys) {
                            $usrMissionDaily = $usrMissionDailys->get($mstMission->id);
                            return $usrMissionDaily?->status_label ?? MissionStatus::LOCKED->label();
                        }
                    )
                    ->badge(true)
                    ->color(function (MstMissionDaily $mstMission) use ($usrMissionDailys) {
                        $usrMissionDaily = $usrMissionDailys->get($mstMission->id);
                        return $usrMissionDaily?->status_badge ?? MissionStatus::LOCKED->badge();
                    }),
                TextColumn::make('open_status')
                    ->label('開放ステータス')
                    ->searchable()
                    ->getStateUsing(
                        function (MstMissionDaily $mstMission) use ($usrMissionDailys) {
                            $usrMissionDaily = $usrMissionDailys->get($mstMission->id);
                            return $usrMissionDaily?->is_open ? MissionUnlockStatus::OPEN->label() : MissionUnlockStatus::LOCK->label();
                        }
                    )
                    ->badge(true)
                    ->color(function (MstMissionDaily $mstMission) use ($usrMissionDailys) {
                        $usrMissionDaily = $usrMissionDailys->get($mstMission->id);
                        return $usrMissionDaily?->is_open ? MissionUnlockStatus::OPEN->badge() : MissionUnlockStatus::LOCK->badge();
                    }),
                TextColumn::make('progress')
                    ->label('進捗値')
                    ->searchable()
                    ->getStateUsing(
                        function (MstMissionDaily $mstMission) use ($usrMissionDailys) {
                            $usrMissionDaily = $usrMissionDailys->get($mstMission->id);
                            return $usrMissionDaily?->progress ?? 0;
                        }
                    ),
                TextColumn::make('unlock_progress')
                    ->label('開放進捗値')
                    ->searchable()
                    ->getStateUsing(
                        function (MstMissionDaily $mstMission) use ($usrMissionDailys) {
                            $usrMissionDaily = $usrMissionDailys->get($mstMission->id);
                            return $usrMissionDaily?->unlock_progress ?? 0;
                        }
                    ),
                TextColumn::make('cleared_at')
                    ->label('達成日時')
                    ->searchable()
                    ->getStateUsing(
                        function (MstMissionDaily $mstMission) use ($usrMissionDailys) {
                            $usrMissionDaily = $usrMissionDailys->get($mstMission->id);
                            return $usrMissionDaily?->cleared_at ?? '';
                        }
                    ),
                TextColumn::make('received_reward_at')
                    ->label('報酬受取日時')
                    ->searchable()
                    ->getStateUsing(
                        function (MstMissionDaily $mstMission) use ($usrMissionDailys) {
                            $usrMissionDaily = $usrMissionDailys->get($mstMission->id);
                            return $usrMissionDaily?->received_reward_at ?? '';
                        }
                    ),
                ])
                ->filters([
                    Filter::make('id')
                        ->form([
                            TextInput::make('id')
                                ->label('ミッションID')
                        ])
                        ->label('ミッションID')
                        ->query(function (Builder $query, array $data): Builder {
                            if (blank($data['id'])) {
                                return $query;
                            }
                            return $query->where('id', $data['id']);
                        }),
                    Filter::make('description')
                        ->form([
                            TextInput::make('description')
                                ->label('ミッション説明')
                        ])
                        ->label('ミッション説明')
                        ->query(function (Builder $query, array $data): Builder {
                            if (blank($data['description'])) {
                                return $query;
                            }
                            return $query->whereHas('mst_mission_i18n', function ($query) use ($data) {
                                $query->where('description', 'like', "%{$data['description']}%");
                            });
                        }),
                    SelectFilter::make('status')
                        ->options(MissionStatus::labels()->toArray())
                        ->query(function (Builder $query, $data): Builder {
                            if (blank($data['value'])) {
                                return $query;
                            }

                            if ($data['value'] == MissionStatus::LOCKED->value) {
                                $missionIds = UsrMissionNormal::query()
                                    ->where('usr_user_id', $this->userId)
                                    ->where('mission_type', MissionType::DAILY->getIntValue())
                                    ->pluck('mst_mission_id');
                                return $query->whereNotIn('id', $missionIds);
                            }

                            $missionIds = UsrMissionNormal::query()
                                ->where('usr_user_id', $this->userId)
                                ->where('mission_type', MissionType::DAILY->getIntValue())
                                ->where('status', $data['value'])
                                ->pluck('mst_mission_id');
                            return $query->whereIn('id', $missionIds);
                        })
                        ->label('ミッションステータス'),
                    ], FiltersLayout::AboveContent)
                ->deferFilters()
                ->filtersApplyAction(
                    fn (Action $action) => $action
                        ->label('適用'),
                )
                ->actions([
                    Action::make('edit')
                        ->label('編集')
                        ->button()
                        ->url(function (MstMissionDaily $mstMission) {
                            return EditUserMission::getUrl([
                                'userId' => $this->userId,
                                'mstMissionId' => $mstMission->id,
                                'missionType' => MissionType::DAILY->getIntValue()
                            ]);
                        })
                        ->visible(fn () => EditUserMission::canAccess()),
                ], position: ActionsPosition::BeforeColumns);
                ;
    }
}
