<?php

namespace App\Filament\Pages;

use App\Constants\ProductType;
use App\Constants\UserSearchTabs;
use App\Filament\Pages\User\UserDataBasePage;
use App\Models\Opr\OprProduct;
use App\Tables\Columns\OprProductInfoColumn;
use Filament\Forms\Components\DatePicker;
use Filament\Tables\Actions\Action;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Concerns\InteractsWithTable;
use Filament\Tables\Contracts\HasTable;
use Filament\Tables\Enums\ActionsPosition;
use Filament\Tables\Enums\FiltersLayout;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;

class UserStoreProduct extends UserDataBasePage implements HasTable
{
    use InteractsWithTable;

    protected static ?string $navigationIcon = 'heroicon-o-document-text';

    protected static string $view = 'filament.pages.user-store-product';

    public string $currentTab = UserSearchTabs::SHOP_PURCHASE->value;

    public function mount()
    {
        parent::mount(); // TODO: Change the autogenerated stub
        $this->breadcrumbList = array_merge($this->breadcrumbList, [
            self::getUrl(['userId' => $this->userId]) => UserSearchTabs::SHOP_PURCHASE->value,
        ]);
    }

    public function table(Table $table): Table
    {
        $query = OprProduct::query()
            ->with([
                'usr_store_product' => function ($query) {
                    $query->where('usr_user_id', $this->userId);
                },
            ]);

        return $table
            ->query($query)
            ->searchable(false)
            ->hiddenFilterIndicators()
            ->columns([
                OprProductInfoColumn::make('opr_product_info')
                    ->label('ストア商品情報')
                    ->searchable()
                    ->getStateUsing(
                        function (OprProduct $oprProduct) {
                            return $oprProduct;
                        }
                    ),
                TextColumn::make('purchase_count')
                    ->label('購入回数')
                    ->searchable()
                    ->getStateUsing(
                        function (OprProduct $oprProduct) {
                            return $oprProduct->usr_store_product?->purchase_count ?? 0;
                        }
                    ),
                TextColumn::make('purchase_total_count')
                    ->label('累計購入回数')
                    ->searchable()
                    ->getStateUsing(
                        function (OprProduct $oprProduct) {
                            return $oprProduct->usr_store_product?->purchase_total_count ?? 0;
                        }
                    ),
                TextColumn::make('last_reset_at')
                    ->label('最終リセット日時')
                    ->searchable()
                    ->getStateUsing(
                        function (OprProduct $oprProduct) {
                            return $oprProduct->usr_store_product?->last_reset_at ?? "-";
                        }
                    ),
            ])
            ->filters([
                SelectFilter::make('product_type')
                    ->options(ProductType::labels()->toArray())
                    ->query(function (Builder $query, $data): Builder {
                        if (blank($data['value'])) {
                            return $query;
                        }
                        return $query->where('product_type', $data);
                    })
                    ->label('商品タイプ'),
                SelectFilter::make('duration')
                    ->form([
                        DatePicker::make('datetime')
                                ->label('有効日時'),
                    ])
                    ->label('有効日時')
                    ->query(function (Builder $query, array $data): Builder {
                        if (blank($data['datetime'])) {
                            return $query;
                        }
                        return $query->where('start_date', '<=', $data['datetime'])
                            ->where('end_date', '>=', $data['datetime']);
                    }),
                ], FiltersLayout::AboveContent)
            ->deferFilters()
            ->filtersApplyAction(
                fn (Action $action) => $action
                    ->label('適用'),
            )
            ->actions([
                Action::make('edit')
                    ->label('編集')
                    ->button()
                    ->url(function (OprProduct $record) {
                        return EditUserStoreProduct::getUrl([
                            'userId' => $this->userId,
                            'productSubId' => $record->id,
                        ]);
                    })
                    ->visible(fn () => EditUserStoreProduct::canAccess()),
            ], position: ActionsPosition::BeforeColumns);
    }
}
