<?php

namespace App\Filament\Pages;

use App\Constants\MissionDailyBonusType;
use App\Constants\MissionStatus;
use App\Constants\UserSearchTabs;
use App\Filament\Pages\User\UserDataBasePage;
use App\Models\Mst\MstMissionDailyBonus;
use App\Models\Usr\UsrMissionDailyBonus;
use App\Models\Usr\UsrUserLogin;
use App\Tables\Columns\MstMissionDailyBonusInfoColumn;
use Filament\Forms\Components\TextInput;
use Filament\Tables\Actions\Action;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Concerns\InteractsWithTable;
use Filament\Tables\Contracts\HasTable;
use Filament\Tables\Enums\ActionsPosition;
use Filament\Tables\Enums\FiltersLayout;
use Filament\Tables\Filters\Filter;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;

class UserMissionDailyBonus extends UserDataBasePage implements HasTable
{
    use InteractsWithTable;

    protected static ?string $navigationIcon = 'heroicon-o-document-text';

    protected static string $view = 'filament.pages.user-mission-daily-bonus';

    public string $currentTab = UserSearchTabs::MISSION_DAILY_BONUS->value;

    public function mount()
    {
        parent::mount(); // TODO: Change the autogenerated stub
        $this->breadcrumbList = array_merge($this->breadcrumbList, [
            self::getUrl(['userId' => $this->userId]) => $this->currentTab,
        ]);
    }

    public function table(Table $table): Table
    {
        $query = MstMissionDailyBonus::query()
            ->with([
                'usr_mission' => function ($query) {
                    $query->where('usr_user_id', $this->userId);
                },
            ]);

        $usrUserLogin = UsrUserLogin::where('usr_user_id', $this->userId)->first();
        $loginDayCount = $usrUserLogin?->getLoginDayCount() ?? 0;
        $loginContinueDayCount = $usrUserLogin?->getLoginContinueDayCount() ?? 0;

        return $table
            ->query($query)
            ->searchable(false)
            ->hiddenFilterIndicators()
            ->columns([
                MstMissionDailyBonusInfoColumn::make('mst_mission_daily_bonus_info')
                    ->label('ログボ情報')
                    ->searchable()
                    ->getStateUsing(
                        function (MstMissionDailyBonus $mstMission) {
                            return $mstMission;
                        }
                    ),
                TextColumn::make('status_label')
                    ->label('ステータス')
                    ->searchable()
                    ->getStateUsing(
                        function (MstMissionDailyBonus $mstMission) {
                            return $mstMission->usr_mission?->status_label ?? MissionStatus::LOCKED->label();
                        }
                    )
                    ->badge(true)
                    ->color(function (MstMissionDailyBonus $mstMission) {
                        return $mstMission->usr_mission?->status_badge ?? MissionStatus::LOCKED->badge();
                    }),
                TextColumn::make('progress')
                    ->label('進捗値')
                    ->searchable()
                    ->getStateUsing(
                        function (MstMissionDailyBonus $mstMission) use ($loginDayCount, $loginContinueDayCount) {
                            switch ($mstMission->type) {
                                case MissionDailyBonusType::DAILY_BONUS->value:
                                    return $loginContinueDayCount;
                                default:
                                    return 0;
                            }
                        }
                    ),
                TextColumn::make('cleared_at')
                    ->label('達成日時')
                    ->searchable()
                    ->getStateUsing(
                        function (MstMissionDailyBonus $mstMission) {
                            return $mstMission->usr_mission?->cleared_at ?? '';
                        }
                    ),
                TextColumn::make('received_reward_at')
                    ->label('報酬受取日時')
                    ->searchable()
                    ->getStateUsing(
                        function (MstMissionDailyBonus $mstMission) {
                            return $mstMission->usr_mission?->received_reward_at ?? '';
                        }
                    ),
                ])
            ->filters([
                Filter::make('id')
                    ->form([
                        TextInput::make('id')
                            ->label('ミッションID')
                    ])
                    ->label('ミッションID')
                    ->query(function (Builder $query, array $data): Builder {
                        if (blank($data['id'])) {
                            return $query;
                        }
                        return $query->where('id', $data['id']);
                    }),
                SelectFilter::make('type')
                    ->options(MissionDailyBonusType::labels()->toArray())
                    ->query(function (Builder $query, $data): Builder {
                        if (blank($data['value'])) {
                            return $query;
                        }

                        return $query->where('type', $data['value']);
                    })
                    ->label('ログボタイプ'),
                Filter::make('login_day_count')
                    ->form([
                        TextInput::make('login_day_count')
                            ->label('ログイン日数')
                    ])
                    ->label('ログイン日数')
                    ->query(function (Builder $query, array $data): Builder {
                        if (blank($data['login_day_count'])) {
                            return $query;
                        }
                        return $query->where('login_day_count', $data['login_day_count']);
                    }),
                SelectFilter::make('status')
                    ->options(MissionStatus::labels()->toArray())
                    ->query(function (Builder $query, $data): Builder {
                        if (blank($data['value'])) {
                            return $query;
                        }

                        if ($data['value'] == MissionStatus::LOCKED->value) {
                            $missionIds = UsrMissionDailyBonus::query()
                                ->where('usr_user_id', $this->userId)
                                ->pluck('mst_mission_daily_bonus_id');
                            return $query->whereNotIn('id', $missionIds);
                        }

                        $missionIds = UsrMissionDailyBonus::query()
                            ->where('usr_user_id', $this->userId)
                            ->where('status', $data)
                            ->pluck('mst_mission_daily_bonus_id');
                        return $query->whereIn('id', $missionIds);
                    })
                    ->label('ステータス'),
                ], FiltersLayout::AboveContent)
            ->deferFilters()
            ->filtersApplyAction(
                fn (Action $action) => $action
                    ->label('適用'),
            )
            ->actions([
                Action::make('edit')
                    ->label('編集')
                    ->button()
                    ->url(function (MstMissionDailyBonus $mstMission) {
                        return EditUserMissionDailyBonus::getUrl([
                            'userId' => $this->userId,
                            'mstMissionId' => $mstMission->id,
                        ]);
                    })
                    ->visible(fn () => EditUserMissionDailyBonus::canAccess()),
            ], position: ActionsPosition::BeforeColumns);
    }
}
