<?php

namespace App\Filament\Pages;

use App\Constants\RewardReceiptStatusType;
use App\Constants\UserSearchTabs;
use App\Entities\Clock;
use App\Filament\Pages\User\UserDataBasePage;
use App\Models\Mst\MstAdventBattle;
use App\Models\Usr\UsrAdventBattle;
use App\Traits\RewardInfoGetTrait;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\TextInput;
use Filament\Tables\Actions\Action;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Concerns\InteractsWithTable;
use Filament\Tables\Contracts\HasTable;
use Filament\Tables\Enums\ActionsPosition;
use Filament\Tables\Enums\FiltersLayout;
use Filament\Tables\Filters\Filter;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;

class UserAdventBattle extends UserDataBasePage implements HasTable
{
    use InteractsWithTable;
    use RewardInfoGetTrait;

    protected static ?string $navigationIcon = 'heroicon-o-document-text';

    protected static string $view = 'filament.pages.user-advent-battle';
    public string $currentTab = UserSearchTabs::ADVENT_BATTLE->value;

    public function mount()
    {
        parent::mount(); // TODO: Change the autogenerated stub
        $this->breadcrumbList = array_merge($this->breadcrumbList, [
            self::getUrl(['userId' => $this->userId]) => $this->currentTab,
        ]);
    }

    public function table(Table $table): Table
    {
        $query = UsrAdventBattle::query()
            ->where('usr_user_id', $this->userId)
            ->orderBy('created_at', 'desc');

        $mstAdventBattles = MstAdventBattle::query()
            ->get()
            ->keyBy(function (MstAdventBattle $mstAdventBattle) {
                return $mstAdventBattle->id;
            });

        return $table
            ->query($query)
            ->searchable(false)
            ->hiddenFilterIndicators()
            ->columns([
                TextColumn::make('mst_advent_battle_id')
                    ->label('降臨バトルID'),
                TextColumn::make('start_at')
                    ->label('開始日')
                    ->searchable()
                    ->getStateUsing(
                        function (UsrAdventBattle $usrAdventBattle) use ($mstAdventBattles) {
                            $mstAdventBattle = $mstAdventBattles->get($usrAdventBattle->mst_advent_battle_id);
                            return $mstAdventBattle?->start_at;
                        }
                    ),
                TextColumn::make('end_at')
                    ->label('終了日')
                    ->searchable()
                    ->getStateUsing(
                        function (UsrAdventBattle $usrAdventBattle) use ($mstAdventBattles) {
                            $mstAdventBattle = $mstAdventBattles->get($usrAdventBattle->mst_advent_battle_id);
                            return $mstAdventBattle?->end_at;
                        }
                    ),
                TextColumn::make('max_score')
                    ->label('最大スコア'),
                TextColumn::make('total_score')
                    ->label('合計スコア'),
                TextColumn::make('challenge_count')
                    ->label('通算挑戦回数')
                    ->tooltip('挑戦回数(リセットなし)'),
                TextColumn::make('reset_challenge_count')
                    ->label('デイリー挑戦回数')
                    ->tooltip('挑戦回数(デイリーリセット対象)')
                    ->getStateUsing(
                        function ($record) {
                            return $this->checkReset($record->latest_reset_at, $record->reset_challenge_count);
                        }
                    ),
                TextColumn::make('reset_ad_challenge_count')
                    ->label('広告視聴挑戦回数')
                    ->tooltip('広告視聴での挑戦回数(デイリーリセット対象)')
                    ->getStateUsing(
                        function ($record) {
                            return $this->checkReset($record->latest_reset_at, $record->reset_ad_challenge_count);
                        }
                    ),
                TextColumn::make('max_received_max_score_reward')
                    ->label('最大スコア報酬')
                    ->tooltip('受取済みの最大スコア報酬の最大スコア')
                    ->getStateUsing(
                        function ($record) {
                            return $this->checkReset($record->latest_reset_at, $record->max_received_max_score_reward);
                        }
                    ),
                TextColumn::make('is_ranking_reward_received')
                    ->label('報酬受取り状況')
                    ->tooltip('順位またはランク報酬')
                    ->getStateUsing(
                        function ($record) {
                            return RewardReceiptStatusType::tryFrom($record->is_ranking_reward_received)->label();
                        }
                    ),
                TextColumn::make('latest_reset_at')
                    ->label('リセット日時'),
            ])
            ->filters([
                Filter::make('mst_advent_battle_id')
                    ->form([
                        TextInput::make('mst_advent_battle_id')
                            ->label('降臨バトルID')
                    ])
                    ->label('降臨バトルID')
                    ->query(function (Builder $query, array $data): Builder {
                        if (blank($data['mst_advent_battle_id'])) {
                            return $query;
                        }
                        return $query->where('mst_advent_battle_id', 'like', "%{$data['mst_advent_battle_id']}%");
                    }),
                SelectFilter::make('duration')
                    ->form([
                        DatePicker::make('datetime')
                            ->label('開催期間'),
                    ])
                    ->label('有効日時')
                    ->query(function (Builder $query, array $data): Builder {
                        if (blank($data['datetime'])) {
                            return $query;
                        }
                        $mstAdventBattleIds = MstAdventBattle::query()
                            ->where('start_at', '<=', $data['datetime'])
                            ->where('end_at', '>=', $data['datetime'])
                            ->pluck('id');
                        return $query->whereIn('mst_advent_battle_id', $mstAdventBattleIds);
                    }),
                ], FiltersLayout::AboveContent)
            ->filtersFormColumns(3)
            ->deferFilters()
            ->filtersApplyAction(
                fn (Action $action) => $action
                    ->label('適用'),
            )
            ->actions([
                Action::make('edit')
                    ->label('編集')
                    ->button()
                    ->url(function (UsrAdventBattle $record) {
                        return EditUserAdventBattle::getUrl([
                            'userId' => $this->userId,
                            'mstAdventBattleId' => $record->mst_advent_battle_id,
                        ]);
                    })
                    ->visible(fn () => EditUserAdventBattle::canAccess()),
            ], position: ActionsPosition::BeforeColumns);
        ;
    }

    private function checkReset(string $latestResetAt = null, int $count) {
        $clock = app(Clock::class);
        if ($clock->isFirstToday($latestResetAt ?? '')) {
            return 0;
        }
        return $count;
    }
}
