<?php

namespace App\Filament\Pages;

use App\Constants\MessageSource;
use App\Constants\UserSearchTabs;
use App\Filament\Pages\User\UserDataBasePage;
use App\Models\Usr\UsrMessage;
use App\Services\Reward\RewardInfoGetHandleService;
use App\Tables\Columns\RewardInfoColumn;
use Filament\Forms\Components\TextInput;
use Filament\Tables\Actions\Action;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Concerns\InteractsWithTable;
use Filament\Tables\Contracts\HasTable;
use Filament\Tables\Enums\FiltersLayout;
use Filament\Tables\Filters\Filter;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Collection;

class UserMailBox extends UserDataBasePage implements HasTable
{
    use InteractsWithTable;
    protected static ?string $navigationIcon = 'heroicon-o-document-text';

    protected static string $view = 'filament.pages.user-mail-box';

    public string $currentTab = UserSearchTabs::MAIL_BOX->value;

    private static ?RewardInfoGetHandleService $rewardInfoGetHandleService = null;

    private static Collection $rewardInfos;

    private static function initializeService(): void
    {
        if (is_null(self::$rewardInfoGetHandleService)) {
            self::$rewardInfoGetHandleService = app(RewardInfoGetHandleService::class);
        }
    }

    public function mount()
    {
        parent::mount(); // TODO: Change the autogenerated stub
        $this->breadcrumbList = array_merge($this->breadcrumbList, [
            self::getUrl(['userId' => $this->userId]) => $this->currentTab,
        ]);
    }

    private function table(Table $table): Table
    {

        $query = UsrMessage::query()
            ->with([
                'mng_message',
                'mng_message.mng_message_i18n',
            ])
            ->where('usr_user_id', $this->userId)
            ->orderBy('created_at', 'DESC');

        $rewardDtoList = UsrMessage::query()->whereNotNull('resource_type')->get()->map(function (UsrMessage $usrMessage) {
            if ($usrMessage->resource_type) {
                return $usrMessage->reward;
            }
        });
        self::initializeService();

        self::$rewardInfos = self::$rewardInfoGetHandleService->build($rewardDtoList)->getRewardInfos();

        return $table
            ->query($query)
            ->searchable(false)
            ->hiddenFilterIndicators()
            ->columns([
                TextColumn::make('id')
                    ->label('ID'),
                TextColumn::make('title')
                    ->label('タイトル')
                    ->getStateUsing(function ($record) {
                        $title = $record->title;
                        if ($record->mng_message_id) {
                            $title = $record->mng_message->mng_message_i18n->title;
                        }
                        return $title;
                    }),
                TextColumn::make('body')
                    ->label('本文')
                    ->getStateUsing(function ($record) {
                        $body = $record->body;
                        if ($record->mng_message_id) {
                            $body = $record->mng_message->mng_message_i18n->body;
                        }
                        return $body;
                    }),
                TextColumn::make('message_source')
                    ->label('メッセージ送信元')
                    ->getStateUsing(
                        function ($record) {
                            $messageSource = MessageSource::tryFrom($record?->message_source);
                            return $messageSource?->label() ?? $record?->message_source ?? '';
                        }
                    ),
                TextColumn::make('expired_at')
                    ->label('受け取り期限日時')
                    ->getStateUsing(function ($record) {
                        $expired_at = $record->expired_at;
                        if (!$expired_at) {
                            $expired_at = '期限なし';
                        }
                        return $expired_at;
                    }),
                TextColumn::make('opened_at')
                    ->label('読んだ日付')
                    ->getStateUsing(function ($record) {
                        $opened_at = $record->opened_at;
                        if (!$opened_at) {
                            $opened_at = '未読';
                        }
                        return $opened_at;
                    }),
                TextColumn::make('received_at')
                    ->label('報酬受取日')
                    ->getStateUsing(function ($record) {
                        $received_at = $record->received_at;
                        if (!$received_at) {
                            $received_at = '受け取り前';
                        }
                        return $received_at;
                    }),
                TextColumn::make('resource_type')
                    ->label('報酬タイプ'),
                RewardInfoColumn::make('resource_id')
                    ->label('報酬情報')
                    ->getStateUsing(
                        function ($record) {
                            return self::$rewardInfos->get($record->id);
                        }
                    ),
            ])
            ->filters([
                Filter::make('id')
                    ->form([
                        TextInput::make('id')
                            ->label('ID')
                    ])
                    ->query(function (Builder $query, array $data): Builder {
                        if (blank($data['id'])) {
                            return $query;
                        }
                        return $query->where('id', 'like', "%{$data['id']}%");
                    }),
                Filter::make('title')
                    ->form([
                        TextInput::make('title')
                            ->label('タイトル')
                    ])
                    ->query(function (Builder $query, array $data): Builder {
                        if (blank($data['title'])) {
                            return $query;
                        }
                        return $query->where('title', 'like', "%{$data['title']}%");
                    }),
                SelectFilter::make('message_source')
                    ->options(MessageSource::labels()->toArray())
                    ->query(function (Builder $query, $data): Builder {
                        if (blank($data['value'])) {
                            return $query;
                        }
                        return
                            $query->where('message_source', $data);
                    })
                    ->label('メッセージ送信元'),
            ], FiltersLayout::AboveContent)
            ->filtersFormColumns(4)
            ->deferFilters()
            ->filtersApplyAction(
                fn(Action $action) => $action
                    ->label('検索'),
            )->actions([]);
    }
}
