// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Threading;
using Cysharp.Threading.Tasks;
using Newtonsoft.Json;
using UnityEngine;
using UnityHTTPLibrary;
using WPFramework.Data.Extensions;
using GLOW.Core.Data.Data;
using GLOW.Core.Domain.Constants;
using Zenject;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.DataStores
{
    public sealed class EncyclopediaApi
    {
        [Serializable]
        class JsonParamReceiveReward
        {
            [IgnoreDataMember] [JsonIgnore]
            public string[] MstUnitEncyclopediaRewardIds {
                get => mstUnitEncyclopediaRewardIds;
                set => mstUnitEncyclopediaRewardIds = value;
            }
            [DataMember(Name = "mstUnitEncyclopediaRewardIds")] [SerializeField] [JsonProperty("mstUnitEncyclopediaRewardIds")] string[] mstUnitEncyclopediaRewardIds;
        }
        [Serializable]
        class JsonParamReceiveFirstCollectionReward
        {
            [IgnoreDataMember] [JsonIgnore]
            public string EncyclopediaType {
                get => encyclopediaType;
                set => encyclopediaType = value;
            }
            [IgnoreDataMember] [JsonIgnore]
            public string EncyclopediaId {
                get => encyclopediaId;
                set => encyclopediaId = value;
            }
            [DataMember(Name = "encyclopediaType")] [SerializeField] [JsonProperty("encyclopediaType")] string encyclopediaType;
            [DataMember(Name = "encyclopediaId")] [SerializeField] [JsonProperty("encyclopediaId")] string encyclopediaId;
        }

        [Inject(Id = WPFramework.Constants.Zenject.FrameworkInjectId.ServerApi.Game)] ServerApi APIContext { get; }

        public async UniTask<EncyclopediaReceiveRewardResultData> ReceiveReward(CancellationToken cancellationToken, string[] mstUnitEncyclopediaRewardIds)
        {
            var param = new JsonParamReceiveReward();
            param.MstUnitEncyclopediaRewardIds = mstUnitEncyclopediaRewardIds;
            var json = JsonConvert.SerializeObject(param);
            var payload = new Payload()
            {
                Data = System.Text.Encoding.UTF8.GetBytes(json),
                ContentType = MimeTypes.Json
            };
    
            return await APIContext.Post<EncyclopediaReceiveRewardResultData>(cancellationToken, "/api/encyclopedia/receive_reward", payload);
        }
        public async UniTask<EncyclopediaReceiveFirstCollectionRewardResultData> ReceiveFirstCollectionReward(CancellationToken cancellationToken, string encyclopediaType, string encyclopediaId)
        {
            var param = new JsonParamReceiveFirstCollectionReward();
            param.EncyclopediaType = encyclopediaType;
            param.EncyclopediaId = encyclopediaId;
            var json = JsonConvert.SerializeObject(param);
            var payload = new Payload()
            {
                Data = System.Text.Encoding.UTF8.GetBytes(json),
                ContentType = MimeTypes.Json
            };
    
            return await APIContext.Post<EncyclopediaReceiveFirstCollectionRewardResultData>(cancellationToken, "/api/encyclopedia/receive_first_collection_reward", payload);
        }
    }
}
