using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Threading;
using Cysharp.Threading.Tasks;
using Newtonsoft.Json;
using UnityEngine;
using UnityHTTPLibrary;
using WPFramework.Data.Extensions;
using GLOW.Core.Data.Data;
using GLOW.Core.Domain.Constants;
using Zenject;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.DataStores
{
    public sealed class ExchangeApi
    {
        [Serializable]
        class JsonParamTrade
        {
            [IgnoreDataMember] [JsonIgnore]
            public string MstExchangeId {
                get => mstExchangeId;
                set => mstExchangeId = value;
            }
            [IgnoreDataMember] [JsonIgnore]
            public string MstExchangeLineupId {
                get => mstExchangeLineupId;
                set => mstExchangeLineupId = value;
            }
            [IgnoreDataMember] [JsonIgnore]
            public int TradeCount {
                get => tradeCount;
                set => tradeCount = value;
            }
            [DataMember(Name = "mstExchangeId")] [SerializeField] [JsonProperty("mstExchangeId")] string mstExchangeId;
            [DataMember(Name = "mstExchangeLineupId")] [SerializeField] [JsonProperty("mstExchangeLineupId")] string mstExchangeLineupId;
            [DataMember(Name = "tradeCount")] [SerializeField] [JsonProperty("tradeCount")] int tradeCount;
        }

        [Inject(Id = WPFramework.Constants.Zenject.FrameworkInjectId.ServerApi.Game)] ServerApi APIContext { get; }

        public async UniTask<ExchangeTradeResultData> Trade(CancellationToken cancellationToken, string mstExchangeId, string mstExchangeLineupId, int tradeCount)
        {
            var param = new JsonParamTrade();
            param.MstExchangeId = mstExchangeId;
            param.MstExchangeLineupId = mstExchangeLineupId;
            param.TradeCount = tradeCount;
            var json = JsonConvert.SerializeObject(param);
            var payload = new Payload()
            {
                Data = System.Text.Encoding.UTF8.GetBytes(json),
                ContentType = MimeTypes.Json
            };
    
            return await APIContext.Post<ExchangeTradeResultData>(cancellationToken, "/api/exchange/trade", payload);
        }
    }
}