// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Threading;
using Cysharp.Threading.Tasks;
using Newtonsoft.Json;
using UnityEngine;
using UnityHTTPLibrary;
using WPFramework.Data.Extensions;
using GLOW.Core.Data.Data;
using GLOW.Core.Domain.Constants;
using Zenject;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.DataStores
{
    public sealed class ItemApi
    {
        [Serializable]
        class JsonParamConsume
        {
            [IgnoreDataMember] [JsonIgnore]
            public string MstItemId {
                get => mstItemId;
                set => mstItemId = value;
            }
            [IgnoreDataMember] [JsonIgnore]
            public int Amount {
                get => amount;
                set => amount = value;
            }
            [DataMember(Name = "mstItemId")] [SerializeField] [JsonProperty("mstItemId")] string mstItemId;
            [DataMember(Name = "amount")] [SerializeField] [JsonProperty("amount")] int amount;
        }
        [Serializable]
        class JsonParamExchangeSelectItem
        {
            [IgnoreDataMember] [JsonIgnore]
            public string MstItemId {
                get => mstItemId;
                set => mstItemId = value;
            }
            [IgnoreDataMember] [JsonIgnore]
            public string SelectMstItemId {
                get => selectMstItemId;
                set => selectMstItemId = value;
            }
            [IgnoreDataMember] [JsonIgnore]
            public int Amount {
                get => amount;
                set => amount = value;
            }
            [DataMember(Name = "mstItemId")] [SerializeField] [JsonProperty("mstItemId")] string mstItemId;
            [DataMember(Name = "selectMstItemId")] [SerializeField] [JsonProperty("selectMstItemId")] string selectMstItemId;
            [DataMember(Name = "amount")] [SerializeField] [JsonProperty("amount")] int amount;
        }

        [Inject(Id = WPFramework.Constants.Zenject.FrameworkInjectId.ServerApi.Game)] ServerApi APIContext { get; }

        public async UniTask<ItemConsumeResultData> Consume(CancellationToken cancellationToken, string mstItemId, int amount)
        {
            var param = new JsonParamConsume();
            param.MstItemId = mstItemId;
            param.Amount = amount;
            var json = JsonConvert.SerializeObject(param);
            var payload = new Payload()
            {
                Data = System.Text.Encoding.UTF8.GetBytes(json),
                ContentType = MimeTypes.Json
            };
    
            return await APIContext.Post<ItemConsumeResultData>(cancellationToken, "/api/item/consume", payload);
        }
        public async UniTask<ItemExchangeSelectItemResultData> ExchangeSelectItem(CancellationToken cancellationToken, string mstItemId, string selectMstItemId, int amount)
        {
            var param = new JsonParamExchangeSelectItem();
            param.MstItemId = mstItemId;
            param.SelectMstItemId = selectMstItemId;
            param.Amount = amount;
            var json = JsonConvert.SerializeObject(param);
            var payload = new Payload()
            {
                Data = System.Text.Encoding.UTF8.GetBytes(json),
                ContentType = MimeTypes.Json
            };
    
            return await APIContext.Post<ItemExchangeSelectItemResultData>(cancellationToken, "/api/item/exchange_select_item", payload);
        }
    }
}
