// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Threading;
using Cysharp.Threading.Tasks;
using Newtonsoft.Json;
using UnityEngine;
using UnityHTTPLibrary;
using WPFramework.Data.Extensions;
using GLOW.Core.Data.Data;
using GLOW.Core.Domain.Constants;
using Zenject;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.DataStores
{
    public sealed class PartyApi
    {
        [Serializable]
        class JsonParamSave
        {
            [IgnoreDataMember] [JsonIgnore]
            public PartySaveRequestData[] Parties {
                get => parties;
                set => parties = value;
            }
            [DataMember(Name = "parties")] [SerializeField] [JsonProperty("parties")] PartySaveRequestData[] parties;
        }

        [Inject(Id = WPFramework.Constants.Zenject.FrameworkInjectId.ServerApi.Game)] ServerApi APIContext { get; }

        public async UniTask<PartySaveResultData> Save(CancellationToken cancellationToken, PartySaveRequestData[] parties)
        {
            var param = new JsonParamSave();
            param.Parties = parties;
            var json = JsonConvert.SerializeObject(param);
            var payload = new Payload()
            {
                Data = System.Text.Encoding.UTF8.GetBytes(json),
                ContentType = MimeTypes.Json
            };
    
            return await APIContext.Post<PartySaveResultData>(cancellationToken, "/api/party/save", payload);
        }
    }
}
