using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Threading;
using Cysharp.Threading.Tasks;
using Newtonsoft.Json;
using UnityEngine;
using UnityHTTPLibrary;
using WPFramework.Data.Extensions;
using GLOW.Core.Data.Data;
using GLOW.Core.Domain.Constants;
using Zenject;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.DataStores
{
    public sealed class StageApi
    {
        [Serializable]
        class JsonParamStart
        {
            [IgnoreDataMember] [JsonIgnore]
            public string MstStageId {
                get => mstStageId;
                set => mstStageId = value;
            }
            [IgnoreDataMember] [JsonIgnore]
            public int PartyNo {
                get => partyNo;
                set => partyNo = value;
            }
            [IgnoreDataMember] [JsonIgnore]
            public bool IsChallengeAd {
                get => isChallengeAd;
                set => isChallengeAd = value;
            }
            [IgnoreDataMember] [JsonIgnore]
            public int? LapCount {
                get => lapCount;
                set => lapCount = value;
            }
            [DataMember(Name = "mstStageId")] [SerializeField] [JsonProperty("mstStageId")] string mstStageId;
            [DataMember(Name = "partyNo")] [SerializeField] [JsonProperty("partyNo")] int partyNo;
            [DataMember(Name = "isChallengeAd")] [SerializeField] [JsonProperty("isChallengeAd")] bool isChallengeAd;
            [DataMember(Name = "lapCount")] [SerializeField] [JsonProperty("lapCount")] int? lapCount;
        }
        [Serializable]
        class JsonParamEnd
        {
            [IgnoreDataMember] [JsonIgnore]
            public string MstStageId {
                get => mstStageId;
                set => mstStageId = value;
            }
            [IgnoreDataMember] [JsonIgnore]
            public InGameEndBattleLogData InGameBattleLog {
                get => inGameBattleLog;
                set => inGameBattleLog = value;
            }
            [DataMember(Name = "mstStageId")] [SerializeField] [JsonProperty("mstStageId")] string mstStageId;
            [DataMember(Name = "inGameBattleLog")] [SerializeField] [JsonProperty("inGameBattleLog")] InGameEndBattleLogData inGameBattleLog;
        }
        [Serializable]
        class JsonParamContinueDiamond
        {
            [IgnoreDataMember] [JsonIgnore]
            public string MstStageId {
                get => mstStageId;
                set => mstStageId = value;
            }
            [DataMember(Name = "mstStageId")] [SerializeField] [JsonProperty("mstStageId")] string mstStageId;
        }
        [Serializable]
        class JsonParamContinueAd
        {
            [IgnoreDataMember] [JsonIgnore]
            public string MstStageId {
                get => mstStageId;
                set => mstStageId = value;
            }
            [DataMember(Name = "mstStageId")] [SerializeField] [JsonProperty("mstStageId")] string mstStageId;
        }
        [Serializable]
        class JsonParamAbort
        {
            [IgnoreDataMember] [JsonIgnore]
            public int AbortType {
                get => abortType;
                set => abortType = value;
            }
            [DataMember(Name = "abortType")] [SerializeField] [JsonProperty("abortType")] int abortType;
        }
        [Serializable]
        class JsonParamCleanup
        {
        }

        [Inject(Id = WPFramework.Constants.Zenject.FrameworkInjectId.ServerApi.Game)] ServerApi APIContext { get; }

        public async UniTask<StageStartResultData> Start(CancellationToken cancellationToken, string mstStageId, int partyNo, bool isChallengeAd, int? lapCount)
        {
            var param = new JsonParamStart();
            param.MstStageId = mstStageId;
            param.PartyNo = partyNo;
            param.IsChallengeAd = isChallengeAd;
            if(lapCount.HasValue)
            {
                param.LapCount = lapCount.Value;
            }
            var json = JsonConvert.SerializeObject(param);
            var payload = new Payload()
            {
                Data = System.Text.Encoding.UTF8.GetBytes(json),
                ContentType = MimeTypes.Json
            };

            return await APIContext.Post<StageStartResultData>(cancellationToken, "/api/stage/start", payload);
        }
        public async UniTask<StageEndResultData> End(CancellationToken cancellationToken, string mstStageId, InGameEndBattleLogData inGameBattleLog)
        {
            var param = new JsonParamEnd();
            param.MstStageId = mstStageId;
            param.InGameBattleLog = inGameBattleLog;
            var json = JsonConvert.SerializeObject(param);
            var payload = new Payload()
            {
                Data = System.Text.Encoding.UTF8.GetBytes(json),
                ContentType = MimeTypes.Json
            };

            return await APIContext.Post<StageEndResultData>(cancellationToken, "/api/stage/end", payload);
        }
        public async UniTask<StageContinueDiamondResultData> ContinueDiamond(CancellationToken cancellationToken, string mstStageId)
        {
            var param = new JsonParamContinueDiamond();
            param.MstStageId = mstStageId;
            var json = JsonConvert.SerializeObject(param);
            var payload = new Payload()
            {
                Data = System.Text.Encoding.UTF8.GetBytes(json),
                ContentType = MimeTypes.Json
            };

            return await APIContext.Post<StageContinueDiamondResultData>(cancellationToken, "/api/stage/continue_diamond", payload);
        }
        public async UniTask<StageContinueAdResultData> ContinueAd(CancellationToken cancellationToken, string mstStageId)
        {
            var param = new JsonParamContinueAd();
            param.MstStageId = mstStageId;
            var json = JsonConvert.SerializeObject(param);
            var payload = new Payload()
            {
                Data = System.Text.Encoding.UTF8.GetBytes(json),
                ContentType = MimeTypes.Json
            };

            return await APIContext.Post<StageContinueAdResultData>(cancellationToken, "/api/stage/continue_ad", payload);
        }
        public async UniTask<HeadOK> Abort(CancellationToken cancellationToken, int abortType)
        {
            var param = new JsonParamAbort();
            param.AbortType = abortType;
            var json = JsonConvert.SerializeObject(param);
            var payload = new Payload()
            {
                Data = System.Text.Encoding.UTF8.GetBytes(json),
                ContentType = MimeTypes.Json
            };

            return await APIContext.Post<HeadOK>(cancellationToken, "/api/stage/abort", payload);
        }
        public async UniTask<HeadOK> Cleanup(CancellationToken cancellationToken)
        {

            var payload = new Payload()
            {
                Data = Array.Empty<byte>(),
                ContentType = MimeTypes.Json
            };

            return await APIContext.Post<HeadOK>(cancellationToken, "/api/stage/cleanup", payload);
        }
    }
}
