using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Threading;
using Cysharp.Threading.Tasks;
using Newtonsoft.Json;
using UnityEngine;
using UnityHTTPLibrary;
using WPFramework.Data.Extensions;
using GLOW.Core.Data.Data;
using GLOW.Core.Domain.Constants;
using Zenject;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.DataStores
{
    public sealed class UnitApi
    {
        [Serializable]
        class JsonParamLevelUp
        {
            [IgnoreDataMember] [JsonIgnore]
            public string UsrUnitId {
                get => usrUnitId;
                set => usrUnitId = value;
            }
            [IgnoreDataMember] [JsonIgnore]
            public int Level {
                get => level;
                set => level = value;
            }
            [DataMember(Name = "usrUnitId")] [SerializeField] [JsonProperty("usrUnitId")] string usrUnitId;
            [DataMember(Name = "level")] [SerializeField] [JsonProperty("level")] int level;
        }
        [Serializable]
        class JsonParamRankUp
        {
            [IgnoreDataMember] [JsonIgnore]
            public string UsrUnitId {
                get => usrUnitId;
                set => usrUnitId = value;
            }
            [DataMember(Name = "usrUnitId")] [SerializeField] [JsonProperty("usrUnitId")] string usrUnitId;
        }
        [Serializable]
        class JsonParamGradeUp
        {
            [IgnoreDataMember] [JsonIgnore]
            public string UsrUnitId {
                get => usrUnitId;
                set => usrUnitId = value;
            }
            [DataMember(Name = "usrUnitId")] [SerializeField] [JsonProperty("usrUnitId")] string usrUnitId;
        }

        [Inject(Id = WPFramework.Constants.Zenject.FrameworkInjectId.ServerApi.Game)] ServerApi APIContext { get; }

        public async UniTask<LevelUpResultData> LevelUp(CancellationToken cancellationToken, string usrUnitId, int level)
        {
            var param = new JsonParamLevelUp();
            param.UsrUnitId = usrUnitId;
            param.Level = level;
            var json = JsonConvert.SerializeObject(param);
            var payload = new Payload()
            {
                Data = System.Text.Encoding.UTF8.GetBytes(json),
                ContentType = MimeTypes.Json
            };
    
            return await APIContext.Post<LevelUpResultData>(cancellationToken, "/api/unit/level_up", payload);
        }
        public async UniTask<RankUpResultData> RankUp(CancellationToken cancellationToken, string usrUnitId)
        {
            var param = new JsonParamRankUp();
            param.UsrUnitId = usrUnitId;
            var json = JsonConvert.SerializeObject(param);
            var payload = new Payload()
            {
                Data = System.Text.Encoding.UTF8.GetBytes(json),
                ContentType = MimeTypes.Json
            };
    
            return await APIContext.Post<RankUpResultData>(cancellationToken, "/api/unit/rank_up", payload);
        }
        public async UniTask<GradeUpResultData> GradeUp(CancellationToken cancellationToken, string usrUnitId)
        {
            var param = new JsonParamGradeUp();
            param.UsrUnitId = usrUnitId;
            var json = JsonConvert.SerializeObject(param);
            var payload = new Payload()
            {
                Data = System.Text.Encoding.UTF8.GetBytes(json),
                ContentType = MimeTypes.Json
            };
    
            return await APIContext.Post<GradeUpResultData>(cancellationToken, "/api/unit/grade_up", payload);
        }
    }
}