// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class AdventBattleRankingItemData
    {
        [DataMember(Name = "myId")][JsonProperty("myId")]
        public string MyId 
        {
            get => _obscured_myId;
            set => _obscured_myId = value ?? string.Empty;
        }
        [DataMember(Name = "rank")][JsonProperty("rank")]
        public int Rank 
        {
            get => _obscured_rank;
            set => _obscured_rank = value;
        }
        [DataMember(Name = "name")][JsonProperty("name")]
        public string Name 
        {
            get => _obscured_name;
            set => _obscured_name = value ?? string.Empty;
        }
        [DataMember(Name = "mstUnitId")][JsonProperty("mstUnitId")]
        public string MstUnitId 
        {
            get => _obscured_mstUnitId;
            set => _obscured_mstUnitId = value ?? string.Empty;
        }
        [DataMember(Name = "mstEmblemId")][JsonProperty("mstEmblemId")]
        public string MstEmblemId 
        {
            get => _obscured_mstEmblemId;
            set => _obscured_mstEmblemId = value ?? string.Empty;
        }
        [DataMember(Name = "score")][JsonProperty("score")]
        public long Score 
        {
            get => _obscured_score;
            set => _obscured_score = value;
        }
        [DataMember(Name = "totalScore")][JsonProperty("totalScore")]
        public long TotalScore 
        {
            get => _obscured_totalScore;
            set => _obscured_totalScore = value;
        }
        [DataMember(Name = "maxScoreParty")][JsonProperty("maxScoreParty")]
        public MaxScorePartyUnitData[] MaxScoreParty { get; set; }


        ObscuredString _obscured_myId;
        ObscuredInt _obscured_rank;
        ObscuredString _obscured_name;
        ObscuredString _obscured_mstUnitId;
        ObscuredString _obscured_mstEmblemId;
        ObscuredLong _obscured_score;
        ObscuredLong _obscured_totalScore;
    }
}
