// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class EncyclopediaReceiveFirstCollectionRewardResultData
    {
        [DataMember(Name = "usrEmblems")][JsonProperty("usrEmblems")]
        public UsrEmblemData[] UsrEmblems { get; set; }
        [DataMember(Name = "usrArtworks")][JsonProperty("usrArtworks")]
        public UsrArtworkData[] UsrArtworks { get; set; }
        [DataMember(Name = "usrEnemyDiscoveries")][JsonProperty("usrEnemyDiscoveries")]
        public UsrEnemyDiscoveryData[] UsrEnemyDiscoveries { get; set; }
        [DataMember(Name = "usrUnits")][JsonProperty("usrUnits")]
        public UsrUnitData[] UsrUnits { get; set; }
        [DataMember(Name = "usrParameter")][JsonProperty("usrParameter")]
        public UsrParameterData UsrParameter { get; set; }
        [DataMember(Name = "encyclopediaFirstCollectionRewards")][JsonProperty("encyclopediaFirstCollectionRewards")]
        public EncyclopediaFirstCollectionRewardData[] EncyclopediaFirstCollectionRewards { get; set; }


    }
}
