// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class GachaPrizeData
    {
        [DataMember(Name = "resourceType")][JsonProperty("resourceType")]
        public ResourceType ResourceType { get; set; }
        [DataMember(Name = "resourceId")][JsonProperty("resourceId")]
        public string ResourceId 
        {
            get => _obscured_resourceId;
            set => _obscured_resourceId = value ?? string.Empty;
        }
        [DataMember(Name = "resourceAmount")][JsonProperty("resourceAmount")]
        public int ResourceAmount 
        {
            get => _obscured_resourceAmount;
            set => _obscured_resourceAmount = value;
        }
        [DataMember(Name = "probability")][JsonProperty("probability")]
        public float Probability 
        {
            get => _obscured_probability;
            set => _obscured_probability = value;
        }
        [DataMember(Name = "isPickup")][JsonProperty("isPickup")]
        public bool IsPickup 
        {
            get => _obscured_isPickup;
            set => _obscured_isPickup = value;
        }


        ObscuredString _obscured_resourceId;
        ObscuredInt _obscured_resourceAmount;
        ObscuredFloat _obscured_probability;
        ObscuredBool _obscured_isPickup;
    }
}
