// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class GameBadgeResultData
    {
        [DataMember(Name = "badges")][JsonProperty("badges")]
        public BadgeData Badges { get; set; }
        [DataMember(Name = "mngContentCloses")][JsonProperty("mngContentCloses")]
        public MngContentCloseData[] MngContentCloses { get; set; }


    }
}
