// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class InGameEndBattleLogData
    {
        [DataMember(Name = "defeatEnemyCount")][JsonProperty("defeatEnemyCount")]
        public int DefeatEnemyCount 
        {
            get => _obscured_defeatEnemyCount;
            set => _obscured_defeatEnemyCount = value;
        }
        [DataMember(Name = "defeatBossEnemyCount")][JsonProperty("defeatBossEnemyCount")]
        public int DefeatBossEnemyCount 
        {
            get => _obscured_defeatBossEnemyCount;
            set => _obscured_defeatBossEnemyCount = value;
        }
        [DataMember(Name = "score")][JsonProperty("score")]
        public long Score 
        {
            get => _obscured_score;
            set => _obscured_score = value;
        }
        [DataMember(Name = "clearTimeMs")][JsonProperty("clearTimeMs")]
        public int ClearTimeMs 
        {
            get => _obscured_clearTimeMs;
            set => _obscured_clearTimeMs = value;
        }
        [DataMember(Name = "partyStatus")][JsonProperty("partyStatus")]
        public PartyStatusData[] PartyStatus { get; set; }
        [DataMember(Name = "maxDamage")][JsonProperty("maxDamage")]
        public int MaxDamage 
        {
            get => _obscured_maxDamage;
            set => _obscured_maxDamage = value;
        }
        [DataMember(Name = "discoveredEnemies")][JsonProperty("discoveredEnemies")]
        public DiscoveredEnemyData[] DiscoveredEnemies { get; set; }


        ObscuredInt _obscured_defeatEnemyCount;
        ObscuredInt _obscured_defeatBossEnemyCount;
        ObscuredLong _obscured_score;
        ObscuredInt _obscured_clearTimeMs;
        ObscuredInt _obscured_maxDamage;
    }
}
