// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MessageData
    {
        [DataMember(Name = "usrMessageId")][JsonProperty("usrMessageId")]
        public string UsrMessageId 
        {
            get => _obscured_usrMessageId;
            set => _obscured_usrMessageId = value ?? string.Empty;
        }
        [DataMember(Name = "oprMessageId")][JsonProperty("oprMessageId")]
        public string? OprMessageId 
        {
            get => _obscured_oprMessageId;
            set => _obscured_oprMessageId = value;
        }
        [DataMember(Name = "startAt")][JsonProperty("startAt")]
        public DateTimeOffset StartAt { get; set; }
        [DataMember(Name = "openedAt")][JsonProperty("openedAt")]
        public DateTimeOffset? OpenedAt { get; set; }
        [DataMember(Name = "receivedAt")][JsonProperty("receivedAt")]
        public DateTimeOffset? ReceivedAt { get; set; }
        [DataMember(Name = "expiredAt")][JsonProperty("expiredAt")]
        public DateTimeOffset? ExpiredAt { get; set; }
        [DataMember(Name = "messageRewards")][JsonProperty("messageRewards")]
        public MessageRewardData[] MessageRewards { get; set; }
        [DataMember(Name = "title")][JsonProperty("title")]
        public string Title 
        {
            get => _obscured_title;
            set => _obscured_title = value ?? string.Empty;
        }
        [DataMember(Name = "body")][JsonProperty("body")]
        public string Body 
        {
            get => _obscured_body;
            set => _obscured_body = value ?? string.Empty;
        }


        ObscuredString _obscured_usrMessageId;
        ObscuredString? _obscured_oprMessageId;
        ObscuredString _obscured_title;
        ObscuredString _obscured_body;
    }
}
