// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MissionUpdateAndFetchResultData
    {
        [DataMember(Name = "usrMissionAchievements")][JsonProperty("usrMissionAchievements")]
        public UsrMissionAchievementData[] UsrMissionAchievements { get; set; }
        [DataMember(Name = "usrMissionDailyBonuses")][JsonProperty("usrMissionDailyBonuses")]
        public UsrMissionDailyBonusData[] UsrMissionDailyBonuses { get; set; }
        [DataMember(Name = "usrMissionDailies")][JsonProperty("usrMissionDailies")]
        public UsrMissionDailyData[] UsrMissionDailies { get; set; }
        [DataMember(Name = "usrMissionWeeklies")][JsonProperty("usrMissionWeeklies")]
        public UsrMissionWeeklyData[] UsrMissionWeeklies { get; set; }
        [DataMember(Name = "usrMissionBeginners")][JsonProperty("usrMissionBeginners")]
        public UsrMissionBeginnerData[] UsrMissionBeginners { get; set; }
        [DataMember(Name = "missionBeginnerDaysFromStart")][JsonProperty("missionBeginnerDaysFromStart")]
        public int MissionBeginnerDaysFromStart 
        {
            get => _obscured_missionBeginnerDaysFromStart;
            set => _obscured_missionBeginnerDaysFromStart = value;
        }
        [DataMember(Name = "usrMissionBonusPoints")][JsonProperty("usrMissionBonusPoints")]
        public UsrMissionBonusPointData[] UsrMissionBonusPoints { get; set; }


        ObscuredInt _obscured_missionBeginnerDaysFromStart;
    }
}
