// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MissionEventDailyBonusUpdateResultData
    {
        [DataMember(Name = "eventDailyBonusRewards")][JsonProperty("eventDailyBonusRewards")]
        public EventDailyBonusRewardData[] EventDailyBonusRewards { get; set; }
        [DataMember(Name = "usrMissionEventDailyBonusProgresses")][JsonProperty("usrMissionEventDailyBonusProgresses")]
        public UsrMissionEventDailyBonusProgressData[] UsrMissionEventDailyBonusProgresses { get; set; }
        [DataMember(Name = "usrParameter")][JsonProperty("usrParameter")]
        public UsrParameterData UsrParameter { get; set; }
        [DataMember(Name = "usrItems")][JsonProperty("usrItems")]
        public UsrItemData[] UsrItems { get; set; }
        [DataMember(Name = "usrUnits")][JsonProperty("usrUnits")]
        public UsrUnitData[] UsrUnits { get; set; }
        [DataMember(Name = "usrEmblems")][JsonProperty("usrEmblems")]
        public UsrEmblemData[] UsrEmblems { get; set; }
        [DataMember(Name = "userLevel")][JsonProperty("userLevel")]
        public UserLevelUpData UserLevel { get; set; }
        [DataMember(Name = "usrConditionPacks")][JsonProperty("usrConditionPacks")]
        public UsrConditionPackData[] UsrConditionPacks { get; set; }


    }
}
