// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MissionBulkReceiveRewardResultData
    {
        [DataMember(Name = "missionReceiveRewards")][JsonProperty("missionReceiveRewards")]
        public MissionReceiveRewardData[] MissionReceiveRewards { get; set; }
        [DataMember(Name = "missionRewards")][JsonProperty("missionRewards")]
        public MissionRewardData[] MissionRewards { get; set; }
        [DataMember(Name = "usrMissionAchievements")][JsonProperty("usrMissionAchievements")]
        public UsrMissionAchievementData[] UsrMissionAchievements { get; set; }
        [DataMember(Name = "usrMissionDailies")][JsonProperty("usrMissionDailies")]
        public UsrMissionDailyData[] UsrMissionDailies { get; set; }
        [DataMember(Name = "usrMissionWeeklies")][JsonProperty("usrMissionWeeklies")]
        public UsrMissionWeeklyData[] UsrMissionWeeklies { get; set; }
        [DataMember(Name = "usrMissionBeginners")][JsonProperty("usrMissionBeginners")]
        public UsrMissionBeginnerData[] UsrMissionBeginners { get; set; }
        [DataMember(Name = "missionEvents")][JsonProperty("missionEvents")]
        public MissionEventData[] MissionEvents { get; set; }
        [DataMember(Name = "usrMissionLimitedTerms")][JsonProperty("usrMissionLimitedTerms")]
        public UsrMissionLimitedTermData[] UsrMissionLimitedTerms { get; set; }
        [DataMember(Name = "usrMissionBonusPoints")][JsonProperty("usrMissionBonusPoints")]
        public UsrMissionBonusPointData[] UsrMissionBonusPoints { get; set; }
        [DataMember(Name = "usrParameter")][JsonProperty("usrParameter")]
        public UsrParameterData UsrParameter { get; set; }
        [DataMember(Name = "usrItems")][JsonProperty("usrItems")]
        public UsrItemData[] UsrItems { get; set; }
        [DataMember(Name = "usrUnits")][JsonProperty("usrUnits")]
        public UsrUnitData[] UsrUnits { get; set; }
        [DataMember(Name = "userLevel")][JsonProperty("userLevel")]
        public UserLevelUpData UserLevel { get; set; }
        [DataMember(Name = "usrConditionPacks")][JsonProperty("usrConditionPacks")]
        public UsrConditionPackData[] UsrConditionPacks { get; set; }


    }
}
