// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MstArtworkFragmentData
    {
        [DataMember(Name = "id")][JsonProperty("id")]
        public string Id 
        {
            get => _obscured_id;
            set => _obscured_id = value ?? string.Empty;
        }
        [DataMember(Name = "mstArtworkId")][JsonProperty("mstArtworkId")]
        public string MstArtworkId 
        {
            get => _obscured_mstArtworkId;
            set => _obscured_mstArtworkId = value ?? string.Empty;
        }
        [DataMember(Name = "dropGroupId")][JsonProperty("dropGroupId")]
        public string DropGroupId 
        {
            get => _obscured_dropGroupId;
            set => _obscured_dropGroupId = value ?? string.Empty;
        }
        [DataMember(Name = "dropPercentage")][JsonProperty("dropPercentage")]
        public int DropPercentage 
        {
            get => _obscured_dropPercentage;
            set => _obscured_dropPercentage = value;
        }
        [DataMember(Name = "rarity")][JsonProperty("rarity")]
        public Rarity Rarity { get; set; }
        [DataMember(Name = "assetNum")][JsonProperty("assetNum")]
        public int AssetNum 
        {
            get => _obscured_assetNum;
            set => _obscured_assetNum = value;
        }


        ObscuredString _obscured_id;
        ObscuredString _obscured_mstArtworkId;
        ObscuredString _obscured_dropGroupId;
        ObscuredInt _obscured_dropPercentage;
        ObscuredInt _obscured_assetNum;
    }
}
