// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MstAdventBattleRankData
    {
        [DataMember(Name = "id")][JsonProperty("id")]
        public string Id 
        {
            get => _obscured_id;
            set => _obscured_id = value ?? string.Empty;
        }
        [DataMember(Name = "mstAdventBattleId")][JsonProperty("mstAdventBattleId")]
        public string MstAdventBattleId 
        {
            get => _obscured_mstAdventBattleId;
            set => _obscured_mstAdventBattleId = value ?? string.Empty;
        }
        [DataMember(Name = "rankType")][JsonProperty("rankType")]
        public RankType RankType { get; set; }
        [DataMember(Name = "rankLevel")][JsonProperty("rankLevel")]
        public int RankLevel 
        {
            get => _obscured_rankLevel;
            set => _obscured_rankLevel = value;
        }
        [DataMember(Name = "requiredLowerScore")][JsonProperty("requiredLowerScore")]
        public long RequiredLowerScore 
        {
            get => _obscured_requiredLowerScore;
            set => _obscured_requiredLowerScore = value;
        }
        [DataMember(Name = "assetKey")][JsonProperty("assetKey")]
        public string AssetKey 
        {
            get => _obscured_assetKey;
            set => _obscured_assetKey = value ?? string.Empty;
        }


        ObscuredString _obscured_id;
        ObscuredString _obscured_mstAdventBattleId;
        ObscuredInt _obscured_rankLevel;
        ObscuredLong _obscured_requiredLowerScore;
        ObscuredString _obscured_assetKey;
    }
}
