// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MstArtworkData
    {
        [DataMember(Name = "id")][JsonProperty("id")]
        public string Id 
        {
            get => _obscured_id;
            set => _obscured_id = value ?? string.Empty;
        }
        [DataMember(Name = "mstSeriesId")][JsonProperty("mstSeriesId")]
        public string MstSeriesId 
        {
            get => _obscured_mstSeriesId;
            set => _obscured_mstSeriesId = value ?? string.Empty;
        }
        [DataMember(Name = "outpostAdditionalHp")][JsonProperty("outpostAdditionalHp")]
        public int OutpostAdditionalHp 
        {
            get => _obscured_outpostAdditionalHp;
            set => _obscured_outpostAdditionalHp = value;
        }
        [DataMember(Name = "assetKey")][JsonProperty("assetKey")]
        public string AssetKey 
        {
            get => _obscured_assetKey;
            set => _obscured_assetKey = value ?? string.Empty;
        }
        [DataMember(Name = "sortOrder")][JsonProperty("sortOrder")]
        public int SortOrder 
        {
            get => _obscured_sortOrder;
            set => _obscured_sortOrder = value;
        }


        ObscuredString _obscured_id;
        ObscuredString _obscured_mstSeriesId;
        ObscuredInt _obscured_outpostAdditionalHp;
        ObscuredString _obscured_assetKey;
        ObscuredInt _obscured_sortOrder;
    }
}
