// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MstBoxGachaData
    {
        [DataMember(Name = "id")][JsonProperty("id")]
        public string Id 
        {
            get => _obscured_id;
            set => _obscured_id = value ?? string.Empty;
        }
        [DataMember(Name = "mstEventId")][JsonProperty("mstEventId")]
        public string MstEventId 
        {
            get => _obscured_mstEventId;
            set => _obscured_mstEventId = value ?? string.Empty;
        }
        [DataMember(Name = "costId")][JsonProperty("costId")]
        public string CostId 
        {
            get => _obscured_costId;
            set => _obscured_costId = value ?? string.Empty;
        }
        [DataMember(Name = "costNum")][JsonProperty("costNum")]
        public int CostNum 
        {
            get => _obscured_costNum;
            set => _obscured_costNum = value;
        }
        [DataMember(Name = "loopType")][JsonProperty("loopType")]
        public BoxGachaLoopType LoopType { get; set; }
        [DataMember(Name = "assetKey")][JsonProperty("assetKey")]
        public string AssetKey 
        {
            get => _obscured_assetKey;
            set => _obscured_assetKey = value ?? string.Empty;
        }
        [DataMember(Name = "displayMstUnitId1")][JsonProperty("displayMstUnitId1")]
        public string DisplayMstUnitId1 
        {
            get => _obscured_displayMstUnitId1;
            set => _obscured_displayMstUnitId1 = value ?? string.Empty;
        }
        [DataMember(Name = "displayMstUnitId2")][JsonProperty("displayMstUnitId2")]
        public string DisplayMstUnitId2 
        {
            get => _obscured_displayMstUnitId2;
            set => _obscured_displayMstUnitId2 = value ?? string.Empty;
        }


        ObscuredString _obscured_id;
        ObscuredString _obscured_mstEventId;
        ObscuredString _obscured_costId;
        ObscuredInt _obscured_costNum;
        ObscuredString _obscured_assetKey;
        ObscuredString _obscured_displayMstUnitId1;
        ObscuredString _obscured_displayMstUnitId2;
    }
}
