// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MstDungeonCardData
    {
        [DataMember(Name = "id")][JsonProperty("id")]
        public string Id 
        {
            get => _obscured_id;
            set => _obscured_id = value ?? string.Empty;
        }
        [DataMember(Name = "iconAssetKey")][JsonProperty("iconAssetKey")]
        public string IconAssetKey 
        {
            get => _obscured_iconAssetKey;
            set => _obscured_iconAssetKey = value ?? string.Empty;
        }
        [DataMember(Name = "backgroundAssetKey")][JsonProperty("backgroundAssetKey")]
        public string BackgroundAssetKey 
        {
            get => _obscured_backgroundAssetKey;
            set => _obscured_backgroundAssetKey = value ?? string.Empty;
        }
        [DataMember(Name = "rarity")][JsonProperty("rarity")]
        public Rarity Rarity { get; set; }
        [DataMember(Name = "mstAttackId")][JsonProperty("mstAttackId")]
        public string MstAttackId 
        {
            get => _obscured_mstAttackId;
            set => _obscured_mstAttackId = value ?? string.Empty;
        }


        ObscuredString _obscured_id;
        ObscuredString _obscured_iconAssetKey;
        ObscuredString _obscured_backgroundAssetKey;
        ObscuredString _obscured_mstAttackId;
    }
}
