// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MstEventData
    {
        [DataMember(Name = "id")][JsonProperty("id")]
        public string Id 
        {
            get => _obscured_id;
            set => _obscured_id = value ?? string.Empty;
        }
        [DataMember(Name = "mstSeriesId")][JsonProperty("mstSeriesId")]
        public string MstSeriesId 
        {
            get => _obscured_mstSeriesId;
            set => _obscured_mstSeriesId = value ?? string.Empty;
        }
        [DataMember(Name = "isDisplayedSeriesLogo")][JsonProperty("isDisplayedSeriesLogo")]
        public bool IsDisplayedSeriesLogo 
        {
            get => _obscured_isDisplayedSeriesLogo;
            set => _obscured_isDisplayedSeriesLogo = value;
        }
        [DataMember(Name = "isDisplayedJumpPlus")][JsonProperty("isDisplayedJumpPlus")]
        public bool IsDisplayedJumpPlus 
        {
            get => _obscured_isDisplayedJumpPlus;
            set => _obscured_isDisplayedJumpPlus = value;
        }
        [DataMember(Name = "startAt")][JsonProperty("startAt")]
        public DateTimeOffset StartAt { get; set; }
        [DataMember(Name = "endAt")][JsonProperty("endAt")]
        public DateTimeOffset EndAt { get; set; }
        [DataMember(Name = "assetKey")][JsonProperty("assetKey")]
        public string AssetKey 
        {
            get => _obscured_assetKey;
            set => _obscured_assetKey = value ?? string.Empty;
        }


        ObscuredString _obscured_id;
        ObscuredString _obscured_mstSeriesId;
        ObscuredBool _obscured_isDisplayedSeriesLogo;
        ObscuredBool _obscured_isDisplayedJumpPlus;
        ObscuredString _obscured_assetKey;
    }
}
