// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MstExchangeLineupData
    {
        [DataMember(Name = "id")][JsonProperty("id")]
        public string Id 
        {
            get => _obscured_id;
            set => _obscured_id = value ?? string.Empty;
        }
        [DataMember(Name = "groupId")][JsonProperty("groupId")]
        public string GroupId 
        {
            get => _obscured_groupId;
            set => _obscured_groupId = value ?? string.Empty;
        }
        [DataMember(Name = "tradableCount")][JsonProperty("tradableCount")]
        public int? TradableCount 
        {
            get => _obscured_tradableCount;
            set => _obscured_tradableCount = value;
        }
        [DataMember(Name = "displayOrder")][JsonProperty("displayOrder")]
        public int DisplayOrder 
        {
            get => _obscured_displayOrder;
            set => _obscured_displayOrder = value;
        }


        ObscuredString _obscured_id;
        ObscuredString _obscured_groupId;
        ObscuredInt? _obscured_tradableCount;
        ObscuredInt _obscured_displayOrder;
    }
}
