// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MstEnemyStageParameterData
    {
        [DataMember(Name = "id")][JsonProperty("id")]
        public string Id 
        {
            get => _obscured_id;
            set => _obscured_id = value ?? string.Empty;
        }
        [DataMember(Name = "mstEnemyCharacterId")][JsonProperty("mstEnemyCharacterId")]
        public string MstEnemyCharacterId 
        {
            get => _obscured_mstEnemyCharacterId;
            set => _obscured_mstEnemyCharacterId = value ?? string.Empty;
        }
        [DataMember(Name = "characterUnitKind")][JsonProperty("characterUnitKind")]
        public CharacterUnitKind CharacterUnitKind { get; set; }
        [DataMember(Name = "roleType")][JsonProperty("roleType")]
        public CharacterUnitRoleType RoleType { get; set; }
        [DataMember(Name = "color")][JsonProperty("color")]
        public CharacterColor Color { get; set; }
        [DataMember(Name = "sortOrder")][JsonProperty("sortOrder")]
        public int SortOrder 
        {
            get => _obscured_sortOrder;
            set => _obscured_sortOrder = value;
        }
        [DataMember(Name = "hp")][JsonProperty("hp")]
        public int Hp 
        {
            get => _obscured_hp;
            set => _obscured_hp = value;
        }
        [DataMember(Name = "damageKnockBackCount")][JsonProperty("damageKnockBackCount")]
        public int DamageKnockBackCount 
        {
            get => _obscured_damageKnockBackCount;
            set => _obscured_damageKnockBackCount = value;
        }
        [DataMember(Name = "moveSpeed")][JsonProperty("moveSpeed")]
        public int MoveSpeed 
        {
            get => _obscured_moveSpeed;
            set => _obscured_moveSpeed = value;
        }
        [DataMember(Name = "wellDistance")][JsonProperty("wellDistance")]
        public float WellDistance 
        {
            get => _obscured_wellDistance;
            set => _obscured_wellDistance = value;
        }
        [DataMember(Name = "attackPower")][JsonProperty("attackPower")]
        public int AttackPower 
        {
            get => _obscured_attackPower;
            set => _obscured_attackPower = value;
        }
        [DataMember(Name = "attackComboCycle")][JsonProperty("attackComboCycle")]
        public int AttackComboCycle 
        {
            get => _obscured_attackComboCycle;
            set => _obscured_attackComboCycle = value;
        }
        [DataMember(Name = "mstUnitAbilityId1")][JsonProperty("mstUnitAbilityId1")]
        public string MstUnitAbilityId1 
        {
            get => _obscured_mstUnitAbilityId1;
            set => _obscured_mstUnitAbilityId1 = value ?? string.Empty;
        }
        [DataMember(Name = "DropBattlePoint")][JsonProperty("DropBattlePoint")]
        public int DropBattlePoint 
        {
            get => _obscured_DropBattlePoint;
            set => _obscured_DropBattlePoint = value;
        }
        [DataMember(Name = "mstTransformationEnemyStageParameterId")][JsonProperty("mstTransformationEnemyStageParameterId")]
        public string MstTransformationEnemyStageParameterId 
        {
            get => _obscured_mstTransformationEnemyStageParameterId;
            set => _obscured_mstTransformationEnemyStageParameterId = value ?? string.Empty;
        }
        [DataMember(Name = "transformationConditionType")][JsonProperty("transformationConditionType")]
        public UnitTransformationConditionType TransformationConditionType { get; set; }
        [DataMember(Name = "transformationConditionValue")][JsonProperty("transformationConditionValue")]
        public string TransformationConditionValue 
        {
            get => _obscured_transformationConditionValue;
            set => _obscured_transformationConditionValue = value ?? string.Empty;
        }


        ObscuredString _obscured_id;
        ObscuredString _obscured_mstEnemyCharacterId;
        ObscuredInt _obscured_sortOrder;
        ObscuredInt _obscured_hp;
        ObscuredInt _obscured_damageKnockBackCount;
        ObscuredInt _obscured_moveSpeed;
        ObscuredFloat _obscured_wellDistance;
        ObscuredInt _obscured_attackPower;
        ObscuredInt _obscured_attackComboCycle;
        ObscuredString _obscured_mstUnitAbilityId1;
        ObscuredInt _obscured_DropBattlePoint;
        ObscuredString _obscured_mstTransformationEnemyStageParameterId;
        ObscuredString _obscured_transformationConditionValue;
    }
}
