// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MstEventBonusUnitData
    {
        [DataMember(Name = "mstUnitId")][JsonProperty("mstUnitId")]
        public string MstUnitId 
        {
            get => _obscured_mstUnitId;
            set => _obscured_mstUnitId = value ?? string.Empty;
        }
        [DataMember(Name = "bonusPercentage")][JsonProperty("bonusPercentage")]
        public int BonusPercentage 
        {
            get => _obscured_bonusPercentage;
            set => _obscured_bonusPercentage = value;
        }
        [DataMember(Name = "eventBonusGroupId")][JsonProperty("eventBonusGroupId")]
        public string EventBonusGroupId 
        {
            get => _obscured_eventBonusGroupId;
            set => _obscured_eventBonusGroupId = value ?? string.Empty;
        }
        [DataMember(Name = "isPickUp")][JsonProperty("isPickUp")]
        public bool IsPickUp 
        {
            get => _obscured_isPickUp;
            set => _obscured_isPickUp = value;
        }


        ObscuredString _obscured_mstUnitId;
        ObscuredInt _obscured_bonusPercentage;
        ObscuredString _obscured_eventBonusGroupId;
        ObscuredBool _obscured_isPickUp;
    }
}
