// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MstExchangeRewardData
    {
        [DataMember(Name = "id")][JsonProperty("id")]
        public string Id 
        {
            get => _obscured_id;
            set => _obscured_id = value ?? string.Empty;
        }
        [DataMember(Name = "mstExchangeLineupId")][JsonProperty("mstExchangeLineupId")]
        public string MstExchangeLineupId 
        {
            get => _obscured_mstExchangeLineupId;
            set => _obscured_mstExchangeLineupId = value ?? string.Empty;
        }
        [DataMember(Name = "resourceType")][JsonProperty("resourceType")]
        public ResourceType ResourceType { get; set; }
        [DataMember(Name = "resourceId")][JsonProperty("resourceId")]
        public string ResourceId 
        {
            get => _obscured_resourceId;
            set => _obscured_resourceId = value ?? string.Empty;
        }
        [DataMember(Name = "resourceAmount")][JsonProperty("resourceAmount")]
        public int ResourceAmount 
        {
            get => _obscured_resourceAmount;
            set => _obscured_resourceAmount = value;
        }


        ObscuredString _obscured_id;
        ObscuredString _obscured_mstExchangeLineupId;
        ObscuredString _obscured_resourceId;
        ObscuredInt _obscured_resourceAmount;
    }
}
