// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MstEnemyOutpostData
    {
        [DataMember(Name = "id")][JsonProperty("id")]
        public string Id 
        {
            get => _obscured_id;
            set => _obscured_id = value ?? string.Empty;
        }
        [DataMember(Name = "hp")][JsonProperty("hp")]
        public int Hp 
        {
            get => _obscured_hp;
            set => _obscured_hp = value;
        }
        [DataMember(Name = "outpostAssetKey")][JsonProperty("outpostAssetKey")]
        public string OutpostAssetKey 
        {
            get => _obscured_outpostAssetKey;
            set => _obscured_outpostAssetKey = value ?? string.Empty;
        }
        [DataMember(Name = "artworkAssetKey")][JsonProperty("artworkAssetKey")]
        public string ArtworkAssetKey 
        {
            get => _obscured_artworkAssetKey;
            set => _obscured_artworkAssetKey = value ?? string.Empty;
        }
        [DataMember(Name = "isDamageInvalidation")][JsonProperty("isDamageInvalidation")]
        public bool IsDamageInvalidation 
        {
            get => _obscured_isDamageInvalidation;
            set => _obscured_isDamageInvalidation = value;
        }


        ObscuredString _obscured_id;
        ObscuredInt _obscured_hp;
        ObscuredString _obscured_outpostAssetKey;
        ObscuredString _obscured_artworkAssetKey;
        ObscuredBool _obscured_isDamageInvalidation;
    }
}
