// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MstI18nData
    {
        [DataMember(Name = "mstAbilityI18n")][JsonProperty("mstAbilityI18n")]
        public MstAbilityI18nData[] MstAbilityI18n { get; set; }
        [DataMember(Name = "mstArtworkI18n")][JsonProperty("mstArtworkI18n")]
        public MstArtworkI18nData[] MstArtworkI18n { get; set; }
        [DataMember(Name = "mstArtworkFragmentI18n")][JsonProperty("mstArtworkFragmentI18n")]
        public MstArtworkFragmentI18nData[] MstArtworkFragmentI18n { get; set; }
        [DataMember(Name = "mstAttackI18n")][JsonProperty("mstAttackI18n")]
        public MstAttackI18nData[] MstAttackI18n { get; set; }
        [DataMember(Name = "MstEnemyCharacterI18n")][JsonProperty("MstEnemyCharacterI18n")]
        public MstEnemyCharacterI18nData[] MstEnemyCharacterI18n { get; set; }
        [DataMember(Name = "mstEmblemI18n")][JsonProperty("mstEmblemI18n")]
        public MstEmblemI18nData[] MstEmblemI18n { get; set; }
        [DataMember(Name = "mstEventI18n")][JsonProperty("mstEventI18n")]
        public MstEventI18nData[] MstEventI18n { get; set; }
        [DataMember(Name = "mstEventDisplayUnitI18n")][JsonProperty("mstEventDisplayUnitI18n")]
        public MstEventDisplayUnitI18nData[] MstEventDisplayUnitI18n { get; set; }
        [DataMember(Name = "mstUnitI18n")][JsonProperty("mstUnitI18n")]
        public MstUnitI18nData[] MstUnitI18n { get; set; }
        [DataMember(Name = "mstInGameI18n")][JsonProperty("mstInGameI18n")]
        public MstInGameI18nData[] MstInGameI18n { get; set; }
        [DataMember(Name = "mstItemI18n")][JsonProperty("mstItemI18n")]
        public MstItemI18nData[] MstItemI18n { get; set; }
        [DataMember(Name = "mstMissionAchievementI18n")][JsonProperty("mstMissionAchievementI18n")]
        public MstMissionAchievementI18nData[] MstMissionAchievementI18n { get; set; }
        [DataMember(Name = "mstMissionDailyI18n")][JsonProperty("mstMissionDailyI18n")]
        public MstMissionDailyI18nData[] MstMissionDailyI18n { get; set; }
        [DataMember(Name = "mstMissionWeeklyI18n")][JsonProperty("mstMissionWeeklyI18n")]
        public MstMissionWeeklyI18nData[] MstMissionWeeklyI18n { get; set; }
        [DataMember(Name = "mstMissionBeginnerI18n")][JsonProperty("mstMissionBeginnerI18n")]
        public MstMissionBeginnerI18nData[] MstMissionBeginnerI18n { get; set; }
        [DataMember(Name = "mstMissionBeginnerPromptPhraseI18n")][JsonProperty("mstMissionBeginnerPromptPhraseI18n")]
        public MstMissionBeginnerPromptPhraseI18nData[] MstMissionBeginnerPromptPhraseI18n { get; set; }
        [DataMember(Name = "mstMissionEventI18n")][JsonProperty("mstMissionEventI18n")]
        public MstMissionEventI18nData[] MstMissionEventI18n { get; set; }
        [DataMember(Name = "mstMissionLimitedTermI18n")][JsonProperty("mstMissionLimitedTermI18n")]
        public MstMissionLimitedTermI18nData[] MstMissionLimitedTermI18n { get; set; }
        [DataMember(Name = "mstOutpostEnhancementI18n")][JsonProperty("mstOutpostEnhancementI18n")]
        public MstOutpostEnhancementI18nData[] MstOutpostEnhancementI18n { get; set; }
        [DataMember(Name = "mstOutpostEnhancementLevelI18n")][JsonProperty("mstOutpostEnhancementLevelI18n")]
        public MstOutpostEnhancementLevelI18nData[] MstOutpostEnhancementLevelI18n { get; set; }
        [DataMember(Name = "mstPackI18n")][JsonProperty("mstPackI18n")]
        public MstPackI18nData[] MstPackI18n { get; set; }
        [DataMember(Name = "mstShopPassI18n")][JsonProperty("mstShopPassI18n")]
        public MstShopPassI18nData[] MstShopPassI18n { get; set; }
        [DataMember(Name = "mstExchangeI18n")][JsonProperty("mstExchangeI18n")]
        public MstExchangeI18nData[] MstExchangeI18n { get; set; }
        [DataMember(Name = "mstQuestI18n")][JsonProperty("mstQuestI18n")]
        public MstQuestI18nData[] MstQuestI18n { get; set; }
        [DataMember(Name = "mstSeriesI18n")][JsonProperty("mstSeriesI18n")]
        public MstSeriesI18nData[] MstSeriesI18n { get; set; }
        [DataMember(Name = "mstSpecialAttackI18n")][JsonProperty("mstSpecialAttackI18n")]
        public MstSpecialAttackI18nData[] MstSpecialAttackI18n { get; set; }
        [DataMember(Name = "mstSpeechBalloonI18n")][JsonProperty("mstSpeechBalloonI18n")]
        public MstSpeechBalloonI18nData[] MstSpeechBalloonI18n { get; set; }
        [DataMember(Name = "mstStageI18n")][JsonProperty("mstStageI18n")]
        public MstStageI18nData[] MstStageI18n { get; set; }
        [DataMember(Name = "mstStoreProductI18n")][JsonProperty("mstStoreProductI18n")]
        public MstStoreProductI18nData[] MstStoreProductI18n { get; set; }
        [DataMember(Name = "mstTutorialTipI18n")][JsonProperty("mstTutorialTipI18n")]
        public MstTutorialTipI18nData[] MstTutorialTipI18n { get; set; }
        [DataMember(Name = "mstResultTipI18n")][JsonProperty("mstResultTipI18n")]
        public MstResultTipI18nData[] MstResultTipI18n { get; set; }
        [DataMember(Name = "mstAdventBattleI18n")][JsonProperty("mstAdventBattleI18n")]
        public MstAdventBattleI18nData[] MstAdventBattleI18n { get; set; }
        [DataMember(Name = "mstDummyUserI18n")][JsonProperty("mstDummyUserI18n")]
        public MstDummyUserI18nData[] MstDummyUserI18n { get; set; }
        [DataMember(Name = "mstPvpI18n")][JsonProperty("mstPvpI18n")]
        public MstPvpI18nData[] MstPvpI18n { get; set; }


    }
}
