// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MstInGameSpecialRuleUnitStatusData
    {
        [DataMember(Name = "id")][JsonProperty("id")]
        public string Id 
        {
            get => _obscured_id;
            set => _obscured_id = value ?? string.Empty;
        }
        [DataMember(Name = "groupId")][JsonProperty("groupId")]
        public string GroupId 
        {
            get => _obscured_groupId;
            set => _obscured_groupId = value ?? string.Empty;
        }
        [DataMember(Name = "targetType")][JsonProperty("targetType")]
        public InGameSpecialRuleUnitStatusTargetType TargetType { get; set; }
        [DataMember(Name = "targetValue")][JsonProperty("targetValue")]
        public string TargetValue 
        {
            get => _obscured_targetValue;
            set => _obscured_targetValue = value ?? string.Empty;
        }
        [DataMember(Name = "statusParameterType")][JsonProperty("statusParameterType")]
        public InGameSpecialRuleUnitStatusParameterType StatusParameterType { get; set; }
        [DataMember(Name = "effectValue")][JsonProperty("effectValue")]
        public int EffectValue 
        {
            get => _obscured_effectValue;
            set => _obscured_effectValue = value;
        }


        ObscuredString _obscured_id;
        ObscuredString _obscured_groupId;
        ObscuredString _obscured_targetValue;
        ObscuredInt _obscured_effectValue;
    }
}
