// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MstIdleIncentiveItemData
    {
        [DataMember(Name = "id")][JsonProperty("id")]
        public string Id 
        {
            get => _obscured_id;
            set => _obscured_id = value ?? string.Empty;
        }
        [DataMember(Name = "mstIdleIncentiveItemGroupId")][JsonProperty("mstIdleIncentiveItemGroupId")]
        public string MstIdleIncentiveItemGroupId 
        {
            get => _obscured_mstIdleIncentiveItemGroupId;
            set => _obscured_mstIdleIncentiveItemGroupId = value ?? string.Empty;
        }
        [DataMember(Name = "mstItemId")][JsonProperty("mstItemId")]
        public string MstItemId 
        {
            get => _obscured_mstItemId;
            set => _obscured_mstItemId = value ?? string.Empty;
        }
        [DataMember(Name = "baseAmount")][JsonProperty("baseAmount")]
        public float BaseAmount 
        {
            get => _obscured_baseAmount;
            set => _obscured_baseAmount = value;
        }


        ObscuredString _obscured_id;
        ObscuredString _obscured_mstIdleIncentiveItemGroupId;
        ObscuredString _obscured_mstItemId;
        ObscuredFloat _obscured_baseAmount;
    }
}
