// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MstItemTransitionData
    {
        [DataMember(Name = "id")][JsonProperty("id")]
        public string Id 
        {
            get => _obscured_id;
            set => _obscured_id = value ?? string.Empty;
        }
        [DataMember(Name = "mstItemId")][JsonProperty("mstItemId")]
        public string MstItemId 
        {
            get => _obscured_mstItemId;
            set => _obscured_mstItemId = value ?? string.Empty;
        }
        [DataMember(Name = "transition1")][JsonProperty("transition1")]
        public ItemTransitionType Transition1 { get; set; }
        [DataMember(Name = "transition1MstId")][JsonProperty("transition1MstId")]
        public string Transition1MstId 
        {
            get => _obscured_transition1MstId;
            set => _obscured_transition1MstId = value ?? string.Empty;
        }
        [DataMember(Name = "transition2")][JsonProperty("transition2")]
        public ItemTransitionType Transition2 { get; set; }
        [DataMember(Name = "transition2MstId")][JsonProperty("transition2MstId")]
        public string Transition2MstId 
        {
            get => _obscured_transition2MstId;
            set => _obscured_transition2MstId = value ?? string.Empty;
        }


        ObscuredString _obscured_id;
        ObscuredString _obscured_mstItemId;
        ObscuredString _obscured_transition1MstId;
        ObscuredString _obscured_transition2MstId;
    }
}
