// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MstKomaLineData
    {
        [DataMember(Name = "id")][JsonProperty("id")]
        public string Id 
        {
            get => _obscured_id;
            set => _obscured_id = value ?? string.Empty;
        }
        [DataMember(Name = "mstPageId")][JsonProperty("mstPageId")]
        public string MstPageId 
        {
            get => _obscured_mstPageId;
            set => _obscured_mstPageId = value ?? string.Empty;
        }
        [DataMember(Name = "row")][JsonProperty("row")]
        public int Row 
        {
            get => _obscured_row;
            set => _obscured_row = value;
        }
        [DataMember(Name = "height")][JsonProperty("height")]
        public float Height 
        {
            get => _obscured_height;
            set => _obscured_height = value;
        }
        [DataMember(Name = "komaLineLayoutAssetKey")][JsonProperty("komaLineLayoutAssetKey")]
        public string KomaLineLayoutAssetKey 
        {
            get => _obscured_komaLineLayoutAssetKey;
            set => _obscured_komaLineLayoutAssetKey = value ?? string.Empty;
        }
        [DataMember(Name = "koma1AssetKey")][JsonProperty("koma1AssetKey")]
        public string Koma1AssetKey 
        {
            get => _obscured_koma1AssetKey;
            set => _obscured_koma1AssetKey = value ?? string.Empty;
        }
        [DataMember(Name = "koma1Width")][JsonProperty("koma1Width")]
        public float Koma1Width 
        {
            get => _obscured_koma1Width;
            set => _obscured_koma1Width = value;
        }
        [DataMember(Name = "koma1BackGroundOffset")][JsonProperty("koma1BackGroundOffset")]
        public float Koma1BackGroundOffset 
        {
            get => _obscured_koma1BackGroundOffset;
            set => _obscured_koma1BackGroundOffset = value;
        }
        [DataMember(Name = "koma1EffectType")][JsonProperty("koma1EffectType")]
        public KomaEffectType Koma1EffectType { get; set; }
        [DataMember(Name = "koma1EffectParameter1")][JsonProperty("koma1EffectParameter1")]
        public string Koma1EffectParameter1 
        {
            get => _obscured_koma1EffectParameter1;
            set => _obscured_koma1EffectParameter1 = value ?? string.Empty;
        }
        [DataMember(Name = "koma1EffectParameter2")][JsonProperty("koma1EffectParameter2")]
        public string Koma1EffectParameter2 
        {
            get => _obscured_koma1EffectParameter2;
            set => _obscured_koma1EffectParameter2 = value ?? string.Empty;
        }
        [DataMember(Name = "koma1EffectTargetSide")][JsonProperty("koma1EffectTargetSide")]
        public KomaEffectTargetSide Koma1EffectTargetSide { get; set; }
        [DataMember(Name = "koma1EffectTargetColors")][JsonProperty("koma1EffectTargetColors")]
        public string Koma1EffectTargetColors 
        {
            get => _obscured_koma1EffectTargetColors;
            set => _obscured_koma1EffectTargetColors = value ?? string.Empty;
        }
        [DataMember(Name = "koma1EffectTargetRoles")][JsonProperty("koma1EffectTargetRoles")]
        public string Koma1EffectTargetRoles 
        {
            get => _obscured_koma1EffectTargetRoles;
            set => _obscured_koma1EffectTargetRoles = value ?? string.Empty;
        }
        [DataMember(Name = "koma2AssetKey")][JsonProperty("koma2AssetKey")]
        public string Koma2AssetKey 
        {
            get => _obscured_koma2AssetKey;
            set => _obscured_koma2AssetKey = value ?? string.Empty;
        }
        [DataMember(Name = "koma2Width")][JsonProperty("koma2Width")]
        public float? Koma2Width 
        {
            get => _obscured_koma2Width;
            set => _obscured_koma2Width = value;
        }
        [DataMember(Name = "koma2BackGroundOffset")][JsonProperty("koma2BackGroundOffset")]
        public float? Koma2BackGroundOffset 
        {
            get => _obscured_koma2BackGroundOffset;
            set => _obscured_koma2BackGroundOffset = value;
        }
        [DataMember(Name = "koma2EffectType")][JsonProperty("koma2EffectType")]
        public KomaEffectType? Koma2EffectType { get; set; }
        [DataMember(Name = "koma2EffectParameter1")][JsonProperty("koma2EffectParameter1")]
        public string Koma2EffectParameter1 
        {
            get => _obscured_koma2EffectParameter1;
            set => _obscured_koma2EffectParameter1 = value ?? string.Empty;
        }
        [DataMember(Name = "koma2EffectParameter2")][JsonProperty("koma2EffectParameter2")]
        public string Koma2EffectParameter2 
        {
            get => _obscured_koma2EffectParameter2;
            set => _obscured_koma2EffectParameter2 = value ?? string.Empty;
        }
        [DataMember(Name = "koma2EffectTargetSide")][JsonProperty("koma2EffectTargetSide")]
        public KomaEffectTargetSide? Koma2EffectTargetSide { get; set; }
        [DataMember(Name = "koma2EffectTargetColors")][JsonProperty("koma2EffectTargetColors")]
        public string Koma2EffectTargetColors 
        {
            get => _obscured_koma2EffectTargetColors;
            set => _obscured_koma2EffectTargetColors = value ?? string.Empty;
        }
        [DataMember(Name = "koma2EffectTargetRoles")][JsonProperty("koma2EffectTargetRoles")]
        public string Koma2EffectTargetRoles 
        {
            get => _obscured_koma2EffectTargetRoles;
            set => _obscured_koma2EffectTargetRoles = value ?? string.Empty;
        }
        [DataMember(Name = "koma3AssetKey")][JsonProperty("koma3AssetKey")]
        public string Koma3AssetKey 
        {
            get => _obscured_koma3AssetKey;
            set => _obscured_koma3AssetKey = value ?? string.Empty;
        }
        [DataMember(Name = "koma3Width")][JsonProperty("koma3Width")]
        public float? Koma3Width 
        {
            get => _obscured_koma3Width;
            set => _obscured_koma3Width = value;
        }
        [DataMember(Name = "koma3BackGroundOffset")][JsonProperty("koma3BackGroundOffset")]
        public float? Koma3BackGroundOffset 
        {
            get => _obscured_koma3BackGroundOffset;
            set => _obscured_koma3BackGroundOffset = value;
        }
        [DataMember(Name = "koma3EffectType")][JsonProperty("koma3EffectType")]
        public KomaEffectType? Koma3EffectType { get; set; }
        [DataMember(Name = "koma3EffectParameter1")][JsonProperty("koma3EffectParameter1")]
        public string Koma3EffectParameter1 
        {
            get => _obscured_koma3EffectParameter1;
            set => _obscured_koma3EffectParameter1 = value ?? string.Empty;
        }
        [DataMember(Name = "koma3EffectParameter2")][JsonProperty("koma3EffectParameter2")]
        public string Koma3EffectParameter2 
        {
            get => _obscured_koma3EffectParameter2;
            set => _obscured_koma3EffectParameter2 = value ?? string.Empty;
        }
        [DataMember(Name = "koma3EffectTargetSide")][JsonProperty("koma3EffectTargetSide")]
        public KomaEffectTargetSide? Koma3EffectTargetSide { get; set; }
        [DataMember(Name = "koma3EffectTargetColors")][JsonProperty("koma3EffectTargetColors")]
        public string Koma3EffectTargetColors 
        {
            get => _obscured_koma3EffectTargetColors;
            set => _obscured_koma3EffectTargetColors = value ?? string.Empty;
        }
        [DataMember(Name = "koma3EffectTargetRoles")][JsonProperty("koma3EffectTargetRoles")]
        public string Koma3EffectTargetRoles 
        {
            get => _obscured_koma3EffectTargetRoles;
            set => _obscured_koma3EffectTargetRoles = value ?? string.Empty;
        }
        [DataMember(Name = "koma4AssetKey")][JsonProperty("koma4AssetKey")]
        public string Koma4AssetKey 
        {
            get => _obscured_koma4AssetKey;
            set => _obscured_koma4AssetKey = value ?? string.Empty;
        }
        [DataMember(Name = "koma4Width")][JsonProperty("koma4Width")]
        public float? Koma4Width 
        {
            get => _obscured_koma4Width;
            set => _obscured_koma4Width = value;
        }
        [DataMember(Name = "koma4BackGroundOffset")][JsonProperty("koma4BackGroundOffset")]
        public float? Koma4BackGroundOffset 
        {
            get => _obscured_koma4BackGroundOffset;
            set => _obscured_koma4BackGroundOffset = value;
        }
        [DataMember(Name = "koma4EffectType")][JsonProperty("koma4EffectType")]
        public KomaEffectType? Koma4EffectType { get; set; }
        [DataMember(Name = "koma4EffectParameter1")][JsonProperty("koma4EffectParameter1")]
        public string Koma4EffectParameter1 
        {
            get => _obscured_koma4EffectParameter1;
            set => _obscured_koma4EffectParameter1 = value ?? string.Empty;
        }
        [DataMember(Name = "koma4EffectParameter2")][JsonProperty("koma4EffectParameter2")]
        public string Koma4EffectParameter2 
        {
            get => _obscured_koma4EffectParameter2;
            set => _obscured_koma4EffectParameter2 = value ?? string.Empty;
        }
        [DataMember(Name = "koma4EffectTargetSide")][JsonProperty("koma4EffectTargetSide")]
        public KomaEffectTargetSide? Koma4EffectTargetSide { get; set; }
        [DataMember(Name = "koma4EffectTargetColors")][JsonProperty("koma4EffectTargetColors")]
        public string Koma4EffectTargetColors 
        {
            get => _obscured_koma4EffectTargetColors;
            set => _obscured_koma4EffectTargetColors = value ?? string.Empty;
        }
        [DataMember(Name = "koma4EffectTargetRoles")][JsonProperty("koma4EffectTargetRoles")]
        public string Koma4EffectTargetRoles 
        {
            get => _obscured_koma4EffectTargetRoles;
            set => _obscured_koma4EffectTargetRoles = value ?? string.Empty;
        }


        ObscuredString _obscured_id;
        ObscuredString _obscured_mstPageId;
        ObscuredInt _obscured_row;
        ObscuredFloat _obscured_height;
        ObscuredString _obscured_komaLineLayoutAssetKey;
        ObscuredString _obscured_koma1AssetKey;
        ObscuredFloat _obscured_koma1Width;
        ObscuredFloat _obscured_koma1BackGroundOffset;
        ObscuredString _obscured_koma1EffectParameter1;
        ObscuredString _obscured_koma1EffectParameter2;
        ObscuredString _obscured_koma1EffectTargetColors;
        ObscuredString _obscured_koma1EffectTargetRoles;
        ObscuredString _obscured_koma2AssetKey;
        ObscuredFloat? _obscured_koma2Width;
        ObscuredFloat? _obscured_koma2BackGroundOffset;
        ObscuredString _obscured_koma2EffectParameter1;
        ObscuredString _obscured_koma2EffectParameter2;
        ObscuredString _obscured_koma2EffectTargetColors;
        ObscuredString _obscured_koma2EffectTargetRoles;
        ObscuredString _obscured_koma3AssetKey;
        ObscuredFloat? _obscured_koma3Width;
        ObscuredFloat? _obscured_koma3BackGroundOffset;
        ObscuredString _obscured_koma3EffectParameter1;
        ObscuredString _obscured_koma3EffectParameter2;
        ObscuredString _obscured_koma3EffectTargetColors;
        ObscuredString _obscured_koma3EffectTargetRoles;
        ObscuredString _obscured_koma4AssetKey;
        ObscuredFloat? _obscured_koma4Width;
        ObscuredFloat? _obscured_koma4BackGroundOffset;
        ObscuredString _obscured_koma4EffectParameter1;
        ObscuredString _obscured_koma4EffectParameter2;
        ObscuredString _obscured_koma4EffectTargetColors;
        ObscuredString _obscured_koma4EffectTargetRoles;
    }
}
