// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MstMangaAnimationData
    {
        [DataMember(Name = "id")][JsonProperty("id")]
        public string Id 
        {
            get => _obscured_id;
            set => _obscured_id = value ?? string.Empty;
        }
        [DataMember(Name = "mstStageId")][JsonProperty("mstStageId")]
        public string MstStageId 
        {
            get => _obscured_mstStageId;
            set => _obscured_mstStageId = value ?? string.Empty;
        }
        [DataMember(Name = "conditionType")][JsonProperty("conditionType")]
        public MangaAnimationConditionType ConditionType { get; set; }
        [DataMember(Name = "conditionValue")][JsonProperty("conditionValue")]
        public string ConditionValue 
        {
            get => _obscured_conditionValue;
            set => _obscured_conditionValue = value ?? string.Empty;
        }
        [DataMember(Name = "animationStartDelay")][JsonProperty("animationStartDelay")]
        public int AnimationStartDelay 
        {
            get => _obscured_animationStartDelay;
            set => _obscured_animationStartDelay = value;
        }
        [DataMember(Name = "animationSpeed")][JsonProperty("animationSpeed")]
        public float AnimationSpeed 
        {
            get => _obscured_animationSpeed;
            set => _obscured_animationSpeed = value;
        }
        [DataMember(Name = "isPause")][JsonProperty("isPause")]
        public bool IsPause 
        {
            get => _obscured_isPause;
            set => _obscured_isPause = value;
        }
        [DataMember(Name = "canSkip")][JsonProperty("canSkip")]
        public bool CanSkip 
        {
            get => _obscured_canSkip;
            set => _obscured_canSkip = value;
        }
        [DataMember(Name = "assetKey")][JsonProperty("assetKey")]
        public string AssetKey 
        {
            get => _obscured_assetKey;
            set => _obscured_assetKey = value ?? string.Empty;
        }


        ObscuredString _obscured_id;
        ObscuredString _obscured_mstStageId;
        ObscuredString _obscured_conditionValue;
        ObscuredInt _obscured_animationStartDelay;
        ObscuredFloat _obscured_animationSpeed;
        ObscuredBool _obscured_isPause;
        ObscuredBool _obscured_canSkip;
        ObscuredString _obscured_assetKey;
    }
}
