// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MstMissionWeeklyI18nData
    {
        [DataMember(Name = "id")][JsonProperty("id")]
        public string Id 
        {
            get => _obscured_id;
            set => _obscured_id = value ?? string.Empty;
        }
        [DataMember(Name = "mstMissionWeeklyId")][JsonProperty("mstMissionWeeklyId")]
        public string MstMissionWeeklyId 
        {
            get => _obscured_mstMissionWeeklyId;
            set => _obscured_mstMissionWeeklyId = value ?? string.Empty;
        }
        [DataMember(Name = "language")][JsonProperty("language")]
        public Language Language { get; set; }
        [DataMember(Name = "description")][JsonProperty("description")]
        public string Description 
        {
            get => _obscured_description;
            set => _obscured_description = value ?? string.Empty;
        }


        ObscuredString _obscured_id;
        ObscuredString _obscured_mstMissionWeeklyId;
        ObscuredString _obscured_description;
    }
}
