// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MstPvpBonusPointData
    {
        [DataMember(Name = "id")][JsonProperty("id")]
        public string Id 
        {
            get => _obscured_id;
            set => _obscured_id = value ?? string.Empty;
        }
        [DataMember(Name = "bonusType")][JsonProperty("bonusType")]
        public PvpBonusType BonusType { get; set; }
        [DataMember(Name = "conditionValue")][JsonProperty("conditionValue")]
        public string? ConditionValue 
        {
            get => _obscured_conditionValue;
            set => _obscured_conditionValue = value;
        }
        [DataMember(Name = "bonusPoint")][JsonProperty("bonusPoint")]
        public int BonusPoint 
        {
            get => _obscured_bonusPoint;
            set => _obscured_bonusPoint = value;
        }


        ObscuredString _obscured_id;
        ObscuredString? _obscured_conditionValue;
        ObscuredInt _obscured_bonusPoint;
    }
}
