// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MstPartyUnitCountData
    {
        [DataMember(Name = "id")][JsonProperty("id")]
        public string Id 
        {
            get => _obscured_id;
            set => _obscured_id = value ?? string.Empty;
        }
        [DataMember(Name = "mstStageId")][JsonProperty("mstStageId")]
        public string MstStageId 
        {
            get => _obscured_mstStageId;
            set => _obscured_mstStageId = value ?? string.Empty;
        }
        [DataMember(Name = "maxCount")][JsonProperty("maxCount")]
        public int MaxCount 
        {
            get => _obscured_maxCount;
            set => _obscured_maxCount = value;
        }


        ObscuredString _obscured_id;
        ObscuredString _obscured_mstStageId;
        ObscuredInt _obscured_maxCount;
    }
}
