// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MstPvpRankData
    {
        [DataMember(Name = "id")][JsonProperty("id")]
        public string Id 
        {
            get => _obscured_id;
            set => _obscured_id = value ?? string.Empty;
        }
        [DataMember(Name = "assetKey")][JsonProperty("assetKey")]
        public string AssetKey 
        {
            get => _obscured_assetKey;
            set => _obscured_assetKey = value ?? string.Empty;
        }
        [DataMember(Name = "rankClassType")][JsonProperty("rankClassType")]
        public PvpRankClassType RankClassType { get; set; }
        [DataMember(Name = "rankClassLevel")][JsonProperty("rankClassLevel")]
        public int RankClassLevel 
        {
            get => _obscured_rankClassLevel;
            set => _obscured_rankClassLevel = value;
        }
        [DataMember(Name = "requiredLowerScore")][JsonProperty("requiredLowerScore")]
        public long RequiredLowerScore 
        {
            get => _obscured_requiredLowerScore;
            set => _obscured_requiredLowerScore = value;
        }
        [DataMember(Name = "winAddPoint")][JsonProperty("winAddPoint")]
        public int WinAddPoint 
        {
            get => _obscured_winAddPoint;
            set => _obscured_winAddPoint = value;
        }
        [DataMember(Name = "loseSubPoint")][JsonProperty("loseSubPoint")]
        public int LoseSubPoint 
        {
            get => _obscured_loseSubPoint;
            set => _obscured_loseSubPoint = value;
        }


        ObscuredString _obscured_id;
        ObscuredString _obscured_assetKey;
        ObscuredInt _obscured_rankClassLevel;
        ObscuredLong _obscured_requiredLowerScore;
        ObscuredInt _obscured_winAddPoint;
        ObscuredInt _obscured_loseSubPoint;
    }
}
