// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MstPvpData
    {
        [DataMember(Name = "id")][JsonProperty("id")]
        public string Id 
        {
            get => _obscured_id;
            set => _obscured_id = value ?? string.Empty;
        }
        [DataMember(Name = "rankingMinPvpRankClass")][JsonProperty("rankingMinPvpRankClass")]
        public PvpRankClassType? RankingMinPvpRankClass { get; set; }
        [DataMember(Name = "maxDailyChallengeCount")][JsonProperty("maxDailyChallengeCount")]
        public int MaxDailyChallengeCount 
        {
            get => _obscured_maxDailyChallengeCount;
            set => _obscured_maxDailyChallengeCount = value;
        }
        [DataMember(Name = "maxDailyItemChallengeCount")][JsonProperty("maxDailyItemChallengeCount")]
        public int MaxDailyItemChallengeCount 
        {
            get => _obscured_maxDailyItemChallengeCount;
            set => _obscured_maxDailyItemChallengeCount = value;
        }
        [DataMember(Name = "itemChallengeCostAmount")][JsonProperty("itemChallengeCostAmount")]
        public int ItemChallengeCostAmount 
        {
            get => _obscured_itemChallengeCostAmount;
            set => _obscured_itemChallengeCostAmount = value;
        }
        [DataMember(Name = "initialBattlePoint")][JsonProperty("initialBattlePoint")]
        public int InitialBattlePoint 
        {
            get => _obscured_initialBattlePoint;
            set => _obscured_initialBattlePoint = value;
        }
        [DataMember(Name = "mstInGameId")][JsonProperty("mstInGameId")]
        public string MstInGameId 
        {
            get => _obscured_mstInGameId;
            set => _obscured_mstInGameId = value ?? string.Empty;
        }


        ObscuredString _obscured_id;
        ObscuredInt _obscured_maxDailyChallengeCount;
        ObscuredInt _obscured_maxDailyItemChallengeCount;
        ObscuredInt _obscured_itemChallengeCostAmount;
        ObscuredInt _obscured_initialBattlePoint;
        ObscuredString _obscured_mstInGameId;
    }
}
