// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MstQuestI18nData
    {
        [DataMember(Name = "id")][JsonProperty("id")]
        public string Id 
        {
            get => _obscured_id;
            set => _obscured_id = value ?? string.Empty;
        }
        [DataMember(Name = "mstQuestId")][JsonProperty("mstQuestId")]
        public string MstQuestId 
        {
            get => _obscured_mstQuestId;
            set => _obscured_mstQuestId = value ?? string.Empty;
        }
        [DataMember(Name = "language")][JsonProperty("language")]
        public Language Language { get; set; }
        [DataMember(Name = "name")][JsonProperty("name")]
        public string Name 
        {
            get => _obscured_name;
            set => _obscured_name = value ?? string.Empty;
        }
        [DataMember(Name = "categoryName")][JsonProperty("categoryName")]
        public string CategoryName 
        {
            get => _obscured_categoryName;
            set => _obscured_categoryName = value ?? string.Empty;
        }
        [DataMember(Name = "flavorText")][JsonProperty("flavorText")]
        public string FlavorText 
        {
            get => _obscured_flavorText;
            set => _obscured_flavorText = value ?? string.Empty;
        }


        ObscuredString _obscured_id;
        ObscuredString _obscured_mstQuestId;
        ObscuredString _obscured_name;
        ObscuredString _obscured_categoryName;
        ObscuredString _obscured_flavorText;
    }
}
