// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MstQuestEventBonusScheduleData
    {
        [DataMember(Name = "mstQuestId")][JsonProperty("mstQuestId")]
        public string MstQuestId 
        {
            get => _obscured_mstQuestId;
            set => _obscured_mstQuestId = value ?? string.Empty;
        }
        [DataMember(Name = "eventBonusGroupId")][JsonProperty("eventBonusGroupId")]
        public string EventBonusGroupId 
        {
            get => _obscured_eventBonusGroupId;
            set => _obscured_eventBonusGroupId = value ?? string.Empty;
        }
        [DataMember(Name = "startAt")][JsonProperty("startAt")]
        public DateTimeOffset StartAt { get; set; }
        [DataMember(Name = "endAt")][JsonProperty("endAt")]
        public DateTimeOffset EndAt { get; set; }


        ObscuredString _obscured_mstQuestId;
        ObscuredString _obscured_eventBonusGroupId;
    }
}
