// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MstStageClearTimeRewardData
    {
        [DataMember(Name = "mstStageId")][JsonProperty("mstStageId")]
        public string MstStageId 
        {
            get => _obscured_mstStageId;
            set => _obscured_mstStageId = value ?? string.Empty;
        }
        [DataMember(Name = "upperClearTimeMs")][JsonProperty("upperClearTimeMs")]
        public int UpperClearTimeMs 
        {
            get => _obscured_upperClearTimeMs;
            set => _obscured_upperClearTimeMs = value;
        }
        [DataMember(Name = "resourceType")][JsonProperty("resourceType")]
        public ResourceType ResourceType { get; set; }
        [DataMember(Name = "resourceId")][JsonProperty("resourceId")]
        public string ResourceId 
        {
            get => _obscured_resourceId;
            set => _obscured_resourceId = value ?? string.Empty;
        }
        [DataMember(Name = "resourceAmount")][JsonProperty("resourceAmount")]
        public int ResourceAmount 
        {
            get => _obscured_resourceAmount;
            set => _obscured_resourceAmount = value;
        }


        ObscuredString _obscured_mstStageId;
        ObscuredInt _obscured_upperClearTimeMs;
        ObscuredString _obscured_resourceId;
        ObscuredInt _obscured_resourceAmount;
    }
}
