// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MstSpecialAttackI18nData
    {
        [DataMember(Name = "id")][JsonProperty("id")]
        public string Id 
        {
            get => _obscured_id;
            set => _obscured_id = value ?? string.Empty;
        }
        [DataMember(Name = "mstUnitId")][JsonProperty("mstUnitId")]
        public string MstUnitId 
        {
            get => _obscured_mstUnitId;
            set => _obscured_mstUnitId = value ?? string.Empty;
        }
        [DataMember(Name = "language")][JsonProperty("language")]
        public Language Language { get; set; }
        [DataMember(Name = "name")][JsonProperty("name")]
        public string Name 
        {
            get => _obscured_name;
            set => _obscured_name = value ?? string.Empty;
        }


        ObscuredString _obscured_id;
        ObscuredString _obscured_mstUnitId;
        ObscuredString _obscured_name;
    }
}
