// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MstStoreProductData
    {
        [DataMember(Name = "id")][JsonProperty("id")]
        public string Id 
        {
            get => _obscured_id;
            set => _obscured_id = value ?? string.Empty;
        }
        [DataMember(Name = "releaseKey")][JsonProperty("releaseKey")]
        public int ReleaseKey 
        {
            get => _obscured_releaseKey;
            set => _obscured_releaseKey = value;
        }
        [DataMember(Name = "productIdIos")][JsonProperty("productIdIos")]
        public string ProductIdIos 
        {
            get => _obscured_productIdIos;
            set => _obscured_productIdIos = value ?? string.Empty;
        }
        [DataMember(Name = "productIdAndroid")][JsonProperty("productIdAndroid")]
        public string ProductIdAndroid 
        {
            get => _obscured_productIdAndroid;
            set => _obscured_productIdAndroid = value ?? string.Empty;
        }


        ObscuredString _obscured_id;
        ObscuredInt _obscured_releaseKey;
        ObscuredString _obscured_productIdIos;
        ObscuredString _obscured_productIdAndroid;
    }
}
