// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MstTutorialTipI18nData
    {
        [DataMember(Name = "id")][JsonProperty("id")]
        public string Id 
        {
            get => _obscured_id;
            set => _obscured_id = value ?? string.Empty;
        }
        [DataMember(Name = "mstTutorialId")][JsonProperty("mstTutorialId")]
        public string MstTutorialId 
        {
            get => _obscured_mstTutorialId;
            set => _obscured_mstTutorialId = value ?? string.Empty;
        }
        [DataMember(Name = "language")][JsonProperty("language")]
        public Language Language { get; set; }
        [DataMember(Name = "sortOrder")][JsonProperty("sortOrder")]
        public int SortOrder 
        {
            get => _obscured_sortOrder;
            set => _obscured_sortOrder = value;
        }
        [DataMember(Name = "title")][JsonProperty("title")]
        public string Title 
        {
            get => _obscured_title;
            set => _obscured_title = value ?? string.Empty;
        }
        [DataMember(Name = "assetKey")][JsonProperty("assetKey")]
        public string AssetKey 
        {
            get => _obscured_assetKey;
            set => _obscured_assetKey = value ?? string.Empty;
        }


        ObscuredString _obscured_id;
        ObscuredString _obscured_mstTutorialId;
        ObscuredInt _obscured_sortOrder;
        ObscuredString _obscured_title;
        ObscuredString _obscured_assetKey;
    }
}
