// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MstTradePieceData
    {
        [DataMember(Name = "mstTradePieceId")][JsonProperty("mstTradePieceId")]
        public string MstTradePieceId 
        {
            get => _obscured_mstTradePieceId;
            set => _obscured_mstTradePieceId = value ?? string.Empty;
        }
        [DataMember(Name = "mstUnitId")][JsonProperty("mstUnitId")]
        public string MstUnitId 
        {
            get => _obscured_mstUnitId;
            set => _obscured_mstUnitId = value ?? string.Empty;
        }
        [DataMember(Name = "tradeRequiredAmount")][JsonProperty("tradeRequiredAmount")]
        public int TradeRequiredAmount 
        {
            get => _obscured_tradeRequiredAmount;
            set => _obscured_tradeRequiredAmount = value;
        }
        [DataMember(Name = "tradeAmount")][JsonProperty("tradeAmount")]
        public int TradeAmount 
        {
            get => _obscured_tradeAmount;
            set => _obscured_tradeAmount = value;
        }


        ObscuredString _obscured_mstTradePieceId;
        ObscuredString _obscured_mstUnitId;
        ObscuredInt _obscured_tradeRequiredAmount;
        ObscuredInt _obscured_tradeAmount;
    }
}
