// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MstUnitLevelUpData
    {
        [DataMember(Name = "id")][JsonProperty("id")]
        public string Id 
        {
            get => _obscured_id;
            set => _obscured_id = value ?? string.Empty;
        }
        [DataMember(Name = "level")][JsonProperty("level")]
        public int Level 
        {
            get => _obscured_level;
            set => _obscured_level = value;
        }
        [DataMember(Name = "unitLabel")][JsonProperty("unitLabel")]
        public UnitLabel UnitLabel { get; set; }
        [DataMember(Name = "requiredCoin")][JsonProperty("requiredCoin")]
        public int RequiredCoin 
        {
            get => _obscured_requiredCoin;
            set => _obscured_requiredCoin = value;
        }


        ObscuredString _obscured_id;
        ObscuredInt _obscured_level;
        ObscuredInt _obscured_requiredCoin;
    }
}
