// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MstUserLevelUpData
    {
        [DataMember(Name = "level")][JsonProperty("level")]
        public int Level 
        {
            get => _obscured_level;
            set => _obscured_level = value;
        }
        [DataMember(Name = "requiredExp")][JsonProperty("requiredExp")]
        public int RequiredExp 
        {
            get => _obscured_requiredExp;
            set => _obscured_requiredExp = value;
        }
        [DataMember(Name = "rewardDiamond")][JsonProperty("rewardDiamond")]
        public int RewardDiamond 
        {
            get => _obscured_rewardDiamond;
            set => _obscured_rewardDiamond = value;
        }
        [DataMember(Name = "rewardStamina")][JsonProperty("rewardStamina")]
        public int RewardStamina 
        {
            get => _obscured_rewardStamina;
            set => _obscured_rewardStamina = value;
        }
        [DataMember(Name = "mstHandoutId")][JsonProperty("mstHandoutId")]
        public string MstHandoutId 
        {
            get => _obscured_mstHandoutId;
            set => _obscured_mstHandoutId = value ?? string.Empty;
        }


        ObscuredInt _obscured_level;
        ObscuredInt _obscured_requiredExp;
        ObscuredInt _obscured_rewardDiamond;
        ObscuredInt _obscured_rewardStamina;
        ObscuredString _obscured_mstHandoutId;
    }
}
