// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MstUnitGradeUpData
    {
        [DataMember(Name = "id")][JsonProperty("id")]
        public string Id 
        {
            get => _obscured_id;
            set => _obscured_id = value ?? string.Empty;
        }
        [DataMember(Name = "gradeLevel")][JsonProperty("gradeLevel")]
        public int GradeLevel 
        {
            get => _obscured_gradeLevel;
            set => _obscured_gradeLevel = value;
        }
        [DataMember(Name = "unitLabel")][JsonProperty("unitLabel")]
        public UnitLabel UnitLabel { get; set; }
        [DataMember(Name = "requireAmount")][JsonProperty("requireAmount")]
        public int RequireAmount 
        {
            get => _obscured_requireAmount;
            set => _obscured_requireAmount = value;
        }


        ObscuredString _obscured_id;
        ObscuredInt _obscured_gradeLevel;
        ObscuredInt _obscured_requireAmount;
    }
}
