// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class MstUnitEncyclopediaEffectData
    {
        [DataMember(Name = "id")][JsonProperty("id")]
        public string Id 
        {
            get => _obscured_id;
            set => _obscured_id = value ?? string.Empty;
        }
        [DataMember(Name = "mstUnitEncyclopediaRewardId")][JsonProperty("mstUnitEncyclopediaRewardId")]
        public string MstUnitEncyclopediaRewardId 
        {
            get => _obscured_mstUnitEncyclopediaRewardId;
            set => _obscured_mstUnitEncyclopediaRewardId = value ?? string.Empty;
        }
        [DataMember(Name = "effectType")][JsonProperty("effectType")]
        public UnitEncyclopediaEffectType EffectType { get; set; }
        [DataMember(Name = "value")][JsonProperty("value")]
        public float Value 
        {
            get => _obscured_value;
            set => _obscured_value = value;
        }


        ObscuredString _obscured_id;
        ObscuredString _obscured_mstUnitEncyclopediaRewardId;
        ObscuredFloat _obscured_value;
    }
}
