// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class OprGachaI18nData
    {
        [DataMember(Name = "oprGachaId")][JsonProperty("oprGachaId")]
        public string OprGachaId 
        {
            get => _obscured_oprGachaId;
            set => _obscured_oprGachaId = value ?? string.Empty;
        }
        [DataMember(Name = "language")][JsonProperty("language")]
        public Language Language { get; set; }
        [DataMember(Name = "name")][JsonProperty("name")]
        public string Name 
        {
            get => _obscured_name;
            set => _obscured_name = value ?? string.Empty;
        }
        [DataMember(Name = "description")][JsonProperty("description")]
        public string Description 
        {
            get => _obscured_description;
            set => _obscured_description = value ?? string.Empty;
        }
        [DataMember(Name = "maxRarityUpperDescription")][JsonProperty("maxRarityUpperDescription")]
        public string MaxRarityUpperDescription 
        {
            get => _obscured_maxRarityUpperDescription;
            set => _obscured_maxRarityUpperDescription = value ?? string.Empty;
        }
        [DataMember(Name = "pickupUpperDescription")][JsonProperty("pickupUpperDescription")]
        public string PickupUpperDescription 
        {
            get => _obscured_pickupUpperDescription;
            set => _obscured_pickupUpperDescription = value ?? string.Empty;
        }
        [DataMember(Name = "fixedPrizeDescription")][JsonProperty("fixedPrizeDescription")]
        public string FixedPrizeDescription 
        {
            get => _obscured_fixedPrizeDescription;
            set => _obscured_fixedPrizeDescription = value ?? string.Empty;
        }
        [DataMember(Name = "bannerUrl")][JsonProperty("bannerUrl")]
        public string BannerUrl 
        {
            get => _obscured_bannerUrl;
            set => _obscured_bannerUrl = value ?? string.Empty;
        }
        [DataMember(Name = "logoAssetKey")][JsonProperty("logoAssetKey")]
        public string LogoAssetKey 
        {
            get => _obscured_logoAssetKey;
            set => _obscured_logoAssetKey = value ?? string.Empty;
        }
        [DataMember(Name = "logoBannerUrl")][JsonProperty("logoBannerUrl")]
        public string LogoBannerUrl 
        {
            get => _obscured_logoBannerUrl;
            set => _obscured_logoBannerUrl = value ?? string.Empty;
        }
        [DataMember(Name = "gachaBackgroundColor")][JsonProperty("gachaBackgroundColor")]
        public GachaBackgroundColor GachaBackgroundColor { get; set; }
        [DataMember(Name = "gachaBannerSize")][JsonProperty("gachaBannerSize")]
        public GachaBannerSize GachaBannerSize { get; set; }


        ObscuredString _obscured_oprGachaId;
        ObscuredString _obscured_name;
        ObscuredString _obscured_description;
        ObscuredString _obscured_maxRarityUpperDescription;
        ObscuredString _obscured_pickupUpperDescription;
        ObscuredString _obscured_fixedPrizeDescription;
        ObscuredString _obscured_bannerUrl;
        ObscuredString _obscured_logoAssetKey;
        ObscuredString _obscured_logoBannerUrl;
    }
}
