// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class OprGachaUseResourceData
    {
        [DataMember(Name = "oprGachaId")][JsonProperty("oprGachaId")]
        public string OprGachaId 
        {
            get => _obscured_oprGachaId;
            set => _obscured_oprGachaId = value ?? string.Empty;
        }
        [DataMember(Name = "costType")][JsonProperty("costType")]
        public CostType CostType { get; set; }
        [DataMember(Name = "costId")][JsonProperty("costId")]
        public string CostId 
        {
            get => _obscured_costId;
            set => _obscured_costId = value ?? string.Empty;
        }
        [DataMember(Name = "costNum")][JsonProperty("costNum")]
        public int CostNum 
        {
            get => _obscured_costNum;
            set => _obscured_costNum = value;
        }
        [DataMember(Name = "drawCount")][JsonProperty("drawCount")]
        public int DrawCount 
        {
            get => _obscured_drawCount;
            set => _obscured_drawCount = value;
        }
        [DataMember(Name = "costPriority")][JsonProperty("costPriority")]
        public int CostPriority 
        {
            get => _obscured_costPriority;
            set => _obscured_costPriority = value;
        }


        ObscuredString _obscured_oprGachaId;
        ObscuredString _obscured_costId;
        ObscuredInt _obscured_costNum;
        ObscuredInt _obscured_drawCount;
        ObscuredInt _obscured_costPriority;
    }
}
