// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class OprInGameNoticeData
    {
        [DataMember(Name = "id")][JsonProperty("id")]
        public string Id 
        {
            get => _obscured_id;
            set => _obscured_id = value ?? string.Empty;
        }
        [DataMember(Name = "displayType")][JsonProperty("displayType")]
        public IgnDisplayType DisplayType { get; set; }
        [DataMember(Name = "destinationType")][JsonProperty("destinationType")]
        public string DestinationType 
        {
            get => _obscured_destinationType;
            set => _obscured_destinationType = value ?? string.Empty;
        }
        [DataMember(Name = "destinationPath")][JsonProperty("destinationPath")]
        public string DestinationPath 
        {
            get => _obscured_destinationPath;
            set => _obscured_destinationPath = value ?? string.Empty;
        }
        [DataMember(Name = "destinationPathDetail")][JsonProperty("destinationPathDetail")]
        public string DestinationPathDetail 
        {
            get => _obscured_destinationPathDetail;
            set => _obscured_destinationPathDetail = value ?? string.Empty;
        }
        [DataMember(Name = "priority")][JsonProperty("priority")]
        public int Priority 
        {
            get => _obscured_priority;
            set => _obscured_priority = value;
        }
        [DataMember(Name = "displayFrequencyType")][JsonProperty("displayFrequencyType")]
        public IgnDisplayFrequencyType DisplayFrequencyType { get; set; }
        [DataMember(Name = "title")][JsonProperty("title")]
        public string Title 
        {
            get => _obscured_title;
            set => _obscured_title = value ?? string.Empty;
        }
        [DataMember(Name = "description")][JsonProperty("description")]
        public string Description 
        {
            get => _obscured_description;
            set => _obscured_description = value ?? string.Empty;
        }
        [DataMember(Name = "bannerUrl")][JsonProperty("bannerUrl")]
        public string BannerUrl 
        {
            get => _obscured_bannerUrl;
            set => _obscured_bannerUrl = value ?? string.Empty;
        }
        [DataMember(Name = "buttonTitle")][JsonProperty("buttonTitle")]
        public string ButtonTitle 
        {
            get => _obscured_buttonTitle;
            set => _obscured_buttonTitle = value ?? string.Empty;
        }


        ObscuredString _obscured_id;
        ObscuredString _obscured_destinationType;
        ObscuredString _obscured_destinationPath;
        ObscuredString _obscured_destinationPathDetail;
        ObscuredInt _obscured_priority;
        ObscuredString _obscured_title;
        ObscuredString _obscured_description;
        ObscuredString _obscured_bannerUrl;
        ObscuredString _obscured_buttonTitle;
    }
}
