// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class OprStepupGachaStepData
    {
        [DataMember(Name = "id")][JsonProperty("id")]
        public string Id 
        {
            get => _obscured_id;
            set => _obscured_id = value ?? string.Empty;
        }
        [DataMember(Name = "oprGachaId")][JsonProperty("oprGachaId")]
        public string OprGachaId 
        {
            get => _obscured_oprGachaId;
            set => _obscured_oprGachaId = value ?? string.Empty;
        }
        [DataMember(Name = "stepNumber")][JsonProperty("stepNumber")]
        public int StepNumber 
        {
            get => _obscured_stepNumber;
            set => _obscured_stepNumber = value;
        }
        [DataMember(Name = "costType")][JsonProperty("costType")]
        public CostType CostType { get; set; }
        [DataMember(Name = "costId")][JsonProperty("costId")]
        public string? CostId 
        {
            get => _obscured_costId;
            set => _obscured_costId = value;
        }
        [DataMember(Name = "costNum")][JsonProperty("costNum")]
        public int CostNum 
        {
            get => _obscured_costNum;
            set => _obscured_costNum = value;
        }
        [DataMember(Name = "drawCount")][JsonProperty("drawCount")]
        public int DrawCount 
        {
            get => _obscured_drawCount;
            set => _obscured_drawCount = value;
        }
        [DataMember(Name = "fixedPrizeCount")][JsonProperty("fixedPrizeCount")]
        public int FixedPrizeCount 
        {
            get => _obscured_fixedPrizeCount;
            set => _obscured_fixedPrizeCount = value;
        }
        [DataMember(Name = "prizeGroupId")][JsonProperty("prizeGroupId")]
        public string? PrizeGroupId 
        {
            get => _obscured_prizeGroupId;
            set => _obscured_prizeGroupId = value;
        }
        [DataMember(Name = "fixedPrizeGroupId")][JsonProperty("fixedPrizeGroupId")]
        public string? FixedPrizeGroupId 
        {
            get => _obscured_fixedPrizeGroupId;
            set => _obscured_fixedPrizeGroupId = value;
        }
        [DataMember(Name = "isFirstFree")][JsonProperty("isFirstFree")]
        public bool IsFirstFree 
        {
            get => _obscured_isFirstFree;
            set => _obscured_isFirstFree = value;
        }


        ObscuredString _obscured_id;
        ObscuredString _obscured_oprGachaId;
        ObscuredInt _obscured_stepNumber;
        ObscuredString? _obscured_costId;
        ObscuredInt _obscured_costNum;
        ObscuredInt _obscured_drawCount;
        ObscuredInt _obscured_fixedPrizeCount;
        ObscuredString? _obscured_prizeGroupId;
        ObscuredString? _obscured_fixedPrizeGroupId;
        ObscuredBool _obscured_isFirstFree;
    }
}
