// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class OprStepupGachaStepRewardData
    {
        [DataMember(Name = "id")][JsonProperty("id")]
        public string Id 
        {
            get => _obscured_id;
            set => _obscured_id = value ?? string.Empty;
        }
        [DataMember(Name = "oprGachaId")][JsonProperty("oprGachaId")]
        public string OprGachaId 
        {
            get => _obscured_oprGachaId;
            set => _obscured_oprGachaId = value ?? string.Empty;
        }
        [DataMember(Name = "stepNumber")][JsonProperty("stepNumber")]
        public int StepNumber 
        {
            get => _obscured_stepNumber;
            set => _obscured_stepNumber = value;
        }
        [DataMember(Name = "loopCountTarget")][JsonProperty("loopCountTarget")]
        public int? LoopCountTarget 
        {
            get => _obscured_loopCountTarget;
            set => _obscured_loopCountTarget = value;
        }
        [DataMember(Name = "resourceType")][JsonProperty("resourceType")]
        public ResourceType ResourceType { get; set; }
        [DataMember(Name = "resourceId")][JsonProperty("resourceId")]
        public string? ResourceId 
        {
            get => _obscured_resourceId;
            set => _obscured_resourceId = value;
        }
        [DataMember(Name = "resourceAmount")][JsonProperty("resourceAmount")]
        public int ResourceAmount 
        {
            get => _obscured_resourceAmount;
            set => _obscured_resourceAmount = value;
        }


        ObscuredString _obscured_id;
        ObscuredString _obscured_oprGachaId;
        ObscuredInt _obscured_stepNumber;
        ObscuredInt? _obscured_loopCountTarget;
        ObscuredString? _obscured_resourceId;
        ObscuredInt _obscured_resourceAmount;
    }
}
