// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class PvpEndResultBonusPointData
    {
        [DataMember(Name = "resultPoint")][JsonProperty("resultPoint")]
        public int ResultPoint 
        {
            get => _obscured_resultPoint;
            set => _obscured_resultPoint = value;
        }
        [DataMember(Name = "opponentBonusPoint")][JsonProperty("opponentBonusPoint")]
        public int OpponentBonusPoint 
        {
            get => _obscured_opponentBonusPoint;
            set => _obscured_opponentBonusPoint = value;
        }
        [DataMember(Name = "timeBonusPoint")][JsonProperty("timeBonusPoint")]
        public int TimeBonusPoint 
        {
            get => _obscured_timeBonusPoint;
            set => _obscured_timeBonusPoint = value;
        }


        ObscuredInt _obscured_resultPoint;
        ObscuredInt _obscured_opponentBonusPoint;
        ObscuredInt _obscured_timeBonusPoint;
    }
}
