// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class PvpMyRankingData
    {
        [DataMember(Name = "rank")][JsonProperty("rank")]
        public int Rank 
        {
            get => _obscured_rank;
            set => _obscured_rank = value;
        }
        [DataMember(Name = "score")][JsonProperty("score")]
        public int Score 
        {
            get => _obscured_score;
            set => _obscured_score = value;
        }
        [DataMember(Name = "isExcludeRanking")][JsonProperty("isExcludeRanking")]
        public bool IsExcludeRanking 
        {
            get => _obscured_isExcludeRanking;
            set => _obscured_isExcludeRanking = value;
        }


        ObscuredInt _obscured_rank;
        ObscuredInt _obscured_score;
        ObscuredBool _obscured_isExcludeRanking;
    }
}
