// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class UserLevelUpData
    {
        [DataMember(Name = "beforeExp")][JsonProperty("beforeExp")]
        public int BeforeExp 
        {
            get => _obscured_beforeExp;
            set => _obscured_beforeExp = value;
        }
        [DataMember(Name = "afterExp")][JsonProperty("afterExp")]
        public int AfterExp 
        {
            get => _obscured_afterExp;
            set => _obscured_afterExp = value;
        }
        [DataMember(Name = "usrLevelReward")][JsonProperty("usrLevelReward")]
        public UsrLevelRewardData[] UsrLevelReward { get; set; }
        [DataMember(Name = "isEmblemDuplicated")][JsonProperty("isEmblemDuplicated")]
        public bool IsEmblemDuplicated 
        {
            get => _obscured_isEmblemDuplicated;
            set => _obscured_isEmblemDuplicated = value;
        }


        ObscuredInt _obscured_beforeExp;
        ObscuredInt _obscured_afterExp;
        ObscuredBool _obscured_isEmblemDuplicated;
    }
}
