// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class UserLinkBnidConfirmResultData
    {
        [DataMember(Name = "name")][JsonProperty("name")]
        public string Name 
        {
            get => _obscured_name;
            set => _obscured_name = value ?? string.Empty;
        }
        [DataMember(Name = "level")][JsonProperty("level")]
        public int? Level 
        {
            get => _obscured_level;
            set => _obscured_level = value;
        }
        [DataMember(Name = "myId")][JsonProperty("myId")]
        public string MyId 
        {
            get => _obscured_myId;
            set => _obscured_myId = value ?? string.Empty;
        }


        ObscuredString _obscured_name;
        ObscuredInt? _obscured_level;
        ObscuredString _obscured_myId;
    }
}
