// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class UsrArtworkPartyData
    {
        [DataMember(Name = "mstArtworkId1")][JsonProperty("mstArtworkId1")]
        public string MstArtworkId1 
        {
            get => _obscured_mstArtworkId1;
            set => _obscured_mstArtworkId1 = value ?? string.Empty;
        }
        [DataMember(Name = "mstArtworkId2")][JsonProperty("mstArtworkId2")]
        public string MstArtworkId2 
        {
            get => _obscured_mstArtworkId2;
            set => _obscured_mstArtworkId2 = value ?? string.Empty;
        }
        [DataMember(Name = "mstArtworkId3")][JsonProperty("mstArtworkId3")]
        public string MstArtworkId3 
        {
            get => _obscured_mstArtworkId3;
            set => _obscured_mstArtworkId3 = value ?? string.Empty;
        }
        [DataMember(Name = "mstArtworkId4")][JsonProperty("mstArtworkId4")]
        public string MstArtworkId4 
        {
            get => _obscured_mstArtworkId4;
            set => _obscured_mstArtworkId4 = value ?? string.Empty;
        }
        [DataMember(Name = "mstArtworkId5")][JsonProperty("mstArtworkId5")]
        public string MstArtworkId5 
        {
            get => _obscured_mstArtworkId5;
            set => _obscured_mstArtworkId5 = value ?? string.Empty;
        }
        [DataMember(Name = "mstArtworkId6")][JsonProperty("mstArtworkId6")]
        public string MstArtworkId6 
        {
            get => _obscured_mstArtworkId6;
            set => _obscured_mstArtworkId6 = value ?? string.Empty;
        }
        [DataMember(Name = "mstArtworkId7")][JsonProperty("mstArtworkId7")]
        public string MstArtworkId7 
        {
            get => _obscured_mstArtworkId7;
            set => _obscured_mstArtworkId7 = value ?? string.Empty;
        }
        [DataMember(Name = "mstArtworkId8")][JsonProperty("mstArtworkId8")]
        public string MstArtworkId8 
        {
            get => _obscured_mstArtworkId8;
            set => _obscured_mstArtworkId8 = value ?? string.Empty;
        }
        [DataMember(Name = "mstArtworkId9")][JsonProperty("mstArtworkId9")]
        public string MstArtworkId9 
        {
            get => _obscured_mstArtworkId9;
            set => _obscured_mstArtworkId9 = value ?? string.Empty;
        }
        [DataMember(Name = "mstArtworkId10")][JsonProperty("mstArtworkId10")]
        public string MstArtworkId10 
        {
            get => _obscured_mstArtworkId10;
            set => _obscured_mstArtworkId10 = value ?? string.Empty;
        }


        ObscuredString _obscured_mstArtworkId1;
        ObscuredString _obscured_mstArtworkId2;
        ObscuredString _obscured_mstArtworkId3;
        ObscuredString _obscured_mstArtworkId4;
        ObscuredString _obscured_mstArtworkId5;
        ObscuredString _obscured_mstArtworkId6;
        ObscuredString _obscured_mstArtworkId7;
        ObscuredString _obscured_mstArtworkId8;
        ObscuredString _obscured_mstArtworkId9;
        ObscuredString _obscured_mstArtworkId10;
    }
}
