// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class UsrArtworkData
    {
        [DataMember(Name = "mstArtworkId")][JsonProperty("mstArtworkId")]
        public string MstArtworkId 
        {
            get => _obscured_mstArtworkId;
            set => _obscured_mstArtworkId = value ?? string.Empty;
        }
        [DataMember(Name = "isNewEncyclopedia")][JsonProperty("isNewEncyclopedia")]
        public bool IsNewEncyclopedia 
        {
            get => _obscured_isNewEncyclopedia;
            set => _obscured_isNewEncyclopedia = value;
        }


        ObscuredString _obscured_mstArtworkId;
        ObscuredBool _obscured_isNewEncyclopedia;
    }
}
