// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class UsrBoxGachaData
    {
        [DataMember(Name = "mstBoxGachaId")][JsonProperty("mstBoxGachaId")]
        public string MstBoxGachaId 
        {
            get => _obscured_mstBoxGachaId;
            set => _obscured_mstBoxGachaId = value ?? string.Empty;
        }
        [DataMember(Name = "resetCount")][JsonProperty("resetCount")]
        public int ResetCount 
        {
            get => _obscured_resetCount;
            set => _obscured_resetCount = value;
        }
        [DataMember(Name = "totalDrawCount")][JsonProperty("totalDrawCount")]
        public int TotalDrawCount 
        {
            get => _obscured_totalDrawCount;
            set => _obscured_totalDrawCount = value;
        }
        [DataMember(Name = "currentBoxLevel")][JsonProperty("currentBoxLevel")]
        public int CurrentBoxLevel 
        {
            get => _obscured_currentBoxLevel;
            set => _obscured_currentBoxLevel = value;
        }
        [DataMember(Name = "drawPrizes")][JsonProperty("drawPrizes")]
        public UsrBoxGachaPrizeData[] DrawPrizes { get; set; }


        ObscuredString _obscured_mstBoxGachaId;
        ObscuredInt _obscured_resetCount;
        ObscuredInt _obscured_totalDrawCount;
        ObscuredInt _obscured_currentBoxLevel;
    }
}
