// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class UsrInGameStatusData
    {
        [DataMember(Name = "isStartedSession")][JsonProperty("isStartedSession")]
        public bool IsStartedSession 
        {
            get => _obscured_isStartedSession;
            set => _obscured_isStartedSession = value;
        }
        [DataMember(Name = "inGameContentType")][JsonProperty("inGameContentType")]
        public InGameContentType? InGameContentType { get; set; }
        [DataMember(Name = "targetMstId")][JsonProperty("targetMstId")]
        public string TargetMstId 
        {
            get => _obscured_targetMstId;
            set => _obscured_targetMstId = value ?? string.Empty;
        }
        [DataMember(Name = "partyNo")][JsonProperty("partyNo")]
        public int PartyNo 
        {
            get => _obscured_partyNo;
            set => _obscured_partyNo = value;
        }
        [DataMember(Name = "continueCount")][JsonProperty("continueCount")]
        public int ContinueCount 
        {
            get => _obscured_continueCount;
            set => _obscured_continueCount = value;
        }
        [DataMember(Name = "continueAdCount")][JsonProperty("continueAdCount")]
        public int ContinueAdCount 
        {
            get => _obscured_continueAdCount;
            set => _obscured_continueAdCount = value;
        }


        ObscuredBool _obscured_isStartedSession;
        ObscuredString _obscured_targetMstId;
        ObscuredInt _obscured_partyNo;
        ObscuredInt _obscured_continueCount;
        ObscuredInt _obscured_continueAdCount;
    }
}
