// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class UsrIdleIncentiveData
    {
        [DataMember(Name = "idleStartedAt")][JsonProperty("idleStartedAt")]
        public DateTimeOffset IdleStartedAt { get; set; }
        [DataMember(Name = "diamondQuickReceiveCount")][JsonProperty("diamondQuickReceiveCount")]
        public int DiamondQuickReceiveCount 
        {
            get => _obscured_diamondQuickReceiveCount;
            set => _obscured_diamondQuickReceiveCount = value;
        }
        [DataMember(Name = "adQuickReceiveCount")][JsonProperty("adQuickReceiveCount")]
        public int AdQuickReceiveCount 
        {
            get => _obscured_adQuickReceiveCount;
            set => _obscured_adQuickReceiveCount = value;
        }
        [DataMember(Name = "diamondQuickReceiveAt")][JsonProperty("diamondQuickReceiveAt")]
        public DateTimeOffset DiamondQuickReceiveAt { get; set; }
        [DataMember(Name = "adQuickReceiveAt")][JsonProperty("adQuickReceiveAt")]
        public DateTimeOffset AdQuickReceiveAt { get; set; }


        ObscuredInt _obscured_diamondQuickReceiveCount;
        ObscuredInt _obscured_adQuickReceiveCount;
    }
}
