// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class UsrMissionEventDailyBonusProgressData
    {
        [DataMember(Name = "mstMissionEventDailyBonusScheduleId")][JsonProperty("mstMissionEventDailyBonusScheduleId")]
        public string MstMissionEventDailyBonusScheduleId 
        {
            get => _obscured_mstMissionEventDailyBonusScheduleId;
            set => _obscured_mstMissionEventDailyBonusScheduleId = value ?? string.Empty;
        }
        [DataMember(Name = "progress")][JsonProperty("progress")]
        public int Progress 
        {
            get => _obscured_progress;
            set => _obscured_progress = value;
        }


        ObscuredString _obscured_mstMissionEventDailyBonusScheduleId;
        ObscuredInt _obscured_progress;
    }
}
