// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class UsrMissionBeginnerData
    {
        [DataMember(Name = "mstMissionBeginnerId")][JsonProperty("mstMissionBeginnerId")]
        public string MstMissionBeginnerId 
        {
            get => _obscured_mstMissionBeginnerId;
            set => _obscured_mstMissionBeginnerId = value ?? string.Empty;
        }
        [DataMember(Name = "progress")][JsonProperty("progress")]
        public int Progress 
        {
            get => _obscured_progress;
            set => _obscured_progress = value;
        }
        [DataMember(Name = "isCleared")][JsonProperty("isCleared")]
        public bool IsCleared 
        {
            get => _obscured_isCleared;
            set => _obscured_isCleared = value;
        }
        [DataMember(Name = "isReceivedReward")][JsonProperty("isReceivedReward")]
        public bool IsReceivedReward 
        {
            get => _obscured_isReceivedReward;
            set => _obscured_isReceivedReward = value;
        }


        ObscuredString _obscured_mstMissionBeginnerId;
        ObscuredInt _obscured_progress;
        ObscuredBool _obscured_isCleared;
        ObscuredBool _obscured_isReceivedReward;
    }
}
