// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class UsrMissionBonusPointData
    {
        [DataMember(Name = "missionType")][JsonProperty("missionType")]
        public MissionType MissionType { get; set; }
        [DataMember(Name = "point")][JsonProperty("point")]
        public int Point 
        {
            get => _obscured_point;
            set => _obscured_point = value;
        }
        [DataMember(Name = "receivedRewardPoints")][JsonProperty("receivedRewardPoints")]
        public int[] ReceivedRewardPoints { get; set; }


        ObscuredInt _obscured_point;
    }
}
