// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class UsrPartyData
    {
        [DataMember(Name = "partyNo")][JsonProperty("partyNo")]
        public int PartyNo 
        {
            get => _obscured_partyNo;
            set => _obscured_partyNo = value;
        }
        [DataMember(Name = "partyName")][JsonProperty("partyName")]
        public string PartyName 
        {
            get => _obscured_partyName;
            set => _obscured_partyName = value ?? string.Empty;
        }
        [DataMember(Name = "usrUnitId1")][JsonProperty("usrUnitId1")]
        public string UsrUnitId1 
        {
            get => _obscured_usrUnitId1;
            set => _obscured_usrUnitId1 = value ?? string.Empty;
        }
        [DataMember(Name = "usrUnitId2")][JsonProperty("usrUnitId2")]
        public string UsrUnitId2 
        {
            get => _obscured_usrUnitId2;
            set => _obscured_usrUnitId2 = value ?? string.Empty;
        }
        [DataMember(Name = "usrUnitId3")][JsonProperty("usrUnitId3")]
        public string UsrUnitId3 
        {
            get => _obscured_usrUnitId3;
            set => _obscured_usrUnitId3 = value ?? string.Empty;
        }
        [DataMember(Name = "usrUnitId4")][JsonProperty("usrUnitId4")]
        public string UsrUnitId4 
        {
            get => _obscured_usrUnitId4;
            set => _obscured_usrUnitId4 = value ?? string.Empty;
        }
        [DataMember(Name = "usrUnitId5")][JsonProperty("usrUnitId5")]
        public string UsrUnitId5 
        {
            get => _obscured_usrUnitId5;
            set => _obscured_usrUnitId5 = value ?? string.Empty;
        }
        [DataMember(Name = "usrUnitId6")][JsonProperty("usrUnitId6")]
        public string UsrUnitId6 
        {
            get => _obscured_usrUnitId6;
            set => _obscured_usrUnitId6 = value ?? string.Empty;
        }
        [DataMember(Name = "usrUnitId7")][JsonProperty("usrUnitId7")]
        public string UsrUnitId7 
        {
            get => _obscured_usrUnitId7;
            set => _obscured_usrUnitId7 = value ?? string.Empty;
        }
        [DataMember(Name = "usrUnitId8")][JsonProperty("usrUnitId8")]
        public string UsrUnitId8 
        {
            get => _obscured_usrUnitId8;
            set => _obscured_usrUnitId8 = value ?? string.Empty;
        }
        [DataMember(Name = "usrUnitId9")][JsonProperty("usrUnitId9")]
        public string UsrUnitId9 
        {
            get => _obscured_usrUnitId9;
            set => _obscured_usrUnitId9 = value ?? string.Empty;
        }
        [DataMember(Name = "usrUnitId10")][JsonProperty("usrUnitId10")]
        public string UsrUnitId10 
        {
            get => _obscured_usrUnitId10;
            set => _obscured_usrUnitId10 = value ?? string.Empty;
        }


        ObscuredInt _obscured_partyNo;
        ObscuredString _obscured_partyName;
        ObscuredString _obscured_usrUnitId1;
        ObscuredString _obscured_usrUnitId2;
        ObscuredString _obscured_usrUnitId3;
        ObscuredString _obscured_usrUnitId4;
        ObscuredString _obscured_usrUnitId5;
        ObscuredString _obscured_usrUnitId6;
        ObscuredString _obscured_usrUnitId7;
        ObscuredString _obscured_usrUnitId8;
        ObscuredString _obscured_usrUnitId9;
        ObscuredString _obscured_usrUnitId10;
    }
}
