// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class UsrStageEventData
    {
        [DataMember(Name = "mstStageId")][JsonProperty("mstStageId")]
        public string MstStageId 
        {
            get => _obscured_mstStageId;
            set => _obscured_mstStageId = value ?? string.Empty;
        }
        [DataMember(Name = "resetClearCount")][JsonProperty("resetClearCount")]
        public int ResetClearCount 
        {
            get => _obscured_resetClearCount;
            set => _obscured_resetClearCount = value;
        }
        [DataMember(Name = "resetAdChallengeCount")][JsonProperty("resetAdChallengeCount")]
        public int ResetAdChallengeCount 
        {
            get => _obscured_resetAdChallengeCount;
            set => _obscured_resetAdChallengeCount = value;
        }
        [DataMember(Name = "latestResetAt")][JsonProperty("latestResetAt")]
        public DateTimeOffset? LatestResetAt { get; set; }
        [DataMember(Name = "totalClearCount")][JsonProperty("totalClearCount")]
        public int TotalClearCount 
        {
            get => _obscured_totalClearCount;
            set => _obscured_totalClearCount = value;
        }
        [DataMember(Name = "lastChallengedAt")][JsonProperty("lastChallengedAt")]
        public DateTimeOffset? LastChallengedAt { get; set; }
        [DataMember(Name = "clearTimeMs")][JsonProperty("clearTimeMs")]
        public int? ClearTimeMs 
        {
            get => _obscured_clearTimeMs;
            set => _obscured_clearTimeMs = value;
        }
        [DataMember(Name = "resetClearTimeMs")][JsonProperty("resetClearTimeMs")]
        public int? ResetClearTimeMs 
        {
            get => _obscured_resetClearTimeMs;
            set => _obscured_resetClearTimeMs = value;
        }
        [DataMember(Name = "latestEventSettingEndAt")][JsonProperty("latestEventSettingEndAt")]
        public DateTimeOffset? LatestEventSettingEndAt { get; set; }


        ObscuredString _obscured_mstStageId;
        ObscuredInt _obscured_resetClearCount;
        ObscuredInt _obscured_resetAdChallengeCount;
        ObscuredInt _obscured_totalClearCount;
        ObscuredInt? _obscured_clearTimeMs;
        ObscuredInt? _obscured_resetClearTimeMs;
    }
}
