// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class UsrStoreProductData
    {
        [DataMember(Name = "productSubId")][JsonProperty("productSubId")]
        public string ProductSubId 
        {
            get => _obscured_productSubId;
            set => _obscured_productSubId = value ?? string.Empty;
        }
        [DataMember(Name = "purchaseCount")][JsonProperty("purchaseCount")]
        public int PurchaseCount 
        {
            get => _obscured_purchaseCount;
            set => _obscured_purchaseCount = value;
        }
        [DataMember(Name = "purchaseTotalCount")][JsonProperty("purchaseTotalCount")]
        public int PurchaseTotalCount 
        {
            get => _obscured_purchaseTotalCount;
            set => _obscured_purchaseTotalCount = value;
        }


        ObscuredString _obscured_productSubId;
        ObscuredInt _obscured_purchaseCount;
        ObscuredInt _obscured_purchaseTotalCount;
    }
}
