// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class UsrStageEnhanceData
    {
        [DataMember(Name = "mstStageId")][JsonProperty("mstStageId")]
        public string MstStageId 
        {
            get => _obscured_mstStageId;
            set => _obscured_mstStageId = value ?? string.Empty;
        }
        [DataMember(Name = "resetChallengeCount")][JsonProperty("resetChallengeCount")]
        public int ResetChallengeCount 
        {
            get => _obscured_resetChallengeCount;
            set => _obscured_resetChallengeCount = value;
        }
        [DataMember(Name = "resetAdChallengeCount")][JsonProperty("resetAdChallengeCount")]
        public int ResetAdChallengeCount 
        {
            get => _obscured_resetAdChallengeCount;
            set => _obscured_resetAdChallengeCount = value;
        }
        [DataMember(Name = "maxScore")][JsonProperty("maxScore")]
        public long MaxScore 
        {
            get => _obscured_maxScore;
            set => _obscured_maxScore = value;
        }


        ObscuredString _obscured_mstStageId;
        ObscuredInt _obscured_resetChallengeCount;
        ObscuredInt _obscured_resetAdChallengeCount;
        ObscuredLong _obscured_maxScore;
    }
}
