// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class UsrShopPassData
    {
        [DataMember(Name = "mstShopPassId")][JsonProperty("mstShopPassId")]
        public string MstShopPassId 
        {
            get => _obscured_mstShopPassId;
            set => _obscured_mstShopPassId = value ?? string.Empty;
        }
        [DataMember(Name = "dailyRewardReceivedCount")][JsonProperty("dailyRewardReceivedCount")]
        public int DailyRewardReceivedCount 
        {
            get => _obscured_dailyRewardReceivedCount;
            set => _obscured_dailyRewardReceivedCount = value;
        }
        [DataMember(Name = "dailyLatestReceivedAt")][JsonProperty("dailyLatestReceivedAt")]
        public DateTimeOffset DailyLatestReceivedAt { get; set; }
        [DataMember(Name = "startAt")][JsonProperty("startAt")]
        public DateTimeOffset StartAt { get; set; }
        [DataMember(Name = "endAt")][JsonProperty("endAt")]
        public DateTimeOffset EndAt { get; set; }


        ObscuredString _obscured_mstShopPassId;
        ObscuredInt _obscured_dailyRewardReceivedCount;
    }
}
