// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class UsrStoreInfoData
    {
        [DataMember(Name = "age")][JsonProperty("age")]
        public int? Age 
        {
            get => _obscured_age;
            set => _obscured_age = value;
        }
        [DataMember(Name = "currentMonthTotalBilling")][JsonProperty("currentMonthTotalBilling")]
        public int CurrentMonthTotalBilling 
        {
            get => _obscured_currentMonthTotalBilling;
            set => _obscured_currentMonthTotalBilling = value;
        }
        [DataMember(Name = "renotifyAt")][JsonProperty("renotifyAt")]
        public DateTimeOffset? RenotifyAt { get; set; }


        ObscuredInt? _obscured_age;
        ObscuredInt _obscured_currentMonthTotalBilling;
    }
}
