// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
#pragma warning disable CS8632 // nullable reference types should only be used in code within a '#nullable' annotations context.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using UnityEngine;
using WondlerPlanet.CheatProtectKit.ObscuredTypes;
using GLOW.Core.Domain.Constants;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Data.Data
{
    [Serializable]
    public class UsrTradePackData
    {
        [DataMember(Name = "mstPackId")][JsonProperty("mstPackId")]
        public string MstPackId 
        {
            get => _obscured_mstPackId;
            set => _obscured_mstPackId = value ?? string.Empty;
        }
        [DataMember(Name = "dailyTradeCount")][JsonProperty("dailyTradeCount")]
        public int DailyTradeCount 
        {
            get => _obscured_dailyTradeCount;
            set => _obscured_dailyTradeCount = value;
        }


        ObscuredString _obscured_mstPackId;
        ObscuredInt _obscured_dailyTradeCount;
    }
}
