<?php

use App\Domain\Constants\Database;
use App\Traits\MigrationAddColumnCommentsTrait;
use App\Traits\MigrationAddTableCommentTrait;
use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    use MigrationAddTableCommentTrait;
    use MigrationAddColumnCommentsTrait;

    protected $connection = Database::MST_CONNECTION;

    private array $tableCommentList = [
        'mst_abilities' => 'ユニット特性・コマ効果の設定',
        'mst_abilities_i18n' => 'ユニット特性・コマ効果の多言語設定',
        'mst_advent_battle_clear_rewards' => '降臨バトルのクリア報酬設定',
        'mst_advent_battle_ranks' => '降臨バトルのランク設定',
        'mst_advent_battle_reward_groups' => '降臨バトルの報酬情報をグルーピング',
        'mst_advent_battle_rewards' => '降臨バトルの報酬設定',
        'mst_advent_battles' => '降臨バトルの基本設定',
        'mst_advent_battles_i18n' => '降臨バトルの基本設定の多言語設定',
        'mst_api_actions' => 'API動作設定',
        'mst_attack_elements' => 'インゲーム向けユニットの攻撃データ',
        'mst_attack_hit_effects' => 'ユニットの攻撃ヒット演出設定',
        'mst_attacks' => 'ユニットの攻撃データ',
        'mst_attacks_i18n' => 'ユニットの攻撃データの多言語設定',
        'mst_auto_player_sequences' => 'インゲーム内敵出現ルール',
        'mst_battle_point_levels' => 'インゲームで使用するバトルポイントについての設定(初期ポイント、ポイントが貯まる速度、最大ポイント etc) (現在未使用)',
        'mst_cheat_settings' => 'インゲームコンテンツごとに検出すべきチート手法と閾値を設定',
        'mst_comeback_bonus_schedules' => 'カムバックボーナスのスケジュール設定(現在未対応、対応予定あり)',
        'mst_comeback_bonuses' => 'カムバックボーナスの設定(現在未対応、対応予定あり)',
        'mst_configs' => '定数設定',
        'mst_daily_bonus_rewards' => 'ログインボーナスの設定用テーブル(ただ、現在は通常ログインボーナスもイベントログインボーナスもmst_mission_rewardsで設定されている)(現在は未使用)',
        'mst_defense_targets' => 'インゲーム向け防衛オブジェクトの設定',
        'mst_emblems' => 'エンブレム設定',
        'mst_emblems_i18n' => 'エンブレム設定の多言語設定',
        'mst_enemy_characters' => '敵ユニットの設定',
        'mst_enemy_characters_i18n' => '敵ユニットの設定の多言語設定',
        'mst_enemy_outposts' => '敵タワーの設定',
        'mst_enemy_stage_parameters' => 'インゲーム向け敵ユニットの設定',
        'mst_event_bonus_units' => 'キャラごとのイベントボーナス設定',
        'mst_event_display_rewards' => '(現在未使用)旧イベントクエスト画面で出す目玉報酬の設定',
        'mst_event_display_units' => 'イベントTOP画面で表示するユニットデータ',
        'mst_event_display_units_i18n' => 'イベントTOP画面で表示するユニットデータの多言語設定',
        'mst_events' => 'イベント設定',
        'mst_events_i18n' => 'イベント設定の多言語設定',
        'mst_fragment_box_groups' => 'かけらボックスアイテムの交換先アイテム設定',
        'mst_fragment_boxes' => 'かけらボックスアイテム設定',
        'mst_home_banners' => 'ホームのバナー設定',
        'mst_idle_incentive_items' => '探索報酬として配布したいアイテムをまとめて複数設定できるテーブル',
        'mst_idle_incentive_rewards' => '探索報酬の基本設定',
        'mst_idle_incentives' => '探索の基本設定',
        'mst_in_game_gimmick_objects' => '各種インゲームコンテンツの特別ルール設定',
        'mst_in_game_special_rules' => 'アイテムのレアリティ別交換レート設定',
        'mst_in_games' => 'インゲームの設定',
        'mst_in_games_i18n' => 'インゲームの設定の多言語設定',
        'mst_item_rarity_trades' => 'キャラのかけらをかけらBOXに交換する際の設定(交換可能個数、レート、交換可能回数上限、交換可能回数リセット設定)',
        'mst_item_transitions' => 'アイテム詳細からの遷移先の設定',
        'mst_items' => 'アイテム設定',
        'mst_items_i18n' => 'アイテム設定の多言語設定',
        'mst_koma_lines' => 'インゲーム内のコマ設定',
        'mst_manga_animations' => 'ステージ原画演出設定',
        'mst_mission_achievement_dependencies' => 'アチーブメントミッション同士のつながりの設定。あるミッションの開放条件として他ミッション達成を設定したい場合に設定する。',
        'mst_mission_achievements' => 'アチーブメントミッションの設定',
        'mst_mission_achievements_i18n' => 'アチーブメントミッションの設定の多言語設定',
        'mst_mission_beginner_prompt_phrases_i18n' => '初心者ミッションのUIの煽り文言の設定',
        'mst_mission_beginners' => '初心者ミッションの設定',
        'mst_mission_beginners_i18n' => '初心者ミッションの設定の多言語設定',
        'mst_mission_dailies' => 'デイリーミッションの設定',
        'mst_mission_dailies_i18n' => 'デイリーミッションの設定の多言語設定',
        'mst_mission_daily_bonuses' => 'デイリーボーナス(ログボ)の設定',
        'mst_mission_event_dailies' => 'イベントデイリーミッションの設定',
        'mst_mission_event_dailies_i18n' => 'イベントデイリーミッションの設定の多言語設定',
        'mst_mission_event_daily_bonus_schedules' => 'イベントデイリーボーナス(イベントログボ)のスケジュール設定',
        'mst_mission_event_daily_bonuses' => 'イベントデイリーボーナス(イベントログボ)の設定',
        'mst_mission_event_dependencies' => 'イベントミッション同士のつながりの設定。あるミッションの開放条件として他ミッション達成を設定したい場合に設定する。',
        'mst_mission_events' => 'イベントミッションの設定',
        'mst_mission_events_i18n' => 'イベントミッションの設定の多言語設定',
        'mst_mission_limited_term_dependencies' => '期間限定ミッション同士のつながりの設定。あるミッションの開放条件として他ミッション達成を設定したい場合に設定する。',
        'mst_mission_limited_terms' => '期間限定ミッションの設定',
        'mst_mission_limited_terms_i18n' => '期間限定ミッションの設定の多言語設定',
        'mst_mission_rewards' => 'ミッション報酬設定',
        'mst_mission_weeklies' => 'ウィークリーミッションの設定',
        'mst_mission_weeklies_i18n' => 'ウィークリーミッションの設定の多言語設定',
        'mst_ng_words' => 'ユーザー名やユニット名でのNGワードリスト設定',
        'mst_outpost_enhancement_levels' => 'ゲート強化項目ごとのレベル設定',
        'mst_outpost_enhancement_levels_i18n' => 'ゲート強化項目ごとのレベル設定の多言語設定',
        'mst_outpost_enhancements' => 'ゲート強化項目の設定',
        'mst_outpost_enhancements_i18n' => 'ゲート強化項目の設定の多言語設定',
        'mst_outposts' => 'ゲートの基本設定',
        'mst_pack_contents' => 'ショップのパックの内容物の設定',
        'mst_packs' => 'ショップのパック設定',
        'mst_packs_i18n' => 'ショップのパック設定の多言語設定',
        'mst_pages' => 'インゲーム内のステージ設定',
        'mst_party_unit_counts' => 'メインクエストの進捗に応じたパーティ編成可能なキャラ数の設定',
        'mst_quest_bonus_units' => 'キャラごとのコインクエストボーナス設定',
        'mst_quest_event_bonus_schedules' => 'クエストごとのイベントボーナス設定',
        'mst_quests' => 'クエスト設定',
        'mst_quests_i18n' => 'クエスト名などの多言語設定',
        'mst_release_keys' => 'リリースキー設定',
        'mst_result_tips_i18n' => '敗北時の汎用Tipsテキストの多言語設定',
        'mst_series' => 'ジャンプ+の漫画作品をGLOW内で識別するための情報の設定',
        'mst_shop_pass_effects' => 'ショップパスの効果設定',
        'mst_shop_pass_rewards' => 'ショップパスの報酬設定',
        'mst_shop_passes' => 'ショップパスの基本設定',
        'mst_shop_passes_i18n' => 'ショップパスの基本設定の多言語設定',
        'mst_special_attacks_i18n' => '必殺ワザの名前設定',
        'mst_special_role_level_up_attack_elements' => 'スペシャルキャラのレベルアップに応じて',
        'mst_speech_balloons_i18n' => 'ユニット吹き出しテキストの多言語設定',
        'mst_stage_clear_time_rewards' => 'ステージごとのクリアタイムに応じた報酬設定',
        'mst_stage_end_conditions' => 'インゲームにて、特殊な勝利・敗北などのバトル終了条件を設定したい時に',
        'mst_stage_enhance_reward_params' => '強化クエストステージクリア時の報酬量算出に使う係数設定',
        'mst_stage_event_rewards' => 'イベントクエストステージのクリア報酬設定',
        'mst_stage_event_settings' => 'ステージの基本設定にはないイベントクエスト用の追加設定',
        'mst_stage_rewards' => 'ステージ報酬設定',
        'mst_stage_tips' => 'ステージで表示するtips設定',
        'mst_stages' => 'ステージの基本設定',
        'mst_stages_i18n' => 'ステージの基本設定の多言語設定',
        'mst_tutorial_tips_i18n' => 'チュートリアルダイアログで表示するtips画像パスの設定',
        'mst_tutorials' => 'チュートリアルの項目と開始条件の設定',
        'mst_unit_abilities' => 'ユニット特性の設定',
        'mst_unit_encyclopedia_effects' => 'キャラ図鑑報酬のインゲーム効果設定',
        'mst_unit_fragment_converts' => 'キャラ重複獲得時のキャラのかけらへの変換レートの設定',
        'mst_unit_grade_coefficients' => 'キャラのグレードアップ後のステータス係数の設定',
        'mst_unit_grade_ups' => 'キャラのグレードアップ設定',
        'mst_unit_level_ups' => 'キャラのレベルアップ設定',
        'mst_unit_rank_coefficients' => 'キャラのランクアップ後のステータス係数の設定',
        'mst_unit_rank_ups' => 'キャラのランクアップ設定',
        'mst_unit_role_bonuses' => 'インゲームでのロールごとの属性有利時の攻撃と防御にかけるボーナス係数の設定',
        'mst_units' => 'キャラ設定',
        'mst_units_i18n' => 'キャラ設定の多言語設定',
        'mst_user_level_bonus_groups' => 'ユーザーレベル報酬のグルーピング設定',
        'mst_user_level_bonuses' => 'ユーザーレベルごとの報酬設定',
        'mst_user_levels' => 'ユーザーレベル設定',
    ];

    private array $columnCommentList = [
        'mst_abilities' => [
            'id' => 'UUID',
            'ability_type' => 'アビリティタイプ',
            'release_key' => 'リリースキー',
            'asset_key' => 'アセットキー',
        ],
        'mst_abilities_i18n' => [
            'id' => 'UUID',
            'mst_ability_id' => 'リレーション向けMstAbilityId',
            'language' => '言語設定',
            'description' => '説明文',
            'filter_title' => 'ユニットソートフィルタータイトル',
            'release_key' => 'リリースキー',
        ],
        'mst_advent_battle_clear_rewards' => [
            'id' => 'UUID',
            'resource_id' => '報酬のID(アイテムだったらアイテムのID、コインやプリズムなら空)',
            'resource_amount' => '配布される報酬の量',
            'release_key' => 'リリースキー',
        ],
        'mst_advent_battle_ranks' => [
            'id' => 'UUID',
            'asset_key' => 'アセットキー',
            'release_key' => 'リリースキー',
        ],
        'mst_advent_battle_reward_groups' => [
            'id' => 'UUID',
            'reward_category' => '報酬カテゴリー',
            'release_key' => 'リリースキー',
        ],
        'mst_advent_battle_rewards' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_advent_battles' => [
            'id' => 'UUID',
            'mst_event_id' => 'mst_events.id',
            'mst_in_game_id' => 'mst_in_games.id',
            'asset_key' => 'アセットキー',
            'initial_battle_point' => 'インゲーム開始時のリーダーP',
            'release_key' => 'リリースキー',
            'score_addition_type' => '降臨バトルスコア加算タイプ(スコアチャレンジ、レイド)',
            'score_additional_coef' => '降臨バトルスコア加算係数',

        ],
        'mst_advent_battles_i18n' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
            'boss_description' => '降臨バトルボス説明文',
        ],
        'mst_api_actions' => [
            'id' => 'UUID',
            'api_path' => 'APIパス',
            'release_key' => 'リリースキー',
            'resource' => 'API追加情報',
            'created_at' => '作成日時のタイムスタンプ',
            'updated_at' => '更新日時のタイムスタンプ',
        ],
        'mst_artwork_fragment_positions' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_artwork_fragments' => [
            'id' => 'UUID',
            'rarity' => 'レアリティ',
            'asset_num' => 'アセット番号',
            'release_key' => 'リリースキー',
        ],
        'mst_artwork_fragments_i18n' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_artworks' => [
            'id' => 'UUID',
            'asset_key' => '原画画像アセット',
            'release_key' => 'リリースキー',
        ],
        'mst_artworks_i18n' => [
            'id' => 'UUID',
            'description' => '原画の説明文',
            'release_key' => 'リリースキー',
        ],
        'mst_attack_elements' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
            'mst_attack_id' => 'mst_attacks.id',
            'sort_order' => '表示順',
            'attack_delay' => '攻撃が発生するまでの時間',
            'attack_type' => '攻撃タイプ',
            'range_start_type' => '攻撃範囲開始タイプ',
            'range_start_parameter' => '攻撃範囲開始値',
            'range_end_type' => '攻撃範囲終了タイプ',
            'range_end_parameter' => '攻撃範囲終了値',
            'max_target_count' => '攻撃対象最大数',
            'target' => '対象',
            'target_type' => '対象タイプ',
            'target_colors' => '対象属性',
            'target_roles' => '対象ロールタイプ',
            'damage_type' => 'ダメージタイプ',
            'hit_type' => '命中効果タイプ',
            'hit_parameter1' => '命中効果値1',
            'hit_parameter2' => '命中効果値2',
            'hit_effect_id' => '命中時エフェクトID',
            'hit_onomatopoeia_group_id' => '命中時擬音語グループID',
            'is_hit_stop' => 'ヒットストップするか',
            'probability' => '確率',
            'power_parameter_type' => '攻撃力増減タイプ',
            'power_parameter' => '攻撃力増減値',
            'effect_type' => '攻撃効果タイプ',
            'effective_count' => '攻撃効果回数',
            'effective_duration' => '攻撃効果間隔',
            'effect_parameter' => '攻撃効果値',
        ],
        'mst_attack_hit_effects' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
            'onomatopoeia1_asset_key' => '擬音語アセットキー1',
            'onomatopoeia2_asset_key' => '擬音語アセットキー2',
            'onomatopoeia3_asset_key' => '擬音語アセットキー3',
            'sound_effect_asset_key' => 'SEアセットキー',
            'killer_sound_effect_asset_key' => '弱点攻撃SEアセットキー',
        ],
        'mst_attacks' => [
            'id' => 'UUID',
            'mst_unit_id' => 'mst.units.id',
            'unit_grade' => 'ユニットグレード',
            'attack_kind' => '攻撃種別',
            'killer_colors' => '弱点対象属性',
            'killer_percentage' => '弱点割合',
            'action_frames' => 'アクションフレーム数',
            'attack_delay' => '攻撃が発生するまでの時間',
            'next_attack_interval' => '次回攻撃間隔',
            'release_key' => 'リリースキー',
        ],
        'mst_attacks_i18n' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
            'mst_attack_id' => 'mst_attacks.id',
            'language' => '言語',
            'description' => '攻撃説明',
            'grade_description' => 'グレード説明',
        ],
        'mst_auto_player_sequences' => [
            'id' => 'UUID',
            'sequence_element_id' => '順序要素ID',
            'sequence_group_id' => '順序グループID',
            'priority_sequence_element_id' => '優先順序要素ID',
            'condition_type' => '条件タイプ',
            'condition_value' => '条件値',
            'action_type' => 'アクション種別',
            'action_value' => 'アクション値',
            'action_value2' => 'アクション値2',
            'summon_animation_type' => '召喚アニメーションタイプ',
            'summon_count' => '召喚数',
            'summon_interval' => '召喚間隔',
            'action_delay' => 'アクションするまでの時間',
            'summon_position' => '召喚位置',
            'move_start_condition_type' => '移動を開始する条件',
            'move_start_condition_value' => '移動開始条件で使用するパラメータ',
            'move_stop_condition_type' => '移動を停止する条件',
            'move_stop_condition_value' => '移動停止条件で使用するパラメータ',
            'move_restart_condition_type' => '移動停止後に再度移動開始する条件',
            'move_restart_condition_value' => '再移動開始条件で使用するパラメータ',
            'move_loop_count' => '移動・停止を繰り返す回数',
            'last_boss_trigger' => 'ラスボストリガー',
            'aura_type' => 'オーラタイプ',
            'death_type' => '死亡タイプ',
            'override_drop_battle_point' => '上書きするドロップバトルポイント',
            'enemy_hp_coef' => '敵HP係数',
            'enemy_attack_coef' => '敵攻撃力係数',
            'enemy_speed_coef' => '敵速度係数',
            'deactivation_condition_type' => 'このSequenceが非活性化する条件',
            'deactivation_condition_value' => '非活性化条件で使用するパラメータ',
            'is_summon_unit_outpost_damage_invalidation' => '召喚ユニットの基地ダメージを無効化するか',
            'release_key' => 'リリースキー',
        ],
        'mst_battle_point_levels' => [
            'id' => 'ID',
            'release_key' => 'リリースキー',
            'level' => 'レベル(当初は貯まるとレベルを上げて更にポイントが貯まる速度とかを強化できる仕様だった)',
            'required_level_up_battle_point' => 'レベルを上げるために必要なポイント',
            'max_battle_point' => '上限ポイント',
            'charge_amount' => '一回で貯まるポイントの量',
            'charge_interval' => '何フレーム毎にポイントが貯まるかの設定',
        ],
        'mst_cheat_settings' => [
            'release_key' => 'リリースキー',
        ],
        'mst_comeback_bonus_schedules' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_comeback_bonuses' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_configs' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
            'key' => 'キー',
            'value' => '設定値',
        ],
        'mst_daily_bonus_rewards' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_defense_targets' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
            'asset_key' => 'アセットキー',
            'position' => 'インゲーム内座標',
            'hp' => '守備対象HP',
        ],
        'mst_emblems' => [
            'id' => 'UUID',
            'asset_key' => '経緯情報ソース',
            'release_key' => 'リリースキー',
        ],
        'mst_emblems_i18n' => [
            'id' => 'UUID',
            'mst_emblem_id' => 'mst_emblems.id',
            'release_key' => 'リリースキー',
        ],
        'mst_enemy_characters' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
            'asset_key' => '経緯情報ソース',
            'is_displayed_encyclopedia' => '図鑑に表示するかのフラグ',
        ],
        'mst_enemy_characters_i18n' => [
            'id' => 'UUID',
            'mst_enemy_character_id' => 'ファントムID',
            'language' => '言語',
            'name' => 'ファントム名',
            'description' => 'ファントム説明',
            'release_key' => 'リリースキー',
        ],
        'mst_enemy_outposts' => [
            'id' => 'UUID',
            'hp' => '敵タワーHP',
            'outpost_asset_key' => '敵タワーアセットキー',
            'artwork_asset_key' => '敵タワー原画アセットキー',
            'is_damage_invalidation' => '無敵判定',
            'release_key' => 'リリースキー',
        ],
        'mst_enemy_stage_parameters' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
            'mst_enemy_character_id' => 'リレーション向けMstEnemyCharacterId',
            'character_unit_kind' => '敵カテゴリ(通常、ボス、降臨バトルボス)',
            'role_type' => 'ロールタイプ',
            'color' => '影色',
            'sort_order' => '表示並び順',
            'hp' => 'HP',
            'damage_knock_back_count' => '被撃破までのHP減少によるノックバック回数',
            'move_speed' => '移動速度',
            'well_distance' => '索敵距離',
            'attack_power' => '攻撃力',
            'attack_combo_cycle' => '攻撃サイクル',
            'mst_unit_ability_id1' => 'リレーション向けMstUnitAbilityId',
            'drop_battle_point' => '被撃破時のリーダーP獲得量',
            'mst_transformation_enemy_stage_parameter_id' => 'リレーション向けMstTransformationEnemyStageParameterId',
            'transformation_condition_type' => '敵が変身する際の条件',
            'transformation_condition_value' => '変身条件に使用するパラメータ',
        ],
        'mst_event_bonus_units' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
            'mst_unit_id' => 'ボーナス対象キャラID',
            'bonus_percentage' => 'ステータスボーナス割合',
            'event_bonus_group_id' => 'ボーナスグループ',
            'is_pick_up' => 'ボーナスキャラ簡易表示の対象フラグ',
        ],
        'mst_event_display_rewards' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
            'mst_event_id' => 'リレーション向けMstEventId',
            'resource_type' => 'リソースカテゴリ',
            'resource_id' => 'リレーション向けリソースId',
            'sort_order' => '表示順番',
        ],
        'mst_event_display_units' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
            'mst_quest_id' => 'リレーション向けMstQuestId',
            'mst_unit_id' => 'リレーション向けMstUnitId',
        ],
        'mst_event_display_units_i18n' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
            'mst_event_display_unit_id' => 'リレーション向けMstEventDisplayUnitId',
            'language' => '言語設定',
            'speech_balloon_text1' => '吹き出しセリフ1',
            'speech_balloon_text2' => '吹き出しセリフ2',
            'speech_balloon_text3' => '吹き出しセリフ3',
        ],
        'mst_events' => [
            'id' => 'UUID',
            'asset_key' => 'アセットキー',
            'release_key' => 'リリースキー',
        ],
        'mst_events_i18n' => [
            'id' => 'UUID',
            'mst_event_id' => 'リレーション向けMstEventId',
            'language' => '言語設定',
            'release_key' => 'リリースキー',
        ],
        'mst_fragment_box_groups' => [
            'id' => 'UUID',
            'mst_fragment_box_group_id' => 'BOXのアイテムID',
            'mst_item_id' => 'ラインナップされるかけらのアイテムID',
            'start_at' => 'ラインナップアイテムの開始日',
            'end_at' => 'ラインナップアイテムの終了日',
            'release_key' => 'リリースキー',
        ],
        'mst_fragment_boxes' => [
            'id' => 'UUID',
            'mst_item_id' => 'リレーション向けMstItemId',
            'mst_fragment_box_group_id' => 'リレーション向けMstFragmentBoxGroupId',
            'release_key' => 'リリースキー',
        ],
        'mst_idle_incentive_items' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
            'mst_idle_incentive_item_group_id' => 'グループID',
            'mst_item_id' => 'mst_items.id',
            'base_amount' => 'ベース量',
        ],
        'mst_idle_incentive_rewards' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
            'mst_stage_id' => '報酬が変わるステージ進捗の閾値',
            'base_coin_amount' => 'N分ごとのコインの基礎獲得数',
            'base_exp_amount' => 'N分ごとの経験値の基礎獲得数',
            'mst_idle_incentive_item_group_id' => 'mst_idle_incentive_items.mst_idle_incentive_item_group_id',
        ],
        'mst_idle_incentives' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
            'asset_key' => 'アセットキー',
            'initial_reward_receive_minutes' => '放置後最初に報酬が獲得可能になる放置時間',
            'max_idle_hours' => '最大放置時間',
            'required_quick_receive_diamond_amount' => 'クイック獲得時に必要なプリズム量',
            'max_daily_diamond_quick_receive_amount' => '１日の一次通貨での最大獲得回数',
            'max_daily_ad_quick_receive_amount' => '１日の広告での最大獲得回数',
            'ad_interval_seconds' => '広告視聴のインターバル',
            'quick_idle_minutes' => 'クイック獲得での実質放置時間',
        ],
        'mst_in_game_gimmick_objects' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
            'asset_key' => 'アセットキー',
        ],
        'mst_in_game_special_rules' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_in_games' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
            'mst_auto_player_sequence_id' => 'リレーション向けMstAutoPlayerSequenceId',
            'bgm_asset_key' => 'BGMアセットキー',
            'loop_background_asset_key' => '背景アセットキー',
            'player_outpost_asset_key' => 'プレイヤータワーアセットキー',
            'mst_page_id' => 'リレーション向けMstPageId',
            'mst_enemy_outpost_id' => 'リレーション向けMstEnemyOutpostId',
            'mst_defense_target_id' => 'リレーション向けMstDefenceTargetId',
            'boss_mst_enemy_stage_parameter_id' => 'リレーション向けMstEnemyStageParameterId',
            'normal_enemy_hp_coef' => 'ステージ内敵HP倍率(通常敵)',
            'normal_enemy_attack_coef' => 'ステージ内敵攻撃倍率(通常敵)',
            'normal_enemy_speed_coef' => 'ステージ内敵スピード倍率(通常敵)',
            'boss_enemy_hp_coef' => 'ステージ内敵HP倍率(ボス)',
            'boss_enemy_attack_coef' => 'ステージ内敵攻撃倍率(ボス)',
            'boss_enemy_speed_coef' => 'ステージ内敵スピード倍率(ボス)',
        ],
        'mst_in_games_i18n' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
            'mst_in_game_id' => 'リレーション向けMstInGameId',
            'language' => '言語設定',
            'result_tips' => '敗北時Tips',
        ],
        'mst_item_rarity_trades' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_item_transitions' => [
            'id' => 'UUID',
            'mst_item_id' => 'リレーション向けMstItemId',
            'transition1' => '画面遷移先1',
            'transition1_mst_id' => '画面遷移先条件向けMasterDataId',
            'transition2' => '画面遷移先2',
            'transition2_mst_id' => '画面遷移先条件向けMasterDataId',
            'release_key' => 'リリースキー',
        ],
        'mst_items' => [
            'id' => 'UUID',
            'type' => 'アイテムの種別を定義',
            'group_type' => 'アプリの表示タブ用',
            'rarity' => 'レア度',
            'asset_key' => 'アセットキー',
            'sort_order' => '表示順番',
            'start_date' => '開始日',
            'end_date' => '終了日',
            'release_key' => 'リリースキー',
            'destination_opr_product_id' => '画面遷移先条件向けOprProductId',
        ],
        'mst_items_i18n' => [
            'id' => 'UUID',
            'mst_item_id' => 'アイテムID',
            'language' => '言語',
            'name' => '名前',
            'description' => '説明',
            'release_key' => 'リリースキー',
        ],
        'mst_koma_lines' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
            'mst_page_id' => 'リレーション向けMstPageId',
            'row' => '列番号',
            'height' => 'コマ列高さ',
            'koma_line_layout_asset_key' => 'コマレイアウトアセットキー',
            'koma1_asset_key' => 'コマアセットキー',
            'koma1_width' => 'コマ幅',
            'koma1_back_ground_offset' => 'コマ背景オフセット',
            'koma1_effect_type' => 'コマ効果タイプ',
            'koma1_effect_parameter1' => 'コマ効果パラメータ1',
            'koma1_effect_parameter2' => 'コマ効果パラメータ2',
            'koma1_effect_target_side' => 'コマ効果影響対象',
            'koma1_effect_target_colors' => 'コマ効果影響カラー',
            'koma1_effect_target_roles' => 'コマ効果影響ロール',
            'koma2_asset_key' => 'コマアセットキー',
            'koma2_width' => 'コマ幅',
            'koma2_back_ground_offset' => 'コマ背景オフセット',
            'koma2_effect_type' => 'コマ効果タイプ',
            'koma2_effect_parameter1' => 'コマ効果パラメータ1',
            'koma2_effect_parameter2' => 'コマ効果パラメータ2',
            'koma2_effect_target_side' => 'コマ効果影響対象',
            'koma2_effect_target_colors' => 'コマ効果影響カラー',
            'koma2_effect_target_roles' => 'コマ効果影響ロール',
            'koma3_asset_key' => 'コマアセットキー',
            'koma3_width' => 'コマ幅',
            'koma3_back_ground_offset' => 'コマ背景オフセット',
            'koma3_effect_type' => 'コマ効果タイプ',
            'koma3_effect_parameter1' => 'コマ効果パラメータ1',
            'koma3_effect_parameter2' => 'コマ効果パラメータ2',
            'koma3_effect_target_side' => 'コマ効果影響対象',
            'koma3_effect_target_colors' => 'コマ効果影響カラー',
            'koma3_effect_target_roles' => 'コマ効果影響ロール',
            'koma4_asset_key' => 'コマアセットキー',
            'koma4_width' => 'コマ幅',
            'koma4_back_ground_offset' => 'コマ背景オフセット',
            'koma4_effect_type' => 'コマ効果タイプ',
            'koma4_effect_parameter1' => 'コマ効果パラメータ1',
            'koma4_effect_parameter2' => 'コマ効果パラメータ2',
            'koma4_effect_target_side' => 'コマ効果影響対象',
            'koma4_effect_target_colors' => 'コマ効果影響カラー',
            'koma4_effect_target_roles' => 'コマ効果影響ロール',
        ],
        'mst_manga_animations' => [
            'id' => 'UUID',
            'mst_stage_id' => 'mst_stages.id',
            'condition_type' => '条件タイプ',
            'condition_value' => '条件値',
            'animation_start_delay' => 'アニメーション開始までの時間',
            'is_pause' => '一時停止するか',
            'can_skip' => 'スキップ可能か',
            'asset_key' => 'アセットキー',
            'release_key' => 'リリースキー',
        ],
        'mst_mission_achievement_dependencies' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_mission_achievements' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_mission_achievements_i18n' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_mission_beginner_prompt_phrases_i18n' => [
            'id' => 'UUID',
            'language' => '言語',
            'prompt_phrase_text' => '設定文言',
            'start_at' => '設定文言を表示する開始期間',
            'end_at' => '設定文言を表示する終了期間',
            'release_key' => 'リリースキー',
        ],
        'mst_mission_beginners' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_mission_beginners_i18n' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_mission_dailies' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_mission_dailies_i18n' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_mission_daily_bonuses' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_mission_event_dailies' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_mission_event_dailies_i18n' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_mission_event_daily_bonus_schedules' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_mission_event_daily_bonuses' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_mission_event_dependencies' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_mission_events' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_mission_events_i18n' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_mission_limited_term_dependencies' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_mission_limited_terms' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_mission_limited_terms_i18n' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_mission_rewards' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_mission_weeklies' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_mission_weeklies_i18n' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_ng_words' => [
            'id' => 'UUID',
            'word' => 'NGワード',
            'release_key' => 'リリースキー',
        ],
        'mst_outpost_enhancement_levels' => [
            'id' => 'UUID',
            'mst_outpost_enhancement_id' => '拠点強化ID',
            'level' => 'レベル',
            'cost_coin' => '消費コイン',
            'enhancement_value' => '強化値',
            'release_key' => 'リリースキー',
        ],
        'mst_outpost_enhancement_levels_i18n' => [
            'id' => 'UUID',
            'mst_outpost_enhancement_level_id' => '拠点強化レベルID',
            'language' => '言語',
            'description' => '強化時の説明文',
            'release_key' => 'リリースキー',
        ],
        'mst_outpost_enhancements' => [
            'id' => 'UUID',
            'mst_outpost_id' => '拠点ID',
            'outpost_enhancement_type' => '強化タイプ',
            'asset_key' => 'アセットキー',
            'release_key' => 'リリースキー',
        ],
        'mst_outpost_enhancements_i18n' => [
            'id' => 'UUID',
            'mst_outpost_enhancement_id' => 'mst_outpost_enhancements.id',
            'language' => '言語',
            'name' => '強化できる項目の名前',
            'release_key' => 'リリースキー',
        ],
        'mst_outposts' => [
            'id' => 'UUID',
            'asset_key' => 'アセットキー',
            'start_at' => '開始日時',
            'end_at' => '終了日時',
            'release_key' => 'リリースキー',
        ],
        'mst_pack_contents' => [
            'id' => 'UUID',
            'resource_type' => '内包物のタイプ',
            'release_key' => 'リリースキー',
        ],
        'mst_packs' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_packs_i18n' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_pages' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_quest_bonus_units' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_quest_event_bonus_schedules' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
            'mst_quest_id' => 'ボーナス対象クエストID',
            'event_bonus_group_id' => 'mst_stage_event_bonus_unitsのevent_bonus_group_id',
            'start_at' => '開始日',
            'end_at' => '終了日',
        ],
        'mst_quests' => [
            'id' => 'UUID',
            'sort_order' => 'ソート順序',
            'asset_key' => 'アセットキー',
            'start_date' => '開始日',
            'end_date' => '終了日',
            'release_key' => 'リリースキー',
        ],
        'mst_quests_i18n' => [
            'id' => 'UUID',
            'mst_quest_id' => 'mst_quests.id',
            'language' => '言語',
            'name' => '名前',
            'category_name' => 'カテゴリ名',
            'flavor_text' => 'フレーバーテキスト',
            'release_key' => 'リリースキー',
        ],
        'mst_release_keys' => [
            'release_key' => 'リリースキー',
            'start_at' => '開始日時',
            'description' => '説明文',
        ],
        'mst_result_tips_i18n' => [
            'id' => 'UUID',
            'result_tips' => 'Tips本文',
            'release_key' => 'リリースキー',
        ],
        'mst_series' => [
            'asset_key' => 'アセットキー',
            'release_key' => 'リリースキー',
        ],
        'mst_series_i18n' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_shop_items' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_shop_pass_effects' => [
            'id' => 'UUID',
            'mst_shop_pass_id' => 'mst_shop_passes.id',
            'effect_type' => 'ゲーム内パス効果',
            'effect_value' => 'ゲーム内パス効果設定値',
            'release_key' => 'リリースキー',

        ],
        'mst_shop_pass_rewards' => [
            'id' => 'UUID',
            'mst_shop_pass_id' => 'mst_shop_passes.id',
            'pass_reward_type' => '報酬の受け取りタイミング',
            'resource_type' => '報酬タイプ',
            'resource_id' => '報酬リソースID',
            'resource_amount' => '報酬の個数',
            'release_key' => 'リリースキー',
        ],
        'mst_shop_passes' => [
            'id' => 'UUID',
            'opr_product_id' => 'opr_products.id',
            'asset_key' => 'アセットキー',
            'shop_pass_cell_color' => 'パス表示バナーの背景色',
            'release_key' => 'リリースキー',
        ],
        'mst_shop_passes_i18n' => [
            'id' => 'UUID',
            'mst_shop_pass_id' => 'mst_shop_passes.id',
            'language' => '言語設定',
            'name' => 'パス名',
            'release_key' => 'リリースキー',
        ],
        'mst_special_attacks_i18n' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
            'mst_unit_id' => 'mst_units.id',
            'language' => '言語設定',
            'name' => '名前',
        ],
        'mst_special_role_level_up_attack_elements' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
            'mst_attack_element_id' => '必殺ワザID',
            'min_effective_count' => '強化するeffective_countの最低値',
            'max_effective_count' => '強化するeffective_countの最高値',
            'min_effective_duration' => '強化するeffective_durationの最低値',
            'max_effective_duration' => '強化するeffective_durationの最高値',
            'min_effect_parameter' => '強化するeffect_parameterの最低値',
            'max_effect_parameter' => '強化するeffect_parameterの最高値',
        ],
        'mst_speech_balloons_i18n' => [
            'id' => 'UUID',
            'mst_unit_id' => 'リレーション向けMstUnitId',
            'language' => '言語設定',
            'condition_type' => '条件タイプ',
            'balloon_type' => '吹き出しタイプ',
            'side' => '向きタイプ',
            'duration' => '間隔',
            'text' => 'セリフ',
            'release_key' => 'リリースキー',
        ],
        'mst_stage_clear_time_rewards' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_stage_end_conditions' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
            'stage_end_type' => 'Victory(勝利)・Defeat(敗北)・Finish(終了)の3タイプのどれに当たるかを設定',
            'condition_type' => '条件を設定',
            'condition_value1' => '条件が敵討伐であれば討伐数など、条件によって必要な数など値を指定する(不要な場合は空)',
            'condition_value2' => '条件が敵討伐であれば討伐数など、条件によって必要な数など値を指定する(複数必要な場合)',
        ],
        'mst_stage_enhance_reward_params' => [
            'coin_reward_size_type' => '報酬のサイズタイプ',
        ],
        'mst_stage_event_rewards' => [
            'id' => 'UUID',
            'resource_type' => '報酬タイプ',
            'resource_id' => '報酬ID',
            'release_key' => 'リリースキー',
        ],
        'mst_stage_event_settings' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_stage_rewards' => [
            'id' => 'UUID',
            'resource_id' => '報酬ID',
            'resource_amount' => '報酬数',
            'percentage' => '出現比重',
            'release_key' => 'リリースキー',
        ],
        'mst_stage_tips' => [
            'id' => 'UUID',
            'language' => '言語設定',
            'mst_stage_tips_group_id' => 'リレーション向けMstStageTipsGroupId',
            'title' => 'タイトル',
            'description' => '本文',
            'release_key' => 'リリースキー',
        ],
        'mst_stages' => [
            'id' => 'UUID',
            'mst_quest_id' => 'クエストID(mst_quest.id)',
            'mst_in_game_id' => 'インゲーム設定ID(mst_in_game.id)',
            'stage_number' => 'ステージ番号',
            'recommended_level' => 'おすすめレベル',
            'cost_stamina' => '消費スタミナ',
            'exp' => '獲得EXP',
            'coin' => '獲得コイン',
            'prev_mst_stage_id' => '解放条件のステージID',
            'mst_stage_tips_group_id' => 'tipsID',
            'sort_order' => 'ソート順序',
            'asset_key' => 'アセットキー',
            'release_key' => 'リリースキー',
        ],
        'mst_stages_i18n' => [
            'id' => 'UUID',
            'mst_stage_id' => 'ステージID(mst_stage.id)',
            'language' => '言語設定',
            'name' => 'ステージ名',
            'release_key' => 'リリースキー',
        ],
        'mst_store_products' => [
            'id' => 'UUID',
        ],
        'mst_store_products_i18n' => [
            'id' => 'UUID',
            'mst_store_product_id' => 'mst_store_products.id',
            'language' => '言語設定',
            'release_key' => 'リリースキー',
        ],
        'mst_tutorial_tips_i18n' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_tutorials' => [
            'id' => 'UUID',
            'start_at' => '開始日時',
            'end_at' => '終了日時',
        ],
        'mst_unit_abilities' => [
            'id' => 'UUID',
            'mst_ability_id' => 'リレーション向けMstAbilityId',
            'ability_parameter1' => 'Abilityごとに使用するパラメータ1',
            'ability_parameter2' => 'Abilityごとに使用するパラメータ2',
            'ability_parameter3' => 'Abilityごとに使用するパラメータ3',
            'release_key' => 'リリースキー',
        ],
        'mst_unit_encyclopedia_effects' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_unit_encyclopedia_rewards' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_unit_fragment_converts' => [
            'id' => 'UUID',
            'unit_label' => 'ラベル',
            'convert_amount' => 'ガチャとかでキャラが重複した際に変換されるキャラのかけら数',
            'release_key' => 'リリースキー',
        ],
        'mst_unit_grade_coefficients' => [
            'id' => 'UUID',
            'unit_label' => 'ラベル',
            'grade_level' => 'グレードレベル',
            'coefficient' => '体力と攻撃力に係る係数',
            'release_key' => 'リリースキー',
        ],
        'mst_unit_grade_ups' => [
            'id' => 'UUID',
            'unit_label' => 'ラベル',
            'grade_level' => 'グレードレベル',
            'release_key' => 'リリースキー',
        ],
        'mst_unit_level_ups' => [
            'id' => 'UUID',
            'unit_label' => 'ユニットタイプ',
            'level' => 'レベル',
            'required_coin' => 'レベルアップに必要なコイン',
            'release_key' => 'リリースキー',
        ],
        'mst_unit_rank_coefficients' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_unit_rank_ups' => [
            'id' => 'UUID',
            'unit_label' => 'ユニットラベル',
            'rank' => 'Lv上限開放後のユニットのランク',
            'amount' => 'リミテッドメモリーの必要数',
            'require_level' => 'Lv上限開放に必要なユニットのレベル',
            'release_key' => 'リリースキー',
        ],
        'mst_unit_role_bonuses' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
            'role_type' => '該当のロールタイプ',
            'color_advantage_attack_bonus' => '該当ロールが攻撃時に属性有利だった時にダメージ計算にかけるボーナス係数(1.0が基準値。1.3などでダメージが大きくなる)',
            'color_advantage_defense_bonus' => '該当ロールが防御時に属性有利だった時にダメージ計算にかけるボーナス係数(1.0が基準値。0.8などでダメージが小さくなる)',
        ],
        'mst_unit_specific_rank_ups' => [
            'id' => 'UUID',
            'release_key' => 'リリースキー',
        ],
        'mst_units' => [
            'id' => 'UUID',
            'fragment_mst_item_id' => 'かけらID(mst_items.id)',
            'role_type' => '属性',
            'attack_range_type' => 'ロール',
            'unit_label' => 'ラベル',
            'asset_key' => 'アセットキー',
            'rarity' => 'レアリティ',
            'sort_order' => 'ソート順序',
            'summon_cost' => 'インゲーム召喚コスト',
            'summon_cool_time' => 'インゲーム召喚クールタイム',
            'special_attack_initial_cool_time' => '召喚時の必殺ワザクールタイム',
            'special_attack_cool_time' => '必殺ワザ使用後の必殺ワザクールタイム',
            'min_hp' => '基礎最小ステータス',
            'max_hp' => '基礎最大ステータス',
            'damage_knock_back_count' => '被撃破までのHP減少によるノックバック回数',
            'move_speed' => '移動速度',
            'well_distance' => '索敵距離',
            'min_attack_power' => '最小攻撃力',
            'max_attack_power' => '最大攻撃力',
            'mst_unit_ability_id1' => 'リレーション向けMstAbilityId',
            'ability_unlock_rank1' => '開放ランク',
            'mst_unit_ability_id2' => 'リレーション向けMstAbilityId',
            'ability_unlock_rank2' => '開放ランク',
            'mst_unit_ability_id3' => 'リレーション向けMstAbilityId',
            'ability_unlock_rank3' => '開放ランク',
            'is_encyclopedia_special_attack_position_right' => '図鑑画面で必殺ワザ再生時にキャラを右寄りにするかフラグ',
            'release_key' => 'リリースキー',
        ],
        'mst_units_i18n' => [
            'id' => 'UUID',
            'mst_unit_id' => 'リレーション向けMstUnitId',
            'language' => '言語設定',
            'name' => '名前',
            'description' => '詳細',
            'detail' => '情報詳細',
            'release_key' => 'リリースキー',
        ],
        'mst_user_level_bonus_groups' => [
            'id' => 'UUID',
            'mst_user_level_bonus_group_id' => '報酬グループID',
            'resource_type' => '報酬タイプ',
            'resource_id' => 'タイプ対象のID',
            'resource_amount' => '報酬数',
            'release_key' => 'リリースキー',
        ],
        'mst_user_level_bonuses' => [
            'id' => 'UUID',
            'level' => 'プレイヤーレベル',
            'mst_user_level_bonus_group_id' => '報酬グループID',
            'release_key' => 'リリースキー',
        ],
        'mst_user_levels' => [
            'id' => 'プレイヤーレベルID',
            'level' => 'プレイヤーレベル',
            'stamina' => '時間回復最大値のスタミナ',
            'exp' => 'レベルアップに必要な累計経験値',
            'release_key' => 'リリースキー',
        ],
    ];

    /**
     * Run the migrations.
     */
    public function up(): void
    {
        foreach ($this->tableCommentList as $tableName => $comment) {
            $this->addCommentToTable($tableName, $comment);
        }
        foreach ($this->columnCommentList as $tableName => $columnList) {
            $this->addCommentsToColumns($tableName, $columnList);
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        foreach ($this->tableCommentList as $tableName => $comment) {
            $this->addCommentToTable($tableName, "");
        }
        foreach ($this->columnCommentList as $tableName => $columnList) {
            $this->addCommentsToColumns($tableName, array_fill_keys(array_keys($columnList), ""));
        }
    }
};
