<?php

declare(strict_types=1);

namespace Feature\Domain\Stage;

use App\Domain\Campaign\Enums\CampaignTargetIdType;
use App\Domain\Campaign\Enums\CampaignType;
use App\Domain\Emblem\Constants\EmblemConstant;
use App\Domain\Emblem\Models\UsrEmblem;
use App\Domain\InGame\Enums\InGameSpecialRuleType;
use App\Domain\InGame\Models\UsrEnemyDiscovery;
use App\Domain\Item\Models\Eloquent\UsrItem;
use App\Domain\Party\Models\Eloquent\UsrParty;
use App\Domain\Resource\Enums\InGameContentType;
use App\Domain\Resource\Enums\RewardType;
use App\Domain\Resource\Mst\Models\MstEmblem;
use App\Domain\Resource\Mst\Models\MstEnemyCharacter;
use App\Domain\Resource\Mst\Models\MstInGameSpecialRule;
use App\Domain\Resource\Mst\Models\MstItem;
use App\Domain\Resource\Mst\Models\MstPack;
use App\Domain\Resource\Mst\Models\MstQuest;
use App\Domain\Resource\Mst\Models\MstQuestBonusUnit;
use App\Domain\Resource\Mst\Models\MstStage;
use App\Domain\Resource\Mst\Models\MstStageClearTimeReward;
use App\Domain\Resource\Mst\Models\MstStageEnhanceRewardParam;
use App\Domain\Resource\Mst\Models\MstStageEventReward;
use App\Domain\Resource\Mst\Models\MstStageEventSetting;
use App\Domain\Resource\Mst\Models\MstStageReward;
use App\Domain\Resource\Mst\Models\MstUnit;
use App\Domain\Resource\Mst\Models\MstUnitFragmentConvert;
use App\Domain\Resource\Mst\Models\MstUserLevel;
use App\Domain\Resource\Mst\Models\MstUserLevelBonus;
use App\Domain\Resource\Mst\Models\MstUserLevelBonusGroup;
use App\Domain\Resource\Mst\Models\OprCampaign;
use App\Domain\Resource\Mst\Models\OprProduct;
use App\Domain\Shop\Enums\PackType;
use App\Domain\Shop\Enums\ProductType;
use App\Domain\Shop\Enums\SaleCondition;
use App\Domain\Shop\Models\UsrConditionPack;
use App\Domain\Stage\Enums\QuestType;
use App\Domain\Stage\Enums\StageAutoLapType;
use App\Domain\Stage\Enums\StageRewardCategory;
use App\Domain\Stage\Enums\StageSessionStatus;
use App\Domain\Stage\Models\Eloquent\UsrStage;
use App\Domain\Stage\Models\UsrStageEnhance;
use App\Domain\Stage\Models\UsrStageEvent;
use App\Domain\Stage\Models\UsrStageSession;
use App\Domain\Stage\UseCases\StageEndUseCase;
use App\Domain\Unit\Models\Eloquent\UsrUnit;
use App\Domain\User\Constants\UserConstant;
use App\Domain\User\Models\UsrUserParameter;
use App\Http\ResponseFactories\StageResponseFactory;
use App\Http\Responses\ResultData\StageEndResultData;
use Carbon\CarbonImmutable;
use PHPUnit\Framework\Attributes\DataProvider;
use Tests\Support\Entities\CurrentUser;
use Tests\TestCase;

class StageEndUseCaseTest extends TestCase
{
    private StageEndUseCase $useCase;
    private StageResponseFactory $responseFactory;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->useCase = app(StageEndUseCase::class);
        $this->responseFactory = app(StageResponseFactory::class);
    }

    public static function params_test_exec_正常実行()
    {
        return [
            'メインクエストの通常ステージ' => [
                'isSpeadAttack' => false,
                'lapCount' => 1,
            ],
            'メインクエストの通常ステージ スタミナブーストあり' => [
                'isSpeadAttack' => false,
                'lapCount' => 3,
            ],
            'メインクエストのスピードアタックステージ' => [
                'isSpeadAttack' => true,
                'lapCount' => 1,
            ],
            'メインクエストのスピードアタックステージ スタミナブーストあり' => [
                'isSpeadAttack' => true,
                'lapCount' => 3,
            ],
        ];
    }

    #[DataProvider('params_test_exec_正常実行')]
    public function test_exec_正常実行(bool $isSpeedAttack, int $lapCount)
    {
        // Setup
        // user
        $usrUserId = $this->createUsrUser()->getUsrUserId();
        $currentUser = new CurrentUser($usrUserId);
        // usr
        $usrUserParameter = UsrUserParameter::factory()->create([
            'usr_user_id' => $usrUserId,
            'level' => 1,
            'exp' => 0,
            'coin' => 2,
            'stamina' => 4,
        ]);
        $this->createDiamond($usrUserId, 3);
        $usrStage = UsrStage::factory()->create([
            'usr_user_id' => $usrUserId,
            'mst_stage_id' => 'stage1',
            'clear_count' => 0,
            'clear_time_ms' => null,
        ]);
        $usrStageSession = UsrStageSession::factory()->create([
            'usr_user_id' => $usrUserId,
            'mst_stage_id' => 'stage1',
            'is_valid' => StageSessionStatus::STARTED->value,
            'opr_campaign_ids' => json_encode(['campaign1', 'campaign2']),
            'auto_lap_count' => $lapCount,
        ]);
        UsrEnemyDiscovery::factory()->createMany([
            ['usr_user_id' => $usrUserId, 'mst_enemy_character_id' => 'enemy1'],
        ]);
        // mst
        MstQuest::factory()->create([
            'id' => 'quest1',
            'quest_type' => 'Normal',
            'start_date' => '2023-01-01 00:00:00',
            'end_date' => '2037-01-01 00:00:00',
        ]);
        MstStage::factory()->create([
            'id' => 'stage1',
            'mst_quest_id' => 'quest1',
            'exp' => 222,
            'coin' => 333,
            'auto_lap_type' => StageAutoLapType::INITIAL,
            'max_auto_lap_count' => 5,
        ]);
        MstStageReward::factory()->createMany([
            [
                'mst_stage_id' => 'stage1',
                'reward_category' => StageRewardCategory::FIRST_CLEAR,
                'percentage' => 100,
                'resource_type' => RewardType::FREE_DIAMOND->value,
                'resource_id' => null,
                'resource_amount' => 5,
            ],
            [
                'mst_stage_id' => 'stage1',
                'reward_category' => StageRewardCategory::ALWAYS,
                'percentage' => 100,
                'resource_type' => RewardType::COIN->value,
                'resource_id' => null,
                'resource_amount' => 10,
            ],
            [
                'mst_stage_id' => 'stage1',
                'reward_category' => StageRewardCategory::RANDOM,
                'percentage' => 100,
                'resource_type' => RewardType::COIN->value,
                'resource_id' => null,
                'resource_amount' => 10,
            ],
            [
                'mst_stage_id' => 'stage1',
                'reward_category' => StageRewardCategory::RANDOM,
                'percentage' => 0,
                'resource_type' => RewardType::COIN->value,
                'resource_id' => null,
                'resource_amount' => 10,
            ],
        ]);
        if ($isSpeedAttack) {
            MstInGameSpecialRule::factory()->create([
                'content_type' => InGameContentType::STAGE,
                'target_id' => 'stage1',
                'rule_type' => InGameSpecialRuleType::SPEED_ATTACK,
                'start_at' => '2023-01-01 00:00:00',
                'end_at' => '2037-01-01 00:00:00',
            ]);
        }
        MstStageClearTimeReward::factory()->createMany([
            // 獲得できる報酬
            ['id' => 'clearTimeReward1', 'mst_stage_id' => 'stage1', 'upper_clear_time_ms' => 200, 'resource_type' => RewardType::COIN, 'resource_amount' => 50],
            ['id' => 'clearTimeReward2', 'mst_stage_id' => 'stage1', 'upper_clear_time_ms' => 100, 'resource_type' => RewardType::COIN, 'resource_amount' => 100],
            // 獲得できない報酬
            ['id' => 'clearTimeReward3', 'mst_stage_id' => 'stage1', 'upper_clear_time_ms' => 50, 'resource_type' => RewardType::COIN, 'resource_amount' => 200],
        ]);
        MstEnemyCharacter::factory()->createMany([
            ['id' => 'enemy1'],
            ['id' => 'enemy2'],
            ['id' => 'bossEnemy1'],
        ]);
        MstUserLevel::factory()->createMany([
            ['level' => 1, 'stamina' => 10, 'exp' => 0],
            ['level' => 2, 'stamina' => 10, 'exp' => 100],
            ['level' => 3, 'stamina' => 10, 'exp' => 1000],
        ]);

        // Exercise
        $resultData = $this->useCase->exec(
            $currentUser,
            UserConstant::PLATFORM_IOS,
            'stage1',
            [
                'defeatEnemyCount' => 8,
                'defeatBossEnemyCount' => 1,
                'score' => 999,
                'clearTimeMs' => 100,
                'discoveredEnemies' => [
                    ['mstEnemyCharacterId' => 'enemy1', 'count' => 3], // 発見済み
                    ['mstEnemyCharacterId' => 'enemy2', 'count' => 5], // 新発見
                    ['mstEnemyCharacterId' => 'bossEnemy1', 'count' => 1], // 新発見
                    ['mstEnemyCharacterId' => 'invalidEnemy', 'count' => 999],
                ],
            ],
        );

        // Verify

        // resultData確認
        $this->assertCount(2, $resultData->newUsrEnemyDiscoveries);
        $this->assertEqualsCanonicalizing(
            ['enemy2', 'bossEnemy1'],
            $resultData->newUsrEnemyDiscoveries->map->getMstEnemyCharacterId()->toArray(),
        );
        $this->assertEquals(['campaign1', 'campaign2'], $resultData->oprCampaignIds->toArray());

        // 報酬確認
        if ($isSpeedAttack) {
            $this->assertEqualsCanonicalizing(
                ['clearTimeReward1', 'clearTimeReward2'],
                $resultData->stageSpeedAttackClearRewards->map->getMstStageClearTimeRewardTableId()->toArray(),
            );
        } else {
            $this->assertCount(0, $resultData->stageSpeedAttackClearRewards);
        }

        // DB確認
        // ユーザーステージステータス確認
        $usrStage->refresh();
        $this->assertEquals($lapCount, $usrStage->getClearCount());
        $this->assertEquals(100, $usrStage->getClearTimeMs());
        $this->assertTrue($usrStageSession->refresh()->isClosed());
        // リソース値確認
        $usrUserParameter->refresh();
        $this->assertEquals(2, $usrUserParameter->getLevel());
        if ($isSpeedAttack) {
            $this->assertEquals(2 + (10 + 10 + 333) * $lapCount + (50 + 100), $usrUserParameter->getCoin());
        } else {
            $this->assertEquals(2 + (10 + 10 + 333) * $lapCount, $usrUserParameter->getCoin());
        }
        $this->assertEquals(0 + 222 * $lapCount, $usrUserParameter->getExp());
        $this->assertEquals(3 + 5, $this->getDiamond($usrUserId)->getFreeAmount());
        // 発見した敵情報の確認
        $this->assertEqualsCanonicalizing(
            ['enemy1', 'enemy2', 'bossEnemy1'],
            UsrEnemyDiscovery::query()->where('usr_user_id', $usrUserId)->get()->map->getMstEnemyCharacterId()->toArray()
        );
    }

    public function test_ステージ初クリアしてユーザーレベルアップ報酬も付与されることを確認()
    {
        // Setup
        $usrUserId = $this->createUsrUser()->getUsrUserId();
        $mstQuestId = '10';
        $mstStageId = '10';
        $currentUser = new CurrentUser($usrUserId);
        $usrUserParameter = UsrUserParameter::factory()->create([
            'usr_user_id' => $usrUserId,
            'level' => 1,
            'exp' => 0,
            'coin' => 2,
            'stamina' => 4,
        ]);
        $this->createDiamond($usrUserId, 3);
        UsrStage::factory()->create([
            'usr_user_id' => $usrUserId,
            'mst_stage_id' => $mstStageId,
            'clear_count' => 0,

        ]);

        MstQuest::factory()->create([
            'id' => $mstQuestId,
            'quest_type' => 'Normal',
            'start_date' => '2023-01-01 00:00:00',
            'end_date' => '2037-01-01 00:00:00',
        ]);
        MstStage::factory()->create([
            'id' => $mstStageId,
            'mst_quest_id' => $mstQuestId,
            'exp' => 1000,
            'coin' => 1000,
        ]);
        $this->createTestData($usrUserId, $mstStageId);

        // Exercise
        $response = $this->useCase->exec($currentUser, UserConstant::PLATFORM_IOS, $mstStageId);

        // Verify
        $jsonResponse = $this->responseFactory->createEndResponse($response);
        $this->assertTrue($jsonResponse->isSuccessful());

        // レスポンス確認
        $response = $jsonResponse->getData();
        $stageRewards = collect($response->stageRewards);
        $this->assertNotNull($stageRewards);
        $this->assertCount(9, $stageRewards);

        $stageRewards = $stageRewards->groupBy('rewardCategory')->map(function ($rewards) {
            return $rewards->mapWithKeys(function ($reward) {
                $reward = $reward->reward;
                return [
                    $reward->resourceType => $reward,
                ];
            });
        });
        $firstClear = $stageRewards->get(StageRewardCategory::FIRST_CLEAR->value);
        $always = $stageRewards->get(StageRewardCategory::ALWAYS->value);

        $reward = $firstClear->get(RewardType::FREE_DIAMOND->value);
        $this->assertNotNull($reward);
        $this->assertNull($reward->resourceId);
        $this->assertEquals(10, $reward->resourceAmount);
        $this->assertNull($reward->preConversionResource);

        $reward = $firstClear->get(RewardType::UNIT->value);
        $this->assertNotNull($reward);
        $this->assertEquals('unit1', $reward->resourceId);
        $this->assertEquals(1, $reward->resourceAmount);
        $this->assertNull($reward->preConversionResource);
        $reward = $firstClear->get(RewardType::ITEM->value);
        $this->assertNotNull($reward);
        $this->assertEquals('item1', $reward->resourceId);
        $this->assertEquals(10, $reward->resourceAmount);
        $this->assertNotNull($reward->preConversionResource);

        $reward = $always->get(RewardType::COIN->value);
        $this->assertNotNull($reward);
        $this->assertNull($reward->resourceId);
        $this->assertEquals(1000, $reward->resourceAmount);
        $this->assertNull($reward->preConversionResource);
        $reward = $always->get(RewardType::EXP->value);
        $this->assertNotNull($reward);
        $this->assertNull($reward->resourceId);
        $this->assertEquals(1000, $reward->resourceAmount);
        $this->assertNull($reward->preConversionResource);
        $reward = $always->get(RewardType::ITEM->value);
        $this->assertNotNull($reward);
        $this->assertEquals('item1', $reward->resourceId);
        $this->assertEquals(10, $reward->resourceAmount);
        $this->assertNotNull($reward->preConversionResource);

        $userLevelUpData = $response->userLevel;
        $this->assertNotNull($userLevelUpData);
        $this->assertEquals(0, $userLevelUpData->beforeExp);
        $this->assertEquals(1000, $userLevelUpData->afterExp);
        $this->assertCount(2, $userLevelUpData->usrLevelReward);
        $this->assertFalse($userLevelUpData->isEmblemDuplicated);
        $usrLevelUpRewards = collect($userLevelUpData->usrLevelReward)->map(function ($reward) {
            return $reward->reward;
        })->keyBy('resourceType');
        $reward = $usrLevelUpRewards->get(RewardType::ITEM->value);
        $this->assertEquals(RewardType::ITEM->value, $reward->resourceType);
        $this->assertEquals('item1', $reward->resourceId);
        $this->assertEquals(20, $reward->resourceAmount);
        $reward = $usrLevelUpRewards->get(RewardType::EMBLEM->value);
        $this->assertEquals(RewardType::EMBLEM->value, $reward->resourceType);
        $this->assertEquals('emblem2', $reward->resourceId);
        $this->assertEquals(1, $reward->resourceAmount);
        $this->assertTrue($response->isEmblemDuplicated);

        // DB確認
        $usrUserParameter->refresh();
        $this->assertEquals(3, $usrUserParameter->getLevel());
        $this->assertEquals(1000, $usrUserParameter->getExp());
        $this->assertEquals(2 + 2000 + EmblemConstant::DUPLICATE_EMBLEM_CONVERT_COIN, $usrUserParameter->getCoin());

        $diamond = $this->getDiamond($usrUserId);
        $this->assertEquals(3 + 10, $diamond->getFreeAmount());

        $usrItem = UsrItem::query()->where('usr_user_id', $usrUserId)->where('mst_item_id', 'item1')->first();
        $this->assertNotNull($usrItem);
        $this->assertEquals(10 + 10 + 10 * 2, $usrItem->getAmount());

        $usrEmblem = UsrEmblem::query()->where('usr_user_id', $usrUserId)->where('mst_emblem_id', 'emblem1')->first();
        $this->assertNotNull($usrEmblem);

        //$usrUnits = UsrUnit::query()->where('usr_user_id', $usrUserId)->where('mst_unit_id', 'unit1')->first();
        $usrUnits = UsrUnit::query()->where('usr_user_id', $usrUserId)->where('mst_unit_id', 'unit1')->first();
        $this->assertNotNull($usrUnits);
    }

    public function test_ステージクリア2回目でユーザーレベルアップ報酬はない場合を確認()
    {
        // Setup
        $usrUserId = $this->createUsrUser()->getUsrUserId();
        $mstQuestId = '10';
        $mstStageId = '10';
        $currentUser = new CurrentUser($usrUserId);
        $usrUserParameter = UsrUserParameter::factory()->create([
            'usr_user_id' => $usrUserId,
            'level' => 1,
            'exp' => 0,
            'coin' => 2,
            'stamina' => 4,
        ]);
        $this->createDiamond($usrUserId, 3);
        UsrStage::factory()->create([
            'usr_user_id' => $usrUserId,
            'mst_stage_id' => $mstStageId,
            'clear_count' => 1,

        ]);

        MstQuest::factory()->create([
            'id' => $mstQuestId,
            'quest_type' => 'Normal',
            'start_date' => '2023-01-01 00:00:00',
            'end_date' => '2037-01-01 00:00:00',
        ]);
        MstStage::factory()->create([
            'id' => $mstStageId,
            'mst_quest_id' => $mstQuestId,
            'exp' => 1,
            'coin' => 1000,
        ]);
        $this->createTestData($usrUserId, $mstStageId);

        // Exercise
        $response = $this->useCase->exec($currentUser, UserConstant::PLATFORM_IOS, $mstStageId);

        // Verify
        $this->verifyResponse($response);

        // DB確認
        $usrUserParameter->refresh();
        $this->assertEquals(1, $usrUserParameter->getLevel());
        $this->assertEquals(1, $usrUserParameter->getExp());
        $this->assertEquals(2 + 2000, $usrUserParameter->getCoin());

        $diamond = $this->getDiamond($usrUserId);
        $this->assertEquals(3, $diamond->getFreeAmount());

        $usrItem = UsrItem::query()->where('usr_user_id', $usrUserId)->where('mst_item_id', 'item1')->first();
        $this->assertNull($usrItem);
    }

    public function test_イベントステージ初クリアでユーザーレベルアップ報酬も付与されることを確認()
    {
        // Setup
        $usrUserId = $this->createUsrUser()->getUsrUserId();
        $mstQuestId = '10';
        $mstStageId = '10';
        $currentUser = new CurrentUser($usrUserId);
        $usrUserParameter = UsrUserParameter::factory()->create([
            'usr_user_id' => $usrUserId,
            'level' => 1,
            'exp' => 0,
            'coin' => 2,
            'stamina' => 4,
        ]);
        $this->createDiamond($usrUserId, 3);
        UsrStageEvent::factory()->create([
            'usr_user_id' => $usrUserId,
            'mst_stage_id' => $mstStageId,
            'reset_clear_count' => 0,
            'clear_count' => 0,
        ]);
        MstQuest::factory()->create([
            'id' => $mstQuestId,
            'quest_type' => 'Event',
            'start_date' => '2023-01-01 00:00:00',
            'end_date' => '2037-01-01 00:00:00',
        ]);
        MstStage::factory()->create([
            'id' => $mstStageId,
            'mst_quest_id' => $mstQuestId,
            'exp' => 1000,
            'coin' => 1000,
        ]);
        MstStageEventSetting::factory()->create([
            'id' => '1',
            'mst_stage_id' => $mstStageId,
            'clearable_count' => 3,
        ]);
        $this->createTestData($usrUserId, $mstStageId);

        // Exercise
        $response = $this->useCase->exec($currentUser, UserConstant::PLATFORM_IOS, $mstStageId);

        // Verify
        $jsonResponse = $this->responseFactory->createEndResponse($response);
        $this->assertTrue($jsonResponse->isSuccessful());

        // レスポンス確認
        $response = $jsonResponse->getData();
        $stageRewards = collect($response->stageRewards);
        $this->assertNotNull($stageRewards);
        $this->assertCount(6, $stageRewards);

        $stageRewards = $stageRewards->groupBy('rewardCategory')->map(function ($rewards) {
            return $rewards->mapWithKeys(function ($reward) {
                $reward = $reward->reward;
                return [
                    $reward->resourceType => $reward,
                ];
            });
        });

        $reward = $stageRewards->get(StageRewardCategory::FIRST_CLEAR->value, collect())->get(RewardType::COIN->value);
        $this->assertNotNull($reward);
        $this->assertEquals(1000, $reward->resourceAmount);
        $reward = $stageRewards->get(StageRewardCategory::FIRST_CLEAR->value, collect())->get(RewardType::EMBLEM->value);
        $this->assertNotNull($reward);
        $this->assertEquals('emblem1', $reward->resourceId);
        $this->assertEquals(1, $reward->resourceAmount);
        $reward = $stageRewards->get(StageRewardCategory::FIRST_CLEAR->value, collect())->get(RewardType::FREE_DIAMOND->value);
        $this->assertEquals(20, $reward->resourceAmount);
        $reward = $stageRewards->get(StageRewardCategory::ALWAYS->value, collect())->get(RewardType::COIN->value);
        $this->assertEquals(1600, $reward->resourceAmount);
        $reward = $stageRewards->get(StageRewardCategory::ALWAYS->value, collect())->get(RewardType::EXP->value);
        $this->assertEquals(1000, $reward->resourceAmount);

        $reward = $stageRewards->get(StageRewardCategory::RANDOM->value, collect())->get(RewardType::COIN->value);
        $this->assertEquals(500, $reward->resourceAmount);

        $this->assertTrue($response->isEmblemDuplicated);

        $userLevelUpData = $response->userLevel;
        $this->assertNotNull($userLevelUpData);
        $this->assertEquals(0, $userLevelUpData->beforeExp);
        $this->assertEquals(1000, $userLevelUpData->afterExp);
        $this->assertCount(2, $userLevelUpData->usrLevelReward);
        $this->assertFalse($userLevelUpData->isEmblemDuplicated);
        $usrLevelUpRewards = collect($userLevelUpData->usrLevelReward)
            ->map(function ($reward) {
                return $reward->reward;
            })
            ->keyBy(function ($reward) {
                return $reward->resourceType;
            });
        $reward = $usrLevelUpRewards->get(RewardType::ITEM->value);
        $this->assertEquals(RewardType::ITEM->value, $reward->resourceType);
        $this->assertEquals('item1', $reward->resourceId);
        $this->assertEquals(20, $reward->resourceAmount);
        $reward = $usrLevelUpRewards->get(RewardType::EMBLEM->value);
        $this->assertEquals(RewardType::EMBLEM->value, $reward->resourceType);
        $this->assertEquals('emblem2', $reward->resourceId);
        $this->assertEquals(1, $reward->resourceAmount);

        // DB確認
        $usrUserParameter->refresh();
        $this->assertEquals(3, $usrUserParameter->getLevel());
        $this->assertEquals(1000, $usrUserParameter->getExp());
        $this->assertEquals(2 + 2100 + EmblemConstant::DUPLICATE_EMBLEM_CONVERT_COIN, $usrUserParameter->getCoin());

        $diamond = $this->getDiamond($usrUserId);
        $this->assertEquals(3 + 20, $diamond->getFreeAmount());

        $usrItem = UsrItem::query()->where('usr_user_id', $usrUserId)->where('mst_item_id', 'item1')->first();
        $this->assertNotNull($usrItem);
        $this->assertEquals(20, $usrItem->getAmount());

        $usrEmblem = UsrEmblem::query()->where('usr_user_id', $usrUserId)->where('mst_emblem_id', 'emblem1')->first();
        $this->assertNotNull($usrEmblem);
    }

    public static function params_test_exec_イベントステージのスタミナブースト()
    {
        return [
            'スタミナブーストなし' => ['lapCount' => 1, 'expectedCount' => 6],
            'スタミナブースト3周' => ['lapCount' => 3, 'expectedCount' => 12],
            'スタミナブースト5周' => ['lapCount' => 5, 'expectedCount' => 18],
        ];
    }

    #[DataProvider('params_test_exec_イベントステージのスタミナブースト')]
    public function test_exec_イベントステージのスタミナブースト(
        int $lapCount,
        int $expectedCount,
    ) {
        // Setup
        $usrUserId = $this->createUsrUser()->getUsrUserId();
        $mstQuestId = '10';
        $mstStageId = '10';
        $currentUser = new CurrentUser($usrUserId);
        $usrUserParameter = UsrUserParameter::factory()->create([
            'usr_user_id' => $usrUserId,
            'level' => 1,
            'exp' => 0,
            'coin' => 2,
            'stamina' => 4,
        ]);
        $this->createDiamond($usrUserId, 3);
        UsrStageEvent::factory()->create([
            'usr_user_id' => $usrUserId,
            'mst_stage_id' => $mstStageId,
            'reset_clear_count' => 0,
            'clear_count' => 0,
        ]);
        MstQuest::factory()->create([
            'id' => $mstQuestId,
            'quest_type' => 'Event',
            'start_date' => '2023-01-01 00:00:00',
            'end_date' => '2037-01-01 00:00:00',
        ]);
        MstStage::factory()->create([
            'id' => $mstStageId,
            'mst_quest_id' => $mstQuestId,
            'exp' => 1000,
            'coin' => 1000,
        ]);
        MstStageEventSetting::factory()->create([
            'id' => '1',
            'mst_stage_id' => $mstStageId,
            'clearable_count' => 3,
        ]);
        $this->createTestData($usrUserId, $mstStageId);
        UsrStageSession::query()
            ->where('usr_user_id', $usrUserId)
            ->where('mst_stage_id', $mstStageId)
            ->update([
                'auto_lap_count' => $lapCount,
            ]);

        // Exercise
        $response = $this->useCase->exec($currentUser, UserConstant::PLATFORM_IOS, $mstStageId);

        // Verify
        $jsonResponse = $this->responseFactory->createEndResponse($response);
        $this->assertTrue($jsonResponse->isSuccessful());

        // レスポンス確認
        $response = $jsonResponse->getData();
        $stageRewards = collect($response->stageRewards);
        $this->assertNotNull($stageRewards);
        $this->assertCount($expectedCount, $stageRewards);

        $stageRewards = $stageRewards->groupBy('rewardCategory')->map(function ($rewards) {
            return $rewards->mapWithKeys(function ($reward) {
                $reward = $reward->reward;
                return [
                    $reward->resourceType => $reward,
                ];
            });
        });

        $reward = $stageRewards->get(StageRewardCategory::FIRST_CLEAR->value, collect())->get(RewardType::COIN->value);
        $this->assertNotNull($reward);
        $this->assertEquals(1000, $reward->resourceAmount);
        $reward = $stageRewards->get(StageRewardCategory::FIRST_CLEAR->value, collect())->get(RewardType::EMBLEM->value);
        $this->assertNotNull($reward);
        $this->assertEquals('emblem1', $reward->resourceId);
        $this->assertEquals(1, $reward->resourceAmount);
        $reward = $stageRewards->get(StageRewardCategory::FIRST_CLEAR->value, collect())->get(RewardType::FREE_DIAMOND->value);
        $this->assertEquals(20, $reward->resourceAmount);
        $reward = $stageRewards->get(StageRewardCategory::ALWAYS->value, collect())->get(RewardType::COIN->value);
        $this->assertEquals(1600, $reward->resourceAmount);
        $reward = $stageRewards->get(StageRewardCategory::ALWAYS->value, collect())->get(RewardType::EXP->value);
        $this->assertEquals(1000, $reward->resourceAmount);

        $reward = $stageRewards->get(StageRewardCategory::RANDOM->value, collect())->get(RewardType::COIN->value);
        $this->assertEquals(500, $reward->resourceAmount);

        $this->assertTrue($response->isEmblemDuplicated);

        $userLevelUpData = $response->userLevel;
        $this->assertNotNull($userLevelUpData);
        $this->assertEquals(0, $userLevelUpData->beforeExp);
        $this->assertEquals(1000, $userLevelUpData->afterExp);
        $this->assertCount(2, $userLevelUpData->usrLevelReward);
        $this->assertFalse($userLevelUpData->isEmblemDuplicated);
        $usrLevelUpRewards = collect($userLevelUpData->usrLevelReward)
            ->map(function ($reward) {
                return $reward->reward;
            })
            ->keyBy(function ($reward) {
                return $reward->resourceType;
            });
        $reward = $usrLevelUpRewards->get(RewardType::ITEM->value);
        $this->assertEquals(RewardType::ITEM->value, $reward->resourceType);
        $this->assertEquals('item1', $reward->resourceId);
        $this->assertEquals(20, $reward->resourceAmount);
        $reward = $usrLevelUpRewards->get(RewardType::EMBLEM->value);
        $this->assertEquals(RewardType::EMBLEM->value, $reward->resourceType);
        $this->assertEquals('emblem2', $reward->resourceId);
        $this->assertEquals(1, $reward->resourceAmount);

        // DB確認
        $usrUserParameter->refresh();
        $this->assertEquals(3, $usrUserParameter->getLevel());
        $this->assertEquals(1000, $usrUserParameter->getExp());
        $this->assertEquals(2 + (2100 * $lapCount) + EmblemConstant::DUPLICATE_EMBLEM_CONVERT_COIN, $usrUserParameter->getCoin());

        $diamond = $this->getDiamond($usrUserId);
        $this->assertEquals(3 + 20, $diamond->getFreeAmount());

        $usrItem = UsrItem::query()->where('usr_user_id', $usrUserId)->where('mst_item_id', 'item1')->first();
        $this->assertNotNull($usrItem);
        $this->assertEquals(20, $usrItem->getAmount());

        $usrEmblem = UsrEmblem::query()->where('usr_user_id', $usrUserId)->where('mst_emblem_id', 'emblem1')->first();
        $this->assertNotNull($usrEmblem);
    }

    public function testExec_ユーザーレベルパック開放テスト()
    {
        // NOTE バグ修正確認のためのテスト
        // Setup
        $usrUserId = $this->createUsrUser()->getUsrUserId();
        $mstQuestId = MstQuest::factory()->create()->toEntity()->getId();
        $mstStageId = MstStage::factory()->create(['mst_quest_id' => $mstQuestId, 'exp' => 10])->toEntity()->getId();
        MstUserLevel::factory()->createMany([
            ['level' => 1, 'exp' => 0],
            ['level' => 2, 'exp' => 10],
        ]);
        $oprProduct = OprProduct::factory()->create(['product_type' => ProductType::PACK->value])->toEntity();
        $mstPackId = MstPack::factory()->create([
            'product_sub_id' => $oprProduct->getId(),
            'pack_type'=> PackType::NORMAL->value,
            'sale_condition' => SaleCondition::USER_LEVEL->value,
            'sale_condition_value' => '2',
        ])->toEntity()->getId();

        $currentUser = new CurrentUser($usrUserId);
        UsrUserParameter::factory()->create([
            'usr_user_id' => $usrUserId,
            'level' => 1,
            'exp' => 0,
            'stamina' => 1,
        ]);
        UsrStage::factory()->create(['usr_user_id' => $usrUserId, 'mst_stage_id' => $mstStageId]);
        UsrStageSession::factory()->create([
            'usr_user_id' => $usrUserId,
            'mst_stage_id' => $mstStageId,
            'is_valid' => 1,
        ]);

        $response = $this->useCase->exec($currentUser, UserConstant::PLATFORM_IOS, $mstStageId);

        $usrConditionPack = $response->usrConditionPacks->first();
        $this->assertNotNull($usrConditionPack);
        $this->assertEquals($mstPackId, $usrConditionPack->getMstPackId());

        // DB確認
        $usrConditionPack = UsrConditionPack::query()
            ->where('usr_user_id', $usrUserId)
            ->where('mst_pack_id', $mstPackId)
            ->first();
        $this->assertNotNull($usrConditionPack);
    }

    public function testExec_経験値キャンペーンが適用される場合()
    {
        // Setup
        $usrUserId = $this->createUsrUser()->getId();
        $this->fixTime();
        $currentUser = new CurrentUser($usrUserId);

        $mstQuest = MstQuest::factory()->create([
            'quest_type' => 'Normal'
        ])->toEntity();
        $mstStage = MstStage::factory()->create([
            'mst_quest_id' => $mstQuest->getId(),
            'exp' => 100,
            'cost_stamina' => 1,
        ])->toEntity();
        MstUserLevel::factory()->createMany([
            ['level' => 1, 'stamina' => 10, 'exp' => 0],
            ['level' => 2, 'stamina' => 10, 'exp' => 1000],
        ]);
        $oprCampaign = OprCampaign::factory()->create([
            'campaign_type' => CampaignType::EXP->value,
            'target_type' => 'NormalQuest',
            'target_id_type' => CampaignTargetIdType::QUEST->value,
            'target_id' => $mstQuest->getId(),
            'effect_value' => 200,
        ])->toEntity();

        UsrStage::factory()->create([
            'usr_user_id' => $usrUserId,
            'mst_stage_id' => $mstStage->getId(),
        ]);
        UsrUserParameter::factory()->create([
            'usr_user_id' => $usrUserId,
            'level' => 1,
            'exp' => 100,
            'stamina' => 10,
        ]);
        $this->createDiamond($usrUserId);
        UsrStageSession::factory()->create([
            'usr_user_id' => $usrUserId,
            'mst_stage_id' => $mstStage->getId(),
            'is_valid' => 1,
            'opr_campaign_ids' => json_encode([$oprCampaign->getId()]),
        ]);

        $this->useCase->exec($currentUser, UserConstant::PLATFORM_IOS, $mstStage->getId());
        $this->saveAll();

        // Verify
        /** @var UsrUserParameter $usrUserParameter */
        $usrUserParameter = UsrUserParameter::query()->where('usr_user_id', $usrUserId)->first();
        $this->assertEquals(100 + 200, $usrUserParameter->getExp());
    }

    public function testExec_コインドロップキャンペーンが適用される場合()
    {
        // Setup
        $usrUserId = $this->createUsrUser()->getId();
        $this->fixTime();
        $currentUser = new CurrentUser($usrUserId);

        $mstStageRewardGroupId = 'group1';
        $mstQuest = MstQuest::factory()->create([
            'quest_type' => 'Normal'
        ])->toEntity();
        $mstStage = MstStage::factory()->create([
            'mst_quest_id' => $mstQuest->getId(),
            'cost_stamina' => 1,
            'coin' => 100,
        ])->toEntity();
        MstStageReward::factory()->createMany([
            [
                'mst_stage_id' => $mstStage->getId(),
                'reward_category' => StageRewardCategory::FIRST_CLEAR->value,
                'resource_type' => RewardType::COIN->value,
                'resource_id' => null,
                'resource_amount' => 200,
                'percentage' => 100,
            ],
            [
                'mst_stage_id' => $mstStage->getId(),
                'reward_category' => StageRewardCategory::ALWAYS->value,
                'resource_type' => RewardType::COIN->value,
                'resource_id' => null,
                'resource_amount' => 200,
                'percentage' => 100,
            ],
        ]);
        MstUserLevel::factory()->createMany([
            ['level' => 1, 'stamina' => 10, 'exp' => 0],
            ['level' => 2, 'stamina' => 10, 'exp' => 1000],
        ]);
        $oprCampaignId = OprCampaign::factory()->create([
            'campaign_type' => CampaignType::COIN_DROP->value,
            'target_type' => 'NormalQuest',
            'target_id_type' => CampaignTargetIdType::QUEST->value,
            'target_id' => $mstQuest->getId(),
            'effect_value' => 200,
        ])->toEntity()->getId();

        UsrStage::factory()->create([
            'usr_user_id' => $usrUserId,
            'mst_stage_id' => $mstStage->getId(),
            'clear_count' => 0,

        ]);
        UsrUserParameter::factory()->create([
            'usr_user_id' => $usrUserId,
            'level' => 1,
            'coin' => 100,
            'stamina' => 10,
        ]);
        $this->createDiamond($usrUserId);
        UsrStageSession::factory()->create([
            'usr_user_id' => $usrUserId,
            'mst_stage_id' => $mstStage->getId(),
            'is_valid' => 1,
            'opr_campaign_ids' => json_encode([$oprCampaignId]),
        ]);

        $this->useCase->exec($currentUser, UserConstant::PLATFORM_IOS, $mstStage->getId());
        $this->saveAll();

        // Verify
        /** @var UsrUserParameter $usrUserParameter */
        $usrUserParameter = UsrUserParameter::query()->where('usr_user_id', $usrUserId)->first();
        // 初期値 + ステージ固定 + 初回クリア(キャンペーン適用なし) + 毎回報酬
        $this->assertEquals(100 + 200 + 200 + 400, $usrUserParameter->getCoin());
    }

    public function testExec_アイテムドロップキャンペーンが適用される場合()
    {
        // Setup
        $usrUserId = $this->createUsrUser()->getId();
        $this->fixTime();
        $currentUser = new CurrentUser($usrUserId);

        $mstItem = MstItem::factory()->create()->toEntity();

        $mstQuest = MstQuest::factory()->create([
            'quest_type' => 'Normal'
        ])->toEntity();
        $mstStage = MstStage::factory()->create([
            'mst_quest_id' => $mstQuest->getId(),
            'cost_stamina' => 1,
            'coin' => 100,
        ])->toEntity();
        MstStageReward::factory()->createMany([
            [
                'mst_stage_id' => $mstStage->getId(),
                'reward_category' => StageRewardCategory::FIRST_CLEAR->value,
                'resource_type' => RewardType::ITEM->value,
                'resource_id' => $mstItem->getId(),
                'resource_amount' => 10,
                'percentage' => 100,
            ],
            [
                'mst_stage_id' => $mstStage->getId(),
                'reward_category' => StageRewardCategory::ALWAYS->value,
                'resource_type' => RewardType::ITEM->value,
                'resource_id' => $mstItem->getId(),
                'resource_amount' => 10,
                'percentage' => 100,
            ],
            [
                'mst_stage_id' => $mstStage->getId(),
                'reward_category' => StageRewardCategory::RANDOM->value,
                'resource_type' => RewardType::ITEM->value,
                'resource_id' => $mstItem->getId(),
                'resource_amount' => 10,
                'percentage' => 100,
            ],
        ]);
        MstUserLevel::factory()->createMany([
            ['level' => 1, 'stamina' => 10, 'exp' => 0],
            ['level' => 2, 'stamina' => 10, 'exp' => 1000],
        ]);
        $oprCampaignId = OprCampaign::factory()->create([
            'campaign_type' => CampaignType::ITEM_DROP->value,
            'target_type' => 'NormalQuest',
            'target_id_type' => CampaignTargetIdType::QUEST->value,
            'target_id' => $mstQuest->getId(),
            'effect_value' => 200,
        ])->toEntity()->getId();

        UsrStage::factory()->create([
            'usr_user_id' => $usrUserId,
            'mst_stage_id' => $mstStage->getId(),
            'clear_count' => 0,

        ]);
        UsrUserParameter::factory()->create([
            'usr_user_id' => $usrUserId,
            'level' => 1,
            'stamina' => 10,
        ]);
        UsrItem::factory()->create([
            'usr_user_id' => $usrUserId,
            'mst_item_id' => $mstItem->getId(),
            'amount' => 10,
        ]);
        $this->createDiamond($usrUserId);
        UsrStageSession::factory()->create([
            'usr_user_id' => $usrUserId,
            'mst_stage_id' => $mstStage->getId(),
            'is_valid' => 1,
            'opr_campaign_ids' => json_encode([$oprCampaignId]),
        ]);

        $this->useCase->exec($currentUser, UserConstant::PLATFORM_IOS, $mstStage->getId());
        $this->saveAll();

        // Verify
        /** @var UsrItem $usrItem */
        $usrItem = UsrItem::query()
            ->where('usr_user_id', $usrUserId)
            ->where('mst_item_id', $mstItem->getId())
            ->first();
        // 初期値 + 初回クリア(キャンペーン適用なし) + 毎回報酬 + ランダム報酬
        $this->assertEquals(10 + 10 + 20 + 20, $usrItem->getAmount());
    }

    public static function params_test_exec_強化クエストの終了処理()
    {
        return [
            'スコアがある場合' => [
                'score' => 999,
                'scoreBonusCoin' => 500,
                'highScore' => 999,
            ],
            'スコア０' => [
                'score' => 0,
                'scoreBonusCoin' => 0,
                'highScore' => 111,
            ],
        ];
    }

    #[DataProvider('params_test_exec_強化クエストの終了処理')]
    public function test_exec_強化クエストの終了処理の確認(int $score, int $scoreBonusCoin, int $highScore)
    {
        // Setup
        $usrUserId = $this->createUsrUser()->getId();
        $this->fixTime();
        $currentUser = new CurrentUser($usrUserId);

        // mst
        MstQuest::factory()->createMany([
            [
                'id' => 'normal_quest',
                'quest_type' => QuestType::NORMAL->value,
                'difficulty' => 'Normal',
                'start_date' => '2000-01-01 00:00:00',
                'end_date' => '2037-01-01 00:00:00',
            ],
            [
                'id' => 'enhance_quest',
                'quest_type' => QuestType::ENHANCE->value,
                'start_date' => '2000-01-01 00:00:00',
                'end_date' => '2037-01-01 00:00:00',
            ],
        ]);
        MstStage::factory()->createMany([
            [
                'id' => 'enhance_quest_stage',
                'mst_quest_id' => 'enhance_quest',
            ],
            [
                'id' => 'normal_quest_stage',
                'mst_quest_id' => 'normal_quest',
            ],
        ]);
        MstStageEnhanceRewardParam::factory()->createMany([
            [
                'min_threshold_score' => 1,
                'coin_reward_amount' => 10,
            ],
            [
                'min_threshold_score' => 100,
                'coin_reward_amount' => 100,
            ],
            [
                'min_threshold_score' => 500,
                'coin_reward_amount' => 500,
            ],
            [
                'min_threshold_score' => 1000,
                'coin_reward_amount' => 1000,
            ],
        ]);
        MstUnit::factory()->createMany([
            ['id' => 'unit1'],
            ['id' => 'unit2'],
            ['id' => 'unit3'],
        ]);
        UsrUnit::factory()->createMany([
            ['id' => 'usrUnit1', 'usr_user_id' => $usrUserId, 'mst_unit_id' => 'unit1'],
            ['id' => 'usrUnit2', 'usr_user_id' => $usrUserId, 'mst_unit_id' => 'unit2'],
            ['id' => 'usrUnit3', 'usr_user_id' => $usrUserId, 'mst_unit_id' => 'unit3'],
        ]);
        UsrParty::factory()->createMany([
            [
                'usr_user_id' => $usrUserId,
                'party_no' => 1,
                'usr_unit_id_1' => 'usrUnit3',
                'usr_unit_id_2' => 'usrUnit1',
                'usr_unit_id_3' => 'usrUnit2'
            ],
        ]);

        $oprCampaigns = OprCampaign::factory()->createMany([
            // コイン報酬が2倍になるキャンペーン
            [
                'campaign_type' => CampaignType::COIN_DROP->value,
                'target_type' => QuestType::ENHANCE->value . 'Quest',
                'effect_value' => 200, // 200%=2倍
                'difficulty' => 'Normal',
                'target_id_type' => CampaignTargetIdType::QUEST->value,
                'target_id' => null,
                // 現在日時が有効範囲になるように設定
                'start_at' => '2000-01-01 00:00:00',
                'end_at' => '2037-01-01 00:00:00',
            ],
        ])->map(fn($entity) => $entity->toEntity());

        MstQuestBonusUnit::factory()->createMany([
            [
                'mst_quest_id' => 'enhance_quest',
                'mst_unit_id' => 'unit1',
                'coin_bonus_rate' => 0.2,
                'start_at' => '2000-01-01 00:00:00',
                'end_at' => '2037-01-01 00:00:00',
            ],
            [
                'mst_quest_id' => 'enhance_quest',
                'mst_unit_id' => 'unit2',
                'coin_bonus_rate' => 0.4,
                'start_at' => '2000-01-01 00:00:00',
                'end_at' => '2037-01-01 00:00:00',
            ],
        ]);

        MstUserLevel::factory()->createMany([
            ['level' => 1, 'stamina' => 10, 'exp' => 0],
        ]);

        // usr
        $usrStageEnhance = UsrStageEnhance::factory()->create([
            'usr_user_id' => $usrUserId,
            'mst_stage_id' => 'enhance_quest_stage',
            'clear_count' => 0,
            'reset_challenge_count' => 0,
            'reset_ad_challenge_count' => 0,
            'max_score' => 111,
        ]);
        $usrStage = UsrStage::factory()->create([
            'usr_user_id' => $usrUserId,
            'mst_stage_id' => 'normal_quest_stage',
            'clear_count' => 1, // 探索の報酬用にクリア済み状態で用意
        ]);
        $usrStageSession = UsrStageSession::factory()->create([
            'usr_user_id' => $usrUserId,
            'mst_stage_id' => 'enhance_quest_stage',
            'is_valid' => StageSessionStatus::STARTED->value,
            'party_no' => 1,
            'opr_campaign_ids' => json_encode(
                $oprCampaigns->map(fn($entity) => $entity->getId())->toArray()
            ),
        ]);
        $usrUserParameter = UsrUserParameter::factory()->create([
            'usr_user_id' => $usrUserId,
            'coin' => 1,
        ]);

        $this->useCase->exec(
            $currentUser,
            UserConstant::PLATFORM_IOS,
            'enhance_quest_stage',
            [
                'score' => $score,
            ]
        );
        $this->saveAll();

        // Verify
        // ハイスコアの更新を確認
        $usrStageEnhance->refresh();
        $this->assertEquals($highScore, $usrStageEnhance->getMaxScore());

        // コイン報酬の付与を確認
        $usrUserParameter->refresh();
        /**
         * 1: stage/end前のコイン所持数
         * $scoreBonusCoin 対象のMstStageEnhanceRewardParamのcoin_reward_amountの値、　対象ない時は０
         * ×2: キャンペーン適用
         * +($scoreBonusCoin * 0.6): ユニットボーナス適用
         */
        $this->assertEquals(1 + ($scoreBonusCoin * 2) + ($scoreBonusCoin * 0.6), $usrUserParameter->getCoin());

        // セッションが閉じている
        $usrStageSession->refresh();
        $this->assertEquals(StageSessionStatus::CLOSED, $usrStageSession->getIsValid());

        // クリアステータスになっている
        $usrStageEnhance->refresh();
        $this->assertEquals(true, $usrStageEnhance->isClear());
        $this->assertEquals(1, $usrStageEnhance->getClearCount());
    }

    public static function params_test_exec_強化クエストのスタミナブースト()
    {
        return [
            'スタミナブーストなし' => ['lapCount' => 1],
            'スタミナブースト3周' => ['lapCount' => 3],
            'スタミナブースト5周' => ['lapCount' => 5],
        ];
    }
    #[DataProvider('params_test_exec_強化クエストのスタミナブースト')]
    public function test_exec_強化クエストのスタミナブースト(
        int $lapCount
    ) {
        // Setup
        $usrUserId = $this->createUsrUser()->getId();
        $this->fixTime();
        $currentUser = new CurrentUser($usrUserId);
        $score = 999;
        $scoreBonusCoin = 500;
        $highScore = 999;

        // mst
        MstQuest::factory()->createMany([
            [
                'id' => 'normal_quest',
                'quest_type' => QuestType::NORMAL->value,
                'difficulty' => 'Normal',
                'start_date' => '2000-01-01 00:00:00',
                'end_date' => '2037-01-01 00:00:00',
            ],
            [
                'id' => 'enhance_quest',
                'quest_type' => QuestType::ENHANCE->value,
                'start_date' => '2000-01-01 00:00:00',
                'end_date' => '2037-01-01 00:00:00',
            ],
        ]);
        MstStage::factory()->createMany([
            [
                'id' => 'enhance_quest_stage',
                'mst_quest_id' => 'enhance_quest',
            ],
            [
                'id' => 'normal_quest_stage',
                'mst_quest_id' => 'normal_quest',
            ],
        ]);
        MstStageEnhanceRewardParam::factory()->createMany([
            [
                'min_threshold_score' => 1,
                'coin_reward_amount' => 10,
            ],
            [
                'min_threshold_score' => 100,
                'coin_reward_amount' => 100,
            ],
            [
                'min_threshold_score' => 500,
                'coin_reward_amount' => 500,
            ],
            [
                'min_threshold_score' => 1000,
                'coin_reward_amount' => 1000,
            ],
        ]);
        MstUnit::factory()->createMany([
            ['id' => 'unit1'],
            ['id' => 'unit2'],
            ['id' => 'unit3'],
        ]);
        UsrUnit::factory()->createMany([
            ['id' => 'usrUnit1', 'usr_user_id' => $usrUserId, 'mst_unit_id' => 'unit1'],
            ['id' => 'usrUnit2', 'usr_user_id' => $usrUserId, 'mst_unit_id' => 'unit2'],
            ['id' => 'usrUnit3', 'usr_user_id' => $usrUserId, 'mst_unit_id' => 'unit3'],
        ]);
        UsrParty::factory()->createMany([
            [
                'usr_user_id' => $usrUserId,
                'party_no' => 1,
                'usr_unit_id_1' => 'usrUnit3',
                'usr_unit_id_2' => 'usrUnit1',
                'usr_unit_id_3' => 'usrUnit2'
            ],
        ]);

        $oprCampaigns = OprCampaign::factory()->createMany([
            // コイン報酬が2倍になるキャンペーン
            [
                'campaign_type' => CampaignType::COIN_DROP->value,
                'target_type' => QuestType::ENHANCE->value . 'Quest',
                'effect_value' => 200, // 200%=2倍
                'difficulty' => 'Normal',
                'target_id_type' => CampaignTargetIdType::QUEST->value,
                'target_id' => null,
                // 現在日時が有効範囲になるように設定
                'start_at' => '2000-01-01 00:00:00',
                'end_at' => '2037-01-01 00:00:00',
            ],
        ])->map(fn($entity) => $entity->toEntity());

        MstQuestBonusUnit::factory()->createMany([
            [
                'mst_quest_id' => 'enhance_quest',
                'mst_unit_id' => 'unit1',
                'coin_bonus_rate' => 0.2,
                'start_at' => '2000-01-01 00:00:00',
                'end_at' => '2037-01-01 00:00:00',
            ],
            [
                'mst_quest_id' => 'enhance_quest',
                'mst_unit_id' => 'unit2',
                'coin_bonus_rate' => 0.4,
                'start_at' => '2000-01-01 00:00:00',
                'end_at' => '2037-01-01 00:00:00',
            ],
        ]);

        MstUserLevel::factory()->createMany([
            ['level' => 1, 'stamina' => 10, 'exp' => 0],
        ]);

        // usr
        $usrStageEnhance = UsrStageEnhance::factory()->create([
            'usr_user_id' => $usrUserId,
            'mst_stage_id' => 'enhance_quest_stage',
            'clear_count' => 0,
            'reset_challenge_count' => 0,
            'reset_ad_challenge_count' => 0,
            'max_score' => 111,
        ]);
        $usrStage = UsrStage::factory()->create([
            'usr_user_id' => $usrUserId,
            'mst_stage_id' => 'normal_quest_stage',
            'clear_count' => 1, // 探索の報酬用にクリア済み状態で用意
        ]);
        $usrStageSession = UsrStageSession::factory()->create([
            'usr_user_id' => $usrUserId,
            'mst_stage_id' => 'enhance_quest_stage',
            'is_valid' => StageSessionStatus::STARTED->value,
            'party_no' => 1,
            'opr_campaign_ids' => json_encode(
                $oprCampaigns->map(fn($entity) => $entity->getId())->toArray()
            ),
            'auto_lap_count' => $lapCount,
        ]);
        $usrUserParameter = UsrUserParameter::factory()->create([
            'usr_user_id' => $usrUserId,
            'coin' => 1,
        ]);

        $this->useCase->exec(
            $currentUser,
            UserConstant::PLATFORM_IOS,
            'enhance_quest_stage',
            [
                'score' => $score,
            ]
        );
        $this->saveAll();

        // Verify
        // ハイスコアの更新を確認
        $usrStageEnhance->refresh();
        $this->assertEquals($highScore, $usrStageEnhance->getMaxScore());

        // コイン報酬の付与を確認
        $usrUserParameter->refresh();
        /**
         * 1: stage/end前のコイン所持数
         * $scoreBonusCoin 対象のMstStageEnhanceRewardParamのcoin_reward_amountの値、　対象ない時は０
         * ×2: キャンペーン適用
         * +($scoreBonusCoin * 0.6): ユニットボーナス適用
         */
        $this->assertEquals(1 + (($scoreBonusCoin * 2) + ($scoreBonusCoin * 0.6)) * $lapCount, $usrUserParameter->getCoin());

        // セッションが閉じている
        $usrStageSession->refresh();
        $this->assertEquals(StageSessionStatus::CLOSED, $usrStageSession->getIsValid());

        // クリアステータスになっている
        $usrStageEnhance->refresh();
        $this->assertEquals(true, $usrStageEnhance->isClear());
        $this->assertEquals($lapCount, $usrStageEnhance->getClearCount());
    }

    public function test_スピードアタックを初回クリアした場合()
    {
        // Setup
        $now = $this->fixTime();
        $usrUserId = $this->createUsrUser()->getUsrUserId();
        $currentUser = new CurrentUser($usrUserId);
        $usrUserParameter = UsrUserParameter::factory()->create([
            'usr_user_id' => $usrUserId,
            'level' => 1,
            'exp' => 0,
            'coin' => 100,
            'stamina' => 10,
        ]);
        $this->createTestDataSpeedAttack($usrUserId, $now);
        UsrStageEvent::factory()->create([
            'usr_user_id' => $usrUserId,
            'mst_stage_id' => 'mstStageId',
            'clear_count' => 1,
            'reset_clear_count' => 1,
            'reset_ad_challenge_count' => 1,
            'reset_clear_time_ms' => null,
            'clear_time_ms' => null,
            'latest_reset_at' => now(),
            'latest_event_setting_end_at' => '2000-01-01 00:00:00',
        ]);

        // Exercise
        $response = $this->useCase->exec(
            $currentUser,
            UserConstant::PLATFORM_IOS,
            'mstStageId',
            [
                'defeatEnemyCount' => 50,
                'defeatBossEnemyCount' => 2,
                'score' => 999,
                'clearTimeMs' => 20000,
            ]
        );

        // Verify
        $stageAlwaysClearRewards = $response->stageAlwaysClearRewards->keyBy(function ($entity) {
            /** @var \App\Domain\Resource\Entities\Rewards\StageAlwaysClearReward $entity */
            return $entity->getType();
        });
        $this->assertCount(2, $stageAlwaysClearRewards);
        /** @var \App\Domain\Resource\Entities\Rewards\StageAlwaysClearReward|null $stageAlwaysClearReward */
        $stageAlwaysClearReward = $stageAlwaysClearRewards->get(RewardType::COIN->value);
        $this->assertNotNull($stageAlwaysClearReward);
        $this->assertEquals(1000, $stageAlwaysClearReward->getAmount());
        /** @var \App\Domain\Resource\Entities\Rewards\StageAlwaysClearReward|null $stageAlwaysClearReward */
        $stageAlwaysClearReward = $stageAlwaysClearRewards->get(RewardType::EXP->value);
        $this->assertNotNull($stageAlwaysClearReward);
        $this->assertEquals(1, $stageAlwaysClearReward->getAmount());

        $stageSpeedAttackClearRewards = $response->stageSpeedAttackClearRewards->keyBy(function ($entity) {
            /** @var \App\Domain\Resource\Entities\Rewards\StageSpeedAttackClearReward $entity */
            return $entity->getResourceId();
        });
        $this->assertCount(2, $stageSpeedAttackClearRewards);
        /** @var \App\Domain\Resource\Entities\Rewards\StageSpeedAttackClearReward|null $stageSpeedAttackClearReward */
        $stageSpeedAttackClearReward = $stageSpeedAttackClearRewards->get('item2');
        $this->assertNotNull($stageSpeedAttackClearReward);
        $this->assertEquals(200, $stageSpeedAttackClearReward->getAmount());
        /** @var \App\Domain\Resource\Entities\Rewards\StageSpeedAttackClearReward|null $stageSpeedAttackClearReward */
        $stageSpeedAttackClearReward = $stageSpeedAttackClearRewards->get('item3');
        $this->assertNotNull($stageSpeedAttackClearReward);
        $this->assertEquals(300, $stageSpeedAttackClearReward->getAmount());

        // DB確認
        $usrUserParameter->refresh();
        $this->assertEquals(1, $usrUserParameter->getLevel());
        $this->assertEquals(0 + 1, $usrUserParameter->getExp());
        $this->assertEquals(100 + 1000, $usrUserParameter->getCoin());

        $usrItems = UsrItem::query()
            ->where('usr_user_id', $usrUserId)
            ->get()
            ->keyBy(function ($model) {
                /** @var \App\Domain\Item\Models\Eloquent\UsrItem $entity */
                return $model->getMstItemId();
            });
        $this->assertCount(3, $usrItems);
        /** @var \App\Domain\Item\Models\Eloquent\UsrItem|null $usrItem */
        $usrItem = $usrItems->get('item1');
        $this->assertNotNull($usrItem);
        $this->assertEquals(10 + 0, $usrItem->getAmount());
        /** @var \App\Domain\Item\Models\Eloquent\UsrItem|null $usrItem */
        $usrItem = $usrItems->get('item2');
        $this->assertNotNull($usrItem);
        $this->assertEquals(20 + 200, $usrItem->getAmount());
        /** @var \App\Domain\Item\Models\Eloquent\UsrItem|null $usrItem */
        $usrItem = $usrItems->get('item3');
        $this->assertNotNull($usrItem);
        $this->assertEquals(30 + 300, $usrItem->getAmount());

        $usrStageEvents = UsrStageEvent::query()->where('usr_user_id', $usrUserId)->first();
        $this->assertEquals(20000, $usrStageEvents->getClearTimeMs());
        $this->assertEquals(20000, $usrStageEvents->getResetClearTimeMs());
    }

    public function test_既に一部報酬を受け取っている状態のスピードアタッククリアした場合()
    {
        // Setup
        $now = $this->fixTime();
        $usrUserId = $this->createUsrUser()->getUsrUserId();
        $currentUser = new CurrentUser($usrUserId);
        $usrUserParameter = UsrUserParameter::factory()->create([
            'usr_user_id' => $usrUserId,
            'level' => 1,
            'exp' => 0,
            'coin' => 100,
            'stamina' => 10,
        ]);
        $this->createTestDataSpeedAttack($usrUserId, $now);
        UsrStageEvent::factory()->create([
            'usr_user_id' => $usrUserId,
            'mst_stage_id' => 'mstStageId',
            'clear_count' => 1,
            'reset_clear_count' => 1,
            'reset_ad_challenge_count' => 1,
            'reset_clear_time_ms' => 20000,
            'clear_time_ms' => 20000,
            'latest_reset_at' => now(),
            'latest_event_setting_end_at' => $now->addDays(1)->toDateTimeString(),
        ]);

        // Exercise
        $response = $this->useCase->exec(
            $currentUser,
            UserConstant::PLATFORM_IOS,
            'mstStageId',
            [
                'defeatEnemyCount' => 50,
                'defeatBossEnemyCount' => 2,
                'score' => 999,
                'clearTimeMs' => 10000,
            ]
        );

        // Verify
        $stageAlwaysClearRewards = $response->stageAlwaysClearRewards->keyBy(function ($entity) {
            /** @var \App\Domain\Resource\Entities\Rewards\StageAlwaysClearReward $entity */
            return $entity->getType();
        });
        /** @var \App\Domain\Resource\Entities\Rewards\StageAlwaysClearReward|null $stageAlwaysClearReward */
        $stageAlwaysClearReward = $stageAlwaysClearRewards->get(RewardType::COIN->value);
        $this->assertNotNull($stageAlwaysClearReward);
        $this->assertEquals(1000, $stageAlwaysClearReward->getAmount());
        /** @var \App\Domain\Resource\Entities\Rewards\StageAlwaysClearReward|null $stageAlwaysClearReward */
        $stageAlwaysClearReward = $stageAlwaysClearRewards->get(RewardType::EXP->value);
        $this->assertNotNull($stageAlwaysClearReward);
        $this->assertEquals(1, $stageAlwaysClearReward->getAmount());

        $stageSpeedAttackClearRewards = $response->stageSpeedAttackClearRewards->keyBy(function ($entity) {
            /** @var \App\Domain\Resource\Entities\Rewards\StageSpeedAttackClearReward $entity */
            return $entity->getResourceId();
        });
        $this->assertCount(1, $stageSpeedAttackClearRewards);
        /** @var \App\Domain\Resource\Entities\Rewards\StageSpeedAttackClearReward|null $stageSpeedAttackClearReward */
        $stageSpeedAttackClearReward = $stageSpeedAttackClearRewards->get('item1');
        $this->assertNotNull($stageSpeedAttackClearReward);
        $this->assertEquals(100, $stageSpeedAttackClearReward->getAmount());

        // DB確認
        $usrUserParameter->refresh();
        $this->assertEquals(1, $usrUserParameter->getLevel());
        $this->assertEquals(0 + 1, $usrUserParameter->getExp());
        $this->assertEquals(100 + 1000, $usrUserParameter->getCoin());

        $usrItems = UsrItem::query()
            ->where('usr_user_id', $usrUserId)
            ->get()
            ->keyBy(function ($model) {
                /** @var \App\Domain\Item\Models\Eloquent\UsrItem $entity */
                return $model->getMstItemId();
            });
        $this->assertCount(3, $usrItems);
        /** @var \App\Domain\Item\Models\Eloquent\UsrItem|null $usrItem */
        $usrItem = $usrItems->get('item1');
        $this->assertNotNull($usrItem);
        $this->assertEquals(10 + 100, $usrItem->getAmount());
        /** @var \App\Domain\Item\Models\Eloquent\UsrItem|null $usrItem */
        $usrItem = $usrItems->get('item2');
        $this->assertNotNull($usrItem);
        $this->assertEquals(20 + 0, $usrItem->getAmount());
        /** @var \App\Domain\Item\Models\Eloquent\UsrItem|null $usrItem */
        $usrItem = $usrItems->get('item3');
        $this->assertNotNull($usrItem);
        $this->assertEquals(30 + 0, $usrItem->getAmount());
    }

    public function test_復刻したスピードアタックをクリアした場合()
    {
        // Setup
        $now = $this->fixTime();
        $usrUserId = $this->createUsrUser()->getUsrUserId();
        $currentUser = new CurrentUser($usrUserId);
        $usrUserParameter = UsrUserParameter::factory()->create([
            'usr_user_id' => $usrUserId,
            'level' => 1,
            'exp' => 0,
            'coin' => 100,
            'stamina' => 10,
        ]);
        $this->createTestDataSpeedAttack($usrUserId, $now);
        UsrStageEvent::factory()->create([
            'usr_user_id' => $usrUserId,
            'mst_stage_id' => 'mstStageId',
            'clear_count' => 1,
            'reset_clear_count' => 1,
            'reset_ad_challenge_count' => 1,
            'reset_clear_time_ms' => 20000,
            'clear_time_ms' => 20000,
            'latest_reset_at' => now(),
            'latest_event_setting_end_at' => $now->subDays(2)->toDateTimeString(),
        ]);

        // Exercise
        $response = $this->useCase->exec(
            $currentUser,
            UserConstant::PLATFORM_IOS,
            'mstStageId',
            [
                'defeatEnemyCount' => 50,
                'defeatBossEnemyCount' => 2,
                'score' => 999,
                'clearTimeMs' => 10000,
            ]
        );

        // Verify
        $stageAlwaysClearRewards = $response->stageAlwaysClearRewards->keyBy(function ($entity) {
            /** @var \App\Domain\Resource\Entities\Rewards\StageAlwaysClearReward $entity */
            return $entity->getType();
        });
        /** @var \App\Domain\Resource\Entities\Rewards\StageAlwaysClearReward|null $stageAlwaysClearReward */
        $stageAlwaysClearReward = $stageAlwaysClearRewards->get(RewardType::COIN->value);
        $this->assertNotNull($stageAlwaysClearReward);
        $this->assertEquals(1000, $stageAlwaysClearReward->getAmount());
        /** @var \App\Domain\Resource\Entities\Rewards\StageAlwaysClearReward|null $stageAlwaysClearReward */
        $stageAlwaysClearReward = $stageAlwaysClearRewards->get(RewardType::EXP->value);
        $this->assertNotNull($stageAlwaysClearReward);
        $this->assertEquals(1, $stageAlwaysClearReward->getAmount());

        $stageSpeedAttackClearRewards = $response->stageSpeedAttackClearRewards->keyBy(function ($entity) {
            /** @var \App\Domain\Resource\Entities\Rewards\StageSpeedAttackClearReward $entity */
            return $entity->getResourceId();
        });
        $this->assertCount(3, $stageSpeedAttackClearRewards);
        /** @var \App\Domain\Resource\Entities\Rewards\StageSpeedAttackClearReward|null $stageSpeedAttackClearReward */
        $stageSpeedAttackClearReward = $stageSpeedAttackClearRewards->get('item1');
        $this->assertNotNull($stageSpeedAttackClearReward);
        $this->assertEquals(100, $stageSpeedAttackClearReward->getAmount());
        /** @var \App\Domain\Resource\Entities\Rewards\StageSpeedAttackClearReward|null $stageSpeedAttackClearReward */
        $stageSpeedAttackClearReward = $stageSpeedAttackClearRewards->get('item2');
        $this->assertNotNull($stageSpeedAttackClearReward);
        $this->assertEquals(200, $stageSpeedAttackClearReward->getAmount());
        /** @var \App\Domain\Resource\Entities\Rewards\StageSpeedAttackClearReward|null $stageSpeedAttackClearReward */
        $stageSpeedAttackClearReward = $stageSpeedAttackClearRewards->get('item3');
        $this->assertNotNull($stageSpeedAttackClearReward);
        $this->assertEquals(300, $stageSpeedAttackClearReward->getAmount());

        // DB確認
        $usrUserParameter->refresh();
        $this->assertEquals(1, $usrUserParameter->getLevel());
        $this->assertEquals(0 + 1, $usrUserParameter->getExp());
        $this->assertEquals(100 + 1000, $usrUserParameter->getCoin());

        $usrItems = UsrItem::query()
            ->where('usr_user_id', $usrUserId)
            ->get()
            ->keyBy(function ($model) {
                /** @var \App\Domain\Item\Models\Eloquent\UsrItem $entity */
                return $model->getMstItemId();
            });
        $this->assertCount(3, $usrItems);
        /** @var \App\Domain\Item\Models\Eloquent\UsrItem|null $usrItem */
        $usrItem = $usrItems->get('item1');
        $this->assertNotNull($usrItem);
        $this->assertEquals(10 + 100, $usrItem->getAmount());
        /** @var \App\Domain\Item\Models\Eloquent\UsrItem|null $usrItem */
        $usrItem = $usrItems->get('item2');
        $this->assertNotNull($usrItem);
        $this->assertEquals(20 + 200, $usrItem->getAmount());
        /** @var \App\Domain\Item\Models\Eloquent\UsrItem|null $usrItem */
        $usrItem = $usrItems->get('item3');
        $this->assertNotNull($usrItem);
        $this->assertEquals(30 + 300, $usrItem->getAmount());
    }

    private function verifyResponse(StageEndResultData $response)
    {
        $jsonResponse = $this->responseFactory->createEndResponse($response);
        $this->assertTrue($jsonResponse->isSuccessful());

        // レスポンス確認
        $response = $jsonResponse->getData();
        $stageRewards = collect($response->stageRewards);
        $this->assertNotNull($stageRewards);
        $this->assertCount(4, $stageRewards);

        $reward = $stageRewards->get(0);
        $this->assertEquals(StageRewardCategory::ALWAYS->value, $reward->rewardCategory);
        $reward = $reward->reward;
        $this->assertEquals(RewardType::COIN->value, $reward->resourceType);
        $this->assertEquals(1000, $reward->resourceAmount);

        $reward = $stageRewards->get(1);
        $this->assertEquals(StageRewardCategory::ALWAYS->value, $reward->rewardCategory);
        $reward = $reward->reward;
        $this->assertEquals(RewardType::EXP->value, $reward->resourceType);
        $this->assertEquals(1, $reward->resourceAmount);

        $reward = $stageRewards->get(2);
        $this->assertEquals(StageRewardCategory::ALWAYS->value, $reward->rewardCategory);
        $reward = $reward->reward;
        $this->assertEquals(RewardType::UNIT->value, $reward->resourceType);
        $this->assertEquals('unit1', $reward->resourceId);
        $this->assertEquals(1, $reward->resourceAmount);

        $reward = $stageRewards->get(3);
        $this->assertEquals(StageRewardCategory::RANDOM->value, $reward->rewardCategory);
        $reward = $reward->reward;
        $this->assertEquals(RewardType::COIN->value, $reward->resourceType);
        $this->assertEquals(1000, $reward->resourceAmount);

        // TODO: ユーザーレベルアップ報酬情報の確認も
        $userLevelUpRewards = $response->userLevel;
        $this->assertNotNull($userLevelUpRewards);
        $this->assertEquals(0, $userLevelUpRewards->beforeExp);
        $this->assertEquals(1, $userLevelUpRewards->afterExp);
        $this->assertCount(0, $userLevelUpRewards->usrLevelReward);
    }

    private function verifyEventResponse(StageEndResultData $response)
    {
        $jsonResponse = $this->responseFactory->createEndResponse($response);
        $this->assertTrue($jsonResponse->isSuccessful());

        // レスポンス確認
        $response = $jsonResponse->getData();
        $stageRewards = collect($response->stageRewards);
        $this->assertNotNull($stageRewards);
        // 元々の報酬の数は3つだが、always報酬は個数をまとめているので2つになる
        $this->assertCount(3, $stageRewards);

        $reward = $stageRewards->get(0);
        $this->assertEquals(StageRewardCategory::ALWAYS->value, $reward->rewardCategory);
        $reward = $reward->reward;
        $this->assertEquals(RewardType::COIN->value, $reward->resourceType);
        $this->assertEquals(1600, $reward->resourceAmount);

        $reward = $stageRewards->get(1);
        $this->assertEquals(StageRewardCategory::ALWAYS->value, $reward->rewardCategory);
        $reward = $reward->reward;
        $this->assertEquals(RewardType::EXP->value, $reward->resourceType);
        $this->assertEquals(1, $reward->resourceAmount);

        $reward = $stageRewards->get(2);
        $this->assertEquals(StageRewardCategory::RANDOM->value, $reward->rewardCategory);
        $reward = $reward->reward;
        $this->assertEquals(RewardType::COIN->value, $reward->resourceType);
        $this->assertEquals(500, $reward->resourceAmount);

        // TODO: ユーザーレベルアップ報酬情報の確認も
        $userLevelUpRewards = $response->userLevel;
        $this->assertNotNull($userLevelUpRewards);
        $this->assertEquals(0, $userLevelUpRewards->beforeExp);
        $this->assertEquals(1, $userLevelUpRewards->afterExp);
        $this->assertCount(0, $userLevelUpRewards->usrLevelReward);
    }

    private function createTestData(string $usrUserId, string $mstStageId)
    {
        UsrStageSession::factory()->create([
            'usr_user_id' => $usrUserId,
            'mst_stage_id' => $mstStageId,
            'is_valid' => 1,
        ]);

        MstItem::factory()->create([
            'id' => 'item1',
        ]);

        MstUnit::factory()->create([
            'id' => 'unit1',
            'fragment_mst_item_id' => 'item1',
        ]);

        MstUnitFragmentConvert::factory()->create([
            'unit_label' => 'DropR',
            'convert_amount' => 10,
        ]);

        MstEmblem::factory()->createMany([
            [
                'id' => 'emblem1',
            ],
            [
                'id' => 'emblem2',
            ],
        ]);

        MstUserLevel::factory()->createMany([
            ['level' => 1, 'stamina' => 10, 'exp' => 0],
            ['level' => 2, 'stamina' => 10, 'exp' => 100],
            ['level' => 3, 'stamina' => 10, 'exp' => 1000],
        ]);
        MstUserLevelBonus::factory()->create([
            'level' => 3,
            'mst_user_level_bonus_group_id' => '2',
        ]);
        MstUserLevelBonusGroup::factory()->createMany([
            [
                'mst_user_level_bonus_group_id' => '2',
                'resource_type' => RewardType::ITEM->value,
                'resource_id' => 'item1',
                'resource_amount' => 20,
            ],
            [
                'mst_user_level_bonus_group_id' => '2',
                'resource_type' => RewardType::EMBLEM->value,
                'resource_id' => 'emblem2',
                'resource_amount' => 1,
            ],
        ]);
        MstStageReward::factory()->createMany([
            [
                'mst_stage_id' => $mstStageId,
                'reward_category' => StageRewardCategory::FIRST_CLEAR,
                'resource_type' => RewardType::FREE_DIAMOND->value,
                'resource_id' => null,
                'resource_amount' => 10,
                'percentage' => 100,
            ],
            [
                'mst_stage_id' => $mstStageId,
                'reward_category' => StageRewardCategory::FIRST_CLEAR,
                'resource_type' => RewardType::EMBLEM->value,
                'resource_id' => 'emblem1',
                'resource_amount' => 1,
                'percentage' => 100,
            ],
            [
                'mst_stage_id' => $mstStageId,
                'reward_category' => StageRewardCategory::FIRST_CLEAR,
                'resource_type' => RewardType::EMBLEM->value,
                'resource_id' => 'emblem1',
                'resource_amount' => 1,
                'percentage' => 100,
            ],
            [
                'mst_stage_id' => $mstStageId,
                'reward_category' => StageRewardCategory::FIRST_CLEAR,
                'resource_type' => RewardType::UNIT->value,
                'resource_id' => 'unit1',
                'resource_amount' => 1,
                'percentage' => 100,
            ],
            [
                'mst_stage_id' => $mstStageId,
                'reward_category' => StageRewardCategory::FIRST_CLEAR,
                'resource_type' => RewardType::UNIT->value,
                'resource_id' => 'unit1',
                'resource_amount' => 1,
                'percentage' => 100,
            ],
            [
                'mst_stage_id' => $mstStageId,
                'reward_category' => StageRewardCategory::ALWAYS,
                'resource_type' => RewardType::UNIT->value,
                'resource_id' => 'unit1',
                'resource_amount' => 1,
                'percentage' => 100,
            ],
            [
                'mst_stage_id' => $mstStageId,
                'reward_category' => StageRewardCategory::RANDOM,
                'resource_type' => RewardType::COIN->value,
                'resource_id' => null,
                'resource_amount' => 1000,
                'percentage' => 100,
            ],
            [
                'mst_stage_id' => $mstStageId,
                'reward_category' => StageRewardCategory::RANDOM,
                'resource_type' => RewardType::COIN->value,
                'resource_id' => null,
                'resource_amount' => 20000,
                'percentage' => 0,
            ],
        ]);
        MstStageEventReward::factory()->createMany([
            [
                'mst_stage_id' => $mstStageId,
                'reward_category' => StageRewardCategory::FIRST_CLEAR,
                'resource_type' => RewardType::FREE_DIAMOND->value,
                'resource_id' => null,
                'resource_amount' => 20,
                'percentage' => 100,
            ],
            [
                'mst_stage_id' => $mstStageId,
                'reward_category' => StageRewardCategory::FIRST_CLEAR,
                'resource_type' => RewardType::EMBLEM->value,
                'resource_id' => 'emblem1',
                'resource_amount' => 1,
                'percentage' => 0,
            ],
            [
                'mst_stage_id' => $mstStageId,
                'reward_category' => StageRewardCategory::FIRST_CLEAR,
                'resource_type' => RewardType::EMBLEM->value,
                'resource_id' => 'emblem1',
                'resource_amount' => 1,
                'percentage' => 50,
            ],
            [
                'mst_stage_id' => $mstStageId,
                'reward_category' => StageRewardCategory::ALWAYS,
                'resource_type' => RewardType::COIN->value,
                'resource_id' => null,
                'resource_amount' => 300,
                'percentage' => 100,
            ],
            [
                'mst_stage_id' => $mstStageId,
                'reward_category' => StageRewardCategory::ALWAYS,
                'resource_type' => RewardType::COIN->value,
                'resource_id' => null,
                'resource_amount' => 200,
                'percentage' => 100,
            ],
            [
                'mst_stage_id' => $mstStageId,
                'reward_category' => StageRewardCategory::ALWAYS,
                'resource_type' => RewardType::COIN->value,
                'resource_id' => null,
                'resource_amount' => 100,
                'percentage' => 0,
            ],
            [
                'mst_stage_id' => $mstStageId,
                'reward_category' => StageRewardCategory::RANDOM,
                'resource_type' => RewardType::COIN->value,
                'resource_id' => null,
                'resource_amount' => 500,
                'percentage' => 100,
            ],
            [
                'mst_stage_id' => $mstStageId,
                'reward_category' => StageRewardCategory::RANDOM,
                'resource_type' => RewardType::COIN->value,
                'resource_id' => null,
                'resource_amount' => 10000,
                'percentage' => 0,
            ],
        ]);
    }

    private function createTestDataSpeedAttack(string $usrUserId, CarbonImmutable $now)
    {
        MstQuest::factory()->create([
            'id' => 'mstQuestId',
            'quest_type' => 'Event',
            'start_date' => '2023-01-01 00:00:00',
            'end_date' => '2037-01-01 00:00:00',
        ]);
        MstStage::factory()->create([
            'id' => 'mstStageId',
            'mst_quest_id' => 'mstQuestId',
            'exp' => 1,
            'coin' => 1000,
        ]);
        MstStageEventSetting::factory()->create([
            'mst_stage_id' => 'mstStageId',
            'start_at' => $now->subDays(1)->toDateTimeString(),
            'end_at' => $now->addDays(1)->toDateTimeString(),
        ]);
        MstInGameSpecialRule::factory()->createMany([
            [
                'content_type' => InGameContentType::STAGE,
                'target_id' => 'mstStageId',
                'rule_type' => InGameSpecialRuleType::SPEED_ATTACK,
                'start_at' => $now->subDays(1)->toDateTimeString(),
                'end_at' => $now->addDays(1)->toDateTimeString(),
            ],
        ]);
        MstStageClearTimeReward::factory()->createMany([
            [
                'mst_stage_id' => 'mstStageId',
                'upper_clear_time_ms' => 10000,
                'resource_type' => 'Item',
                'resource_id' => 'item1',
                'resource_amount' => 100,
            ],
            [
                'mst_stage_id' => 'mstStageId',
                'upper_clear_time_ms' => 20000,
                'resource_type' => 'Item',
                'resource_id' => 'item2',
                'resource_amount' => 200,
            ],
            [
                'mst_stage_id' => 'mstStageId',
                'upper_clear_time_ms' => 30000,
                'resource_type' => 'Item',
                'resource_id' => 'item3',
                'resource_amount' => 300,
            ],
        ]);
        MstItem::factory()->createMany([
            ['id' => 'item1'],
            ['id' => 'item2'],
            ['id' => 'item3'],
        ]);
        UsrItem::factory()->createMany([
            [
                'usr_user_id' => $usrUserId,
                'mst_item_id' => 'item1',
                'amount' => 10,
            ],
            [
                'usr_user_id' => $usrUserId,
                'mst_item_id' => 'item2',
                'amount' => 20,
            ],
            [
                'usr_user_id' => $usrUserId,
                'mst_item_id' => 'item3',
                'amount' => 30,
            ],
        ]);
        MstUserLevel::factory()->createMany([
            ['level' => 1, 'stamina' => 10, 'exp' => 0],
            ['level' => 2, 'stamina' => 10, 'exp' => 100],
            ['level' => 3, 'stamina' => 10, 'exp' => 1000],
        ]);
        UsrStageSession::factory()->create([
            'usr_user_id' => $usrUserId,
            'mst_stage_id' => 'mstStageId',
            'is_valid' => 1,
        ]);
    }
}
