<?php

namespace App\Http\Resources\Api\Operationdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class OprGachaResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_gachaType = 'gachaType';
    protected const C_upperGroup = 'upperGroup';
    protected const C_enableAdPlay = 'enableAdPlay';
    protected const C_adPlayIntervalTime = 'adPlayIntervalTime';
    protected const C_multiDrawCount = 'multiDrawCount';
    protected const C_multiFixedPrizeCount = 'multiFixedPrizeCount';
    protected const C_startAt = 'startAt';
    protected const C_endAt = 'endAt';
    protected const C_dailyPlayLimitCount = 'dailyPlayLimitCount';
    protected const C_totalPlayLimitCount = 'totalPlayLimitCount';
    protected const C_dailyAdLimitCount = 'dailyAdLimitCount';
    protected const C_totalAdLimitCount = 'totalAdLimitCount';
    protected const C_appearanceCondition = 'appearanceCondition';
    protected const C_unlockConditionType = 'unlockConditionType';
    protected const C_unlockDurationHours = 'unlockDurationHours';
    protected const C_displayInformationId = 'displayInformationId';
    protected const C_displayGachaCautionId = 'displayGachaCautionId';
    protected const C_gachaPriority = 'gachaPriority';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->gachaType = $data['gachaType'];
            $this->upperGroup = $data['upperGroup'];
            $this->enableAdPlay = $data['enableAdPlay'];
            $this->adPlayIntervalTime = $data['adPlayIntervalTime'];
            $this->multiDrawCount = $data['multiDrawCount'];
            $this->multiFixedPrizeCount = $data['multiFixedPrizeCount'];
            $this->startAt = $data['startAt'];
            $this->endAt = $data['endAt'];
            $this->dailyPlayLimitCount = $data['dailyPlayLimitCount'];
            $this->totalPlayLimitCount = $data['totalPlayLimitCount'];
            $this->dailyAdLimitCount = $data['dailyAdLimitCount'];
            $this->totalAdLimitCount = $data['totalAdLimitCount'];
            $this->appearanceCondition = $data['appearanceCondition'];
            $this->unlockConditionType = $data['unlockConditionType'];
            $this->unlockDurationHours = $data['unlockDurationHours'];
            $this->displayInformationId = $data['displayInformationId'];
            $this->displayGachaCautionId = $data['displayGachaCautionId'];
            $this->gachaPriority = $data['gachaPriority'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'gachaType' => 'string',
        'upperGroup' => 'string',
        'enableAdPlay' => 'string',
        'adPlayIntervalTime' => 'int|null',
        'multiDrawCount' => 'int',
        'multiFixedPrizeCount' => 'int|null',
        'startAt' => 'string',
        'endAt' => 'string',
        'dailyPlayLimitCount' => 'int|null',
        'totalPlayLimitCount' => 'int|null',
        'dailyAdLimitCount' => 'int|null',
        'totalAdLimitCount' => 'int|null',
        'appearanceCondition' => 'string',
        'unlockConditionType' => 'string',
        'unlockDurationHours' => 'int|null',
        'displayInformationId' => 'string',
        'displayGachaCautionId' => 'string',
        'gachaPriority' => 'int',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'gachaType' => 'gacha_type',
        'upperGroup' => 'upper_group',
        'enableAdPlay' => 'enable_ad_play',
        'adPlayIntervalTime' => 'ad_play_interval_time',
        'multiDrawCount' => 'multi_draw_count',
        'multiFixedPrizeCount' => 'multi_fixed_prize_count',
        'startAt' => 'start_at',
        'endAt' => 'end_at',
        'dailyPlayLimitCount' => 'daily_play_limit_count',
        'totalPlayLimitCount' => 'total_play_limit_count',
        'dailyAdLimitCount' => 'daily_ad_limit_count',
        'totalAdLimitCount' => 'total_ad_limit_count',
        'appearanceCondition' => 'appearance_condition',
        'unlockConditionType' => 'unlock_condition_type',
        'unlockDurationHours' => 'unlock_duration_hours',
        'displayInformationId' => 'display_information_id',
        'displayGachaCautionId' => 'display_gacha_caution_id',
        'gachaPriority' => 'gacha_priority',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $gachaType;

    /** @var string */
    protected $upperGroup;

    /** @var string */
    protected $enableAdPlay;

    /** @var int|null */
    protected $adPlayIntervalTime;

    /** @var int */
    protected $multiDrawCount;

    /** @var int|null */
    protected $multiFixedPrizeCount;

    /** @var string */
    protected $startAt;

    /** @var string */
    protected $endAt;

    /** @var int|null */
    protected $dailyPlayLimitCount;

    /** @var int|null */
    protected $totalPlayLimitCount;

    /** @var int|null */
    protected $dailyAdLimitCount;

    /** @var int|null */
    protected $totalAdLimitCount;

    /** @var string */
    protected $appearanceCondition;

    /** @var string */
    protected $unlockConditionType;

    /** @var int|null */
    protected $unlockDurationHours;

    /** @var string */
    protected $displayInformationId;

    /** @var string */
    protected $displayGachaCautionId;

    /** @var int */
    protected $gachaPriority;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'gachaType' => $this->gachaType,
            'upperGroup' => $this->upperGroup,
            'enableAdPlay' => $this->enableAdPlay,
            'adPlayIntervalTime' => $this->adPlayIntervalTime,
            'multiDrawCount' => $this->multiDrawCount,
            'multiFixedPrizeCount' => $this->multiFixedPrizeCount,
            'startAt' => $this->startAt,
            'endAt' => $this->endAt,
            'dailyPlayLimitCount' => $this->dailyPlayLimitCount,
            'totalPlayLimitCount' => $this->totalPlayLimitCount,
            'dailyAdLimitCount' => $this->dailyAdLimitCount,
            'totalAdLimitCount' => $this->totalAdLimitCount,
            'appearanceCondition' => $this->appearanceCondition,
            'unlockConditionType' => $this->unlockConditionType,
            'unlockDurationHours' => $this->unlockDurationHours,
            'displayInformationId' => $this->displayInformationId,
            'displayGachaCautionId' => $this->displayGachaCautionId,
            'gachaPriority' => $this->gachaPriority,
        ];
    }
}
