<?php

namespace App\Http\Resources\Api\Operationdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class OprGachaUseResourceResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_oprGachaId = 'oprGachaId';
    protected const C_costType = 'costType';
    protected const C_costId = 'costId';
    protected const C_costNum = 'costNum';
    protected const C_drawCount = 'drawCount';
    protected const C_costPriority = 'costPriority';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->oprGachaId = $data['oprGachaId'];
            $this->costType = $data['costType'];
            $this->costId = $data['costId'];
            $this->costNum = $data['costNum'];
            $this->drawCount = $data['drawCount'];
            $this->costPriority = $data['costPriority'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'oprGachaId' => 'string',
        'costType' => 'string',
        'costId' => 'string',
        'costNum' => 'int',
        'drawCount' => 'int',
        'costPriority' => 'int',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'oprGachaId' => 'opr_gacha_id',
        'costType' => 'cost_type',
        'costId' => 'cost_id',
        'costNum' => 'cost_num',
        'drawCount' => 'draw_count',
        'costPriority' => 'cost_priority',
    ];

    /** @var string */
    protected $oprGachaId;

    /** @var string */
    protected $costType;

    /** @var string */
    protected $costId;

    /** @var int */
    protected $costNum;

    /** @var int */
    protected $drawCount;

    /** @var int */
    protected $costPriority;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'oprGachaId' => $this->oprGachaId,
            'costType' => $this->costType,
            'costId' => $this->costId,
            'costNum' => $this->costNum,
            'drawCount' => $this->drawCount,
            'costPriority' => $this->costPriority,
        ];
    }
}
