<?php

namespace App\Http\Resources\Api\Operationdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class OprProductResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_mstStoreProductId = 'mstStoreProductId';
    protected const C_productType = 'productType';
    protected const C_purchasableCount = 'purchasableCount';
    protected const C_paidAmount = 'paidAmount';
    protected const C_displayPriority = 'displayPriority';
    protected const C_startDate = 'startDate';
    protected const C_endDate = 'endDate';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->mstStoreProductId = $data['mstStoreProductId'];
            $this->productType = $data['productType'];
            $this->purchasableCount = $data['purchasableCount'];
            $this->paidAmount = $data['paidAmount'];
            $this->displayPriority = $data['displayPriority'];
            $this->startDate = $data['startDate'];
            $this->endDate = $data['endDate'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'mstStoreProductId' => 'string',
        'productType' => 'string',
        'purchasableCount' => 'int|null',
        'paidAmount' => 'int',
        'displayPriority' => 'int',
        'startDate' => 'string',
        'endDate' => 'string',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'mstStoreProductId' => 'mst_store_product_id',
        'productType' => 'product_type',
        'purchasableCount' => 'purchasable_count',
        'paidAmount' => 'paid_amount',
        'displayPriority' => 'display_priority',
        'startDate' => 'start_date',
        'endDate' => 'end_date',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $mstStoreProductId;

    /** @var string */
    protected $productType;

    /** @var int|null */
    protected $purchasableCount;

    /** @var int */
    protected $paidAmount;

    /** @var int */
    protected $displayPriority;

    /** @var string */
    protected $startDate;

    /** @var string */
    protected $endDate;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'mstStoreProductId' => $this->mstStoreProductId,
            'productType' => $this->productType,
            'purchasableCount' => $this->purchasableCount,
            'paidAmount' => $this->paidAmount,
            'displayPriority' => $this->displayPriority,
            'startDate' => $this->startDate,
            'endDate' => $this->endDate,
        ];
    }
}
