<?php

namespace App\Http\Resources\Api\Operationdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class OprStepUpGachaResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_oprGachaId = 'oprGachaId';
    protected const C_maxStepNumber = 'maxStepNumber';
    protected const C_maxLoopCount = 'maxLoopCount';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->oprGachaId = $data['oprGachaId'];
            $this->maxStepNumber = $data['maxStepNumber'];
            $this->maxLoopCount = $data['maxLoopCount'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'oprGachaId' => 'string',
        'maxStepNumber' => 'int',
        'maxLoopCount' => 'int|null',
    ];

    public string $id;
    public string $oprGachaId;
    public int $maxStepNumber;
    public ?int $maxLoopCount;

    /**
     * @return array<mixed>
     */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'oprGachaId' => $this->oprGachaId,
            'maxStepNumber' => $this->maxStepNumber,
            'maxLoopCount' => $this->maxLoopCount,
        ];
    }
}
