<?php

namespace App\Http\Resources\Api\Operationdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class OprStepUpGachaStepResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_oprGachaId = 'oprGachaId';
    protected const C_stepNumber = 'stepNumber';
    protected const C_costType = 'costType';
    protected const C_costId = 'costId';
    protected const C_costNum = 'costNum';
    protected const C_drawCount = 'drawCount';
    protected const C_fixedPrizeCount = 'fixedPrizeCount';
    protected const C_fixedPrizeRarityThresholdType = 'fixedPrizeRarityThresholdType';
    protected const C_prizeGroupId = 'prizeGroupId';
    protected const C_fixedPrizeGroupId = 'fixedPrizeGroupId';
    protected const C_isFirstFree = 'isFirstFree';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->oprGachaId = $data['oprGachaId'];
            $this->stepNumber = $data['stepNumber'];
            $this->costType = $data['costType'];
            $this->costId = $data['costId'];
            $this->costNum = $data['costNum'];
            $this->drawCount = $data['drawCount'];
            $this->fixedPrizeCount = $data['fixedPrizeCount'];
            $this->fixedPrizeRarityThresholdType = $data['fixedPrizeRarityThresholdType'];
            $this->prizeGroupId = $data['prizeGroupId'];
            $this->fixedPrizeGroupId = $data['fixedPrizeGroupId'];
            $this->isFirstFree = $data['isFirstFree'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'oprGachaId' => 'string',
        'stepNumber' => 'int',
        'costType' => 'string',
        'costId' => 'string|null',
        'costNum' => 'int',
        'drawCount' => 'int',
        'fixedPrizeCount' => 'int',
        'fixedPrizeRarityThresholdType' => 'string|null',
        'prizeGroupId' => 'string|null',
        'fixedPrizeGroupId' => 'string|null',
        'isFirstFree' => 'string',
    ];

    public string $id;
    public string $oprGachaId;
    public int $stepNumber;
    public string $costType;
    public ?string $costId;
    public int $costNum;
    public int $drawCount;
    public int $fixedPrizeCount;
    public ?string $fixedPrizeRarityThresholdType;
    public ?string $prizeGroupId;
    public ?string $fixedPrizeGroupId;
    public string $isFirstFree;

    /**
     * @return array<mixed>
     */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'oprGachaId' => $this->oprGachaId,
            'stepNumber' => $this->stepNumber,
            'costType' => $this->costType,
            'costId' => $this->costId,
            'costNum' => $this->costNum,
            'drawCount' => $this->drawCount,
            'fixedPrizeCount' => $this->fixedPrizeCount,
            'fixedPrizeRarityThresholdType' => $this->fixedPrizeRarityThresholdType,
            'prizeGroupId' => $this->prizeGroupId,
            'fixedPrizeGroupId' => $this->fixedPrizeGroupId,
            'isFirstFree' => $this->isFirstFree,
        ];
    }
}
