// ReSharper disable InconsistentNaming
// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Domain.Constants
{
    public enum AutoPlayerSequenceActionType
    {
        None,
        SummonEnemy,
        SummonPlayerCharacter,
        SwitchSequenceGroup,
        PlayerSpecialAttack,
        SummonPlayerSpecialCharacter,
        SummonGimmickObject,
        TransformGimmickObjectToEnemy,
        OpponentRush,
    }
}
