// ReSharper disable InconsistentNaming
// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Domain.Constants 
{
    public enum CharacterUnitRoleType 
    {
        None,
        Attack,
        Balance,
        Defense,
        Support,
        Unique,
        Technical,
        Special,
    }
}
