// ReSharper disable InconsistentNaming
// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Domain.Constants
{
    public enum ExchangeTradeType
    {
        NormalExchangeTrade,
        PvpExchangeTrade,
        EventExchangeTrade,
        CharacterFragmentExchangeTrade,
    }
}
