// ReSharper disable InconsistentNaming
// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Domain.Constants
{
    public enum GachaType
    {
        Normal,
        Premium,
        Pickup,
        Free,
        Festival,
        Ticket,
        PaidOnly,
        Medal,
        Tutorial,
    }
}
