// ReSharper disable InconsistentNaming
// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Domain.Constants 
{
    public enum KomaEffectType 
    {
        None,
        AttackPowerUp,
        AttackPowerDown,
        MoveSpeedUp,
        SlipDamage,
        Gust,
        Poison,
        Darkness,
        Burn,
        Stun,
        Freeze,
        Weakening,
    }
}
