// ReSharper disable InconsistentNaming
// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

namespace GLOW.Core.Domain.Constants 
{
    public enum UnitAuraType 
    {
        Default,
        Boss,
        AdventBoss1,
        AdventBoss2,
        AdventBoss3,
    }
}
