# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

# CodeRabbit設定ファイル - glow-server プロジェクト
# 最終更新: 2025-12-04
# 公式ドキュメント: https://docs.coderabbit.ai/reference/configuration

language: "ja-JP"
early_access: false
enable_free_tier: true

reviews:
  # レビューの詳細度（chill: 穏やか、assertive: 積極的）
  profile: "chill"

  # ファイル別詳細説明を折りたたむ
  collapse_walkthrough: true

  # レビュー機能
  high_level_summary: true
  review_status: true
  commit_status: true
  poem: false
  request_changes_workflow: false

  # レビュー対象から除外するパス
  path_filters:
    # === 依存関係・生成ファイル ===
    - "!vendor/**"
    - "!node_modules/**"
    - "!public/build/**"
    - "!public/hot"

    # === キャッシュ・一時ファイル ===
    - "!storage/**"
    - "!bootstrap/cache/**"
    - "!**/.phpunit.cache/**"

    # === ロックファイル ===
    - "!**/composer.lock"
    - "!**/package-lock.json"

    # === 設定ファイル（AIツール） ===
    - "!.claude/**"
    - "!.ai-context/**"
    - "!.github/copilot/**"

  # ファイルパス別のレビュー指示
  path_instructions:
    # === 全体共通ルール ===
    - path: "*"
      instructions: |
        ## 全ファイル共通のコーディング規約
        **重要度: 中**

        ### 命名規則
        - [ ] テーブルに関連する変数は、どのDBのテーブルか一目でわかるようにDB接頭辞を含める（例: `$mstItemId`, `$usrUser`, `$logApiRequest`）

    # === テスト関連 ===
    - path: "api/tests/**/*Test.php"
      instructions: |
        ## 必須チェック項目
        **重要度: 小**
        - [ ] テストメソッド名が「test_」接頭辞を使用している（PHPUnitアノテーション禁止）
        - [ ] テストコードがSetup（準備）/Exercise（実行）/Verify（検証）の3段階構成になっている
        - [ ] 時間固定は親クラスTestCaseの`fixTime()`メソッドを使用している
        - [ ] ユーザー作成は親クラスTestCaseの`createUsrUser()`メソッドを使用している

    # === HTTPレイヤー ===
    # Controller
    - path: "api/app/Http/Controllers/**/*.php"
      instructions: |
        ## Controllerのチェック
        **重要度: 高**
        - [ ] リクエストパラメータのバリデーションが実装されている
        - [ ] バリデーションルールがglow-schemaのYAML定義と一致している
        - [ ] レスポンスはResponseFactory/ResponseDataFactoryを使用して返している
        - [ ] ビジネスロジックはUseCase/Serviceに委譲し、Controllerは薄く保っている

    # Middleware
    - path: "api/app/Http/Middleware/**/*.php"
      instructions: |
        ## Middlewareのセキュリティチェック
        **重要度: 高**
        - [ ] 認証・認可ロジックが適切に実装されているか
        - [ ] CSRF保護が有効か
        - [ ] レート制限が設定されているか
        - [ ] エラーハンドリングが適切か

    # ResponseFactory/ResponseDataFactory
    - path: "api/app/Http/Entity/Response/**/*Factory.php"
      instructions: |
        ## APIレスポンス作成の必須チェック
        **重要度: 高**

        ### 時間データ変換
        - [ ] 時間データは必ず`StringUtil::convertToISO8601()`で変換してISO8601形式で返している

        ### レスポンスキー
        - [ ] レスポンスキーがglow-schemaのYAML定義と一致している
        - [ ] ローワーキャメルケース命名規則に従っている

    # === ドメインレイヤー ===
    # Delegator
    - path: "api/app/Domain/**/Delegators/**/*.php"
      instructions: |
        ## Delegatorレイヤーのチェック
        **重要度: 高**
        - [ ] returnの型指定でarray型やCollection型の場合、要素の型を必ず明示している（例: `@return array<MstModelEntity>` や `@return Collection<UsrModelEntity>`）
        - [ ] returnの型は、api/deptrac.yamlのdeptrac.ruleset.Delegatorで許可されている型のみを使用している（CommonEntity、ResourceEntity、MstModelEntity、UsrModelEntity、Wp Billing Entity、Wp Currency Entity）
        - [ ] DomainEntity（ドメイン固有のEntity）やUsrModelInterface（ユーザーモデルインターフェース）をreturnしていない（アーキテクチャ違反）

    # Repository
    - path: "api/app/Domain/**/Repositories/**/*.php"
      instructions: |
        ## Repositoryレイヤーのチェック
        **重要度: 高**
        - [ ] DBアクセスロジックのみを実装し、ビジネスロジックは含めていない
        - [ ] 複雑なクエリにはN+1問題が発生していないか確認
        - [ ] Eloquentモデルではなく、Entity/ModelEntityを返している

    # Service
    - path: "api/app/Domain/**/Services/**/*.php"
      instructions: |
        ## Serviceレイヤーのチェック
        **重要度: 高**

        ### 設計原則
        - [ ] 単一責任の原則に従い、1つのServiceは1つの責務のみを持っている
        - [ ] 他のServiceを直接呼び出さず、必要に応じてDelegator経由で呼び出している

        ### パフォーマンス（N+1問題の防止）
        - [ ] ユーザーデータ（usr_テーブル）の取得・更新処理（UsrXxxRepositoryクラスのメソッド）がループ内で呼び出されていないか
          - NG例: `foreach ($userIds as $id) { $usrUserRepository->find($id); }`
          - OK例: `$usrUserRepository->findByIds($userIds);`（一括取得）
        - [ ] マスタデータ（mst_/opr_/mng_テーブル）の取得・更新処理（Mst/Opr/MngXxxRepositoryクラスのメソッド）がループ内で呼び出されていないか
          - NG例: `foreach ($itemIds as $id) { $mstItemRepository->find($id); }`
          - OK例: `$mstItemRepository->findByIds($itemIds);`（一括取得）またはキャッシュ活用

    # === UseCaseレイヤー ===
    - path: "api/app/UseCase/**/*.php"
      instructions: |
        ## UseCaseレイヤーのチェック
        **重要度: 高**

        ### トランザクション管理
        - [ ] applyUserTransactionChangesを使う際、UsrDeviceRepository、BillingRepository、CurrencyRepository等のUsrModelCacheRepository非継承のRepositoryは必ずcallbackに含めてトランザクション内で処理している

        ### パフォーマンス（N+1問題の防止）
        - [ ] ユーザーデータ（usr_テーブル）の取得・更新処理（UsrXxxRepositoryクラスのメソッド）がループ内で呼び出されていないか
          - NG例: `foreach ($userIds as $id) { $usrUserRepository->find($id); }`
          - OK例: `$usrUserRepository->findByIds($userIds);`（一括取得）
        - [ ] マスタデータ（mst_/opr_/mng_テーブル）の取得・更新処理（Mst/Opr/MngXxxRepositoryクラスのメソッド）がループ内で呼び出されていないか
          - NG例: `foreach ($itemIds as $id) { $mstItemRepository->find($id); }`
          - OK例: `$mstItemRepository->findByIds($itemIds);`（一括取得）またはキャッシュ活用

    # === データベース（Migration） ===
    # API Migration
    - path: "api/database/migrations/*.php"
      instructions: |
        ## Migrationファイルのチェック
        **重要度: 高**
        - [ ] テーブル名に適切な接頭辞がある（mst_, usr_, log_, mng_, sys_, adm_, 等）
        - [ ] 接頭辞とDB接続先が一致している
        - [ ] テーブルと全カラムにコメント句が適切に設定されている
        - [ ] usr_で始まるテーブルのPKはusr_user_idのみもしくはusr_user_idを含む複合PKになっている
        - [ ] downメソッドが適切に実装されている
        - [ ] データ削除の影響を考慮している

    # Admin Migration
    - path: "admin/database/migrations/*.php"
      instructions: |
        ## Admin Migrationファイルのチェック
        **重要度: 高**
        - [ ] テーブル名に適切な接頭辞がある（adm_等）
        - [ ] 接頭辞とDB接続先が一致している
        - [ ] テーブルと全カラムにコメント句が適切に設定されている
        - [ ] downメソッドが適切に実装されている

    # === Admin Filamentリソース ===
    - path: "admin/app/Filament/**/*.php"
      instructions: |
        ## Filamentリソースのチェック
        **重要度: 高**

        ### 基本チェック
        - [ ] Filamentのベストプラクティスに従っているか
        - [ ] フォームバリデーションが適切か
        - [ ] テーブルカラム設定が適切か
        - [ ] 権限チェック（authorize）が実装されているか
        - [ ] RewardInfoGetTraitを使った報酬情報表示が正しく実装されているか

        ### Null参照エラーの防止（Critical）
        - [ ] Eloquentリレーションのプロパティアクセスに必ずnull safe演算子(`?->`)を使用している
        - [ ] 単一リレーション: `$model->relation?->property ?? ''` の形式（`??`だけでは不十分）
        - [ ] 多段リレーション: 全段階で`?->`を使用（例: `$model->rel1?->rel2?->property ?? ''`）
        - [ ] Filamentの`getStateUsing()`/`formatStateUsing()`内でも同様にnull safe処理を実装している
        - [ ] i18nリレーション（`mst_*_i18n->name`等）で特に注意している

    # === 環境変数テンプレート ===
    - path: "**/.env.example"
      instructions: |
        ## 環境変数テンプレートのチェック
        **重要度: 高**
        - [ ] 本番環境での機密情報がハードコードされていないか
        - [ ] 全ての必須環境変数が含まれているか
        - [ ] コメントで各変数の用途が説明されているか

    # === Docker設定 ===
    - path: "**/docker-compose*.yml"
      instructions: |
        ## Docker設定のチェック
        **重要度: 中**
        - [ ] ポート番号が適切に設定されているか
        - [ ] ボリュームマウントが正しいか
        - [ ] 環境変数が.envから読み込まれているか
        - [ ] セキュリティ設定（secrets等）が適切か

  # 自動レビューの有効化
  auto_review:
    enabled: true
    # ドラフトPRはレビュー対象外
    drafts: false
    base_branches:
      - ".*"
    # プッシュごとに増分レビュー実施
    auto_incremental_review: true
    # タイトルキーワードでレビュー除外
    ignore_title_keywords:
      - "WIP"
      - "DO NOT REVIEW"
      - "wip"

  # 静的解析・セキュリティツール
  tools:
    # PHP静的解析
    phpstan:
      enabled: true
    # PHP問題検出（未使用変数、複雑度等）
    phpmd:
      enabled: true
    # シークレット検出（APIキー、パスワード等の漏洩防止）
    gitleaks:
      enabled: true
    # セキュリティ脆弱性スキャン（SQLインジェクション、XSS等）
    semgrep:
      enabled: true
    # Dockerfile検証
    hadolint:
      enabled: true
    # Markdown品質向上（スタイルチェックのみのため無効化）
    markdownlint:
      enabled: false
    # YAML検証
    yamllint:
      enabled: true

chat:
  auto_reply: true

# ナレッジベース設定
knowledge_base:
  # チームのフィードバックから学習
  learnings:
    scope: "auto"
  # 既存のコーディング規約ファイルを自動検出して適用
  code_guidelines:
    enabled: true
    # プロジェクト固有のガイドラインファイル（デフォルトのCLAUDE.md等に加えて追加）
    filePatterns:
      - ".claude/api.md"
      - ".claude/admin.md"
      - "docs/01_project/**/*.md"
      # SDD v2の機能要件ドキュメント
      - "docs/sdd-v2/features/**/*.md"
  # Web検索でコンテキスト拡張
  web_search:
    enabled: true
