<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstAbilityResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_abilityType = 'abilityType';
    protected const C_assetKey = 'assetKey';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->abilityType = $data['abilityType'];
            $this->assetKey = $data['assetKey'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'abilityType' => 'string',
        'assetKey' => 'string',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'abilityType' => 'ability_type',
        'assetKey' => 'asset_key',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $abilityType;

    /** @var string */
    protected $assetKey;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'abilityType' => $this->abilityType,
            'assetKey' => $this->assetKey,
        ];
    }
}
