<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstAdventBattleRankResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_mstAdventBattleId = 'mstAdventBattleId';
    protected const C_rankType = 'rankType';
    protected const C_rankLevel = 'rankLevel';
    protected const C_requiredLowerScore = 'requiredLowerScore';
    protected const C_assetKey = 'assetKey';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->mstAdventBattleId = $data['mstAdventBattleId'];
            $this->rankType = $data['rankType'];
            $this->rankLevel = $data['rankLevel'];
            $this->requiredLowerScore = $data['requiredLowerScore'];
            $this->assetKey = $data['assetKey'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'mstAdventBattleId' => 'string',
        'rankType' => 'string',
        'rankLevel' => 'int',
        'requiredLowerScore' => 'int',
        'assetKey' => 'string',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'mstAdventBattleId' => 'mst_advent_battle_id',
        'rankType' => 'rank_type',
        'rankLevel' => 'rank_level',
        'requiredLowerScore' => 'required_lower_score',
        'assetKey' => 'asset_key',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $mstAdventBattleId;

    /** @var string */
    protected $rankType;

    /** @var int */
    protected $rankLevel;

    /** @var int */
    protected $requiredLowerScore;

    /** @var string */
    protected $assetKey;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'mstAdventBattleId' => $this->mstAdventBattleId,
            'rankType' => $this->rankType,
            'rankLevel' => $this->rankLevel,
            'requiredLowerScore' => $this->requiredLowerScore,
            'assetKey' => $this->assetKey,
        ];
    }
}
