<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstArtworkEffectTargetRuleResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_mstArtworkEffectId = 'mstArtworkEffectId';
    protected const C_conditionType = 'conditionType';
    protected const C_conditionValue = 'conditionValue';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->mstArtworkEffectId = $data['mstArtworkEffectId'];
            $this->conditionType = $data['conditionType'];
            $this->conditionValue = $data['conditionValue'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'mstArtworkEffectId' => 'string',
        'conditionType' => 'string',
        'conditionValue' => 'string',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'mstArtworkEffectId' => 'mst_artwork_effect_id',
        'conditionType' => 'condition_type',
        'conditionValue' => 'condition_value',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $mstArtworkEffectId;

    /** @var string */
    protected $conditionType;

    /** @var string */
    protected $conditionValue;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'mstArtworkEffectId' => $this->mstArtworkEffectId,
            'conditionType' => $this->conditionType,
            'conditionValue' => $this->conditionValue,
        ];
    }
}
