<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstArtworkResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_mstSeriesId = 'mstSeriesId';
    protected const C_outpostAdditionalHp = 'outpostAdditionalHp';
    protected const C_assetKey = 'assetKey';
    protected const C_sortOrder = 'sortOrder';
    protected const C_rarity = 'rarity';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->mstSeriesId = $data['mstSeriesId'];
            $this->outpostAdditionalHp = $data['outpostAdditionalHp'];
            $this->assetKey = $data['assetKey'];
            $this->sortOrder = $data['sortOrder'];
            $this->rarity = $data['rarity'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'mstSeriesId' => 'string',
        'outpostAdditionalHp' => 'int',
        'assetKey' => 'string',
        'sortOrder' => 'int',
        'rarity' => 'string',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'mstSeriesId' => 'mst_series_id',
        'outpostAdditionalHp' => 'outpost_additional_hp',
        'assetKey' => 'asset_key',
        'sortOrder' => 'sort_order',
        'rarity' => 'rarity',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $mstSeriesId;

    /** @var int */
    protected $outpostAdditionalHp;

    /** @var string */
    protected $assetKey;

    /** @var int */
    protected $sortOrder;

    /** @var string */
    protected $rarity;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'mstSeriesId' => $this->mstSeriesId,
            'outpostAdditionalHp' => $this->outpostAdditionalHp,
            'assetKey' => $this->assetKey,
            'sortOrder' => $this->sortOrder,
            'rarity' => $this->rarity,
        ];
    }
}
