<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstArtworkEffectResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_mstArtworkId = 'mstArtworkId';
    protected const C_effectType = 'effectType';
    protected const C_gradeLevel1Value = 'gradeLevel1Value';
    protected const C_gradeLevel2Value = 'gradeLevel2Value';
    protected const C_gradeLevel3Value = 'gradeLevel3Value';
    protected const C_gradeLevel4Value = 'gradeLevel4Value';
    protected const C_gradeLevel5Value = 'gradeLevel5Value';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->mstArtworkId = $data['mstArtworkId'];
            $this->effectType = $data['effectType'];
            $this->gradeLevel1Value = $data['gradeLevel1Value'];
            $this->gradeLevel2Value = $data['gradeLevel2Value'];
            $this->gradeLevel3Value = $data['gradeLevel3Value'];
            $this->gradeLevel4Value = $data['gradeLevel4Value'];
            $this->gradeLevel5Value = $data['gradeLevel5Value'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'mstArtworkId' => 'string',
        'effectType' => 'string',
        'gradeLevel1Value' => 'string',
        'gradeLevel2Value' => 'string',
        'gradeLevel3Value' => 'string',
        'gradeLevel4Value' => 'string',
        'gradeLevel5Value' => 'string',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'mstArtworkId' => 'mst_artwork_id',
        'effectType' => 'effect_type',
        'gradeLevel1Value' => 'grade_level1_value',
        'gradeLevel2Value' => 'grade_level2_value',
        'gradeLevel3Value' => 'grade_level3_value',
        'gradeLevel4Value' => 'grade_level4_value',
        'gradeLevel5Value' => 'grade_level5_value',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $mstArtworkId;

    /** @var string */
    protected $effectType;

    /** @var string */
    protected $gradeLevel1Value;

    /** @var string */
    protected $gradeLevel2Value;

    /** @var string */
    protected $gradeLevel3Value;

    /** @var string */
    protected $gradeLevel4Value;

    /** @var string */
    protected $gradeLevel5Value;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'mstArtworkId' => $this->mstArtworkId,
            'effectType' => $this->effectType,
            'gradeLevel1Value' => $this->gradeLevel1Value,
            'gradeLevel2Value' => $this->gradeLevel2Value,
            'gradeLevel3Value' => $this->gradeLevel3Value,
            'gradeLevel4Value' => $this->gradeLevel4Value,
            'gradeLevel5Value' => $this->gradeLevel5Value,
        ];
    }
}
