<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstArtworkFragmentResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_mstArtworkId = 'mstArtworkId';
    protected const C_dropGroupId = 'dropGroupId';
    protected const C_dropPercentage = 'dropPercentage';
    protected const C_rarity = 'rarity';
    protected const C_assetNum = 'assetNum';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->mstArtworkId = $data['mstArtworkId'];
            $this->dropGroupId = $data['dropGroupId'];
            $this->dropPercentage = $data['dropPercentage'];
            $this->rarity = $data['rarity'];
            $this->assetNum = $data['assetNum'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'mstArtworkId' => 'string',
        'dropGroupId' => 'string',
        'dropPercentage' => 'int',
        'rarity' => 'string',
        'assetNum' => 'int',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'mstArtworkId' => 'mst_artwork_id',
        'dropGroupId' => 'drop_group_id',
        'dropPercentage' => 'drop_percentage',
        'rarity' => 'rarity',
        'assetNum' => 'asset_num',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $mstArtworkId;

    /** @var string */
    protected $dropGroupId;

    /** @var int */
    protected $dropPercentage;

    /** @var string */
    protected $rarity;

    /** @var int */
    protected $assetNum;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'mstArtworkId' => $this->mstArtworkId,
            'dropGroupId' => $this->dropGroupId,
            'dropPercentage' => $this->dropPercentage,
            'rarity' => $this->rarity,
            'assetNum' => $this->assetNum,
        ];
    }
}
