<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstAdventBattleClearRewardResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_mstAdventBattleId = 'mstAdventBattleId';
    protected const C_rewardCategory = 'rewardCategory';
    protected const C_resourceType = 'resourceType';
    protected const C_resourceId = 'resourceId';
    protected const C_resourceAmount = 'resourceAmount';
    protected const C_percentage = 'percentage';
    protected const C_sortOrder = 'sortOrder';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->mstAdventBattleId = $data['mstAdventBattleId'];
            $this->rewardCategory = $data['rewardCategory'];
            $this->resourceType = $data['resourceType'];
            $this->resourceId = $data['resourceId'];
            $this->resourceAmount = $data['resourceAmount'];
            $this->percentage = $data['percentage'];
            $this->sortOrder = $data['sortOrder'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'mstAdventBattleId' => 'string',
        'rewardCategory' => 'string',
        'resourceType' => 'string',
        'resourceId' => 'string',
        'resourceAmount' => 'int',
        'percentage' => 'int',
        'sortOrder' => 'int',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'mstAdventBattleId' => 'mst_advent_battle_id',
        'rewardCategory' => 'reward_category',
        'resourceType' => 'resource_type',
        'resourceId' => 'resource_id',
        'resourceAmount' => 'resource_amount',
        'percentage' => 'percentage',
        'sortOrder' => 'sort_order',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $mstAdventBattleId;

    /** @var string */
    protected $rewardCategory;

    /** @var string */
    protected $resourceType;

    /** @var string */
    protected $resourceId;

    /** @var int */
    protected $resourceAmount;

    /** @var int */
    protected $percentage;

    /** @var int */
    protected $sortOrder;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'mstAdventBattleId' => $this->mstAdventBattleId,
            'rewardCategory' => $this->rewardCategory,
            'resourceType' => $this->resourceType,
            'resourceId' => $this->resourceId,
            'resourceAmount' => $this->resourceAmount,
            'percentage' => $this->percentage,
            'sortOrder' => $this->sortOrder,
        ];
    }
}
