<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstArtworkGradeUpResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_rarity = 'rarity';
    protected const C_gradeLevel = 'gradeLevel';
    protected const C_mstSeriesId = 'mstSeriesId';
    protected const C_mstArtworkId = 'mstArtworkId';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->rarity = $data['rarity'];
            $this->gradeLevel = $data['gradeLevel'];
            $this->mstSeriesId = $data['mstSeriesId'];
            $this->mstArtworkId = $data['mstArtworkId'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'rarity' => 'string',
        'gradeLevel' => 'int',
        'mstSeriesId' => 'string',
        'mstArtworkId' => 'string|null',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'rarity' => 'rarity',
        'gradeLevel' => 'grade_level',
        'mstSeriesId' => 'mst_series_id',
        'mstArtworkId' => 'mst_artwork_id',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $rarity;

    /** @var int */
    protected $gradeLevel;

    /** @var string */
    protected $mstSeriesId;

    /** @var string|null */
    protected $mstArtworkId;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'rarity' => $this->rarity,
            'gradeLevel' => $this->gradeLevel,
            'mstSeriesId' => $this->mstSeriesId,
            'mstArtworkId' => $this->mstArtworkId,
        ];
    }
}
