<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstBoxGachaGroupResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_mstBoxGachaId = 'mstBoxGachaId';
    protected const C_boxLevel = 'boxLevel';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->mstBoxGachaId = $data['mstBoxGachaId'];
            $this->boxLevel = $data['boxLevel'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'mstBoxGachaId' => 'string',
        'boxLevel' => 'int',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'mstBoxGachaId' => 'mst_box_gacha_id',
        'boxLevel' => 'box_level',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $mstBoxGachaId;

    /** @var int */
    protected $boxLevel;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'mstBoxGachaId' => $this->mstBoxGachaId,
            'boxLevel' => $this->boxLevel,
        ];
    }
}
