<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstBoxGachaResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_mstEventId = 'mstEventId';
    protected const C_costId = 'costId';
    protected const C_costNum = 'costNum';
    protected const C_loopType = 'loopType';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->mstEventId = $data['mstEventId'];
            $this->costId = $data['costId'];
            $this->costNum = $data['costNum'];
            $this->loopType = $data['loopType'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'mstEventId' => 'string',
        'costId' => 'string',
        'costNum' => 'int',
        'loopType' => 'string',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'mstEventId' => 'mst_event_id',
        'costId' => 'cost_id',
        'costNum' => 'cost_num',
        'loopType' => 'loop_type',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $mstEventId;

    /** @var string */
    protected $costId;

    /** @var int */
    protected $costNum;

    /** @var string */
    protected $loopType;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'mstEventId' => $this->mstEventId,
            'costId' => $this->costId,
            'costNum' => $this->costNum,
            'loopType' => $this->loopType,
        ];
    }
}
