<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstComebackBonusResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_mstComebackBonusScheduleId = 'mstComebackBonusScheduleId';
    protected const C_loginDayCount = 'loginDayCount';
    protected const C_mstDailyBonusRewardGroupId = 'mstDailyBonusRewardGroupId';
    protected const C_sortOrder = 'sortOrder';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->mstComebackBonusScheduleId = $data['mstComebackBonusScheduleId'];
            $this->loginDayCount = $data['loginDayCount'];
            $this->mstDailyBonusRewardGroupId = $data['mstDailyBonusRewardGroupId'];
            $this->sortOrder = $data['sortOrder'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'mstComebackBonusScheduleId' => 'string',
        'loginDayCount' => 'int',
        'mstDailyBonusRewardGroupId' => 'string',
        'sortOrder' => 'int',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'mstComebackBonusScheduleId' => 'mst_comeback_bonus_schedule_id',
        'loginDayCount' => 'login_day_count',
        'mstDailyBonusRewardGroupId' => 'mst_daily_bonus_reward_group_id',
        'sortOrder' => 'sort_order',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $mstComebackBonusScheduleId;

    /** @var int */
    protected $loginDayCount;

    /** @var string */
    protected $mstDailyBonusRewardGroupId;

    /** @var int */
    protected $sortOrder;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'mstComebackBonusScheduleId' => $this->mstComebackBonusScheduleId,
            'loginDayCount' => $this->loginDayCount,
            'mstDailyBonusRewardGroupId' => $this->mstDailyBonusRewardGroupId,
            'sortOrder' => $this->sortOrder,
        ];
    }
}
