<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstComebackBonusScheduleResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_inactiveConditionDays = 'inactiveConditionDays';
    protected const C_durationDays = 'durationDays';
    protected const C_startAt = 'startAt';
    protected const C_endAt = 'endAt';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->inactiveConditionDays = $data['inactiveConditionDays'];
            $this->durationDays = $data['durationDays'];
            $this->startAt = $data['startAt'];
            $this->endAt = $data['endAt'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'inactiveConditionDays' => 'int',
        'durationDays' => 'int',
        'startAt' => 'string',
        'endAt' => 'string',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'inactiveConditionDays' => 'inactive_condition_days',
        'durationDays' => 'duration_days',
        'startAt' => 'start_at',
        'endAt' => 'end_at',
    ];

    /** @var string */
    protected $id;

    /** @var int */
    protected $inactiveConditionDays;

    /** @var int */
    protected $durationDays;

    /** @var string */
    protected $startAt;

    /** @var string */
    protected $endAt;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'inactiveConditionDays' => $this->inactiveConditionDays,
            'durationDays' => $this->durationDays,
            'startAt' => $this->startAt,
            'endAt' => $this->endAt,
        ];
    }
}
