<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstDummyOutpostResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_mstDummyUserId = 'mstDummyUserId';
    protected const C_mstOutpostEnhancementId = 'mstOutpostEnhancementId';
    protected const C_level = 'level';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->mstDummyUserId = $data['mstDummyUserId'];
            $this->mstOutpostEnhancementId = $data['mstOutpostEnhancementId'];
            $this->level = $data['level'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'mstDummyUserId' => 'string',
        'mstOutpostEnhancementId' => 'string',
        'level' => 'int',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'mstDummyUserId' => 'mst_dummy_user_id',
        'mstOutpostEnhancementId' => 'mst_outpost_enhancement_id',
        'level' => 'level',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $mstDummyUserId;

    /** @var string */
    protected $mstOutpostEnhancementId;

    /** @var int */
    protected $level;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'mstDummyUserId' => $this->mstDummyUserId,
            'mstOutpostEnhancementId' => $this->mstOutpostEnhancementId,
            'level' => $this->level,
        ];
    }
}
