<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstDummyUserUnitResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_mstDummyUserId = 'mstDummyUserId';
    protected const C_mstUnitId = 'mstUnitId';
    protected const C_level = 'level';
    protected const C_rank = 'rank';
    protected const C_gradeLevel = 'gradeLevel';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->mstDummyUserId = $data['mstDummyUserId'];
            $this->mstUnitId = $data['mstUnitId'];
            $this->level = $data['level'];
            $this->rank = $data['rank'];
            $this->gradeLevel = $data['gradeLevel'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'mstDummyUserId' => 'string',
        'mstUnitId' => 'string',
        'level' => 'int',
        'rank' => 'int',
        'gradeLevel' => 'int',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'mstDummyUserId' => 'mst_dummy_user_id',
        'mstUnitId' => 'mst_unit_id',
        'level' => 'level',
        'rank' => 'rank',
        'gradeLevel' => 'grade_level',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $mstDummyUserId;

    /** @var string */
    protected $mstUnitId;

    /** @var int */
    protected $level;

    /** @var int */
    protected $rank;

    /** @var int */
    protected $gradeLevel;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'mstDummyUserId' => $this->mstDummyUserId,
            'mstUnitId' => $this->mstUnitId,
            'level' => $this->level,
            'rank' => $this->rank,
            'gradeLevel' => $this->gradeLevel,
        ];
    }
}
