<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstDefenseTargetResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_assetKey = 'assetKey';
    protected const C_position = 'position';
    protected const C_hp = 'hp';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->assetKey = $data['assetKey'];
            $this->position = $data['position'];
            $this->hp = $data['hp'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'assetKey' => 'string',
        'position' => 'string',
        'hp' => 'int',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'assetKey' => 'asset_key',
        'position' => 'position',
        'hp' => 'hp',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $assetKey;

    /** @var string */
    protected $position;

    /** @var int */
    protected $hp;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'assetKey' => $this->assetKey,
            'position' => $this->position,
            'hp' => $this->hp,
        ];
    }
}
