<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstExchangeLineupResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_groupId = 'groupId';
    protected const C_tradableCount = 'tradableCount';
    protected const C_displayOrder = 'displayOrder';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->groupId = $data['groupId'];
            $this->tradableCount = $data['tradableCount'];
            $this->displayOrder = $data['displayOrder'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'groupId' => 'string',
        'tradableCount' => 'int|null',
        'displayOrder' => 'int',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'groupId' => 'group_id',
        'tradableCount' => 'tradable_count',
        'displayOrder' => 'display_order',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $groupId;

    /** @var int|null */
    protected $tradableCount;

    /** @var int */
    protected $displayOrder;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'groupId' => $this->groupId,
            'tradableCount' => $this->tradableCount,
            'displayOrder' => $this->displayOrder,
        ];
    }
}
