<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstEventDisplayRewardResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_mstEventId = 'mstEventId';
    protected const C_resourceType = 'resourceType';
    protected const C_resourceId = 'resourceId';
    protected const C_sortOrder = 'sortOrder';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->mstEventId = $data['mstEventId'];
            $this->resourceType = $data['resourceType'];
            $this->resourceId = $data['resourceId'];
            $this->sortOrder = $data['sortOrder'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'mstEventId' => 'string',
        'resourceType' => 'string',
        'resourceId' => 'string',
        'sortOrder' => 'int',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'mstEventId' => 'mst_event_id',
        'resourceType' => 'resource_type',
        'resourceId' => 'resource_id',
        'sortOrder' => 'sort_order',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $mstEventId;

    /** @var string */
    protected $resourceType;

    /** @var string */
    protected $resourceId;

    /** @var int */
    protected $sortOrder;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'mstEventId' => $this->mstEventId,
            'resourceType' => $this->resourceType,
            'resourceId' => $this->resourceId,
            'sortOrder' => $this->sortOrder,
        ];
    }
}
