<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstEventResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_mstSeriesId = 'mstSeriesId';
    protected const C_isDisplayedSeriesLogo = 'isDisplayedSeriesLogo';
    protected const C_isDisplayedJumpPlus = 'isDisplayedJumpPlus';
    protected const C_startAt = 'startAt';
    protected const C_endAt = 'endAt';
    protected const C_assetKey = 'assetKey';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->mstSeriesId = $data['mstSeriesId'];
            $this->isDisplayedSeriesLogo = $data['isDisplayedSeriesLogo'];
            $this->isDisplayedJumpPlus = $data['isDisplayedJumpPlus'];
            $this->startAt = $data['startAt'];
            $this->endAt = $data['endAt'];
            $this->assetKey = $data['assetKey'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'mstSeriesId' => 'string',
        'isDisplayedSeriesLogo' => 'string',
        'isDisplayedJumpPlus' => 'string',
        'startAt' => 'string',
        'endAt' => 'string',
        'assetKey' => 'string',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'mstSeriesId' => 'mst_series_id',
        'isDisplayedSeriesLogo' => 'is_displayed_series_logo',
        'isDisplayedJumpPlus' => 'is_displayed_jump_plus',
        'startAt' => 'start_at',
        'endAt' => 'end_at',
        'assetKey' => 'asset_key',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $mstSeriesId;

    /** @var string */
    protected $isDisplayedSeriesLogo;

    /** @var string */
    protected $isDisplayedJumpPlus;

    /** @var string */
    protected $startAt;

    /** @var string */
    protected $endAt;

    /** @var string */
    protected $assetKey;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'mstSeriesId' => $this->mstSeriesId,
            'isDisplayedSeriesLogo' => $this->isDisplayedSeriesLogo,
            'isDisplayedJumpPlus' => $this->isDisplayedJumpPlus,
            'startAt' => $this->startAt,
            'endAt' => $this->endAt,
            'assetKey' => $this->assetKey,
        ];
    }
}
