<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstEmblemResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_emblemType = 'emblemType';
    protected const C_mstSeriesId = 'mstSeriesId';
    protected const C_assetKey = 'assetKey';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->emblemType = $data['emblemType'];
            $this->mstSeriesId = $data['mstSeriesId'];
            $this->assetKey = $data['assetKey'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'emblemType' => 'string',
        'mstSeriesId' => 'string',
        'assetKey' => 'string',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'emblemType' => 'emblem_type',
        'mstSeriesId' => 'mst_series_id',
        'assetKey' => 'asset_key',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $emblemType;

    /** @var string */
    protected $mstSeriesId;

    /** @var string */
    protected $assetKey;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'emblemType' => $this->emblemType,
            'mstSeriesId' => $this->mstSeriesId,
            'assetKey' => $this->assetKey,
        ];
    }
}
