<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstHomeBannerResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_destination = 'destination';
    protected const C_destinationPath = 'destinationPath';
    protected const C_assetKey = 'assetKey';
    protected const C_startAt = 'startAt';
    protected const C_endAt = 'endAt';
    protected const C_sortOrder = 'sortOrder';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->destination = $data['destination'];
            $this->destinationPath = $data['destinationPath'];
            $this->assetKey = $data['assetKey'];
            $this->startAt = $data['startAt'];
            $this->endAt = $data['endAt'];
            $this->sortOrder = $data['sortOrder'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'destination' => 'string',
        'destinationPath' => 'string',
        'assetKey' => 'string',
        'startAt' => 'string',
        'endAt' => 'string',
        'sortOrder' => 'int',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'destination' => 'destination',
        'destinationPath' => 'destination_path',
        'assetKey' => 'asset_key',
        'startAt' => 'start_at',
        'endAt' => 'end_at',
        'sortOrder' => 'sort_order',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $destination;

    /** @var string */
    protected $destinationPath;

    /** @var string */
    protected $assetKey;

    /** @var string */
    protected $startAt;

    /** @var string */
    protected $endAt;

    /** @var int */
    protected $sortOrder;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'destination' => $this->destination,
            'destinationPath' => $this->destinationPath,
            'assetKey' => $this->assetKey,
            'startAt' => $this->startAt,
            'endAt' => $this->endAt,
            'sortOrder' => $this->sortOrder,
        ];
    }
}
