<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstItemResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_type = 'type';
    protected const C_groupType = 'groupType';
    protected const C_rarity = 'rarity';
    protected const C_effectValue = 'effectValue';
    protected const C_sortOrder = 'sortOrder';
    protected const C_assetKey = 'assetKey';
    protected const C_mstSeriesId = 'mstSeriesId';
    protected const C_destinationOprProductId = 'destinationOprProductId';
    protected const C_startDate = 'startDate';
    protected const C_endDate = 'endDate';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->type = $data['type'];
            $this->groupType = $data['groupType'];
            $this->rarity = $data['rarity'];
            $this->effectValue = $data['effectValue'];
            $this->sortOrder = $data['sortOrder'];
            $this->assetKey = $data['assetKey'];
            $this->mstSeriesId = $data['mstSeriesId'];
            $this->destinationOprProductId = $data['destinationOprProductId'];
            $this->startDate = $data['startDate'];
            $this->endDate = $data['endDate'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'type' => 'string',
        'groupType' => 'string',
        'rarity' => 'string',
        'effectValue' => 'string',
        'sortOrder' => 'int',
        'assetKey' => 'string',
        'mstSeriesId' => 'string',
        'destinationOprProductId' => 'string',
        'startDate' => 'string',
        'endDate' => 'string',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'type' => 'type',
        'groupType' => 'group_type',
        'rarity' => 'rarity',
        'effectValue' => 'effect_value',
        'sortOrder' => 'sort_order',
        'assetKey' => 'asset_key',
        'mstSeriesId' => 'mst_series_id',
        'destinationOprProductId' => 'destination_opr_product_id',
        'startDate' => 'start_date',
        'endDate' => 'end_date',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $type;

    /** @var string */
    protected $groupType;

    /** @var string */
    protected $rarity;

    /** @var string */
    protected $effectValue;

    /** @var int */
    protected $sortOrder;

    /** @var string */
    protected $assetKey;

    /** @var string */
    protected $mstSeriesId;

    /** @var string */
    protected $destinationOprProductId;

    /** @var string */
    protected $startDate;

    /** @var string */
    protected $endDate;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'type' => $this->type,
            'groupType' => $this->groupType,
            'rarity' => $this->rarity,
            'effectValue' => $this->effectValue,
            'sortOrder' => $this->sortOrder,
            'assetKey' => $this->assetKey,
            'mstSeriesId' => $this->mstSeriesId,
            'destinationOprProductId' => $this->destinationOprProductId,
            'startDate' => $this->startDate,
            'endDate' => $this->endDate,
        ];
    }
}
