<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstInGameSpecialRuleUnitStatusResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_groupId = 'groupId';
    protected const C_targetType = 'targetType';
    protected const C_targetValue = 'targetValue';
    protected const C_statusParameterType = 'statusParameterType';
    protected const C_effectValue = 'effectValue';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->groupId = $data['groupId'];
            $this->targetType = $data['targetType'];
            $this->targetValue = $data['targetValue'];
            $this->statusParameterType = $data['statusParameterType'];
            $this->effectValue = $data['effectValue'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'groupId' => 'string',
        'targetType' => 'string',
        'targetValue' => 'string',
        'statusParameterType' => 'string',
        'effectValue' => 'int',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'groupId' => 'group_id',
        'targetType' => 'target_type',
        'targetValue' => 'target_value',
        'statusParameterType' => 'status_parameter_type',
        'effectValue' => 'effect_value',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $groupId;

    /** @var string */
    protected $targetType;

    /** @var string */
    protected $targetValue;

    /** @var string */
    protected $statusParameterType;

    /** @var int */
    protected $effectValue;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'groupId' => $this->groupId,
            'targetType' => $this->targetType,
            'targetValue' => $this->targetValue,
            'statusParameterType' => $this->statusParameterType,
            'effectValue' => $this->effectValue,
        ];
    }
}
