<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstMangaAnimationResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_mstStageId = 'mstStageId';
    protected const C_conditionType = 'conditionType';
    protected const C_conditionValue = 'conditionValue';
    protected const C_animationStartDelay = 'animationStartDelay';
    protected const C_animationSpeed = 'animationSpeed';
    protected const C_isPause = 'isPause';
    protected const C_canSkip = 'canSkip';
    protected const C_assetKey = 'assetKey';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->mstStageId = $data['mstStageId'];
            $this->conditionType = $data['conditionType'];
            $this->conditionValue = $data['conditionValue'];
            $this->animationStartDelay = $data['animationStartDelay'];
            $this->animationSpeed = $data['animationSpeed'];
            $this->isPause = $data['isPause'];
            $this->canSkip = $data['canSkip'];
            $this->assetKey = $data['assetKey'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'mstStageId' => 'string',
        'conditionType' => 'string',
        'conditionValue' => 'string',
        'animationStartDelay' => 'int',
        'animationSpeed' => 'string',
        'isPause' => 'string',
        'canSkip' => 'string',
        'assetKey' => 'string',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'mstStageId' => 'mst_stage_id',
        'conditionType' => 'condition_type',
        'conditionValue' => 'condition_value',
        'animationStartDelay' => 'animation_start_delay',
        'animationSpeed' => 'animation_speed',
        'isPause' => 'is_pause',
        'canSkip' => 'can_skip',
        'assetKey' => 'asset_key',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $mstStageId;

    /** @var string */
    protected $conditionType;

    /** @var string */
    protected $conditionValue;

    /** @var int */
    protected $animationStartDelay;

    /** @var string */
    protected $animationSpeed;

    /** @var string */
    protected $isPause;

    /** @var string */
    protected $canSkip;

    /** @var string */
    protected $assetKey;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'mstStageId' => $this->mstStageId,
            'conditionType' => $this->conditionType,
            'conditionValue' => $this->conditionValue,
            'animationStartDelay' => $this->animationStartDelay,
            'animationSpeed' => $this->animationSpeed,
            'isPause' => $this->isPause,
            'canSkip' => $this->canSkip,
            'assetKey' => $this->assetKey,
        ];
    }
}
