<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstMissionAchievementResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_criterionType = 'criterionType';
    protected const C_criterionValue = 'criterionValue';
    protected const C_criterionCount = 'criterionCount';
    protected const C_unlockCriterionType = 'unlockCriterionType';
    protected const C_unlockCriterionValue = 'unlockCriterionValue';
    protected const C_unlockCriterionCount = 'unlockCriterionCount';
    protected const C_groupKey = 'groupKey';
    protected const C_mstMissionRewardGroupId = 'mstMissionRewardGroupId';
    protected const C_sortOrder = 'sortOrder';
    protected const C_destinationScene = 'destinationScene';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->criterionType = $data['criterionType'];
            $this->criterionValue = $data['criterionValue'];
            $this->criterionCount = $data['criterionCount'];
            $this->unlockCriterionType = $data['unlockCriterionType'];
            $this->unlockCriterionValue = $data['unlockCriterionValue'];
            $this->unlockCriterionCount = $data['unlockCriterionCount'];
            $this->groupKey = $data['groupKey'];
            $this->mstMissionRewardGroupId = $data['mstMissionRewardGroupId'];
            $this->sortOrder = $data['sortOrder'];
            $this->destinationScene = $data['destinationScene'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'criterionType' => 'string',
        'criterionValue' => 'string|null',
        'criterionCount' => 'int',
        'unlockCriterionType' => 'string|null',
        'unlockCriterionValue' => 'string',
        'unlockCriterionCount' => 'int|null',
        'groupKey' => 'string',
        'mstMissionRewardGroupId' => 'string',
        'sortOrder' => 'int',
        'destinationScene' => 'string',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'criterionType' => 'criterion_type',
        'criterionValue' => 'criterion_value',
        'criterionCount' => 'criterion_count',
        'unlockCriterionType' => 'unlock_criterion_type',
        'unlockCriterionValue' => 'unlock_criterion_value',
        'unlockCriterionCount' => 'unlock_criterion_count',
        'groupKey' => 'group_key',
        'mstMissionRewardGroupId' => 'mst_mission_reward_group_id',
        'sortOrder' => 'sort_order',
        'destinationScene' => 'destination_scene',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $criterionType;

    /** @var string|null */
    protected $criterionValue;

    /** @var int */
    protected $criterionCount;

    /** @var string|null */
    protected $unlockCriterionType;

    /** @var string */
    protected $unlockCriterionValue;

    /** @var int|null */
    protected $unlockCriterionCount;

    /** @var string */
    protected $groupKey;

    /** @var string */
    protected $mstMissionRewardGroupId;

    /** @var int */
    protected $sortOrder;

    /** @var string */
    protected $destinationScene;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'criterionType' => $this->criterionType,
            'criterionValue' => $this->criterionValue,
            'criterionCount' => $this->criterionCount,
            'unlockCriterionType' => $this->unlockCriterionType,
            'unlockCriterionValue' => $this->unlockCriterionValue,
            'unlockCriterionCount' => $this->unlockCriterionCount,
            'groupKey' => $this->groupKey,
            'mstMissionRewardGroupId' => $this->mstMissionRewardGroupId,
            'sortOrder' => $this->sortOrder,
            'destinationScene' => $this->destinationScene,
        ];
    }
}
