<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstMissionDailyBonusResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_missionDailyBonusType = 'missionDailyBonusType';
    protected const C_loginDayCount = 'loginDayCount';
    protected const C_mstMissionRewardGroupId = 'mstMissionRewardGroupId';
    protected const C_sortOrder = 'sortOrder';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->missionDailyBonusType = $data['missionDailyBonusType'];
            $this->loginDayCount = $data['loginDayCount'];
            $this->mstMissionRewardGroupId = $data['mstMissionRewardGroupId'];
            $this->sortOrder = $data['sortOrder'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'missionDailyBonusType' => 'string',
        'loginDayCount' => 'int',
        'mstMissionRewardGroupId' => 'string',
        'sortOrder' => 'int',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'missionDailyBonusType' => 'mission_daily_bonus_type',
        'loginDayCount' => 'login_day_count',
        'mstMissionRewardGroupId' => 'mst_mission_reward_group_id',
        'sortOrder' => 'sort_order',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $missionDailyBonusType;

    /** @var int */
    protected $loginDayCount;

    /** @var string */
    protected $mstMissionRewardGroupId;

    /** @var int */
    protected $sortOrder;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'missionDailyBonusType' => $this->missionDailyBonusType,
            'loginDayCount' => $this->loginDayCount,
            'mstMissionRewardGroupId' => $this->mstMissionRewardGroupId,
            'sortOrder' => $this->sortOrder,
        ];
    }
}
