<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstOutpostResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_assetKey = 'assetKey';
    protected const C_startAt = 'startAt';
    protected const C_endAt = 'endAt';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->assetKey = $data['assetKey'];
            $this->startAt = $data['startAt'];
            $this->endAt = $data['endAt'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'assetKey' => 'string',
        'startAt' => 'string',
        'endAt' => 'string',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'assetKey' => 'asset_key',
        'startAt' => 'start_at',
        'endAt' => 'end_at',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $assetKey;

    /** @var string */
    protected $startAt;

    /** @var string */
    protected $endAt;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'assetKey' => $this->assetKey,
            'startAt' => $this->startAt,
            'endAt' => $this->endAt,
        ];
    }
}
