<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstPackResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_productSubId = 'productSubId';
    protected const C_discountRate = 'discountRate';
    protected const C_packType = 'packType';
    protected const C_saleCondition = 'saleCondition';
    protected const C_saleConditionValue = 'saleConditionValue';
    protected const C_saleHours = 'saleHours';
    protected const C_tradableCount = 'tradableCount';
    protected const C_costType = 'costType';
    protected const C_costAmount = 'costAmount';
    protected const C_isRecommend = 'isRecommend';
    protected const C_isDisplayExpiration = 'isDisplayExpiration';
    protected const C_isFirstTimeFree = 'isFirstTimeFree';
    protected const C_assetKey = 'assetKey';
    protected const C_packDecoration = 'packDecoration';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->productSubId = $data['productSubId'];
            $this->discountRate = $data['discountRate'];
            $this->packType = $data['packType'];
            $this->saleCondition = $data['saleCondition'];
            $this->saleConditionValue = $data['saleConditionValue'];
            $this->saleHours = $data['saleHours'];
            $this->tradableCount = $data['tradableCount'];
            $this->costType = $data['costType'];
            $this->costAmount = $data['costAmount'];
            $this->isRecommend = $data['isRecommend'];
            $this->isDisplayExpiration = $data['isDisplayExpiration'];
            $this->isFirstTimeFree = $data['isFirstTimeFree'];
            $this->assetKey = $data['assetKey'];
            $this->packDecoration = $data['packDecoration'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'productSubId' => 'string',
        'discountRate' => 'int',
        'packType' => 'string',
        'saleCondition' => 'string|null',
        'saleConditionValue' => 'string',
        'saleHours' => 'int|null',
        'tradableCount' => 'int|null',
        'costType' => 'string',
        'costAmount' => 'int',
        'isRecommend' => 'string',
        'isDisplayExpiration' => 'string',
        'isFirstTimeFree' => 'string',
        'assetKey' => 'string',
        'packDecoration' => 'string|null',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'productSubId' => 'product_sub_id',
        'discountRate' => 'discount_rate',
        'packType' => 'pack_type',
        'saleCondition' => 'sale_condition',
        'saleConditionValue' => 'sale_condition_value',
        'saleHours' => 'sale_hours',
        'tradableCount' => 'tradable_count',
        'costType' => 'cost_type',
        'costAmount' => 'cost_amount',
        'isRecommend' => 'is_recommend',
        'isDisplayExpiration' => 'is_display_expiration',
        'isFirstTimeFree' => 'is_first_time_free',
        'assetKey' => 'asset_key',
        'packDecoration' => 'pack_decoration',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $productSubId;

    /** @var int */
    protected $discountRate;

    /** @var string */
    protected $packType;

    /** @var string|null */
    protected $saleCondition;

    /** @var string */
    protected $saleConditionValue;

    /** @var int|null */
    protected $saleHours;

    /** @var int|null */
    protected $tradableCount;

    /** @var string */
    protected $costType;

    /** @var int */
    protected $costAmount;

    /** @var string */
    protected $isRecommend;

    /** @var string */
    protected $isDisplayExpiration;

    /** @var string */
    protected $isFirstTimeFree;

    /** @var string */
    protected $assetKey;

    /** @var string|null */
    protected $packDecoration;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'productSubId' => $this->productSubId,
            'discountRate' => $this->discountRate,
            'packType' => $this->packType,
            'saleCondition' => $this->saleCondition,
            'saleConditionValue' => $this->saleConditionValue,
            'saleHours' => $this->saleHours,
            'tradableCount' => $this->tradableCount,
            'costType' => $this->costType,
            'costAmount' => $this->costAmount,
            'isRecommend' => $this->isRecommend,
            'isDisplayExpiration' => $this->isDisplayExpiration,
            'isFirstTimeFree' => $this->isFirstTimeFree,
            'assetKey' => $this->assetKey,
            'packDecoration' => $this->packDecoration,
        ];
    }
}
