<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstPvpBonusPointResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_bonusType = 'bonusType';
    protected const C_threshold = 'threshold';
    protected const C_bonusPoint = 'bonusPoint';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->bonusType = $data['bonusType'];
            $this->threshold = $data['threshold'];
            $this->bonusPoint = $data['bonusPoint'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'bonusType' => 'string',
        'threshold' => 'string|null',
        'bonusPoint' => 'int',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'bonusType' => 'bonus_type',
        'threshold' => 'threshold',
        'bonusPoint' => 'bonus_point',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $bonusType;

    /** @var string|null */
    protected $threshold;

    /** @var int */
    protected $bonusPoint;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'bonusType' => $this->bonusType,
            'threshold' => $this->threshold,
            'bonusPoint' => $this->bonusPoint,
        ];
    }
}
