<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstPvpResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_rankingMinPvpRankClass = 'rankingMinPvpRankClass';
    protected const C_maxDailyChallengeCount = 'maxDailyChallengeCount';
    protected const C_maxDailyItemChallengeCount = 'maxDailyItemChallengeCount';
    protected const C_itemChallengeCostAmount = 'itemChallengeCostAmount';
    protected const C_initialBattlePoint = 'initialBattlePoint';
    protected const C_mstInGameId = 'mstInGameId';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->rankingMinPvpRankClass = $data['rankingMinPvpRankClass'];
            $this->maxDailyChallengeCount = $data['maxDailyChallengeCount'];
            $this->maxDailyItemChallengeCount = $data['maxDailyItemChallengeCount'];
            $this->itemChallengeCostAmount = $data['itemChallengeCostAmount'];
            $this->initialBattlePoint = $data['initialBattlePoint'];
            $this->mstInGameId = $data['mstInGameId'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'rankingMinPvpRankClass' => 'string|null',
        'maxDailyChallengeCount' => 'int',
        'maxDailyItemChallengeCount' => 'int',
        'itemChallengeCostAmount' => 'int',
        'initialBattlePoint' => 'int',
        'mstInGameId' => 'string',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'rankingMinPvpRankClass' => 'ranking_min_pvp_rank_class',
        'maxDailyChallengeCount' => 'max_daily_challenge_count',
        'maxDailyItemChallengeCount' => 'max_daily_item_challenge_count',
        'itemChallengeCostAmount' => 'item_challenge_cost_amount',
        'initialBattlePoint' => 'initial_battle_point',
        'mstInGameId' => 'mst_in_game_id',
    ];

    /** @var string */
    protected $id;

    /** @var string|null */
    protected $rankingMinPvpRankClass;

    /** @var int */
    protected $maxDailyChallengeCount;

    /** @var int */
    protected $maxDailyItemChallengeCount;

    /** @var int */
    protected $itemChallengeCostAmount;

    /** @var int */
    protected $initialBattlePoint;

    /** @var string */
    protected $mstInGameId;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'rankingMinPvpRankClass' => $this->rankingMinPvpRankClass,
            'maxDailyChallengeCount' => $this->maxDailyChallengeCount,
            'maxDailyItemChallengeCount' => $this->maxDailyItemChallengeCount,
            'itemChallengeCostAmount' => $this->itemChallengeCostAmount,
            'initialBattlePoint' => $this->initialBattlePoint,
            'mstInGameId' => $this->mstInGameId,
        ];
    }
}
