<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstPageResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
    ];

    /** @var string */
    protected $id;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
        ];
    }
}
