<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstShopItemResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_shopType = 'shopType';
    protected const C_costType = 'costType';
    protected const C_costAmount = 'costAmount';
    protected const C_isFirstTimeFree = 'isFirstTimeFree';
    protected const C_tradableCount = 'tradableCount';
    protected const C_resourceType = 'resourceType';
    protected const C_resourceId = 'resourceId';
    protected const C_resourceAmount = 'resourceAmount';
    protected const C_startDate = 'startDate';
    protected const C_endDate = 'endDate';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->shopType = $data['shopType'];
            $this->costType = $data['costType'];
            $this->costAmount = $data['costAmount'];
            $this->isFirstTimeFree = $data['isFirstTimeFree'];
            $this->tradableCount = $data['tradableCount'];
            $this->resourceType = $data['resourceType'];
            $this->resourceId = $data['resourceId'];
            $this->resourceAmount = $data['resourceAmount'];
            $this->startDate = $data['startDate'];
            $this->endDate = $data['endDate'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'shopType' => 'string',
        'costType' => 'string',
        'costAmount' => 'int|null',
        'isFirstTimeFree' => 'string',
        'tradableCount' => 'int',
        'resourceType' => 'string',
        'resourceId' => 'string',
        'resourceAmount' => 'int',
        'startDate' => 'string',
        'endDate' => 'string',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'shopType' => 'shop_type',
        'costType' => 'cost_type',
        'costAmount' => 'cost_amount',
        'isFirstTimeFree' => 'is_first_time_free',
        'tradableCount' => 'tradable_count',
        'resourceType' => 'resource_type',
        'resourceId' => 'resource_id',
        'resourceAmount' => 'resource_amount',
        'startDate' => 'start_date',
        'endDate' => 'end_date',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $shopType;

    /** @var string */
    protected $costType;

    /** @var int|null */
    protected $costAmount;

    /** @var string */
    protected $isFirstTimeFree;

    /** @var int */
    protected $tradableCount;

    /** @var string */
    protected $resourceType;

    /** @var string */
    protected $resourceId;

    /** @var int */
    protected $resourceAmount;

    /** @var string */
    protected $startDate;

    /** @var string */
    protected $endDate;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'shopType' => $this->shopType,
            'costType' => $this->costType,
            'costAmount' => $this->costAmount,
            'isFirstTimeFree' => $this->isFirstTimeFree,
            'tradableCount' => $this->tradableCount,
            'resourceType' => $this->resourceType,
            'resourceId' => $this->resourceId,
            'resourceAmount' => $this->resourceAmount,
            'startDate' => $this->startDate,
            'endDate' => $this->endDate,
        ];
    }
}
