<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstSkillFixResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_mstSkillId = 'mstSkillId';
    protected const C_addressableName = 'addressableName';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->mstSkillId = $data['mstSkillId'];
            $this->addressableName = $data['addressableName'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'int',
        'mstSkillId' => 'int',
        'addressableName' => 'string',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'mstSkillId' => 'mst_skill_id',
        'addressableName' => 'addressable_name',
    ];

    /** @var int */
    protected $id;

    /** @var int */
    protected $mstSkillId;

    /** @var string */
    protected $addressableName;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'mstSkillId' => $this->mstSkillId,
            'addressableName' => $this->addressableName,
        ];
    }
}
