<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstShopPassRewardResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_mstShopPassId = 'mstShopPassId';
    protected const C_passRewardType = 'passRewardType';
    protected const C_resourceType = 'resourceType';
    protected const C_resourceId = 'resourceId';
    protected const C_resourceAmount = 'resourceAmount';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->mstShopPassId = $data['mstShopPassId'];
            $this->passRewardType = $data['passRewardType'];
            $this->resourceType = $data['resourceType'];
            $this->resourceId = $data['resourceId'];
            $this->resourceAmount = $data['resourceAmount'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'mstShopPassId' => 'string',
        'passRewardType' => 'string',
        'resourceType' => 'string',
        'resourceId' => 'string',
        'resourceAmount' => 'int',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'mstShopPassId' => 'mst_shop_pass_id',
        'passRewardType' => 'pass_reward_type',
        'resourceType' => 'resource_type',
        'resourceId' => 'resource_id',
        'resourceAmount' => 'resource_amount',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $mstShopPassId;

    /** @var string */
    protected $passRewardType;

    /** @var string */
    protected $resourceType;

    /** @var string */
    protected $resourceId;

    /** @var int */
    protected $resourceAmount;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'mstShopPassId' => $this->mstShopPassId,
            'passRewardType' => $this->passRewardType,
            'resourceType' => $this->resourceType,
            'resourceId' => $this->resourceId,
            'resourceAmount' => $this->resourceAmount,
        ];
    }
}
