<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstTutorialResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_type = 'type';
    protected const C_sortOrder = 'sortOrder';
    protected const C_functionName = 'functionName';
    protected const C_conditionType = 'conditionType';
    protected const C_conditionValue = 'conditionValue';
    protected const C_startAt = 'startAt';
    protected const C_endAt = 'endAt';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->type = $data['type'];
            $this->sortOrder = $data['sortOrder'];
            $this->functionName = $data['functionName'];
            $this->conditionType = $data['conditionType'];
            $this->conditionValue = $data['conditionValue'];
            $this->startAt = $data['startAt'];
            $this->endAt = $data['endAt'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'type' => 'string',
        'sortOrder' => 'int',
        'functionName' => 'string',
        'conditionType' => 'string',
        'conditionValue' => 'string',
        'startAt' => 'string',
        'endAt' => 'string',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'type' => 'type',
        'sortOrder' => 'sort_order',
        'functionName' => 'function_name',
        'conditionType' => 'condition_type',
        'conditionValue' => 'condition_value',
        'startAt' => 'start_at',
        'endAt' => 'end_at',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $type;

    /** @var int */
    protected $sortOrder;

    /** @var string */
    protected $functionName;

    /** @var string */
    protected $conditionType;

    /** @var string */
    protected $conditionValue;

    /** @var string */
    protected $startAt;

    /** @var string */
    protected $endAt;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'type' => $this->type,
            'sortOrder' => $this->sortOrder,
            'functionName' => $this->functionName,
            'conditionType' => $this->conditionType,
            'conditionValue' => $this->conditionValue,
            'startAt' => $this->startAt,
            'endAt' => $this->endAt,
        ];
    }
}
