<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstUnitGradeUpResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_gradeLevel = 'gradeLevel';
    protected const C_unitLabel = 'unitLabel';
    protected const C_requireAmount = 'requireAmount';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->gradeLevel = $data['gradeLevel'];
            $this->unitLabel = $data['unitLabel'];
            $this->requireAmount = $data['requireAmount'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'gradeLevel' => 'int',
        'unitLabel' => 'string',
        'requireAmount' => 'int',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'gradeLevel' => 'grade_level',
        'unitLabel' => 'unit_label',
        'requireAmount' => 'require_amount',
    ];

    /** @var string */
    protected $id;

    /** @var int */
    protected $gradeLevel;

    /** @var string */
    protected $unitLabel;

    /** @var int */
    protected $requireAmount;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'gradeLevel' => $this->gradeLevel,
            'unitLabel' => $this->unitLabel,
            'requireAmount' => $this->requireAmount,
        ];
    }
}
