<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstUserLevelResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_level = 'level';
    protected const C_exp = 'exp';
    protected const C_stamina = 'stamina';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->level = $data['level'];
            $this->exp = $data['exp'];
            $this->stamina = $data['stamina'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'level' => 'int',
        'exp' => 'int',
        'stamina' => 'int',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'level' => 'level',
        'exp' => 'exp',
        'stamina' => 'stamina',
    ];

    /** @var string */
    protected $id;

    /** @var int */
    protected $level;

    /** @var int */
    protected $exp;

    /** @var int */
    protected $stamina;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'level' => $this->level,
            'exp' => $this->exp,
            'stamina' => $this->stamina,
        ];
    }
}
