<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstUnitRankCoefficientResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_rank = 'rank';
    protected const C_coefficient = 'coefficient';
    protected const C_specialUnitCoefficient = 'specialUnitCoefficient';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->rank = $data['rank'];
            $this->coefficient = $data['coefficient'];
            $this->specialUnitCoefficient = $data['specialUnitCoefficient'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'rank' => 'int',
        'coefficient' => 'int',
        'specialUnitCoefficient' => 'int',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'rank' => 'rank',
        'coefficient' => 'coefficient',
        'specialUnitCoefficient' => 'special_unit_coefficient',
    ];

    /** @var int */
    protected $rank;

    /** @var int */
    protected $coefficient;

    /** @var int */
    protected $specialUnitCoefficient;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'rank' => $this->rank,
            'coefficient' => $this->coefficient,
            'specialUnitCoefficient' => $this->specialUnitCoefficient,
        ];
    }
}
