<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstUnitRoleBonusResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_roleType = 'roleType';
    protected const C_colorAdvantageAttackBonus = 'colorAdvantageAttackBonus';
    protected const C_colorAdvantageDefenseBonus = 'colorAdvantageDefenseBonus';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->roleType = $data['roleType'];
            $this->colorAdvantageAttackBonus = $data['colorAdvantageAttackBonus'];
            $this->colorAdvantageDefenseBonus = $data['colorAdvantageDefenseBonus'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'roleType' => 'string',
        'colorAdvantageAttackBonus' => 'string',
        'colorAdvantageDefenseBonus' => 'string',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'roleType' => 'role_type',
        'colorAdvantageAttackBonus' => 'color_advantage_attack_bonus',
        'colorAdvantageDefenseBonus' => 'color_advantage_defense_bonus',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $roleType;

    /** @var string */
    protected $colorAdvantageAttackBonus;

    /** @var string */
    protected $colorAdvantageDefenseBonus;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'roleType' => $this->roleType,
            'colorAdvantageAttackBonus' => $this->colorAdvantageAttackBonus,
            'colorAdvantageDefenseBonus' => $this->colorAdvantageDefenseBonus,
        ];
    }
}
