<?php

namespace App\Http\Resources\Api\Masterdata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstUnitGradeUpRewardResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_mstUnitId = 'mstUnitId';
    protected const C_gradeLevel = 'gradeLevel';
    protected const C_resourceType = 'resourceType';
    protected const C_resourceId = 'resourceId';
    protected const C_resourceAmount = 'resourceAmount';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->mstUnitId = $data['mstUnitId'];
            $this->gradeLevel = $data['gradeLevel'];
            $this->resourceType = $data['resourceType'];
            $this->resourceId = $data['resourceId'];
            $this->resourceAmount = $data['resourceAmount'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'mstUnitId' => 'string',
        'gradeLevel' => 'int',
        'resourceType' => 'string',
        'resourceId' => 'string',
        'resourceAmount' => 'int',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'mstUnitId' => 'mst_unit_id',
        'gradeLevel' => 'grade_level',
        'resourceType' => 'resource_type',
        'resourceId' => 'resource_id',
        'resourceAmount' => 'resource_amount',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $mstUnitId;

    /** @var int */
    protected $gradeLevel;

    /** @var string */
    protected $resourceType;

    /** @var string|null */
    protected $resourceId;

    /** @var int */
    protected $resourceAmount;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'mstUnitId' => $this->mstUnitId,
            'gradeLevel' => $this->gradeLevel,
            'resourceType' => $this->resourceType,
            'resourceId' => $this->resourceId,
            'resourceAmount' => $this->resourceAmount,
        ];
    }
}
