<?php

declare(strict_types=1);

namespace Feature\Domain\IdleIncentive\UseCases;

use Tests\Support\Entities\CurrentUser;
use App\Domain\IdleIncentive\Models\UsrIdleIncentive;
use App\Domain\IdleIncentive\UseCases\IdleIncentiveReceiveUseCase;
use App\Domain\Item\Enums\ItemType;
use App\Domain\Resource\Enums\RewardType;
use App\Domain\Resource\Mst\Models\MstIdleIncentive;
use App\Domain\Resource\Mst\Models\MstIdleIncentiveItem;
use App\Domain\Resource\Mst\Models\MstIdleIncentiveReward;
use App\Domain\Resource\Mst\Models\MstItem;
use App\Domain\Resource\Mst\Models\MstPack;
use App\Domain\Resource\Mst\Models\MstQuest;
use App\Domain\Resource\Mst\Models\MstShopPass;
use App\Domain\Resource\Mst\Models\MstShopPassEffect;
use App\Domain\Resource\Mst\Models\MstStage;
use App\Domain\Resource\Mst\Models\MstUserLevel;
use App\Domain\Resource\Mst\Models\OprProduct;
use App\Domain\Shop\Enums\PassEffectType;
use App\Domain\Shop\Enums\ProductType;
use App\Domain\Shop\Enums\SaleCondition;
use App\Domain\Shop\Models\UsrConditionPack;
use App\Domain\Shop\Models\UsrShopPass;
use App\Domain\Stage\Enums\QuestType;
use App\Domain\Stage\Models\Eloquent\UsrStage;
use App\Domain\Unit\Enums\UnitColorType;
use App\Domain\User\Constants\UserConstant;
use App\Domain\User\Models\UsrUserParameter;
use App\Domain\Shop\Enums\PackType;

use Tests\TestCase;

class IdleIncentiveReceiveUseCaseTest extends TestCase
{
    private IdleIncentiveReceiveUseCase $useCase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->useCase = app(IdleIncentiveReceiveUseCase::class);
    }

    public function testExec_ユーザーレベルパック開放テスト()
    {
        // NOTE バグ修正確認のためのテスト
        // Setup
        $usrUserId = $this->createUsrUser()->getUsrUserId();
        $mstQuest = MstQuest::factory()->create([
            'id' => 'normalQuest1',
            'quest_type' => QuestType::NORMAL->value,
        ]);
        $mstStageId = MstStage::factory()->create([
            'mst_quest_id' => 'normalQuest1',
        ])->toEntity()->getId();
        $mstItemId = 'item1';
        MstItem::factory()->createMany([
            ['id' => $mstItemId, 'type' => ItemType::RANK_UP_MATERIAL->value, 'effect_value' => UnitColorType::COLORLESS->value],
        ]);
        MstIdleIncentive::factory()->create([
            'initial_reward_receive_minutes' => 10,
            'reward_increase_interval_minutes' => 10,
        ])->toEntity();
        $mstIdleIncentiveReward = MstIdleIncentiveReward::factory()->create([
            'mst_stage_id' => $mstStageId,
            'base_coin_amount' => 10,
            'base_exp_amount' => 20,
        ])->toEntity();
        MstIdleIncentiveItem::factory()->create([
            'mst_idle_incentive_item_group_id' => $mstIdleIncentiveReward->getMstIdleIncentiveItemGroupId(),
            'mst_item_id' => $mstItemId,
        ]);
        MstUserLevel::factory()->createMany([
            ['level' => 1, 'exp' => 0],
            ['level' => 2, 'exp' => 10],
        ]);
        $oprProduct = OprProduct::factory()->create(['product_type' => ProductType::PACK->value])->toEntity();
        $mstPackId = MstPack::factory()->create([
            'product_sub_id' => $oprProduct->getId(),
            'pack_type'=> PackType::NORMAL->value,
            'sale_condition' => SaleCondition::USER_LEVEL->value,
            'sale_condition_value' => '2',
        ])->toEntity()->getId();

        $currentUser = new CurrentUser($usrUserId);
        $this->createDiamond($usrUserId);
        UsrUserParameter::factory()->create([
            'usr_user_id' => $usrUserId,
            'level' => 1,
            'exp' => 0,
            'stamina' => 1,
        ]);
        UsrStage::factory()->create([
            'usr_user_id' => $usrUserId,
            'mst_stage_id' => $mstStageId,
            
        ]);
        UsrIdleIncentive::factory()->create([
            'usr_user_id' => $usrUserId,
            'idle_started_at' => now()->subMinutes(30),
            'reward_mst_stage_id' => $mstStageId,
        ]);

        $response = $this->useCase->exec($currentUser, UserConstant::PLATFORM_IOS);

        $usrConditionPack = $response->usrConditionPacks->first();
        $this->assertNotNull($usrConditionPack);
        $this->assertEquals($mstPackId, $usrConditionPack->getMstPackId());

        // DB確認
        $usrConditionPack = UsrConditionPack::query()
            ->where('usr_user_id', $usrUserId)
            ->where('mst_pack_id', $mstPackId)
            ->first();
        $this->assertNotNull($usrConditionPack);
    }

    public function test_exec_報酬アップのパス効果が適用されること()
    {
        // Setup
        $usrUserId = $this->createUsrUser()->getUsrUserId();
        $mstQuest = MstQuest::factory()->create([
            'id' => 'normalQuest1',
            'quest_type' => QuestType::NORMAL->value,
        ]);
        $mstStageId = MstStage::factory()->create([
            'mst_quest_id' => 'normalQuest1',
        ])->toEntity()->getId();
        $mstShopPassId = 'shop_pass_id';
        $now = $this->fixTime('2024-07-21 10:00:00');
        MstItem::factory()->createMany([
            [
                'id' => 'item1',
            ],
            [
                'id' => 'item2',
                'type' => ItemType::RANK_UP_MATERIAL->value,
                'effect_value' => UnitColorType::COLORLESS->value
            ],
        ]);
        MstIdleIncentive::factory()->create([
            'initial_reward_receive_minutes' => 10,
            'reward_increase_interval_minutes' => 10,
        ])->toEntity();
        $mstIdleIncentiveReward = MstIdleIncentiveReward::factory()->create([
            'mst_stage_id' => $mstStageId,
            'base_coin_amount' => 10,
            'base_exp_amount' => 20,
        ])->toEntity();
        MstIdleIncentiveItem::factory()->create([
            'mst_idle_incentive_item_group_id' => $mstIdleIncentiveReward->getMstIdleIncentiveItemGroupId(),
            'mst_item_id' => 'item1',
            'base_amount' => 30,
        ]);
        MstUserLevel::factory()->createMany([
            ['level' => 1, 'exp' => 0],
            ['level' => 2, 'exp' => 1000],
        ]);

        MstShopPass::factory()->create([
            'id' => $mstShopPassId,
            'opr_product_id' => 'test',
            'pass_duration_days' => 7,
        ])->toEntity();

        MstShopPassEffect::factory()->createMany([
            [
                'mst_shop_pass_id' => $mstShopPassId,
                'effect_type' => PassEffectType::IDLE_INCENTIVE_ADD_REWARD->value,
                'effect_value' => 3,
            ],
        ]);

        UsrShopPass::factory()->create([
            'usr_user_id' => $usrUserId,
            'mst_shop_pass_id' => $mstShopPassId,
            'daily_reward_received_count' => 0,
            'daily_latest_received_at' => fake()->dateTime()->format('Y-m-d H:i:s'),
            'start_at' => $now->format('Y-m-d H:i:s'),
            'end_at' => $now->addDays(7)->format('Y-m-d H:i:s'),
        ]);

        $currentUser = new CurrentUser($usrUserId);
        $this->createDiamond($usrUserId);
        UsrUserParameter::factory()->create([
            'usr_user_id' => $usrUserId,
            'coin' => 0,
            'level' => 1,
            'exp' => 0,
            'stamina' => 1,
        ]);
        UsrStage::factory()->create([
            'usr_user_id' => $usrUserId,
            'mst_stage_id' => $mstStageId,
            
        ]);
        UsrIdleIncentive::factory()->create([
            'usr_user_id' => $usrUserId,
            'idle_started_at' => $now->subMinutes(40),
            'reward_mst_stage_id' => $mstStageId,
        ]);

        $response = $this->useCase->exec($currentUser, UserConstant::PLATFORM_IOS);

        $idleIncentiveRewards = $response->idleIncentiveRewards;
        $this->assertEquals(3, $idleIncentiveRewards->count());

        /** @var \App\Domain\Resource\Entities\Rewards\IdleIncentiveReward $idleIncentiveReward */
        foreach ($idleIncentiveRewards as $idleIncentiveReward) {
            switch ($idleIncentiveReward->getType()) {
                case RewardType::COIN->value:
                    $this->assertEquals(10 * 4 * 3, $idleIncentiveReward->getAmount());
                    break;
                case RewardType::EXP->value:
                    $this->assertEquals(20 * 4 * 3, $idleIncentiveReward->getAmount());
                    break;
                case RewardType::ITEM->value:
                    if ($idleIncentiveReward->getResourceId() === 'item1') {
                        $this->assertEquals(30 * 4 * 3, $idleIncentiveReward->getAmount());
                    } else if ($idleIncentiveReward->getResourceId() === 'item2') {
                        $this->assertEquals(2 * 4 * 3, $idleIncentiveReward->getAmount());
                    } else {
                        $this->fail();
                    }
                    break;
                default:
                    $this->fail();
            }
        }
    }

    public function test_exec_有効期限外の場合は報酬アップのパス効果が適用されないこと()
    {
        // Setup
        $usrUserId = $this->createUsrUser()->getUsrUserId();
        $mstQuest = MstQuest::factory()->create([
            'id' => 'normalQuest1',
            'quest_type' => QuestType::NORMAL->value,
        ]);
        $mstStageId = MstStage::factory()->create([
            'mst_quest_id' => 'normalQuest1',
        ])->toEntity()->getId();
        $mstShopPassId = 'shop_pass_id';
        $now = $this->fixTime('2024-07-21 10:00:00');
        MstItem::factory()->createMany([
            [
                'id' => 'item1',
            ],
            [
                'id' => 'item2',
                'type' => ItemType::RANK_UP_MATERIAL->value,
                'effect_value' => UnitColorType::COLORLESS->value
            ],
        ]);
        MstIdleIncentive::factory()->create([
            'initial_reward_receive_minutes' => 10,
            'reward_increase_interval_minutes' => 10,
        ])->toEntity();
        $mstIdleIncentiveReward = MstIdleIncentiveReward::factory()->create([
            'mst_stage_id' => $mstStageId,
            'base_coin_amount' => 10,
            'base_exp_amount' => 20,
        ])->toEntity();
        MstIdleIncentiveItem::factory()->create([
            'mst_idle_incentive_item_group_id' => $mstIdleIncentiveReward->getMstIdleIncentiveItemGroupId(),
            'mst_item_id' => 'item1',
            'base_amount' => 30,
        ]);
        MstUserLevel::factory()->createMany([
            ['level' => 1, 'exp' => 0],
            ['level' => 2, 'exp' => 1000],
        ]);

        MstShopPass::factory()->create([
            'id' => $mstShopPassId,
            'opr_product_id' => 'test',
            'pass_duration_days' => 7,
        ])->toEntity();

        MstShopPassEffect::factory()->createMany([
            [
                'mst_shop_pass_id' => $mstShopPassId,
                'effect_type' => PassEffectType::IDLE_INCENTIVE_ADD_REWARD->value,
                'effect_value' => 3,
            ],
        ]);

        UsrShopPass::factory()->create([
            'usr_user_id' => $usrUserId,
            'mst_shop_pass_id' => $mstShopPassId,
            'daily_reward_received_count' => 0,
            'daily_latest_received_at' => fake()->dateTime()->format('Y-m-d H:i:s'),
            'start_at' => $now->subDays(7)->format('Y-m-d H:i:s'),
            'end_at' => $now->subSecond()->format('Y-m-d H:i:s'),
        ]);

        $currentUser = new CurrentUser($usrUserId);
        $this->createDiamond($usrUserId);
        UsrUserParameter::factory()->create([
            'usr_user_id' => $usrUserId,
            'coin' => 0,
            'level' => 1,
            'exp' => 0,
            'stamina' => 1,
        ]);
        UsrStage::factory()->create([
            'usr_user_id' => $usrUserId,
            'mst_stage_id' => $mstStageId,
            
        ]);
        UsrIdleIncentive::factory()->create([
            'usr_user_id' => $usrUserId,
            'idle_started_at' => $now->subMinutes(40),
            'reward_mst_stage_id' => $mstStageId,
        ]);

        $response = $this->useCase->exec($currentUser, UserConstant::PLATFORM_IOS);

        $idleIncentiveRewards = $response->idleIncentiveRewards;
        $this->assertEquals(3, $idleIncentiveRewards->count());

        /** @var \App\Domain\Resource\Entities\Rewards\IdleIncentiveReward $idleIncentiveReward */
        foreach ($idleIncentiveRewards as $idleIncentiveReward) {
            switch ($idleIncentiveReward->getType()) {
                case RewardType::COIN->value:
                    $this->assertEquals(10 * 4, $idleIncentiveReward->getAmount());
                    break;
                case RewardType::EXP->value:
                    $this->assertEquals(20 * 4, $idleIncentiveReward->getAmount());
                    break;
                case RewardType::ITEM->value:
                    if ($idleIncentiveReward->getResourceId() === 'item1') {
                        $this->assertEquals(30 * 4, $idleIncentiveReward->getAmount());
                    } else if ($idleIncentiveReward->getResourceId() === 'item2') {
                        $this->assertEquals(2 * 4, $idleIncentiveReward->getAmount());
                    } else {
                        $this->fail();
                    }
                    break;
                default:
                    $this->fail();
            }
        }
    }
}
