<?php

namespace App\Http\Resources\Api\Masteri18ndata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstAdventBattleI18nResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_mstAdventBattleId = 'mstAdventBattleId';
    protected const C_language = 'language';
    protected const C_name = 'name';
    protected const C_bossDescription = 'bossDescription';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->mstAdventBattleId = $data['mstAdventBattleId'];
            $this->language = $data['language'];
            $this->name = $data['name'];
            $this->bossDescription = $data['bossDescription'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'mstAdventBattleId' => 'string',
        'language' => 'string',
        'name' => 'string',
        'bossDescription' => 'string',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'mstAdventBattleId' => 'mst_advent_battle_id',
        'language' => 'language',
        'name' => 'name',
        'bossDescription' => 'boss_description',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $mstAdventBattleId;

    /** @var string */
    protected $language;

    /** @var string */
    protected $name;

    /** @var string */
    protected $bossDescription;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'mstAdventBattleId' => $this->mstAdventBattleId,
            'language' => $this->language,
            'name' => $this->name,
            'bossDescription' => $this->bossDescription,
        ];
    }
}
