<?php

namespace App\Http\Resources\Api\Masteri18ndata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstDummyUserI18nResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_language = 'language';
    protected const C_mstDummyUserId = 'mstDummyUserId';
    protected const C_name = 'name';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->language = $data['language'];
            $this->mstDummyUserId = $data['mstDummyUserId'];
            $this->name = $data['name'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'language' => 'string',
        'mstDummyUserId' => 'string',
        'name' => 'string',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'language' => 'language',
        'mstDummyUserId' => 'mst_dummy_user_id',
        'name' => 'name',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $language;

    /** @var string */
    protected $mstDummyUserId;

    /** @var string */
    protected $name;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'language' => $this->language,
            'mstDummyUserId' => $this->mstDummyUserId,
            'name' => $this->name,
        ];
    }
}
