<?php

namespace App\Http\Resources\Api\Masteri18ndata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstInGameI18nResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_mstInGameId = 'mstInGameId';
    protected const C_language = 'language';
    protected const C_resultTips = 'resultTips';
    protected const C_description = 'description';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->mstInGameId = $data['mstInGameId'];
            $this->language = $data['language'];
            $this->resultTips = $data['resultTips'];
            $this->description = $data['description'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'mstInGameId' => 'string',
        'language' => 'string',
        'resultTips' => 'string',
        'description' => 'string',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'mstInGameId' => 'mst_in_game_id',
        'language' => 'language',
        'resultTips' => 'result_tips',
        'description' => 'description',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $mstInGameId;

    /** @var string */
    protected $language;

    /** @var string */
    protected $resultTips;

    /** @var string */
    protected $description;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'mstInGameId' => $this->mstInGameId,
            'language' => $this->language,
            'resultTips' => $this->resultTips,
            'description' => $this->description,
        ];
    }
}
