<?php

namespace App\Http\Resources\Api\Masteri18ndata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstI18nResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_mstAbilityI18n = 'mstAbilityI18n';
    protected const C_mstArtworkI18n = 'mstArtworkI18n';
    protected const C_mstArtworkFragmentI18n = 'mstArtworkFragmentI18n';
    protected const C_mstAttackI18n = 'mstAttackI18n';
    protected const C_MstEnemyCharacterI18n = 'MstEnemyCharacterI18n';
    protected const C_mstEmblemI18n = 'mstEmblemI18n';
    protected const C_mstEventI18n = 'mstEventI18n';
    protected const C_mstEventDisplayUnitI18n = 'mstEventDisplayUnitI18n';
    protected const C_mstUnitI18n = 'mstUnitI18n';
    protected const C_mstInGameI18n = 'mstInGameI18n';
    protected const C_mstItemI18n = 'mstItemI18n';
    protected const C_mstMissionAchievementI18n = 'mstMissionAchievementI18n';
    protected const C_mstMissionDailyI18n = 'mstMissionDailyI18n';
    protected const C_mstMissionWeeklyI18n = 'mstMissionWeeklyI18n';
    protected const C_mstMissionBeginnerI18n = 'mstMissionBeginnerI18n';
    protected const C_mstMissionBeginnerPromptPhraseI18n = 'mstMissionBeginnerPromptPhraseI18n';
    protected const C_mstMissionEventI18n = 'mstMissionEventI18n';
    protected const C_mstMissionEventDailyI18n = 'mstMissionEventDailyI18n';
    protected const C_mstMissionLimitedTermI18n = 'mstMissionLimitedTermI18n';
    protected const C_mstOutpostEnhancementI18n = 'mstOutpostEnhancementI18n';
    protected const C_mstOutpostEnhancementLevelI18n = 'mstOutpostEnhancementLevelI18n';
    protected const C_mstPackI18n = 'mstPackI18n';
    protected const C_mstShopPassI18n = 'mstShopPassI18n';
    protected const C_mstExchangeI18n = 'mstExchangeI18n';
    protected const C_mstQuestI18n = 'mstQuestI18n';
    protected const C_mstSeriesI18n = 'mstSeriesI18n';
    protected const C_mstSpecialAttackI18n = 'mstSpecialAttackI18n';
    protected const C_mstSpeechBalloonI18n = 'mstSpeechBalloonI18n';
    protected const C_mstStageI18n = 'mstStageI18n';
    protected const C_mstStoreProductI18n = 'mstStoreProductI18n';
    protected const C_mstTutorialTipI18n = 'mstTutorialTipI18n';
    protected const C_mstResultTipI18n = 'mstResultTipI18n';
    protected const C_mstAdventBattleI18n = 'mstAdventBattleI18n';
    protected const C_mstDummyUserI18n = 'mstDummyUserI18n';
    protected const C_mstPvpI18n = 'mstPvpI18n';
    protected const C_mstBoxGachaI18n = 'mstBoxGachaI18n';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->mstAbilityI18n = $data['mstAbilityI18n'];
            $this->mstArtworkI18n = $data['mstArtworkI18n'];
            $this->mstArtworkFragmentI18n = $data['mstArtworkFragmentI18n'];
            $this->mstAttackI18n = $data['mstAttackI18n'];
            $this->MstEnemyCharacterI18n = $data['MstEnemyCharacterI18n'];
            $this->mstEmblemI18n = $data['mstEmblemI18n'];
            $this->mstEventI18n = $data['mstEventI18n'];
            $this->mstEventDisplayUnitI18n = $data['mstEventDisplayUnitI18n'];
            $this->mstUnitI18n = $data['mstUnitI18n'];
            $this->mstInGameI18n = $data['mstInGameI18n'];
            $this->mstItemI18n = $data['mstItemI18n'];
            $this->mstMissionAchievementI18n = $data['mstMissionAchievementI18n'];
            $this->mstMissionDailyI18n = $data['mstMissionDailyI18n'];
            $this->mstMissionWeeklyI18n = $data['mstMissionWeeklyI18n'];
            $this->mstMissionBeginnerI18n = $data['mstMissionBeginnerI18n'];
            $this->mstMissionBeginnerPromptPhraseI18n = $data['mstMissionBeginnerPromptPhraseI18n'];
            $this->mstMissionEventI18n = $data['mstMissionEventI18n'];
            $this->mstMissionEventDailyI18n = $data['mstMissionEventDailyI18n'];
            $this->mstMissionLimitedTermI18n = $data['mstMissionLimitedTermI18n'];
            $this->mstOutpostEnhancementI18n = $data['mstOutpostEnhancementI18n'];
            $this->mstOutpostEnhancementLevelI18n = $data['mstOutpostEnhancementLevelI18n'];
            $this->mstPackI18n = $data['mstPackI18n'];
            $this->mstShopPassI18n = $data['mstShopPassI18n'];
            $this->mstExchangeI18n = $data['mstExchangeI18n'];
            $this->mstQuestI18n = $data['mstQuestI18n'];
            $this->mstSeriesI18n = $data['mstSeriesI18n'];
            $this->mstSpecialAttackI18n = $data['mstSpecialAttackI18n'];
            $this->mstSpeechBalloonI18n = $data['mstSpeechBalloonI18n'];
            $this->mstStageI18n = $data['mstStageI18n'];
            $this->mstStoreProductI18n = $data['mstStoreProductI18n'];
            $this->mstTutorialTipI18n = $data['mstTutorialTipI18n'];
            $this->mstResultTipI18n = $data['mstResultTipI18n'];
            $this->mstAdventBattleI18n = $data['mstAdventBattleI18n'];
            $this->mstDummyUserI18n = $data['mstDummyUserI18n'];
            $this->mstPvpI18n = $data['mstPvpI18n'];
            $this->mstBoxGachaI18n = $data['mstBoxGachaI18n'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'mstAbilityI18n' => 'string',
        'mstArtworkI18n' => 'string',
        'mstArtworkFragmentI18n' => 'string',
        'mstAttackI18n' => 'string',
        'MstEnemyCharacterI18n' => 'string',
        'mstEmblemI18n' => 'string',
        'mstEventI18n' => 'string',
        'mstEventDisplayUnitI18n' => 'string',
        'mstUnitI18n' => 'string',
        'mstInGameI18n' => 'string',
        'mstItemI18n' => 'string',
        'mstMissionAchievementI18n' => 'string',
        'mstMissionDailyI18n' => 'string',
        'mstMissionWeeklyI18n' => 'string',
        'mstMissionBeginnerI18n' => 'string',
        'mstMissionBeginnerPromptPhraseI18n' => 'string',
        'mstMissionEventI18n' => 'string',
        'mstMissionEventDailyI18n' => 'string',
        'mstMissionLimitedTermI18n' => 'string',
        'mstOutpostEnhancementI18n' => 'string',
        'mstOutpostEnhancementLevelI18n' => 'string',
        'mstPackI18n' => 'string',
        'mstShopPassI18n' => 'string',
        'mstExchangeI18n' => 'string',
        'mstQuestI18n' => 'string',
        'mstSeriesI18n' => 'string',
        'mstSpecialAttackI18n' => 'string',
        'mstSpeechBalloonI18n' => 'string',
        'mstStageI18n' => 'string',
        'mstStoreProductI18n' => 'string',
        'mstTutorialTipI18n' => 'string',
        'mstResultTipI18n' => 'string',
        'mstAdventBattleI18n' => 'string',
        'mstDummyUserI18n' => 'string',
        'mstPvpI18n' => 'string',
        'mstBoxGachaI18n' => 'string',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'mstAbilityI18n' => 'mst_ability_i18n',
        'mstArtworkI18n' => 'mst_artwork_i18n',
        'mstArtworkFragmentI18n' => 'mst_artwork_fragment_i18n',
        'mstAttackI18n' => 'mst_attack_i18n',
        'MstEnemyCharacterI18n' => 'mst_enemy_character_i18n',
        'mstEmblemI18n' => 'mst_emblem_i18n',
        'mstEventI18n' => 'mst_event_i18n',
        'mstEventDisplayUnitI18n' => 'mst_event_display_unit_i18n',
        'mstUnitI18n' => 'mst_unit_i18n',
        'mstInGameI18n' => 'mst_in_game_i18n',
        'mstItemI18n' => 'mst_item_i18n',
        'mstMissionAchievementI18n' => 'mst_mission_achievement_i18n',
        'mstMissionDailyI18n' => 'mst_mission_daily_i18n',
        'mstMissionWeeklyI18n' => 'mst_mission_weekly_i18n',
        'mstMissionBeginnerI18n' => 'mst_mission_beginner_i18n',
        'mstMissionBeginnerPromptPhraseI18n' => 'mst_mission_beginner_prompt_phrase_i18n',
        'mstMissionEventI18n' => 'mst_mission_event_i18n',
        'mstMissionEventDailyI18n' => 'mst_mission_event_daily_i18n',
        'mstMissionLimitedTermI18n' => 'mst_mission_limited_term_i18n',
        'mstOutpostEnhancementI18n' => 'mst_outpost_enhancement_i18n',
        'mstOutpostEnhancementLevelI18n' => 'mst_outpost_enhancement_level_i18n',
        'mstPackI18n' => 'mst_pack_i18n',
        'mstShopPassI18n' => 'mst_shop_pass_i18n',
        'mstExchangeI18n' => 'mst_exchange_i18n',
        'mstQuestI18n' => 'mst_quest_i18n',
        'mstSeriesI18n' => 'mst_series_i18n',
        'mstSpecialAttackI18n' => 'mst_special_attack_i18n',
        'mstSpeechBalloonI18n' => 'mst_speech_balloon_i18n',
        'mstStageI18n' => 'mst_stage_i18n',
        'mstStoreProductI18n' => 'mst_store_product_i18n',
        'mstTutorialTipI18n' => 'mst_tutorial_tip_i18n',
        'mstResultTipI18n' => 'mst_result_tip_i18n',
        'mstAdventBattleI18n' => 'mst_advent_battle_i18n',
        'mstDummyUserI18n' => 'mst_dummy_user_i18n',
        'mstPvpI18n' => 'mst_pvp_i18n',
        'mstBoxGachaI18n' => 'mst_box_gacha_i18n',
    ];

    /** @var string */
    protected $mstAbilityI18n;

    /** @var string */
    protected $mstArtworkI18n;

    /** @var string */
    protected $mstArtworkFragmentI18n;

    /** @var string */
    protected $mstAttackI18n;

    /** @var string */
    protected $MstEnemyCharacterI18n;

    /** @var string */
    protected $mstEmblemI18n;

    /** @var string */
    protected $mstEventI18n;

    /** @var string */
    protected $mstEventDisplayUnitI18n;

    /** @var string */
    protected $mstUnitI18n;

    /** @var string */
    protected $mstInGameI18n;

    /** @var string */
    protected $mstItemI18n;

    /** @var string */
    protected $mstMissionAchievementI18n;

    /** @var string */
    protected $mstMissionDailyI18n;

    /** @var string */
    protected $mstMissionWeeklyI18n;

    /** @var string */
    protected $mstMissionBeginnerI18n;

    /** @var string */
    protected $mstMissionBeginnerPromptPhraseI18n;

    /** @var string */
    protected $mstMissionEventI18n;

    /** @var string */
    protected $mstMissionEventDailyI18n;

    /** @var string */
    protected $mstMissionLimitedTermI18n;

    /** @var string */
    protected $mstOutpostEnhancementI18n;

    /** @var string */
    protected $mstOutpostEnhancementLevelI18n;

    /** @var string */
    protected $mstPackI18n;

    /** @var string */
    protected $mstShopPassI18n;

    /** @var string */
    protected $mstExchangeI18n;

    /** @var string */
    protected $mstQuestI18n;

    /** @var string */
    protected $mstSeriesI18n;

    /** @var string */
    protected $mstSpecialAttackI18n;

    /** @var string */
    protected $mstSpeechBalloonI18n;

    /** @var string */
    protected $mstStageI18n;

    /** @var string */
    protected $mstStoreProductI18n;

    /** @var string */
    protected $mstTutorialTipI18n;

    /** @var string */
    protected $mstResultTipI18n;

    /** @var string */
    protected $mstAdventBattleI18n;

    /** @var string */
    protected $mstDummyUserI18n;

    /** @var string */
    protected $mstPvpI18n;

    /** @var string */
    protected $mstBoxGachaI18n;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'mstAbilityI18n' => $this->mstAbilityI18n,
            'mstArtworkI18n' => $this->mstArtworkI18n,
            'mstArtworkFragmentI18n' => $this->mstArtworkFragmentI18n,
            'mstAttackI18n' => $this->mstAttackI18n,
            'MstEnemyCharacterI18n' => $this->MstEnemyCharacterI18n,
            'mstEmblemI18n' => $this->mstEmblemI18n,
            'mstEventI18n' => $this->mstEventI18n,
            'mstEventDisplayUnitI18n' => $this->mstEventDisplayUnitI18n,
            'mstUnitI18n' => $this->mstUnitI18n,
            'mstInGameI18n' => $this->mstInGameI18n,
            'mstItemI18n' => $this->mstItemI18n,
            'mstMissionAchievementI18n' => $this->mstMissionAchievementI18n,
            'mstMissionDailyI18n' => $this->mstMissionDailyI18n,
            'mstMissionWeeklyI18n' => $this->mstMissionWeeklyI18n,
            'mstMissionBeginnerI18n' => $this->mstMissionBeginnerI18n,
            'mstMissionBeginnerPromptPhraseI18n' => $this->mstMissionBeginnerPromptPhraseI18n,
            'mstMissionEventI18n' => $this->mstMissionEventI18n,
            'mstMissionEventDailyI18n' => $this->mstMissionEventDailyI18n,
            'mstMissionLimitedTermI18n' => $this->mstMissionLimitedTermI18n,
            'mstOutpostEnhancementI18n' => $this->mstOutpostEnhancementI18n,
            'mstOutpostEnhancementLevelI18n' => $this->mstOutpostEnhancementLevelI18n,
            'mstPackI18n' => $this->mstPackI18n,
            'mstShopPassI18n' => $this->mstShopPassI18n,
            'mstExchangeI18n' => $this->mstExchangeI18n,
            'mstQuestI18n' => $this->mstQuestI18n,
            'mstSeriesI18n' => $this->mstSeriesI18n,
            'mstSpecialAttackI18n' => $this->mstSpecialAttackI18n,
            'mstSpeechBalloonI18n' => $this->mstSpeechBalloonI18n,
            'mstStageI18n' => $this->mstStageI18n,
            'mstStoreProductI18n' => $this->mstStoreProductI18n,
            'mstTutorialTipI18n' => $this->mstTutorialTipI18n,
            'mstResultTipI18n' => $this->mstResultTipI18n,
            'mstAdventBattleI18n' => $this->mstAdventBattleI18n,
            'mstDummyUserI18n' => $this->mstDummyUserI18n,
            'mstPvpI18n' => $this->mstPvpI18n,
            'mstBoxGachaI18n' => $this->mstBoxGachaI18n,
        ];
    }
}
