<?php

namespace App\Http\Resources\Api\Masteri18ndata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstMissionEventI18nResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_mstMissionEventId = 'mstMissionEventId';
    protected const C_language = 'language';
    protected const C_description = 'description';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->mstMissionEventId = $data['mstMissionEventId'];
            $this->language = $data['language'];
            $this->description = $data['description'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'mstMissionEventId' => 'string',
        'language' => 'string',
        'description' => 'string',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'mstMissionEventId' => 'mst_mission_event_id',
        'language' => 'language',
        'description' => 'description',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $mstMissionEventId;

    /** @var string */
    protected $language;

    /** @var string */
    protected $description;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'mstMissionEventId' => $this->mstMissionEventId,
            'language' => $this->language,
            'description' => $this->description,
        ];
    }
}
