<?php

namespace App\Http\Resources\Api\Masteri18ndata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstSeriesI18nResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_mstSeriesId = 'mstSeriesId';
    protected const C_language = 'language';
    protected const C_name = 'name';
    protected const C_prefixWord = 'prefixWord';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->mstSeriesId = $data['mstSeriesId'];
            $this->language = $data['language'];
            $this->name = $data['name'];
            $this->prefixWord = $data['prefixWord'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'mstSeriesId' => 'string',
        'language' => 'string',
        'name' => 'string',
        'prefixWord' => 'string',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'mstSeriesId' => 'mst_series_id',
        'language' => 'language',
        'name' => 'name',
        'prefixWord' => 'prefix_word',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $mstSeriesId;

    /** @var string */
    protected $language;

    /** @var string */
    protected $name;

    /** @var string */
    protected $prefixWord;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'mstSeriesId' => $this->mstSeriesId,
            'language' => $this->language,
            'name' => $this->name,
            'prefixWord' => $this->prefixWord,
        ];
    }
}
