<?php

namespace App\Http\Resources\Api\Masteri18ndata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstStoreProductI18nResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_mstStoreProductId = 'mstStoreProductId';
    protected const C_language = 'language';
    protected const C_priceIos = 'priceIos';
    protected const C_priceAndroid = 'priceAndroid';
    protected const C_priceWebstore = 'priceWebstore';
    protected const C_paidDiamondPriceIos = 'paidDiamondPriceIos';
    protected const C_paidDiamondPriceAndroid = 'paidDiamondPriceAndroid';
    protected const C_paidDiamondPriceWebstore = 'paidDiamondPriceWebstore';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->mstStoreProductId = $data['mstStoreProductId'];
            $this->language = $data['language'];
            $this->priceIos = $data['priceIos'];
            $this->priceAndroid = $data['priceAndroid'];
            $this->priceWebstore = $data['priceWebstore'];
            $this->paidDiamondPriceIos = $data['paidDiamondPriceIos'];
            $this->paidDiamondPriceAndroid = $data['paidDiamondPriceAndroid'];
            $this->paidDiamondPriceWebstore = $data['paidDiamondPriceWebstore'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'mstStoreProductId' => 'string',
        'language' => 'string',
        'priceIos' => 'string',
        'priceAndroid' => 'string',
        'priceWebstore' => 'string',
        'paidDiamondPriceIos' => 'string',
        'paidDiamondPriceAndroid' => 'string',
        'paidDiamondPriceWebstore' => 'string',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'mstStoreProductId' => 'mst_store_product_id',
        'language' => 'language',
        'priceIos' => 'price_ios',
        'priceAndroid' => 'price_android',
        'priceWebstore' => 'price_webstore',
        'paidDiamondPriceIos' => 'paid_diamond_price_ios',
        'paidDiamondPriceAndroid' => 'paid_diamond_price_android',
        'paidDiamondPriceWebstore' => 'paid_diamond_price_webstore',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $mstStoreProductId;

    /** @var string */
    protected $language;

    /** @var string */
    protected $priceIos;

    /** @var string */
    protected $priceAndroid;

    /** @var string */
    protected $priceWebstore;

    /** @var string */
    protected $paidDiamondPriceIos;

    /** @var string */
    protected $paidDiamondPriceAndroid;

    /** @var string */
    protected $paidDiamondPriceWebstore;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'mstStoreProductId' => $this->mstStoreProductId,
            'language' => $this->language,
            'priceIos' => $this->priceIos,
            'priceAndroid' => $this->priceAndroid,
            'priceWebstore' => $this->priceWebstore,
            'paidDiamondPriceIos' => $this->paidDiamondPriceIos,
            'paidDiamondPriceAndroid' => $this->paidDiamondPriceAndroid,
            'paidDiamondPriceWebstore' => $this->paidDiamondPriceWebstore,
        ];
    }
}
