<?php

namespace App\Http\Resources\Api\Masteri18ndata;

use App\Http\Resources\Api\Masterdata\Concerns\InstanceByModelResource;
use App\Http\Resources\Api\Masterdata\Concerns\MstResourceAbstract;

// ----------------------------------------------------------------------
// This file is auto-generated by SchemaBuilder. Do not modify directly.
// ----------------------------------------------------------------------

class MstUnitI18nResource
{
    use MstResourceAbstract;
    use InstanceByModelResource;

    protected const C_id = 'id';
    protected const C_mstUnitId = 'mstUnitId';
    protected const C_language = 'language';
    protected const C_name = 'name';
    protected const C_description = 'description';
    protected const C_detail = 'detail';

    /**
     * @param array<mixed>|null $data
     */
    public function __construct(?array $data = null)
    {
        if (!is_null($data)) {
            $this->id = $data['id'];
            $this->mstUnitId = $data['mstUnitId'];
            $this->language = $data['language'];
            $this->name = $data['name'];
            $this->description = $data['description'];
            $this->detail = $data['detail'];
        }
    }

    /** @var array<string> */
    protected $cast = [
        'id' => 'string',
        'mstUnitId' => 'string',
        'language' => 'string',
        'name' => 'string',
        'description' => 'string',
        'detail' => 'string',
    ];

    /** @var array<string> */
    protected $snakeCased = [
        'id' => 'id',
        'mstUnitId' => 'mst_unit_id',
        'language' => 'language',
        'name' => 'name',
        'description' => 'description',
        'detail' => 'detail',
    ];

    /** @var string */
    protected $id;

    /** @var string */
    protected $mstUnitId;

    /** @var string */
    protected $language;

    /** @var string */
    protected $name;

    /** @var string */
    protected $description;

    /** @var string */
    protected $detail;

    /**
     * @return array<string>
     */
    protected function getValue(): array
    {
        return [
            'id' => $this->id,
            'mstUnitId' => $this->mstUnitId,
            'language' => $this->language,
            'name' => $this->name,
            'description' => $this->description,
            'detail' => $this->detail,
        ];
    }
}
